include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// arc ?, ARC - Almeida Revista e Corrigida

[[v58-9-1]]

^<<v58-9-1,1>>^ Ora, também o primeiro tinha ordenanças de culto divino  e um  santuário terrestre.

[[v58-9-2]]

^<<v58-9-2,2>>^ Porque um tabernáculo estava preparado, o primeiro, em que havia o candeeiro, e a mesa, e os pães da proposição; ao que se chama o Santuário.

[[v58-9-3]]

^<<v58-9-3,3>>^ Mas, depois do segundo véu, estava o tabernáculo que se chama o Santo dos Santos,

[[v58-9-4]]

^<<v58-9-4,4>>^ que tinha o incensário de ouro e a arca do concerto, coberta de ouro toda em redor, em que estava um vaso de ouro, que continha o maná, e a vara de Arão, que tinha florescido, e as tábuas do concerto;

[[v58-9-5]]

^<<v58-9-5,5>>^ e sobre a arca,  os querubins da glória, que faziam sombra no propiciatório; das quais coisas não falaremos agora particularmente.

[[v58-9-6]]

^<<v58-9-6,6>>^ Ora, estando essas coisas assim preparadas, a todo o tempo entravam os sacerdotes no primeiro tabernáculo, cumprindo os serviços;

[[v58-9-7]]

^<<v58-9-7,7>>^ mas, no segundo, só o sumo sacerdote, uma vez no ano, não sem sangue, que oferecia por si mesmo e pelas  culpas do povo;

[[v58-9-8]]

^<<v58-9-8,8>>^ dando nisso a entender o Espírito Santo que ainda o caminho do Santuário não estava descoberto, enquanto se conservava em pé o primeiro tabernáculo,

[[v58-9-9]]

^<<v58-9-9,9>>^ que é uma alegoria para o tempo presente, em que se oferecem dons e sacrifícios que, quanto à consciência, não podem aperfeiçoar aquele que faz o serviço,

[[v58-9-10]]

^<<v58-9-10,10>>^ consistindo  somente em manjares, e bebidas, e várias abluções e justificações da carne, impostas até ao tempo da correção.

[[v58-9-11]]

^<<v58-9-11,11>>^ Mas, vindo Cristo, o sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação,

[[v58-9-12]]

^<<v58-9-12,12>>^ nem por sangue de bodes e bezerros, mas por seu próprio sangue, entrou uma vez no santuário, havendo efetuado uma eterna redenção.

[[v58-9-13]]

^<<v58-9-13,13>>^ Porque, se o sangue dos touros e bodes e a cinza de uma novilha, esparzida sobre os imundos, os  santificam, quanto à purificação da carne,

[[v58-9-14]]

^<<v58-9-14,14>>^ quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?

[[v58-9-15]]

^<<v58-9-15,15>>^ E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.

[[v58-9-16]]

^<<v58-9-16,16>>^ Porque, onde há testamento, necessário é que intervenha a morte do testador.

[[v58-9-17]]

^<<v58-9-17,17>>^ Porque um testamento tem força onde houve morte; ou terá ele algum valor enquanto o testador vive?

[[v58-9-18]]

^<<v58-9-18,18>>^ Pelo que também o primeiro não foi consagrado sem sangue;

[[v58-9-19]]

^<<v58-9-19,19>>^ porque, havendo Moisés anunciado a todo o povo todos os mandamentos segundo a lei, tomou o sangue dos bezerros e dos bodes, com água, lã purpúrea e hissopo, e aspergiu tanto o mesmo livro como todo o povo,

[[v58-9-20]]

^<<v58-9-20,20>>^ dizendo: Este é o sangue do testamento que Deus vos tem mandado.

[[v58-9-21]]

^<<v58-9-21,21>>^ E semelhantemente aspergiu com sangue o tabernáculo e todos os vasos do ministério.

[[v58-9-22]]

^<<v58-9-22,22>>^ E quase todas as coisas,  segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.

[[v58-9-23]]

^<<v58-9-23,23>>^ De sorte que era bem necessário que as figuras das coisas que estão no céu assim se purificassem; mas as próprias coisas celestiais, com sacrifícios melhores do que estes.

[[v58-9-24]]

^<<v58-9-24,24>>^ Porque Cristo não entrou num santuário feito por mãos, figura do verdadeiro, porém no mesmo céu, para agora comparecer, por nós, perante a face de Deus;

[[v58-9-25]]

^<<v58-9-25,25>>^ nem também para a si mesmo se oferecer muitas vezes, como o sumo sacerdote cada ano entra no Santuário com sangue alheio.

[[v58-9-26]]

^<<v58-9-26,26>>^ Doutra maneira, necessário lhe fora padecer muitas vezes desde a fundação do mundo; mas, agora, na consumação dos séculos, uma vez se manifestou, para aniquilar o pecado pelo sacrifício de si mesmo.

[[v58-9-27]]

^<<v58-9-27,27>>^ E, como aos homens está ordenado morrerem uma vez, vindo, depois disso,  o juízo,

[[v58-9-28]]

^<<v58-9-28,28>>^ assim também Cristo, oferecendo- se  uma vez, para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para a salvação.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]