include::./index.adoc[]

[[v53-1-0]]
=== 2 Tessalonicenses, 1
// arc ?, ARC - Almeida Revista e Corrigida

[[v53-1-1]]

^<<v53-1-1,1>>^ Paulo, e Silvano, e Timóteo, à igreja dos tessalonicenses, em Deus, nosso Pai, e no Senhor Jesus Cristo:

[[v53-1-2]]

^<<v53-1-2,2>>^ graça e paz a vós, da parte de Deus, nosso Pai, e da do Senhor Jesus Cristo.

[[v53-1-3]]

^<<v53-1-3,3>>^ Sempre devemos, irmãos, dar graças a Deus por vós, como é de razão, porque a vossa fé cresce muitíssimo, e o amor de cada um de vós aumenta de uns para com os outros,

[[v53-1-4]]

^<<v53-1-4,4>>^ de maneira que nós mesmos nos gloriamos de vós nas igrejas de Deus, por causa da vossa paciência e fé, e em todas as vossas perseguições e aflições que suportais,

[[v53-1-5]]

^<<v53-1-5,5>>^ prova clara do justo juízo de Deus, para que sejais havidos por dignos do Reino de Deus, pelo qual também padeceis;

[[v53-1-6]]

^<<v53-1-6,6>>^ se, de fato, é justo diante de Deus que dê em paga tribulação aos que vos atribulam,

[[v53-1-7]]

^<<v53-1-7,7>>^ e a vós, que sois atribulados, descanso conosco, quando se manifestar o Senhor Jesus desde o céu, com os anjos do seu poder,

[[v53-1-8]]

^<<v53-1-8,8>>^ como labareda de fogo, tomando vingança dos que não conhecem a Deus e dos que não obedecem ao evangelho de nosso Senhor Jesus Cristo;

[[v53-1-9]]

^<<v53-1-9,9>>^ os quais, por castigo, padecerão eterna perdição, ante a face do Senhor e a glória do seu poder,

[[v53-1-10]]

^<<v53-1-10,10>>^ quando vier para ser glorificado nos seus santos e para se fazer admirável, naquele Dia, em todos os que creem (porquanto o nosso testemunho foi crido entre vós).

[[v53-1-11]]

^<<v53-1-11,11>>^ Pelo que também rogamos sempre por vós, para que o nosso Deus vos faça dignos da sua  vocação e cumpra todo desejo da sua  bondade e a obra da fé com poder;

[[v53-1-12]]

^<<v53-1-12,12>>^ para que o nome de nosso Senhor Jesus Cristo seja em vós glorificado, e vós nele, segundo a graça de nosso Deus e do Senhor Jesus Cristo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[Próximo Capítulo &#62;]