include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// arc ?, ARC - Almeida Revista e Corrigida

[[v19-115-1]]

^<<v19-115-1,1>>^ Não a nós, SENHOR, não a nós, mas ao teu nome dá glória, por amor da tua benignidade e da tua verdade.

[[v19-115-2]]

^<<v19-115-2,2>>^ Por que dirão as nações: Onde está  o seu Deus?

[[v19-115-3]]

^<<v19-115-3,3>>^ Mas o nosso Deus está  nos céus e faz tudo o que lhe apraz.

[[v19-115-4]]

^<<v19-115-4,4>>^ Os ídolos deles são  prata e ouro, obra das mãos dos homens.

[[v19-115-5]]

^<<v19-115-5,5>>^ Têm boca, mas não falam; têm olhos, mas não veem;

[[v19-115-6]]

^<<v19-115-6,6>>^ têm ouvidos, mas não ouvem; nariz têm, mas não cheiram.

[[v19-115-7]]

^<<v19-115-7,7>>^ Têm mãos, mas não apalpam; têm pés, mas não andam; nem som algum sai da sua garganta.

[[v19-115-8]]

^<<v19-115-8,8>>^ Tornem-se semelhantes a eles os que os fazem e todos os que neles confiam.

[[v19-115-9]]

^<<v19-115-9,9>>^ Confia, ó Israel, no SENHOR; ele é teu auxílio e teu escudo.

[[v19-115-10]]

^<<v19-115-10,10>>^ Casa de Arão, confia no SENHOR; ele é  teu auxílio e teu escudo.

[[v19-115-11]]

^<<v19-115-11,11>>^ Vós, os que temeis ao SENHOR, confiai no SENHOR; ele é  vosso auxílio e vosso escudo.

[[v19-115-12]]

^<<v19-115-12,12>>^ O SENHOR, que se lembrou de nós, abençoará; abençoará a casa de Israel; abençoará a casa de Arão.

[[v19-115-13]]

^<<v19-115-13,13>>^ Abençoará os que temem ao SENHOR, tanto pequenos como grandes.

[[v19-115-14]]

^<<v19-115-14,14>>^ O SENHOR vos aumentará cada vez mais, a  vós e a  vossos filhos.

[[v19-115-15]]

^<<v19-115-15,15>>^ Sede benditos do SENHOR, que fez os céus e a terra.

[[v19-115-16]]

^<<v19-115-16,16>>^ Os céus são os céus do SENHOR; mas a terra, deu-a ele aos filhos dos homens.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos não louvam ao SENHOR, nem os que descem ao silêncio.

[[v19-115-18]]

^<<v19-115-18,18>>^ Mas nós bendiremos ao SENHOR, desde agora e para sempre. Louvai ao SENHOR!

'''

xref:019-salmos/019-salmos-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmos/019-salmos-116.adoc#v19-116-0[Próximo Capítulo &#62;]