include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// arc ?, ARC - Almeida Revista e Corrigida

[[v19-97-1]]

^<<v19-97-1,1>>^ O SENHOR reina. Regozije-se a terra, alegrem-se as muitas ilhas.

[[v19-97-2]]

^<<v19-97-2,2>>^ Nuvens e obscuridade estão  ao redor dele; justiça e juízo são  a base do seu trono.

[[v19-97-3]]

^<<v19-97-3,3>>^ Adiante dele vai um fogo que abrasa os seus inimigos em redor.

[[v19-97-4]]

^<<v19-97-4,4>>^ Os seus relâmpagos alumiam o mundo; a terra viu e tremeu.

[[v19-97-5]]

^<<v19-97-5,5>>^ Os montes se derretem como cera na presença do SENHOR, na presença do Senhor de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus anunciam a sua justiça, e todos os povos veem a sua glória.

[[v19-97-7]]

^<<v19-97-7,7>>^ Confundidos sejam todos os que servem a imagens de escultura, que se gloriam de ídolos inúteis; prostrai-vos diante dele todos os deuses.

[[v19-97-8]]

^<<v19-97-8,8>>^ Sião ouviu e se alegrou; e os filhos de Judá se alegraram por causa da tua justiça, ó SENHOR.

[[v19-97-9]]

^<<v19-97-9,9>>^ Pois tu, SENHOR, és  o Altíssimo em toda a terra; muito mais elevado que todos os deuses.

[[v19-97-10]]

^<<v19-97-10,10>>^ Vós que amais ao SENHOR, aborrecei o mal; ele guarda a alma dos seus santos, ele os livra das mãos dos ímpios.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz semeia-se para o justo, e a alegria, para os retos de coração.

[[v19-97-12]]

^<<v19-97-12,12>>^ Alegrai-vos, ó justos, no SENHOR, e dai louvores em memória da sua santidade.

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]