include::./index.adoc[]

[[v19-12-0]]
=== Salmos, 12
// arc ?, ARC - Almeida Revista e Corrigida

[[v19-12-1]]

^<<v19-12-1,1>>^ Salva-nos, SENHOR, porque faltam os homens benignos; porque são poucos os fiéis entre os filhos dos homens.

[[v19-12-2]]

^<<v19-12-2,2>>^ Cada um fala com falsidade ao seu próximo; falam com  lábios lisonjeiros e coração dobrado.

[[v19-12-3]]

^<<v19-12-3,3>>^ O SENHOR cortará todos os lábios lisonjeiros e  a língua que fala soberbamente.

[[v19-12-4]]

^<<v19-12-4,4>>^ Pois dizem: Com a nossa língua prevaleceremos; os lábios são  nossos; quem é  o senhor sobre nós?

[[v19-12-5]]

^<<v19-12-5,5>>^ Por causa da opressão dos pobres e do gemido dos necessitados, me levantarei agora, diz o SENHOR; porei em salvo aquele  para quem eles assopram.

[[v19-12-6]]

^<<v19-12-6,6>>^ As palavras do Senhor são  palavras puras como  prata refinada em forno de barro e purificada sete vezes.

[[v19-12-7]]

^<<v19-12-7,7>>^ Tu nos guardarás, SENHOR; desta geração nos livrarás para sempre.

[[v19-12-8]]

^<<v19-12-8,8>>^ Os ímpios circulam por toda parte quando os mais vis dos filhos dos homens são exaltados.

'''

xref:019-salmos/019-salmos-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-salmos/019-salmos-013.adoc#v19-13-0[Próximo Capítulo &#62;]