include::./index.adoc[]

[[v19-147-0]]
=== Salmos, 147
// arc ?, ARC - Almeida Revista e Corrigida

[[v19-147-1]]

^<<v19-147-1,1>>^ Louvai ao SENHOR, porque é bom cantar louvores ao nosso Deus; isto é  agradável; decoroso é  o louvor.

[[v19-147-2]]

^<<v19-147-2,2>>^ O SENHOR edifica Jerusalém; congrega os dispersos de Israel;

[[v19-147-3]]

^<<v19-147-3,3>>^ sara os quebrantados de coração e liga-lhes as feridas;

[[v19-147-4]]

^<<v19-147-4,4>>^ conta o número das estrelas, chamando-as a todas pelos seus  nomes.

[[v19-147-5]]

^<<v19-147-5,5>>^ Grande é  o nosso SENHOR e de grande poder; o seu entendimento é  infinito.

[[v19-147-6]]

^<<v19-147-6,6>>^ O SENHOR eleva os humildes e abate os ímpios até à terra.

[[v19-147-7]]

^<<v19-147-7,7>>^ Cantai ao SENHOR em ação de graças; cantai louvores ao nosso Deus sobre a harpa.

[[v19-147-8]]

^<<v19-147-8,8>>^ Ele é  que cobre o céu de nuvens, que prepara a chuva para a terra e  que faz produzir erva sobre os montes;

[[v19-147-9]]

^<<v19-147-9,9>>^ que dá aos animais o seu sustento e  aos filhos dos corvos, quando clamam.

[[v19-147-10]]

^<<v19-147-10,10>>^ Não se deleita na força do cavalo, nem se compraz na agilidade do varão.

[[v19-147-11]]

^<<v19-147-11,11>>^ O SENHOR agrada-se dos que o temem e  dos que esperam na sua misericórdia.

[[v19-147-12]]

^<<v19-147-12,12>>^ Louva, ó Jerusalém, ao SENHOR; louva, ó Sião, ao teu Deus.

[[v19-147-13]]

^<<v19-147-13,13>>^ Porque ele fortaleceu os ferrolhos das tuas portas; abençoa aos teus filhos dentro de ti.

[[v19-147-14]]

^<<v19-147-14,14>>^ Ele é  quem pacifica os teus termos e  da flor da farinha te farta;

[[v19-147-15]]

^<<v19-147-15,15>>^ quem envia o seu mandamento à terra; a sua palavra corre velozmente;

[[v19-147-16]]

^<<v19-147-16,16>>^ quem dá a neve como lã e esparge a geada como cinza;

[[v19-147-17]]

^<<v19-147-17,17>>^ quem lança o seu gelo em pedaços; quem pode resistir ao seu frio?

[[v19-147-18]]

^<<v19-147-18,18>>^ Manda a sua palavra e os faz derreter; faz soprar o vento, e correm as águas.

[[v19-147-19]]

^<<v19-147-19,19>>^ Mostra a sua palavra a Jacó, os seus estatutos e os seus juízos, a Israel.

[[v19-147-20]]

^<<v19-147-20,20>>^ Não fez assim a nenhuma outra nação; e, quanto aos seus juízos, nenhuma os conhece. Louvai ao SENHOR!

'''

xref:019-salmos/019-salmos-146.adoc#v19-146-0[&#60; Capítulo Anterior] | <<v19-147-0,Topo>> | xref:019-salmos/019-salmos-148.adoc#v19-148-0[Próximo Capítulo &#62;]