include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// arc ?, ARC - Almeida Revista e Corrigida

[[v19-65-1]]

^<<v19-65-1,1>>^ A ti, ó Deus, espera o louvor em Sião, e a ti se pagará o voto.

[[v19-65-2]]

^<<v19-65-2,2>>^ Ó tu que ouves as orações! A ti virá toda a carne.

[[v19-65-3]]

^<<v19-65-3,3>>^ Prevalecem as iniquidades contra mim; mas tu perdoas as nossas transgressões.

[[v19-65-4]]

^<<v19-65-4,4>>^ Bem-aventurado aquele a quem  tu escolhes e fazes chegar a ti, para que  habite em teus átrios; nós seremos satisfeitos da bondade da tua casa e  do teu santo templo.

[[v19-65-5]]

^<<v19-65-5,5>>^ Com coisas tremendas de justiça nos responderás, ó Deus da nossa salvação; tu és a esperança de todas as extremidades da terra e daqueles que estão longe sobre o mar;

[[v19-65-6]]

^<<v19-65-6,6>>^ o que pela sua força consolida os montes, cingido de fortaleza;

[[v19-65-7]]

^<<v19-65-7,7>>^ o que aplaca o ruído dos mares, o ruído das suas ondas e o tumulto das nações.

[[v19-65-8]]

^<<v19-65-8,8>>^ E os que habitam nos confins da terra  temem os teus sinais; tu fazes alegres as saídas da manhã e da tarde.

[[v19-65-9]]

^<<v19-65-9,9>>^ Tu visitas a terra e a refrescas; tu a enriqueces grandemente com o rio de Deus, que está  cheio de água; tu lhe dás o trigo, quando assim a tens preparada;

[[v19-65-10]]

^<<v19-65-10,10>>^ tu enches de água  os seus sulcos, regulando a sua altura; tu a amoleces com a muita chuva; tu abençoas as suas novidades;

[[v19-65-11]]

^<<v19-65-11,11>>^ tu coroas o ano da tua bondade, e as tuas veredas destilam gordura;

[[v19-65-12]]

^<<v19-65-12,12>>^ destilam sobre  os pastos do deserto, e os outeiros cingem-se de alegria.

[[v19-65-13]]

^<<v19-65-13,13>>^ Os campos cobrem-se de rebanhos, e os vales vestem-se de trigo; por isso, eles se regozijam e cantam.

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]