include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// arc ?, ARC - Almeida Revista e Corrigida

[[v15-6-1]]

^<<v15-6-1,1>>^ Então, o rei Dario deu ordem, e buscaram na chancelaria, onde se metiam os tesouros em Babilônia.

[[v15-6-2]]

^<<v15-6-2,2>>^ E em Acmetá, no palácio que está na província de Média, se achou um rolo, e nele estava escrito um  memorial, que dizia  assim:

[[v15-6-3]]

^<<v15-6-3,3>>^ No ano primeiro do rei Ciro, o rei Ciro deu esta  ordem: Com respeito à Casa de Deus em Jerusalém, essa  casa se edificará para lugar em que se ofereçam sacrifícios, e seus fundamentos serão firmes; a sua altura, de sessenta côvados, e a sua largura, de sessenta côvados,

[[v15-6-4]]

^<<v15-6-4,4>>^ com  três carreiras de grandes pedras e uma carreira de madeira nova; e a despesa se fará da casa do rei.

[[v15-6-5]]

^<<v15-6-5,5>>^ Demais disto, os utensílios de ouro e de prata da Casa de Deus, que Nabucodonosor transportou do templo que estava  em Jerusalém e levou para Babilônia, se tornarão a dar, para que vão ao seu lugar, ao templo que está  em Jerusalém, e os levarão à Casa de Deus.

[[v15-6-6]]

^<<v15-6-6,6>>^ Agora, pois,  Tatenai, governador de além do rio, Setar-Bozenai e os seus companheiros, os afarsaquitas, que estais  de além do rio, apartai-vos dali.

[[v15-6-7]]

^<<v15-6-7,7>>^ Deixa- os  na obra desta Casa de Deus, para que  o governador dos judeus e os judeus edifiquem esta Casa de Deus no seu lugar.

[[v15-6-8]]

^<<v15-6-8,8>>^ Também por mim se decreta o que haveis de fazer com os anciãos dos judeus, para que edifiquem a Casa de Deus, a saber,  que da fazenda do rei, dos tributos dalém do rio, se pague prontamente a despesa a estes homens, para que não sejam impedidos.

[[v15-6-9]]

^<<v15-6-9,9>>^ E o que for  necessário, como bezerros, e carneiros, e cordeiros, para holocausto ao Deus dos céus, trigo, sal, vinho e azeite, segundo o rito dos sacerdotes que estão  em Jerusalém, dê-se-lhes de dia em dia, para que não haja  falta;

[[v15-6-10]]

^<<v15-6-10,10>>^ para que ofereçam sacrifícios de cheiro suave ao Deus dos céus e orem pela vida do rei e de seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ Também por mim se decreta que todo homem que mudar este decreto, um madeiro se arrancará da sua casa, e, levantado, o pendurarão nele, e da sua casa se fará por isso um monturo.

[[v15-6-12]]

^<<v15-6-12,12>>^ O Deus, pois, que fez habitar ali o seu nome derribe a todos os reis e povos que estenderem a sua mão para o  mudarem e  para destruírem esta Casa de Deus, que está  em Jerusalém. Eu, Dario, dei o decreto; apressuradamente se execute.

[[v15-6-13]]

^<<v15-6-13,13>>^ Então, Tatenai, o governador de além do rio, Setar-Bozenai e os seus companheiros assim fizeram apressuradamente, conforme o que decretara o rei Dario.

[[v15-6-14]]

^<<v15-6-14,14>>^ E os anciãos dos judeus iam edificando e prosperando pela profecia do profeta Ageu e de Zacarias, filho de Ido; e edificaram a casa  e a  aperfeiçoaram conforme o mandado do Deus de Israel, e conforme o mandado de Ciro, e de Dario, e de Artaxerxes, rei da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ E acabou-se esta casa no dia terceiro do mês de Adar, que era o sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ E os filhos de Israel, e os sacerdotes, e os levitas, e o resto dos filhos do cativeiro fizeram a consagração desta Casa de Deus com alegria.

[[v15-6-17]]

^<<v15-6-17,17>>^ E ofereceram para a consagração desta Casa de Deus cem novilhos, duzentos carneiros, quatrocentos cordeiros e doze cabritos, por expiação  do pecado de todo o Israel, segundo o número das tribos de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ E puseram os sacerdotes nas suas turmas e os levitas nas suas divisões, para o ministério de Deus, que está  em Jerusalém, conforme o escrito do livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ E os que vieram do cativeiro celebraram a Páscoa no dia catorze do primeiro mês;

[[v15-6-20]]

^<<v15-6-20,20>>^ porque os sacerdotes e levitas se tinham purificado como se fossem  um só homem,  e todos estavam  limpos; e mataram o cordeiro da  Páscoa para todos os filhos do cativeiro, e para seus irmãos, os sacerdotes, e para si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Assim, comeram a Páscoa  os filhos de Israel que tinham voltado do cativeiro, com todos os que a eles se apartavam da imundícia das nações da terra, para buscarem o SENHOR, Deus de Israel.

[[v15-6-22]]

^<<v15-6-22,22>>^ E celebraram a Festa dos Pães Asmos os sete dias com alegria, porque o SENHOR os tinha alegrado e tinha mudado o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da Casa de Deus, o Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]