include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// arc ?, ARC - Almeida Revista e Corrigida

[[v15-8-1]]

^<<v15-8-1,1>>^ Estes, pois, são  os chefes de seus pais, com as suas genealogias, os que subiram comigo de Babilônia no reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ dos filhos de Fineias, Gérson; dos filhos de Itamar, Daniel; dos filhos de Davi, Hatus;

[[v15-8-3]]

^<<v15-8-3,3>>^ dos filhos de Secanias e  dos filhos de Parós, Zacarias, e com ele por genealogias se contaram até cento e cinquenta homens;

[[v15-8-4]]

^<<v15-8-4,4>>^ dos filhos de Paate-Moabe, Elioenai, filho de Zeraías, e, com ele, duzentos homens;

[[v15-8-5]]

^<<v15-8-5,5>>^ dos filhos de Secanias, o filho de Jaaziel, e, com ele, trezentos homens;

[[v15-8-6]]

^<<v15-8-6,6>>^ e dos filhos de Adim, Ebede, filho de Jônatas, e, com ele, cinquenta homens;

[[v15-8-7]]

^<<v15-8-7,7>>^ e dos filhos de Elão, Jesaías, filho de Atalias, e, com ele, setenta homens;

[[v15-8-8]]

^<<v15-8-8,8>>^ e dos filhos de Sefatias, Zebadias, filho de Micael, e, com ele, oitenta homens;

[[v15-8-9]]

^<<v15-8-9,9>>^ dos filhos de Joabe, Obadias, filho de Jeiel, e, com ele, duzentos e dezoito homens;

[[v15-8-10]]

^<<v15-8-10,10>>^ e dos filhos de Selomite, o filho de Josifias, e, com ele, cento e sessenta homens;

[[v15-8-11]]

^<<v15-8-11,11>>^ e dos filhos de Bebai, Zacarias, o filho de Bebai, e, com ele, vinte e oito homens;

[[v15-8-12]]

^<<v15-8-12,12>>^ e dos filhos de Azgade, Joanã, o filho de Hacatã, e, com ele, cento e dez homens;

[[v15-8-13]]

^<<v15-8-13,13>>^ e dos últimos filhos de Adonicão, seus nomes eram estes: Elifelete, Jeiel e Semaías, e, com eles, sessenta homens;

[[v15-8-14]]

^<<v15-8-14,14>>^ e dos filhos de Bigvai, Utai e Zabude, e, com eles, setenta homens.

[[v15-8-15]]

^<<v15-8-15,15>>^ E ajuntei-os perto do rio que vai a Aava, e ficamos ali acampados três dias; então, atentei para o povo e para os sacerdotes e não achei ali nenhum dos filhos de Levi.

[[v15-8-16]]

^<<v15-8-16,16>>^ Enviei, pois, Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, os chefes, como também a Joiaribe e a Elnatã, que eram  sábios.

[[v15-8-17]]

^<<v15-8-17,17>>^ E dei-lhes mandado para Ido, chefe no lugar de Casifia, e lhes pus palavras na boca para dizerem a Ido, seu irmão, e  aos netineus, no lugar de Casifia, que nos trouxessem ministros para a Casa do nosso Deus.

[[v15-8-18]]

^<<v15-8-18,18>>^ E trouxeram-nos, segundo a boa mão de Deus sobre nós, um homem sábio, dos filhos de Mali, filho de Levi, filho de Israel, a saber,  Serebias, com os seus filhos e irmãos, dezoito;

[[v15-8-19]]

^<<v15-8-19,19>>^ e a Hasabias e com ele Jesaías, dos filhos de Merari, com seus irmãos e os filhos deles, vinte;

[[v15-8-20]]

^<<v15-8-20,20>>^ e dos netineus, que Davi e os príncipes deram para o ministério dos levitas, duzentos e vinte netineus, que todos foram expressos por seus  nomes.

[[v15-8-21]]

^<<v15-8-21,21>>^ Então, apregoei ali um jejum junto ao rio Aava, para nos humilharmos diante da face de nosso Deus, para lhe pedirmos caminho direito para nós, e para nossos filhos, e para toda a nossa fazenda.

[[v15-8-22]]

^<<v15-8-22,22>>^ Porque me envergonhei de pedir ao rei exército e cavaleiros para nos defenderem do inimigo no caminho, porquanto tínhamos falado ao rei, dizendo: A mão do nosso Deus é  sobre todos os que o buscam para o bem, mas a sua força e a sua ira, sobre todos os que o deixam.

[[v15-8-23]]

^<<v15-8-23,23>>^ Nós, pois, jejuamos e pedimos isso ao nosso Deus, e moveu-se pelas nossas orações.

[[v15-8-24]]

^<<v15-8-24,24>>^ Então, separei doze dos maiorais dos sacerdotes: Serebias, Hasabias e com eles dez dos seus irmãos.

[[v15-8-25]]

^<<v15-8-25,25>>^ E pesei-lhes a prata, e o ouro, e os utensílios, que eram  a oferta para a Casa de nosso Deus, a qual ofereceram o rei, e os seus conselheiros, e os seus príncipes, e todo o Israel que ali se achou.

[[v15-8-26]]

^<<v15-8-26,26>>^ E pesei em suas mãos seiscentos e cinquenta talentos de prata, e em objetos de prata cem talentos, e cem talentos de ouro.

[[v15-8-27]]

^<<v15-8-27,27>>^ E vinte taças de ouro de mil daricos e dois vasos de bom metal lustroso, tão  desejável como ouro.

[[v15-8-28]]

^<<v15-8-28,28>>^ E disse-lhes: Consagrados sois do SENHOR, e sagrados são  estes vasos, como também esta prata e este ouro, oferta voluntária, oferecida  ao SENHOR, Deus de vossos pais.

[[v15-8-29]]

^<<v15-8-29,29>>^ Vigiai, pois,  e guardai- os  até que os  peseis na presença dos maiorais dos sacerdotes, e dos levitas, e dos príncipes dos pais de Israel, em Jerusalém, nas câmaras da Casa do SENHOR.

[[v15-8-30]]

^<<v15-8-30,30>>^ Então, receberam os sacerdotes e os levitas o peso da prata, e do ouro, e dos vasos, para trazerem a Jerusalém, à Casa de nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ E partimos do rio de Aava, no dia doze do primeiro mês, para irmos para Jerusalém; e a boa mão do nosso Deus estava sobre nós e livrou-nos da mão dos inimigos e dos que nos  armavam ciladas no caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ E viemos a Jerusalém e repousamos ali três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ E no dia quatro se pesou a prata, e o ouro, e os vasos, na Casa do nosso Deus, por mão de Meremote, filho do sacerdote Urias; e com ele estava Eleazar, filho de Fineias, e com eles, Jozabade, filho de Jesua, e Noadias, filho de Binui, levitas;

[[v15-8-34]]

^<<v15-8-34,34>>^ conforme o número e  conforme o peso de tudo aquilo; e todo o peso se descreveu no mesmo tempo.

[[v15-8-35]]

^<<v15-8-35,35>>^ E os transportados que vieram do cativeiro ofereceram holocaustos ao Deus de Israel: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros e  doze bodes em sacrifício  pelo pecado; tudo em  holocausto ao SENHOR.

[[v15-8-36]]

^<<v15-8-36,36>>^ Então, deram as ordens do rei aos sátrapas do rei e aos governadores de aquém do rio; e ajudaram o povo e a Casa de Deus.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]