include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// arc ?, ARC - Almeida Revista e Corrigida

[[v39-2-1]]

^<<v39-2-1,1>>^ E, agora, ó sacerdotes, este mandamento vos toca  a vós.

[[v39-2-2]]

^<<v39-2-2,2>>^ Se o  não ouvirdes e se não propuserdes no vosso coração dar honra ao meu nome, diz o SENHOR dos Exércitos, enviarei a maldição contra vós e amaldiçoarei as vossas bênçãos; e já as tenho amaldiçoado, porque vós não pondes isso  no coração.

[[v39-2-3]]

^<<v39-2-3,3>>^ Eis que vos corromperei a semente e espalharei esterco sobre o vosso rosto, o esterco das vossas festas; e com ele sereis tirados.

[[v39-2-4]]

^<<v39-2-4,4>>^ Então, sabereis que eu vos enviei este mandamento, para que o meu concerto seja com Levi, diz o SENHOR dos Exércitos.

[[v39-2-5]]

^<<v39-2-5,5>>^ Meu concerto com ele foi de vida e de paz, e eu lhas dei para que me temesse, e me temeu e assombrou-se por causa do meu nome.

[[v39-2-6]]

^<<v39-2-6,6>>^ A lei da verdade esteve na sua boca, e a iniquidade não se achou nos seus lábios; andou comigo em paz e em retidão e apartou a muitos da iniquidade.

[[v39-2-7]]

^<<v39-2-7,7>>^ Porque os lábios do sacerdote guardarão a ciência, e da sua boca buscarão a lei, porque ele é  o anjo do SENHOR dos Exércitos.

[[v39-2-8]]

^<<v39-2-8,8>>^ Mas vós vos desviastes do caminho, a muitos fizestes tropeçar na lei: corrompestes o concerto de Levi, diz o SENHOR dos Exércitos.

[[v39-2-9]]

^<<v39-2-9,9>>^ Por isso, também eu vos fiz desprezíveis e indignos diante de todo o povo, visto que não guardastes os meus caminhos, mas fizestes acepção de pessoas na lei.

[[v39-2-10]]

^<<v39-2-10,10>>^ Não temos nós todos um mesmo  Pai? Não nos criou um mesmo  Deus? Por que seremos desleais uns para com os outros, profanando o concerto de nossos pais?

[[v39-2-11]]

^<<v39-2-11,11>>^ Judá foi desleal, e abominação se cometeu em Israel e em Jerusalém; porque Judá profanou a santidade do SENHOR, a qual ele ama, e se casou com a filha de deus estranho.

[[v39-2-12]]

^<<v39-2-12,12>>^ O SENHOR extirpará das tendas de Jacó o homem que fizer isso, o que vela, e o que responde, e o que oferece dons ao SENHOR dos Exércitos.

[[v39-2-13]]

^<<v39-2-13,13>>^ Ainda fazeis isto: cobris o altar do SENHOR de lágrimas, de choros e de gemidos; de sorte que ele não olha mais para a oferta, nem a aceitará com prazer da vossa mão.

[[v39-2-14]]

^<<v39-2-14,14>>^ E dizeis: Por quê? Porque o SENHOR foi testemunha entre ti e a mulher da tua mocidade, com a qual tu foste desleal, sendo ela a tua companheira e a mulher do teu concerto.

[[v39-2-15]]

^<<v39-2-15,15>>^ E não fez ele somente um, sobejando-lhe espírito? E por que somente um? Ele buscava uma semente de piedosos; portanto, guardai-vos em vosso espírito, e ninguém seja desleal para com a mulher da sua mocidade.

[[v39-2-16]]

^<<v39-2-16,16>>^ Porque o SENHOR, Deus de Israel, diz que aborrece o repúdio e aquele que encobre a violência com a sua veste, diz o SENHOR dos Exércitos; portanto, guardai-vos em vosso espírito e não sejais desleais.

[[v39-2-17]]

^<<v39-2-17,17>>^ Enfadais ao SENHOR com vossas palavras; e ainda dizeis: Em que o enfadamos? Nisto, que dizeis: Qualquer que faz o mal passa por bom aos olhos do SENHOR, e desses é que ele se agrada; ou onde está  o Deus do juízo?

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]