include::./index.adoc[]

[[v5-30-0]]
=== Deuteronômio, 30
// arc ?, ARC - Almeida Revista e Corrigida

[[v5-30-1]]

^<<v5-30-1,1>>^ E será que,  sobrevindo-te todas estas coisas, a bênção ou a maldição, que tenho posto diante de ti, e te recordares delas  entre todas as nações, para onde te lançar o SENHOR, teu Deus;

[[v5-30-2]]

^<<v5-30-2,2>>^ e te converteres ao SENHOR, teu Deus, e deres ouvidos à sua voz conforme tudo o que eu te ordeno hoje, tu e teus filhos, com todo o teu coração e com toda a tua alma,

[[v5-30-3]]

^<<v5-30-3,3>>^ então, o SENHOR, teu Deus, te fará voltar do teu cativeiro, e se apiedará de ti, e tornará a ajuntar-te dentre todas as nações entre as quais te espalhou o SENHOR, teu Deus.

[[v5-30-4]]

^<<v5-30-4,4>>^ Ainda que os teus desterrados estejam para a extremidade do céu, desde ali te ajuntará o SENHOR, teu Deus, e te tomará dali.

[[v5-30-5]]

^<<v5-30-5,5>>^ E o SENHOR, teu Deus, te trará à terra que teus pais possuíram, e a possuirás; e te fará bem e te multiplicará mais do que a teus pais.

[[v5-30-6]]

^<<v5-30-6,6>>^ E o SENHOR, teu Deus, circuncidará o teu coração e o coração de tua semente, para amares ao SENHOR, teu Deus, com todo o coração e com toda a tua alma, para que vivas.

[[v5-30-7]]

^<<v5-30-7,7>>^ E o SENHOR, teu Deus, porá todas estas maldições sobre os teus inimigos e sobre os teus aborrecedores, que te perseguiram.

[[v5-30-8]]

^<<v5-30-8,8>>^ Converter-te-ás, pois, e darás ouvidos à voz do SENHOR; farás todos os seus mandamentos, que hoje te ordeno.

[[v5-30-9]]

^<<v5-30-9,9>>^ E o SENHOR, teu Deus, te dará abundância em toda obra das tuas mãos, no fruto do teu ventre, e no fruto dos teus animais, e no fruto da tua terra para bem; porquanto o SENHOR tornará a alegrar-se em ti para bem, como se alegrou em teus pais;

[[v5-30-10]]

^<<v5-30-10,10>>^ quando deres ouvidos à voz do SENHOR, teu Deus, guardando os seus mandamentos e os seus estatutos, escritos neste livro da Lei, quando te converteres ao SENHOR, teu Deus, com todo o teu coração e com toda a tua alma.

[[v5-30-11]]

^<<v5-30-11,11>>^ Porque este mandamento, que hoje te ordeno, te não é  encoberto e tampouco está  longe de ti.

[[v5-30-12]]

^<<v5-30-12,12>>^ Não está  nos céus, para dizeres: Quem subirá por nós aos céus, que no-lo traga e no-lo faça ouvir, para que o façamos?

[[v5-30-13]]

^<<v5-30-13,13>>^ Nem tampouco está  dalém do mar, para dizeres: Quem passará por nós dalém do mar, para que no-lo traga e no-lo faça ouvir, para que o façamos?

[[v5-30-14]]

^<<v5-30-14,14>>^ Porque esta palavra está  mui perto de ti, na tua boca e no teu coração, para a fazeres.

[[v5-30-15]]

^<<v5-30-15,15>>^ Vês aqui, hoje te tenho proposto a vida e o bem, a morte e o mal;

[[v5-30-16]]

^<<v5-30-16,16>>^ porquanto te ordeno, hoje, que ames o SENHOR, teu Deus, que andes nos seus caminhos e que guardes os seus mandamentos, e os seus estatutos, e os seus juízos, para que vivas e te multipliques, e o SENHOR, teu Deus, te abençoe na terra, a qual passas a possuir.

[[v5-30-17]]

^<<v5-30-17,17>>^ Porém, se o teu coração se desviar, e não quiseres dar ouvidos, e fores seduzido para te inclinares a outros deuses, e os servires,

[[v5-30-18]]

^<<v5-30-18,18>>^ então, eu te denuncio, hoje, que, certamente, perecerás; não prolongarás os dias na terra a que vais, passando o Jordão, para que, entrando nela, a possuas.

[[v5-30-19]]

^<<v5-30-19,19>>^ Os céus e a terra tomo, hoje, por testemunhas contra ti, que  te tenho proposto a vida e a morte, a bênção e a maldição; escolhe, pois, a vida, para que vivas, tu e a tua semente,

[[v5-30-20]]

^<<v5-30-20,20>>^ amando ao SENHOR, teu Deus, dando ouvidos à sua voz e te achegando a ele; pois ele é a tua vida e a longura dos teus dias; para que fiques na terra que o SENHOR jurou a teus pais, a Abraão, a Isaque e a Jacó, que lhes havia de dar.

'''

xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[Próximo Capítulo &#62;]