include::./index.adoc[]

[[v5-31-0]]
=== Deuteronômio, 31
// arc ?, ARC - Almeida Revista e Corrigida

[[v5-31-1]]

^<<v5-31-1,1>>^ Depois, foi Moisés, e falou estas palavras a todo o Israel,

[[v5-31-2]]

^<<v5-31-2,2>>^ e disse-lhes: Da idade de cento e vinte anos sou  eu hoje; já não poderei mais sair e entrar; além disso, o SENHOR me disse: Não passarás o Jordão.

[[v5-31-3]]

^<<v5-31-3,3>>^ O SENHOR, teu Deus, passará adiante de ti; ele destruirá estas nações diante de ti, para que as possuas; Josué passará adiante de ti, como o SENHOR tem dito.

[[v5-31-4]]

^<<v5-31-4,4>>^ E o SENHOR lhes fará como fez a Seom, e a Ogue, reis dos amorreus, e à sua terra, os quais destruiu.

[[v5-31-5]]

^<<v5-31-5,5>>^ Quando, pois, o SENHOR vo-los der diante de vós, então, com eles fareis conforme todo o mandamento que vos tenho ordenado.

[[v5-31-6]]

^<<v5-31-6,6>>^ Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles, porque o SENHOR, vosso Deus, é o que vai convosco; não vos deixará nem vos desamparará.

[[v5-31-7]]

^<<v5-31-7,7>>^ E chamou Moisés a Josué e lhe disse aos olhos de todo o Israel: Esforça-te e anima-te, porque com este povo entrarás na terra que o SENHOR jurou a teus pais lhes dar; e tu os farás herdá-la.

[[v5-31-8]]

^<<v5-31-8,8>>^ O SENHOR, pois, é  aquele que vai adiante de ti; ele será contigo, não te deixará, nem te desamparará; não temas, nem te espantes.

[[v5-31-9]]

^<<v5-31-9,9>>^ E Moisés escreveu esta Lei, e a deu aos sacerdotes, filhos de Levi, que levavam a arca do concerto do SENHOR, e a todos os anciãos de Israel.

[[v5-31-10]]

^<<v5-31-10,10>>^ E deu-lhes ordem Moisés, dizendo: Ao fim de cada  sete anos, no tempo determinado  do ano da remissão, na Festa dos Tabernáculos,

[[v5-31-11]]

^<<v5-31-11,11>>^ quando todo o Israel vier a comparecer perante o SENHOR, teu Deus, no lugar que ele escolher, lerás esta Lei diante de todo o Israel aos seus ouvidos.

[[v5-31-12]]

^<<v5-31-12,12>>^ Ajunta o povo, homens, e mulheres, e meninos, e os teus estrangeiros que estão dentro das tuas portas, para que ouçam, e aprendam, e temam ao SENHOR, vosso Deus, e tenham cuidado de fazer todas as palavras desta Lei;

[[v5-31-13]]

^<<v5-31-13,13>>^ e que  seus filhos que a não souberem ouçam e aprendam a temer ao SENHOR, vosso Deus, todos os dias que viverdes sobre a terra, a que ides, passando o Jordão, para possuí-la.

[[v5-31-14]]

^<<v5-31-14,14>>^ E disse o SENHOR a Moisés: Eis que os teus dias são chegados, para que morras; chama a Josué, e ponde-vos na tenda da congregação, para que eu lhe dê ordem. Assim, foi Moisés e Josué, e se puseram na tenda da congregação.

[[v5-31-15]]

^<<v5-31-15,15>>^ Então, o SENHOR apareceu na tenda, na coluna de nuvem; e a coluna de nuvem estava sobre a porta da tenda.

[[v5-31-16]]

^<<v5-31-16,16>>^ E disse o SENHOR a Moisés: Eis que dormirás com teus pais; e este povo se levantará, e se prostituirá, indo após os deuses dos estranhos da terra para o meio dos quais vai, e me deixará, e anulará o meu concerto que tenho feito com ele.

[[v5-31-17]]

^<<v5-31-17,17>>^ Assim, se acenderá a minha ira, naquele dia, contra ele, e desampará-lo-ei, e esconderei o meu rosto dele, para que seja devorado; e tantos males e angústias o alcançarão, que dirá, naquele dia: Não me alcançaram estes males por não estar o meu Deus no meio de mim?

[[v5-31-18]]

^<<v5-31-18,18>>^ Esconderei, pois, totalmente o meu rosto, naquele dia, por todo o mal que tiver feito, por se haver tornado a outros deuses.

[[v5-31-19]]

^<<v5-31-19,19>>^ Agora, pois, escrevei-vos este cântico e ensinai-o aos filhos de Israel; ponde-o na sua boca, para que este cântico me seja por testemunha contra os filhos de Israel.

[[v5-31-20]]

^<<v5-31-20,20>>^ Porque os meterei na terra que jurei a seus pais, a qual mana leite e mel; e comerão, e se fartarão, e se engordarão; então, se tornarão a outros deuses, e os servirão, e me irritarão, e anularão o meu concerto.

[[v5-31-21]]

^<<v5-31-21,21>>^ E será que,  quando os alcançarem muitos males e angústias, então, este cântico responderá contra eles por testemunha, pois não será esquecido da boca de sua semente; porquanto conheço a sua imaginação, o que eles fazem hoje, antes que os meta na terra que tenho jurado.

[[v5-31-22]]

^<<v5-31-22,22>>^ Assim, Moisés escreveu este cântico naquele dia e o ensinou aos filhos de Israel.

[[v5-31-23]]

^<<v5-31-23,23>>^ E ordenou a Josué, filho de Num, e disse: Esforça-te e anima-te, porque tu meterás os filhos de Israel na terra que lhes jurei; e eu serei contigo.

[[v5-31-24]]

^<<v5-31-24,24>>^ E aconteceu que,  acabando Moisés de escrever as palavras desta Lei num livro, até de todo as acabar,

[[v5-31-25]]

^<<v5-31-25,25>>^ deu ordem Moisés aos levitas que levavam a arca do concerto do SENHOR, dizendo:

[[v5-31-26]]

^<<v5-31-26,26>>^ Tomai este livro da Lei e ponde-o ao lado da arca do concerto do SENHOR, vosso Deus, para que ali esteja por testemunha contra ti.

[[v5-31-27]]

^<<v5-31-27,27>>^ Porque conheço a tua rebelião e a tua dura cerviz; eis que, vivendo eu ainda hoje convosco, rebeldes fostes contra o SENHOR; e quanto mais depois da minha morte.

[[v5-31-28]]

^<<v5-31-28,28>>^ Ajuntai perante mim todos os anciãos das vossas tribos e vossos oficiais, e aos vossos ouvidos falarei estas palavras e contra eles por testemunhas tomarei os céus e a terra.

[[v5-31-29]]

^<<v5-31-29,29>>^ Porque eu sei que, depois da minha morte, certamente vos corrompereis e vos desviareis do caminho que vos ordenei; então, este mal vos alcançará nos últimos dias, quando fizerdes mal aos olhos do SENHOR, para o provocar à ira com a obra das vossas mãos.

[[v5-31-30]]

^<<v5-31-30,30>>^ Então, Moisés falou as palavras deste cântico aos ouvidos de toda a congregação de Israel, até se acabarem:

'''

xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[&#60; Capítulo Anterior] | <<v5-31-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[Próximo Capítulo &#62;]