include::./index.adoc[]

[[v5-18-0]]
=== Deuteronômio, 18
// arc ?, ARC - Almeida Revista e Corrigida

[[v5-18-1]]

^<<v5-18-1,1>>^ Os sacerdotes levitas, toda a tribo de Levi, não terão parte nem herança em Israel; das ofertas queimadas do SENHOR e da sua herança comerão.

[[v5-18-2]]

^<<v5-18-2,2>>^ Pelo que não terão herança no meio de seus irmãos; o Senhor é  a sua herança, como lhe tem dito.

[[v5-18-3]]

^<<v5-18-3,3>>^ Este, pois, será o direito dos sacerdotes, a receber  do povo, dos que sacrificarem sacrifício, seja boi ou gado miúdo: que darão ao sacerdote a espádua, e as queixadas, e o bucho.

[[v5-18-4]]

^<<v5-18-4,4>>^ Dar-lhe-ás as primícias do teu cereal, do teu mosto e do teu azeite e as primícias da tosquia das tuas ovelhas.

[[v5-18-5]]

^<<v5-18-5,5>>^ Porque o SENHOR, teu Deus, o escolheu de todas as tuas tribos, para que assista a servir no nome do SENHOR, ele e seus filhos, todos os dias.

[[v5-18-6]]

^<<v5-18-6,6>>^ E, quando vier um levita de alguma das tuas portas, de todo o Israel, onde habitar, e vier com todo o desejo da sua alma ao lugar que o SENHOR escolheu,

[[v5-18-7]]

^<<v5-18-7,7>>^ e servir no nome do SENHOR, seu Deus, como também todos os seus irmãos, os levitas, que assistem ali perante o SENHOR,

[[v5-18-8]]

^<<v5-18-8,8>>^ igual porção comerão, além das vendas do seu patrimônio.

[[v5-18-9]]

^<<v5-18-9,9>>^ Quando entrares na terra que o SENHOR, teu Deus, te der, não aprenderás a fazer conforme as abominações daquelas nações.

[[v5-18-10]]

^<<v5-18-10,10>>^ Entre ti se não achará quem faça passar pelo fogo o seu filho ou a sua filha, nem adivinhador, nem prognosticador, nem agoureiro, nem feiticeiro,

[[v5-18-11]]

^<<v5-18-11,11>>^ nem encantador de encantamentos, nem quem consulte um espírito adivinhante, nem mágico, nem quem consulte os mortos,

[[v5-18-12]]

^<<v5-18-12,12>>^ pois todo aquele que faz tal coisa é abominação ao SENHOR; e por estas abominações o SENHOR, teu Deus, as lança fora de diante de ti.

[[v5-18-13]]

^<<v5-18-13,13>>^ Perfeito serás, como o SENHOR, teu Deus.

[[v5-18-14]]

^<<v5-18-14,14>>^ Porque estas nações, que hás de possuir, ouvem os prognosticadores e os adivinhadores; porém a ti o SENHOR, teu Deus, não permitiu tal coisa.

[[v5-18-15]]

^<<v5-18-15,15>>^ O SENHOR, teu Deus, te despertará um profeta do meio de ti, de teus irmãos, como eu; a ele ouvireis;

[[v5-18-16]]

^<<v5-18-16,16>>^ conforme tudo o que pediste ao SENHOR, teu Deus, em Horebe, no dia da congregação, dizendo: Não ouvirei mais a voz do SENHOR, meu Deus, nem mais verei este grande fogo, para que não morra.

[[v5-18-17]]

^<<v5-18-17,17>>^ Então, o SENHOR me disse: Bem falaram naquilo  que disseram.

[[v5-18-18]]

^<<v5-18-18,18>>^ Eis que  lhes suscitarei um profeta do meio de seus irmãos, como tu, e porei as minhas palavras na sua boca, e ele lhes falará tudo o que eu lhe ordenar.

[[v5-18-19]]

^<<v5-18-19,19>>^ E será que  qualquer que não ouvir as minhas palavras, que ele falar em meu nome, eu o  requererei dele.

[[v5-18-20]]

^<<v5-18-20,20>>^ Porém o profeta que presumir soberbamente de falar alguma palavra em meu nome, que eu lhe não tenho mandado falar, ou o que falar em nome de outros deuses, o tal profeta morrerá.

[[v5-18-21]]

^<<v5-18-21,21>>^ E se disseres no teu coração: Como conheceremos a palavra que o SENHOR não falou?

[[v5-18-22]]

^<<v5-18-22,22>>^ Quando o tal  profeta falar em nome do SENHOR, e tal  palavra se não cumprir, nem suceder assim,  esta é  palavra que o SENHOR não falou; com soberba a falou o tal  profeta; não tenhas temor dele.

'''

xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[Próximo Capítulo &#62;]