include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// arc ?, ARC - Almeida Revista e Corrigida

[[v6-13-1]]

^<<v6-13-1,1>>^ Era, porém, Josué já velho, entrado em dias; e disse-lhe o SENHOR: Já estás velho, entrado em dias; e ainda muitíssima terra ficou para possuir.

[[v6-13-2]]

^<<v6-13-2,2>>^ A terra que fica de resto é  esta: todos os termos dos filisteus e toda a Gesur;

[[v6-13-3]]

^<<v6-13-3,3>>^ desde Sior, que está  defronte do Egito, até ao termo de Ecrom, para o norte, que  se conta ser dos cananeus; cinco príncipes dos filisteus: o de Gaza, o de Asdode, o de Asquelom, o de Gate e o de Ecrom; e os aveus,

[[v6-13-4]]

^<<v6-13-4,4>>^ desde o sul, também toda a terra dos cananeus e Meara, que é  dos sidônios, até Afeca, ao termo dos amorreus;

[[v6-13-5]]

^<<v6-13-5,5>>^ como também a terra dos gebalitas e todo o Líbano, para o nascente do sol, desde Baal-Gade, ao pé do monte Hermom, até à entrada de Hamate;

[[v6-13-6]]

^<<v6-13-6,6>>^ todos os que habitam nas montanhas desde o Líbano até Misrefote-Maim, todos os sidônios; eu os lançarei de diante dos filhos de Israel; tão somente faze que a terra  caia a Israel em sorte por herança, como já  to tenho mandado.

[[v6-13-7]]

^<<v6-13-7,7>>^ Reparte, pois, agora, esta terra por herança às nove tribos e à meia tribo de Manassés.

[[v6-13-8]]

^<<v6-13-8,8>>^ Com a outra meia tribo os rubenitas e os gaditas já  receberam a sua herança, a qual lhes deu Moisés dalém do Jordão, para o oriente, como já lhes tinha dado Moisés, servo do SENHOR,

[[v6-13-9]]

^<<v6-13-9,9>>^ desde Aroer, que está  à borda do ribeiro de Arnom, e a cidade que está  no meio do vale, e toda a campina de Medeba até Dibom;

[[v6-13-10]]

^<<v6-13-10,10>>^ e todas as cidades de Seom, rei dos amorreus, que reinou em Hesbom, até ao termo dos filhos de Amom;

[[v6-13-11]]

^<<v6-13-11,11>>^ e Gileade, e o termo dos gesureus, e dos maacateus, e todo o monte Hermom, e toda a Basã até Salca;

[[v6-13-12]]

^<<v6-13-12,12>>^ todo o reino de Ogue, em Basã, que reinou em Astarote e em Edrei; este ficou do resto dos gigantes, que Moisés feriu e expeliu.

[[v6-13-13]]

^<<v6-13-13,13>>^ Porém os filhos de Israel não expeliram os gesureus, nem os maacateus; antes, Gesur e Maacate habitaram no meio de Israel até ao dia de  hoje.

[[v6-13-14]]

^<<v6-13-14,14>>^ Tão somente à tribo de Levi não deu herança; os sacrifícios queimados do SENHOR, Deus de Israel, são  a sua herança, como já  lhe tinha dito.

[[v6-13-15]]

^<<v6-13-15,15>>^ Assim, Moisés deu à tribo dos filhos de Rúben, conforme as suas famílias,

[[v6-13-16]]

^<<v6-13-16,16>>^ e foi o seu termo desde Aroer, que está  à borda do ribeiro de Arnom, e a cidade que está  no meio do vale e toda a campina até Medeba;

[[v6-13-17]]

^<<v6-13-17,17>>^ Hesbom e todas as suas cidades, que estão  na campina; Dibom, e Bamote-Baal, e Bete-Baal-Meom;

[[v6-13-18]]

^<<v6-13-18,18>>^ e Jaza, e Quedemote, e Mefaate;

[[v6-13-19]]

^<<v6-13-19,19>>^ e Quiriataim, e Sibma, e Zerete-Saar, no monte do vale;

[[v6-13-20]]

^<<v6-13-20,20>>^ e Bete-Peor, e Asdote-Pisga, e Bete-Jesimote;

[[v6-13-21]]

^<<v6-13-21,21>>^ e todas as cidades da campina, e todo o reino de Seom, rei dos amorreus, que reinou em Hesbom, a quem Moisés feriu, como também aos príncipes de Midiã, e Evi, e Requém, e Zur, e Hur, e Reba, príncipes de Seom, moradores da terra.

[[v6-13-22]]

^<<v6-13-22,22>>^ Também os filhos de Israel mataram a fio de espada a Balaão, filho de Beor, o adivinho, como os mais que por eles foram mortos.

[[v6-13-23]]

^<<v6-13-23,23>>^ E foi o termo dos filhos de Rúben o Jordão e o seu  termo; essa é  a herança dos filhos de Rúben, segundo as suas famílias, com as cidades e as suas aldeias.

[[v6-13-24]]

^<<v6-13-24,24>>^ E deu Moisés à tribo de Gade, aos filhos de Gade, segundo as suas famílias,

[[v6-13-25]]

^<<v6-13-25,25>>^ e foi o seu termo Jazer, e todas as cidades de Gileade, e metade da terra dos filhos de Amom, até Aroer, que está  defronte de Rabá;

[[v6-13-26]]

^<<v6-13-26,26>>^ e desde Hesbom até Ramate-Mispa e Betonim; e desde Maanaim até ao termo de Debir;

[[v6-13-27]]

^<<v6-13-27,27>>^ e, no vale, Bete-Harã, e Bete-Ninra, e Sucote, e Safom, que ficara do  resto do reino de Seom, rei de Hesbom, mas o Jordão e o seu  termo, até à extremidade do mar de Quinerete dalém do Jordão, para o oriente.

[[v6-13-28]]

^<<v6-13-28,28>>^ Essa é  a herança dos filhos de Gade, segundo as suas famílias, com as cidades e as suas aldeias.

[[v6-13-29]]

^<<v6-13-29,29>>^ Deu também Moisés herança  à meia tribo de Manassés, que ficou à meia tribo dos filhos de Manassés, segundo as suas famílias.

[[v6-13-30]]

^<<v6-13-30,30>>^ De maneira que o seu termo foi desde Maanaim, mais todo o Basã, todo o reino de Ogue, rei de Basã, e todas as aldeias de Jair, que estão  em Basã, sessenta cidades;

[[v6-13-31]]

^<<v6-13-31,31>>^ e metade de Gileade, e Astarote, e Edrei, cidades do reino de Ogue, em Basã, foram dadas aos filhos de Maquir, filho de Manassés, a saber,  à metade dos filhos de Maquir, segundo as suas famílias.

[[v6-13-32]]

^<<v6-13-32,32>>^ Isso é  o que Moisés repartiu em herança nas campinas de Moabe, dalém do Jordão, de Jericó para o oriente.

[[v6-13-33]]

^<<v6-13-33,33>>^ Porém à tribo de Levi Moisés não deu herança; o SENHOR, Deus de Israel, é  a sua herança, como já  lhe tinha dito.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]