include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// arc ?, ARC - Almeida Revista e Corrigida

[[v6-15-1]]

^<<v6-15-1,1>>^ E a sorte da tribo dos filhos de Judá, segundo as suas famílias, caiu para o sul, até ao termo de Edom, até o deserto de Zim, até à extremidade da banda do sul.

[[v6-15-2]]

^<<v6-15-2,2>>^ E foi o seu termo para o sul, desde a ribeira do mar Salgado, desde a baía que olha para o sul;

[[v6-15-3]]

^<<v6-15-3,3>>^ e sai para o sul, até à subida de Acrabim, e passa a Zim, e sobe do sul a Cades-Barneia, e passa por Hezrom, e sobe a Adar, e rodeia a Carca;

[[v6-15-4]]

^<<v6-15-4,4>>^ e passa Azmom, e sai ao ribeiro do Egito, e as saídas deste termo irão até ao mar; este será o vosso termo da banda do sul.

[[v6-15-5]]

^<<v6-15-5,5>>^ O termo, porém, para o oriente será  o mar Salgado até à extremidade do Jordão; e o termo para o norte será  da baía do mar, desde a extremidade do Jordão.

[[v6-15-6]]

^<<v6-15-6,6>>^ E este termo subirá até Bete-Hogla, e passará do norte a Bete-Arabá, e este termo subirá até à pedra de Boã, filho de Rúben.

[[v6-15-7]]

^<<v6-15-7,7>>^ Subirá mais este termo a Debir, desde o vale de Acor, e olhará pelo norte para Gilgal, a qual está  à subida de Adumim, que está  para o sul do ribeiro; então, este termo passará até às águas de En-Semes; e as suas saídas estarão  da banda de En-Rogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ E este termo passará pelo vale do Filho de Hinom, da banda dos jebuseus do sul (esta é  Jerusalém) e subirá este termo até ao cume do monte que está  diante do vale de Hinom para o ocidente, que está  no fim do vale dos Refains, da banda do norte.

[[v6-15-9]]

^<<v6-15-9,9>>^ Então, este termo irá desde a altura do monte até à fonte das águas de Neftoa; e sairá até às cidades do monte de Efrom; irá mais este termo até Baalá; esta é  Quiriate-Jearim.

[[v6-15-10]]

^<<v6-15-10,10>>^ Então, tornará este termo desde Baalá para o ocidente, até às montanhas de Seir, e passará ao lado do monte de Jearim da banda do norte; esta é  Quesalom; e descerá a Bete-Semes, e passará por Timna.

[[v6-15-11]]

^<<v6-15-11,11>>^ Sairá este termo mais ao lado de Ecrom para o norte, e este termo irá a Siquerom, e passará o monte de Baalá, e sairá em Jabneel; e as saídas deste termo eram no mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ Será,  porém, o termo da banda do ocidente o mar Grande e o seu  termo; este é  o termo dos filhos de Judá ao redor, segundo as suas famílias.

[[v6-15-13]]

^<<v6-15-13,13>>^ Mas a Calebe, filho de Jefoné, deu uma  parte no meio dos filhos de Judá, conforme o dito do SENHOR a Josué, a saber,  a cidade de Arba, pai de Anaque; este é  Hebrom.

[[v6-15-14]]

^<<v6-15-14,14>>^ E expeliu Calebe dali os três filhos de Anaque: Sesai, e Aimã, e Talmai, gerados de Anaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ E dali subiu aos habitantes de Debir; e fora,  dantes, o nome de Debir Quiriate-Sefer.

[[v6-15-16]]

^<<v6-15-16,16>>^ E disse Calebe: Quem ferir a Quiriate-Sefer e a tomar, lhe darei a minha filha Acsa por mulher.

[[v6-15-17]]

^<<v6-15-17,17>>^ Tomou-a, pois, Otniel, filho de Quenaz, irmão de Calebe, e este deu-lhe a sua filha Acsa por mulher.

[[v6-15-18]]

^<<v6-15-18,18>>^ E sucedeu que,  vindo ela a ele,  o persuadiu que pedisse um campo a seu pai; e ela se apeou do jumento; então, Calebe lhe disse: Que é o que  tens?

[[v6-15-19]]

^<<v6-15-19,19>>^ E ela disse: Dá-me uma  bênção, pois me deste terra seca; dá-me também fontes de águas. Então, lhe deu as fontes superiores e as fontes inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta é  a herança da tribo dos filhos de Judá, segundo as suas famílias.

[[v6-15-21]]

^<<v6-15-21,21>>^ São, pois, as cidades da extremidade da tribo dos filhos de Judá até ao termo de Edom para o sul: Cabzeel, e Éder, e Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ e Quiná, e Dimona, e Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ e Quedes, e Hazor, e Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ e Zife, e Telém, e Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ e Hazor-Hadata, e Quiriote-Hezrom (que é  Hazor),

[[v6-15-26]]

^<<v6-15-26,26>>^ e Amã, e Sema, e Molada,

[[v6-15-27]]

^<<v6-15-27,27>>^ e Hazar-Gada, e Hesmom, e Bete-Palete,

[[v6-15-28]]

^<<v6-15-28,28>>^ e Hasar-Sual, e Berseba, e Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ e Baalá, e Iim, e Ezém,

[[v6-15-30]]

^<<v6-15-30,30>>^ e Eltolade, e Quesil, e Horma,

[[v6-15-31]]

^<<v6-15-31,31>>^ e Ziclague, e Madmana, e Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ e Lebaote, e Silim, e Aim, e Rimom: todas as cidades e as suas aldeias; vinte e nove ao todo.

[[v6-15-33]]

^<<v6-15-33,33>>^ Nas planícies: Estaol, e Zorá, e Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ e Zanoa, e En-Ganim, e Tapua, e Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ e Jarmute, e Adulão, e Socó, e Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ e Saaraim, e Aditaim, e Gedera, e Gederotaim: catorze cidades e as suas aldeias.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã, e Hadasa, e Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ e Dileã, e Mispa, e Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ e Laquis, e Boscate, e Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ e Cabom, e Laamás, e Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ e Gederote, e Bete-Dagom, e Naamá, e Maquedá: dezesseis cidades e as suas aldeias.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna, e Eter, e Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ e Iftá, e Asná, e Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ e Queila, e Aczibe, e Maressa: nove cidades e as suas aldeias.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom, e os lugares da sua jurisdição, e as suas aldeias;

[[v6-15-46]]

^<<v6-15-46,46>>^ desde Ecrom até ao mar, todas as que estão  da banda de Asdode e as suas aldeias.

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, e os lugares da sua jurisdição, e as suas aldeias; Gaza, e os lugares da sua jurisdição, e as suas aldeias, até ao rio do Egito, e o mar Grande, e o seu  termo.

[[v6-15-48]]

^<<v6-15-48,48>>^ E nas montanhas: Samir, e Jatir, e Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ e Daná, e Quiriate-Sana, que é  Debir,

[[v6-15-50]]

^<<v6-15-50,50>>^ e Anabe, e Estemoa, e Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ e Gósen, e Holom, e Gilo: onze cidades e as suas aldeias.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe, e Dumá, e Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ e Janim, e Bete-Tapua, e Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ e Hunta, e Quiriate-Arba ( que é  Hebrom), e Zior: nove cidades e as suas aldeias.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, e Carmelo, e Zife, e Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ e Jezreel, e Jocdeão, e Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ e Caim, e Gibeá, e Timna: dez cidades e as suas aldeias.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, e Bete-Zur, e Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ e Maarate, e Bete-Anote, e Eltecom: seis cidades e as suas aldeias.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal ( que é  Quiriate-Jearim) e Rabá: duas cidades e as suas aldeias.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto: Bete-Arabá, e Midim, e Secaca,

[[v6-15-62]]

^<<v6-15-62,62>>^ e Nibsã, e a Cidade do Sal, e En-Gedi: seis cidades e as suas aldeias.

[[v6-15-63]]

^<<v6-15-63,63>>^ Não puderam, porém, os filhos de Judá expelir os jebuseus que habitavam em Jerusalém; assim, habitaram os jebuseus com os filhos de Judá em Jerusalém até ao dia de  hoje.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]