include::./index.adoc[]

[[v6-19-0]]
=== Josué, 19
// arc ?, ARC - Almeida Revista e Corrigida

[[v6-19-1]]

^<<v6-19-1,1>>^ E saiu a segunda sorte a Simeão, à tribo dos filhos de Simeão, segundo as suas famílias, e foi a sua herança no meio da herança dos filhos de Judá.

[[v6-19-2]]

^<<v6-19-2,2>>^ E tiveram na sua herança: Berseba, e Seba, e Molada,

[[v6-19-3]]

^<<v6-19-3,3>>^ e Hazar-Sual, e Balá, e Ezém,

[[v6-19-4]]

^<<v6-19-4,4>>^ e Eltolade, e Betul, e Horma,

[[v6-19-5]]

^<<v6-19-5,5>>^ e Ziclague, e Bete-Marcabote, e Hazar-Susa,

[[v6-19-6]]

^<<v6-19-6,6>>^ e Bete-Lebaote, e Saruém: treze cidades e as suas aldeias.

[[v6-19-7]]

^<<v6-19-7,7>>^ Aim, e Rimom, e Eter, e Asã: quatro cidades e as suas aldeias.

[[v6-19-8]]

^<<v6-19-8,8>>^ E todas as aldeias que havia  em redor destas cidades, até Baalate-Ber, que é  Ramá do Sul; esta era  a herança da tribo dos filhos de Simeão, segundo as suas famílias.

[[v6-19-9]]

^<<v6-19-9,9>>^ A herança dos filhos de Simeão estava  entre o quinhão dos de Judá, porquanto a herança dos filhos de Judá era demasiadamente grande para eles; pelo que os filhos de Simeão tiveram a sua herança no meio deles.

[[v6-19-10]]

^<<v6-19-10,10>>^ E saiu a terceira sorte aos filhos de Zebulom, segundo as suas famílias, e foi o termo da sua herança até Saride.

[[v6-19-11]]

^<<v6-19-11,11>>^ E subia o seu termo pelo ocidente a Marala, e chegava até Dabesete, e chegava também até ao ribeiro que está  defronte de Jocneão.

[[v6-19-12]]

^<<v6-19-12,12>>^ E, de Saride, voltava para o oriente, para o nascente do sol, até ao termo de Quislote-Tabor, e saía a Daberate, e ia subindo a Jafia;

[[v6-19-13]]

^<<v6-19-13,13>>^ e, dali, passava pelo oriente, para o nascente, a Gate-Hefer, em Ete-Cazim, e saía a Rimom-Metoar, que é  Neá;

[[v6-19-14]]

^<<v6-19-14,14>>^ e tornava este termo para o norte a Hanatom, e as suas saídas eram  o vale de Ifta-El;

[[v6-19-15]]

^<<v6-19-15,15>>^ e Catate, e Naalal, e Sinrom, e Idala, e Belém: doze cidades e as suas aldeias.

[[v6-19-16]]

^<<v6-19-16,16>>^ Esta era  a herança dos filhos de Zebulom, segundo as suas famílias; estas cidades e as suas aldeias.

[[v6-19-17]]

^<<v6-19-17,17>>^ A quarta sorte saiu a Issacar, aos filhos de Issacar, segundo as suas famílias.

[[v6-19-18]]

^<<v6-19-18,18>>^ E foi o seu termo Jezreel, e Quesulote, e Suném,

[[v6-19-19]]

^<<v6-19-19,19>>^ e Hafaraim, e Siom, e Anacarate,

[[v6-19-20]]

^<<v6-19-20,20>>^ e Rabite, e Quisião, e Ebes,

[[v6-19-21]]

^<<v6-19-21,21>>^ e Remete, e En-Ganim, e En-Hada, e Bete-Pasês.

[[v6-19-22]]

^<<v6-19-22,22>>^ E chegava este termo até Tabor, e Saazima, e Bete-Semes; e as saídas do seu termo estavam  no Jordão: dezesseis cidades e as suas aldeias.

[[v6-19-23]]

^<<v6-19-23,23>>^ Esta era  a herança da tribo dos filhos de Issacar, segundo as suas famílias; estas cidades e as suas aldeias.

[[v6-19-24]]

^<<v6-19-24,24>>^ E saiu a quinta sorte à tribo dos filhos de Aser, segundo as suas famílias.

[[v6-19-25]]

^<<v6-19-25,25>>^ E foi o seu termo Helcate, e Hali, e Béten, e Acsafe,

[[v6-19-26]]

^<<v6-19-26,26>>^ e Alameleque, e Amade, e Misal; e chegava ao Carmelo para o ocidente, e a Sior-Libnate;

[[v6-19-27]]

^<<v6-19-27,27>>^ e voltava do nascente do sol a Bete-Dagom, e chegava a Zebulom e ao vale de Ifta-El, ao norte de Bete-Emeque e de Neiel, e vinha sair a Cabul pela esquerda,

[[v6-19-28]]

^<<v6-19-28,28>>^ e Ebrom, e Reobe, e Hamom, e Caná, até à grande Sidom.

[[v6-19-29]]

^<<v6-19-29,29>>^ E voltava este termo a Ramá e até à forte cidade de Tiro; então, tornava este termo a Hosa, e as suas saídas estavam para o mar, desde o quinhão da terra  até Aczibe;

[[v6-19-30]]

^<<v6-19-30,30>>^ e Umá, e Afeca, e Reobe: vinte e duas cidades e as suas aldeias.

[[v6-19-31]]

^<<v6-19-31,31>>^ Esta era  a herança da tribo dos filhos de Aser, segundo as suas famílias; estas cidades e as suas aldeias.

[[v6-19-32]]

^<<v6-19-32,32>>^ E saiu a sexta sorte aos filhos de Naftali, para os filhos de Naftali segundo as suas famílias.

[[v6-19-33]]

^<<v6-19-33,33>>^ E foi o seu termo desde Helefe e desde Alom em Zaananim, e Adami-Nequebe, e Jabneel, até Lacum, e estavam as suas saídas no Jordão.

[[v6-19-34]]

^<<v6-19-34,34>>^ E voltava este termo pelo ocidente a Aznote-Tabor, e dali passava a Hucoque, e chegava a Zebulom para o sul, e chegava a Aser para o ocidente, e a Judá pelo Jordão, para o nascente do sol.

[[v6-19-35]]

^<<v6-19-35,35>>^ E eram  as cidades-fortes: Zidim, e Zer, e Hamate, e Racate, e Quinerete,

[[v6-19-36]]

^<<v6-19-36,36>>^ e Adamá, e Ramá, e Hazor,

[[v6-19-37]]

^<<v6-19-37,37>>^ e Quedes, e Edrei, e En-Hazor,

[[v6-19-38]]

^<<v6-19-38,38>>^ e Irom, e Migdal-El, e Horém, e Bete-Anate, e Bete-Semes: dezenove cidades e as suas aldeias.

[[v6-19-39]]

^<<v6-19-39,39>>^ Esta era  a herança da tribo dos filhos de Naftali, segundo as suas famílias; estas cidades e as suas aldeias.

[[v6-19-40]]

^<<v6-19-40,40>>^ A sétima sorte saiu à tribo dos filhos de Dã, segundo as suas famílias.

[[v6-19-41]]

^<<v6-19-41,41>>^ E foi o termo da sua herança Zorá, e Estaol, e Ir-Semes,

[[v6-19-42]]

^<<v6-19-42,42>>^ e Saalabim, e Aijalom, e Itla,

[[v6-19-43]]

^<<v6-19-43,43>>^ e Elom, e Timna, e Ecrom,

[[v6-19-44]]

^<<v6-19-44,44>>^ e Elteque, e Gibetom, e Baalate,

[[v6-19-45]]

^<<v6-19-45,45>>^ e Jeúde, e Benê-Beraque, e Gate-Rimom,

[[v6-19-46]]

^<<v6-19-46,46>>^ e Me-Jarcom, e Racom com o termo defronte de Jafo.

[[v6-19-47]]

^<<v6-19-47,47>>^ Saiu, porém, pequeno o termo aos filhos de Dã; pelo que subiram os filhos de Dã, e pelejaram contra Lesém, e a tomaram, e a feriram a fio de espada, e a possuíram, e habitaram nela; e a Lesém chamaram Dã, conforme o nome de Dã, seu pai.

[[v6-19-48]]

^<<v6-19-48,48>>^ Esta era  a herança da tribo dos filhos de Dã, segundo as suas famílias; estas cidades e as suas aldeias.

[[v6-19-49]]

^<<v6-19-49,49>>^ Acabando, pois, de repartir a terra em herança segundo os seus termos, deram os filhos de Israel a Josué, filho de Num, herança no meio deles.

[[v6-19-50]]

^<<v6-19-50,50>>^ Segundo o dito do SENHOR, lhe deram a cidade que pediu, Timnate-Sera, na montanha de Efraim; e reedificou aquela cidade e habitou nela.

[[v6-19-51]]

^<<v6-19-51,51>>^ Estas eram  as heranças que Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças dos pais das famílias por sorte em herança repartiram pelas tribos dos filhos de Israel em Siló, perante o SENHOR, à porta da tenda da congregação. E, assim,  acabaram de repartir a terra.

'''

xref:006-josue/006-josue-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-josue/006-josue-020.adoc#v6-20-0[Próximo Capítulo &#62;]