include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// arc ?, ARC - Almeida Revista e Corrigida

[[v6-11-1]]

^<<v6-11-1,1>>^ Sucedeu, depois disso, que,  ouvindo- o  Jabim, rei de Hazor, enviou mensageiros a Jobabe, rei de Madom, e ao rei de Sinrom, e ao rei de Acsafe;

[[v6-11-2]]

^<<v6-11-2,2>>^ e aos reis que estavam  ao norte, nas montanhas, na campina para o sul de Quinerete, nas planícies e em Nafote-Dor, da banda do mar;

[[v6-11-3]]

^<<v6-11-3,3>>^ aos cananeus do  oriente e do  ocidente, aos amorreus, aos heteus, aos ferezeus, aos jebuseus nas montanhas e aos heveus ao pé de Hermom, na terra de Mispa.

[[v6-11-4]]

^<<v6-11-4,4>>^ Saíram, pois, estes e todos os seus exércitos com eles, muito povo, em multidões como a areia que está  na praia do mar, e muitíssimos cavalos e carros.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos esses reis se ajuntaram, e vieram, e se acamparam junto às águas de Merom, para pelejarem contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ E disse o SENHOR a Josué: Não temas diante deles, porque amanhã a esta mesma hora eu os darei todos feridos diante dos filhos de Israel; os seus cavalos jarretarás e os seus carros queimarás a fogo.

[[v6-11-7]]

^<<v6-11-7,7>>^ E Josué, e toda a gente de guerra com ele, veio apressadamente sobre eles às águas de Merom, e deram neles de repente.

[[v6-11-8]]

^<<v6-11-8,8>>^ E o SENHOR os deu na mão de Israel; e os feriram e os seguiram até à grande Sidom, e até Misrefote-Maim, e até ao vale de Mispa ao oriente; feriram-nos até não lhes deixarem nenhum.

[[v6-11-9]]

^<<v6-11-9,9>>^ E fez-lhes Josué como o SENHOR lhe dissera; os seus cavalos jarretou e os seus carros queimou a fogo.

[[v6-11-10]]

^<<v6-11-10,10>>^ E, naquele mesmo tempo, tornou Josué, e tomou a Hazor, e feriu à espada ao seu rei; porquanto Hazor, dantes, era a cabeça de todos esses reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ E a toda alma que nela havia  feriram a fio de espada e totalmente os destruíram, e nada restou do que tinha fôlego; e a Hazor queimou com fogo.

[[v6-11-12]]

^<<v6-11-12,12>>^ E Josué tomou todas as cidades desses reis e todos os seus reis e os feriu a fio de espada, destruindo-os totalmente, como ordenara Moisés, servo do SENHOR.

[[v6-11-13]]

^<<v6-11-13,13>>^ Tão somente não queimaram os israelitas as cidades que estavam  sobre os seus outeiros: salvo Hazor, a qual  Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ E todos os despojos dessas cidades e o gado os filhos de Israel saquearam para si; tão somente a todos os homens feriram a fio de espada, até que os destruíram; nada do que fôlego tinha deixaram com vida.

[[v6-11-15]]

^<<v6-11-15,15>>^ Como ordenara o SENHOR a Moisés, seu servo, assim Moisés ordenou a Josué; e assim Josué o fez; nem uma só palavra tirou de tudo o que o SENHOR ordenara a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Assim, Josué tomou toda aquela terra, as montanhas, e todo o sul, e toda a terra de Gósen, e as planícies, e as campinas, e as montanhas de Israel, e as suas planícies;

[[v6-11-17]]

^<<v6-11-17,17>>^ desde o monte Calvo, que sobe a Seir, até Baal-Gade, no vale do Líbano, às raízes do monte de Hermom; também tomou todos os seus reis, e os feriu, e os matou.

[[v6-11-18]]

^<<v6-11-18,18>>^ Por muitos dias, Josué fez guerra contra todos esses reis.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não houve cidade que fizesse paz com os filhos de Israel, senão os heveus, moradores de Gibeão; por guerra as tomaram todas.

[[v6-11-20]]

^<<v6-11-20,20>>^ Porquanto do SENHOR vinha que o seu coração endurecesse, para saírem ao encontro a Israel na guerra, para os destruir totalmente, para se não ter piedade deles, mas para os destruir a todos, como o SENHOR tinha ordenado a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Naquele tempo, veio Josué e extirpou os anaquins das montanhas de Hebrom, de Debir, de Anabe, de todas as montanhas de Judá e de todas as montanhas de Israel; Josué os destruiu totalmente com as suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Nenhum dos anaquins ficou de resto na terra dos filhos de Israel; somente ficaram de resto em Gaza, em Gate e em Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ Assim, Josué tomou toda esta terra conforme tudo o que o SENHOR tinha dito a Moisés; e Josué a deu em herança aos filhos de Israel, conforme as suas divisões, conforme as suas tribos; e a terra repousou da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]