include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// arc ?, ARC - Almeida Revista e Corrigida

[[v6-10-1]]

^<<v6-10-1,1>>^ E sucedeu que,  ouvindo Adoni-Zedeque, rei de Jerusalém, que Josué tomara a Ai, e a tinha destruído totalmente, e  fizera a Ai e ao seu rei como tinha feito a Jericó e ao seu rei, e que os moradores de Gibeão fizeram paz com os israelitas, e estavam no meio deles,

[[v6-10-2]]

^<<v6-10-2,2>>^ temeu muito, porque Gibeão era  uma cidade grande como uma das cidades reais e ainda maior do que Ai, e todos os seus homens, valentes.

[[v6-10-3]]

^<<v6-10-3,3>>^ Pelo que Adoni-Zedeque, rei de Jerusalém, enviou mensageiros a Hoão, rei de Hebrom, e a Pirã, rei de Jarmute, e a Jafia, rei de Laquis, e a Debir, rei de Eglom, dizendo:

[[v6-10-4]]

^<<v6-10-4,4>>^ Subi a mim e ajudai-me; e firamos a Gibeão, porquanto fez paz com Josué e com os filhos de Israel.

[[v6-10-5]]

^<<v6-10-5,5>>^ Então, se ajuntaram e subiram cinco reis dos amorreus, o rei de Jerusalém, o rei de Hebrom, o rei de Jarmute, o rei de Laquis, o rei de Eglom, eles e todos os seus exércitos; e sitiaram a Gibeão e pelejaram contra ela.

[[v6-10-6]]

^<<v6-10-6,6>>^ Enviaram, pois, os homens de Gibeão a Josué ao arraial de Gilgal, dizendo: Não retires as tuas mãos de teus servos; sobe apressadamente a nós, e livra-nos, e ajuda-nos, porquanto todos os reis dos amorreus que habitam na montanha se ajuntaram contra nós.

[[v6-10-7]]

^<<v6-10-7,7>>^ Então, subiu Josué de Gilgal, ele e toda a gente de guerra com ele e todos os valentes e valorosos.

[[v6-10-8]]

^<<v6-10-8,8>>^ E o SENHOR disse a Josué: Não os temas, porque os tenho dado na tua mão; nenhum deles parará diante de ti.

[[v6-10-9]]

^<<v6-10-9,9>>^ E Josué lhes sobreveio de repente, porque toda a noite veio subindo desde Gilgal.

[[v6-10-10]]

^<<v6-10-10,10>>^ E o SENHOR os conturbou diante de Israel, e os feriu de grande ferida em Gibeão, e seguiu-os pelo caminho que sobe a Bete-Horom, e os feriu até Azeca e Maquedá.

[[v6-10-11]]

^<<v6-10-11,11>>^ E sucedeu que,  fugindo eles diante de Israel à descida de Bete-Horom, o SENHOR lançou sobre eles, do céu, grandes pedras até Azeca, e morreram; e foram  muitos mais os que  morreram das pedras da saraiva do que os que os filhos de Israel mataram à espada.

[[v6-10-12]]

^<<v6-10-12,12>>^ Então, Josué falou ao SENHOR, no dia em que o SENHOR deu os amorreus na mão dos filhos de Israel, e disse aos olhos dos israelitas: Sol, detém-te em Gibeão, e tu  lua, no vale de Aijalom.

[[v6-10-13]]

^<<v6-10-13,13>>^ E o sol se deteve, e a lua parou, até que o povo se vingou de seus inimigos. Isso não está  escrito no Livro do Reto? O sol, pois, se deteve no meio do céu e não se apressou a pôr-se, quase um dia inteiro.

[[v6-10-14]]

^<<v6-10-14,14>>^ E não houve dia semelhante a este, nem  antes nem depois dele, ouvindo o SENHOR, assim, a voz de um homem; porque o SENHOR pelejava por Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ E tornou-se Josué, e todo o Israel com ele, ao arraial, a Gilgal.

[[v6-10-16]]

^<<v6-10-16,16>>^ Aqueles cinco reis, porém, fugiram e se esconderam numa cova em Maquedá.

[[v6-10-17]]

^<<v6-10-17,17>>^ E foi anunciado a Josué, dizendo: Acharam-se os cinco reis escondidos numa cova em Maquedá.

[[v6-10-18]]

^<<v6-10-18,18>>^ Disse, pois, Josué: Arrojai grandes pedras à boca da cova e ponde sobre ela homens que os guardem;

[[v6-10-19]]

^<<v6-10-19,19>>^ porém vós não vos detenhais; segui os vossos inimigos e feri os que ficaram atrás; não os deixeis entrar nas suas cidades, porque o SENHOR, vosso Deus, já vo-los deu na vossa mão.

[[v6-10-20]]

^<<v6-10-20,20>>^ E sucedeu que, acabando Josué e os filhos de Israel de os ferir a grande ferida, até consumi-los, e tendo  os que ficaram deles se retirado às cidades fortes,

[[v6-10-21]]

^<<v6-10-21,21>>^ todo o povo se tornou em paz a Josué, ao arraial em Maquedá; não havendo ninguém que movesse a sua língua contra os filhos de Israel.

[[v6-10-22]]

^<<v6-10-22,22>>^ Depois, disse Josué: Abri a boca da cova e trazei-me aqueles cinco reis para fora da cova.

[[v6-10-23]]

^<<v6-10-23,23>>^ Fizeram, pois, assim e trouxeram-lhe aqueles cinco reis para fora da cova: o rei de Jerusalém, o rei de Hebrom, o rei de Jarmute, o rei de Laquis e  o rei de Eglom.

[[v6-10-24]]

^<<v6-10-24,24>>^ E sucedeu que,  sendo trazidos aqueles reis a Josué, este chamou todos os homens de Israel e disse aos capitães da gente de guerra, que com eles foram: Chegai e ponde os vossos pés sobre os pescoços destes reis. E chegaram e puseram os seus pés sobre os seus pescoços.

[[v6-10-25]]

^<<v6-10-25,25>>^ Então, Josué lhes disse: Não temais, nem vos espanteis; esforçai-vos e animai-vos, porque assim fará o SENHOR a todos os vossos inimigos, contra os quais pelejardes.

[[v6-10-26]]

^<<v6-10-26,26>>^ E, depois disto, Josué os feriu, e os matou, e os pendurou em cinco madeiros; e ficaram enforcados nos madeiros até à tarde.

[[v6-10-27]]

^<<v6-10-27,27>>^ E sucedeu que,  ao tempo do pôr do sol, deu Josué ordem que os tirassem dos madeiros; e lançaram-nos na cova onde se esconderam e puseram grandes pedras à boca da cova, que ainda ali estão  até ao  mesmo dia de  hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ E, naquele mesmo dia, tomou Josué a Maquedá, feriu-a a fio de espada e destruiu o seu rei, a eles e a toda alma que nela havia;  nada deixou de resto; e fez ao rei de Maquedá como fizera ao rei de Jericó.

[[v6-10-29]]

^<<v6-10-29,29>>^ Então, Josué, e todo o Israel com ele, passou de Maquedá a Libna e pelejou contra Libna.

[[v6-10-30]]

^<<v6-10-30,30>>^ E também o SENHOR a deu na mão de Israel, a ela e a seu rei, e a feriu a fio de espada, a ela e a toda alma que nela havia;  nada deixou de resto; e fez ao seu rei como fizera ao rei de Jericó.

[[v6-10-31]]

^<<v6-10-31,31>>^ Então, Josué, e todo o Israel com ele, passou de Libna a Laquis, e a sitiou, e pelejou contra ela.

[[v6-10-32]]

^<<v6-10-32,32>>^ E o SENHOR deu a Laquis na mão de Israel, e tomou-a no dia seguinte, e a feriu a fio de espada, a ela e a toda alma que nela havia,  conforme tudo o que fizera a Libna.

[[v6-10-33]]

^<<v6-10-33,33>>^ Então, Horão, rei de Gezer, subiu a ajudar a Laquis; porém Josué o feriu, a ele e ao seu povo, até que nenhum lhe deixou de resto.

[[v6-10-34]]

^<<v6-10-34,34>>^ E Josué, e todo o Israel com ele, passou de Laquis a Eglom, e a sitiaram e pelejaram contra ela;

[[v6-10-35]]

^<<v6-10-35,35>>^ e, no mesmo dia, a tomaram e a feriram a fio de espada; e a toda alma que nela havia  destruiu totalmente no mesmo dia, conforme tudo o que fizeram a Laquis.

[[v6-10-36]]

^<<v6-10-36,36>>^ Depois, Josué, e todo o Israel com ele, subiu de Eglom a Hebrom, e pelejaram contra ela;

[[v6-10-37]]

^<<v6-10-37,37>>^ e a tomaram e a feriram a fio de espada, assim ao seu rei como a todas as suas cidades, e a toda alma que nelas havia;  a ninguém deixou com vida, conforme tudo o que fizeram a Eglom; e Josué a destruiu totalmente, a ela e a toda alma que nela havia.

[[v6-10-38]]

^<<v6-10-38,38>>^ Então, Josué e todo o Israel com ele, tornou a Debir e pelejou contra ela;

[[v6-10-39]]

^<<v6-10-39,39>>^ e tomou-a com o seu rei e todas as suas cidades e as feriu a fio de espada; e a toda alma que nelas havia  destruiu totalmente, nada deixou de resto; como fizera a Hebrom, a Libna e ao seu rei, assim fez a Debir e ao seu rei.

[[v6-10-40]]

^<<v6-10-40,40>>^ Assim, feriu Josué toda aquela terra, as montanhas, e o sul, e as campinas, e as descidas das águas, e todos os seus reis; nada deixou de resto; mas tudo o que tinha fôlego destruiu, como ordenara o SENHOR, Deus de Israel.

[[v6-10-41]]

^<<v6-10-41,41>>^ E Josué os feriu desde Cades-Barneia até Gaza, como também toda a terra de Gósen até Gibeão.

[[v6-10-42]]

^<<v6-10-42,42>>^ E de uma vez tomou Josué todos esses reis e as suas terras, porquanto o SENHOR, Deus de Israel, pelejava por Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ Então, Josué, e todo o Israel com ele, se tornou ao arraial em Gilgal.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]