include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// arc ?, ARC - Almeida Revista e Corrigida

[[v6-9-1]]

^<<v6-9-1,1>>^ E sucedeu que,  ouvindo isso  todos os reis que estavam  daquém do Jordão, nas montanhas, e nas campinas, e em toda a costa do grande mar, e em frente do Líbano, os heteus, e os amorreus, e os cananeus, e os ferezeus, e os heveus, e os jebuseus,

[[v6-9-2]]

^<<v6-9-2,2>>^ se ajuntaram eles de comum acordo, para pelejar contra Josué e contra Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ E os moradores de Gibeão, ouvindo o que Josué fizera com Jericó e com Ai,

[[v6-9-4]]

^<<v6-9-4,4>>^ usaram também de astúcia, e foram, e se fingiram embaixadores, e tomaram sacos velhos sobre os seus jumentos e odres de vinho velhos, e rotos, e remendados;

[[v6-9-5]]

^<<v6-9-5,5>>^ e nos pés sapatos velhos e remendados e vestes velhas sobre si; e todo o pão que traziam para o caminho era seco e bolorento.

[[v6-9-6]]

^<<v6-9-6,6>>^ E vieram a Josué, ao arraial, a Gilgal e lhe disseram, a ele  e aos homens de Israel: Vimos de uma terra distante; fazei, pois, agora concerto conosco.

[[v6-9-7]]

^<<v6-9-7,7>>^ E os homens de Israel responderam aos heveus: Porventura, habitais no meio de nós; como, pois, faremos concerto convosco?

[[v6-9-8]]

^<<v6-9-8,8>>^ Então, disseram a Josué: Nós somos  teus servos. E disse-lhes Josué: Quem sois  vós e donde vindes?

[[v6-9-9]]

^<<v6-9-9,9>>^ E lhe responderam: Teus servos vieram de uma terra mui distante, por causa do nome do SENHOR, teu Deus; porquanto ouvimos a sua fama e tudo quanto fez no Egito;

[[v6-9-10]]

^<<v6-9-10,10>>^ e tudo quanto fez aos dois reis dos amorreus que estavam  dalém do Jordão, a Seom, rei de Hesbom, e a Ogue, rei de Basã, que estava em Astarote.

[[v6-9-11]]

^<<v6-9-11,11>>^ Pelo que nossos anciãos e todos os moradores da nossa terra nos falaram, dizendo: Tomai convosco em vossas mãos provisão para o caminho, e ide-lhes ao encontro, e dizei-lhes: Nós somos  vossos servos; fazei, pois, agora concerto conosco.

[[v6-9-12]]

^<<v6-9-12,12>>^ Este nosso pão tomamos quente das nossas casas para nossa provisão, no dia em que saímos para vir a vós; e ei-lo aqui, agora, já seco e bolorento;

[[v6-9-13]]

^<<v6-9-13,13>>^ e estes odres que enchemos de vinho eram  novos e ei-los aqui já rotos; e estas nossas vestes e nossos sapatos já se têm envelhecido, por causa do mui longo caminho.

[[v6-9-14]]

^<<v6-9-14,14>>^ Então, aqueles homens israelitas tomaram da sua provisão e não pediram conselho à boca do SENHOR.

[[v6-9-15]]

^<<v6-9-15,15>>^ E Josué fez paz com eles e fez um  concerto com eles, que lhes daria a vida; e os príncipes da congregação lhes prestaram juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ E sucedeu que,  ao fim de três dias, depois de fazerem concerto com eles, ouviram que eram  seus vizinhos e que moravam no meio deles.

[[v6-9-17]]

^<<v6-9-17,17>>^ Porque, partindo os filhos de Israel, chegaram às suas cidades ao terceiro dia; e suas cidades eram Gibeão, e Cefira, e Beerote, e Quiriate-Jearim.

[[v6-9-18]]

^<<v6-9-18,18>>^ E os filhos de Israel os não feriram; porquanto os príncipes da congregação lhes juraram pelo SENHOR, Deus de Israel; pelo que toda a congregação murmurava contra os príncipes.

[[v6-9-19]]

^<<v6-9-19,19>>^ Então, todos os príncipes disseram a toda a congregação: Nós juramos-lhes pelo SENHOR, Deus de Israel; pelo que não podemos tocar-lhes.

[[v6-9-20]]

^<<v6-9-20,20>>^ Isto, porém,  lhes faremos: dar-lhes-emos a vida, para que não haja grande  ira sobre nós, por causa do juramento que já lhes  temos jurado.

[[v6-9-21]]

^<<v6-9-21,21>>^ Disseram-lhes, pois, os príncipes: Vivam. E se tornaram rachadores de lenha e tiradores de água para toda a congregação, como os príncipes lhes haviam dito.

[[v6-9-22]]

^<<v6-9-22,22>>^ E Josué os chamou e falou-lhes dizendo: Por que nos enganastes, dizendo: Mui longe de vós habitamos, morando vós no meio de nós?

[[v6-9-23]]

^<<v6-9-23,23>>^ Agora, pois, sois  malditos; e, dentre vós, não deixará de haver servos, nem rachadores de lenha, nem tiradores de água, para a casa do meu Deus.

[[v6-9-24]]

^<<v6-9-24,24>>^ Então, responderam a Josué e disseram: Porquanto com certeza foi anunciado aos teus servos que o SENHOR, teu Deus, ordenou a Moisés, seu servo, que vos desse toda esta terra e destruísse todos os moradores da terra diante de vós, tememos muito por nossas vidas por causa de vós. Por isso, fizemos assim.

[[v6-9-25]]

^<<v6-9-25,25>>^ E eis que agora estamos na tua mão; faze aquilo que te pareça bom e reto que se nos faça.

[[v6-9-26]]

^<<v6-9-26,26>>^ Assim, pois, lhes fez e livrou-os das mãos dos filhos de Israel; e não os mataram.

[[v6-9-27]]

^<<v6-9-27,27>>^ E, naquele dia, Josué os deu como rachadores de lenha e tiradores de água para a congregação e para o altar do SENHOR até ao dia  de hoje, no lugar que escolhesse.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]