include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v50-3-1]]

^<<v50-3-1,1>>^ Resta, irmãos meus, que vos regozijeis no Senhor. Não me aborreço de escrever-vos as mesmas coisas,  e é segurança para vós.

[[v50-3-2]]

^<<v50-3-2,2>>^ Guardai-vos dos cães, guardai-vos dos maus obreiros, guardai-vos da circuncisão!

[[v50-3-3]]

^<<v50-3-3,3>>^ Porque a circuncisão somos nós, que servimos a Deus no Espírito, e nos gloriamos em Jesus Cristo, e não confiamos na carne.

[[v50-3-4]]

^<<v50-3-4,4>>^ Ainda que também podia confiar na carne; se algum outro cuida que pode confiar na carne, ainda mais eu:

[[v50-3-5]]

^<<v50-3-5,5>>^ circuncidado ao oitavo dia, da linhagem de Israel, da tribo de Benjamim, hebreu de hebreus; segundo a lei, fui fariseu,

[[v50-3-6]]

^<<v50-3-6,6>>^ segundo o zelo, perseguidor da igreja; segundo a justiça que há na lei, irrepreensível.

[[v50-3-7]]

^<<v50-3-7,7>>^ Mas o que para mim era ganho reputei-o perda por Cristo.

[[v50-3-8]]

^<<v50-3-8,8>>^ E, na verdade, tenho também por perda todas as coisas,  pela excelência do conhecimento de Cristo Jesus, meu Senhor; pelo qual sofri a perda de todas estas coisas e as considero como esterco, para que possa ganhar a Cristo

[[v50-3-9]]

^<<v50-3-9,9>>^ e seja achado nele, não tendo a minha justiça que vem da lei, mas a que vem pela fé em Cristo, a saber,  a justiça que vem de Deus, pela fé;

[[v50-3-10]]

^<<v50-3-10,10>>^ para conhecê-lo, e a virtude da sua ressurreição, e a comunicação de suas aflições, sendo feito conforme a sua morte;

[[v50-3-11]]

^<<v50-3-11,11>>^ para ver  se, de alguma maneira, eu possa chegar à ressurreição dos mortos.

[[v50-3-12]]

^<<v50-3-12,12>>^ Não que já a tenha alcançado ou que seja perfeito; mas prossigo para alcançar aquilo para o que fui também preso por Cristo Jesus.

[[v50-3-13]]

^<<v50-3-13,13>>^ Irmãos, quanto a mim, não julgo que o haja alcançado; mas uma coisa faço, e é  que, esquecendo-me das coisas que atrás ficam e avançando para as que estão diante de mim,

[[v50-3-14]]

^<<v50-3-14,14>>^ prossigo para o alvo, pelo prêmio da soberana vocação de Deus em Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Pelo que todos quantos já  somos perfeitos sintamos isto mesmo;  e, se sentis alguma coisa doutra maneira, também Deus vo-lo revelará.

[[v50-3-16]]

^<<v50-3-16,16>>^ Mas, naquilo a que já chegamos, andemos segundo a mesma regra e sintamos o mesmo.

[[v50-3-17]]

^<<v50-3-17,17>>^ Sede também meus imitadores, irmãos, e tende cuidado, segundo o exemplo que tendes em nós, pelos que assim andam.

[[v50-3-18]]

^<<v50-3-18,18>>^ Porque muitos há, dos quais muitas vezes vos disse e agora também digo, chorando, que são  inimigos da cruz de Cristo.

[[v50-3-19]]

^<<v50-3-19,19>>^ O fim deles é  a perdição, o deus deles é  o ventre, e a glória deles é  para confusão deles mesmos, que só  pensam nas coisas terrenas.

[[v50-3-20]]

^<<v50-3-20,20>>^ Mas a nossa cidade está nos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo,

[[v50-3-21]]

^<<v50-3-21,21>>^ que transformará o nosso corpo abatido, para ser conforme o seu corpo glorioso, segundo o seu eficaz poder de sujeitar também a si todas as coisas.

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]