include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// arc ?, ARC - Almeida Revista e Corrigida

[[v26-22-1]]

^<<v26-22-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-22-2]]

^<<v26-22-2,2>>^ Tu, pois, ó filho do homem, julgarás, julgarás a cidade sanguinária? Faze-lhe conhecer, pois, todas as suas abominações

[[v26-22-3]]

^<<v26-22-3,3>>^ e dize: Assim diz o Senhor Jeová : Ai da cidade que derrama o sangue no meio dela, para que venha o seu tempo! Que faz ídolos contra si mesma, para se contaminar!

[[v26-22-4]]

^<<v26-22-4,4>>^ Pelo teu sangue que derramaste te fizeste culpada, e pelos teus ídolos que fabricaste te contaminaste, e fizeste chegar os teus dias, e vieste ao fim dos teus anos; por isso, eu te fiz o opróbrio das nações e o escárnio de todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ As que estão perto e as que estão longe de ti escarnecerão de ti, infamada, cheia de inquietação.

[[v26-22-6]]

^<<v26-22-6,6>>^ Eis que os príncipes de Israel, cada um conforme o seu poder, tiveram domínio sobre ti, para derramarem o sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ Ao pai e à  mãe desprezaram em ti, para com o estrangeiro usaram de opressão no meio de ti e ao órfão e à viúva oprimiram em ti.

[[v26-22-8]]

^<<v26-22-8,8>>^ As minhas coisas santas desprezaste e os meus sábados profanaste.

[[v26-22-9]]

^<<v26-22-9,9>>^ Homens caluniadores se acharam em ti, para derramarem o sangue; e em ti sobre os montes comeram e perversidade cometeram no meio de ti.

[[v26-22-10]]

^<<v26-22-10,10>>^ A vergonha do pai descobriram em ti e a que estava impura, na sua separação, humilharam no meio de ti.

[[v26-22-11]]

^<<v26-22-11,11>>^ Um cometeu abominação com a mulher do seu próximo, outro contaminou abominavelmente a sua nora, e outro humilhou no meio de ti a sua irmã, filha de seu pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ Presentes se receberam no meio de ti para se derramar sangue; usura e lucros tomaste e usaste de avareza com o teu próximo, oprimindo-o; mas de mim te esqueceste, diz o Senhor Jeová .

[[v26-22-13]]

^<<v26-22-13,13>>^ E eis que bati as mãos contra a tua avareza de que usaste e por causa de teu sangue, que houve no meio de ti.

[[v26-22-14]]

^<<v26-22-14,14>>^ Estará firme o teu coração? Estarão fortes as tuas mãos, nos dias em que eu tratarei contigo? Eu, o SENHOR, o disse e o  farei.

[[v26-22-15]]

^<<v26-22-15,15>>^ E espalhar-te-ei entre as nações, e espalhar-te-ei pelas terras, e porei termo à tua imundícia.

[[v26-22-16]]

^<<v26-22-16,16>>^ E tu serás profanada em ti mesma, aos olhos das nações, e saberás que eu sou  o SENHOR.

[[v26-22-17]]

^<<v26-22-17,17>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-22-18]]

^<<v26-22-18,18>>^ Filho do homem, a casa de Israel se tornou para mim em escória; todos eles são  bronze, e estanho, e ferro, e chumbo no meio do forno; em escória de prata se tornaram.

[[v26-22-19]]

^<<v26-22-19,19>>^ Portanto, assim diz o Senhor Jeová : Pois que todos vós vos tornastes em escória, eis que eu vos ajuntarei no meio de Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Como se ajuntam a prata, e o bronze, e o ferro, e o chumbo, e o estanho no meio do forno, para assoprar o fogo sobre eles, a fim de se fundirem, assim vos ajuntarei na minha ira e no meu furor, e ali vos deixarei, e fundirei.

[[v26-22-21]]

^<<v26-22-21,21>>^ E congregar-vos-ei e assoprarei sobre vós o fogo do meu furor; e sereis fundidos no meio dela.

[[v26-22-22]]

^<<v26-22-22,22>>^ Como se funde a prata no meio do forno, assim sereis fundidos no meio dela; e sabereis que eu, o SENHOR, derramei o meu furor sobre vós.

[[v26-22-23]]

^<<v26-22-23,23>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-22-24]]

^<<v26-22-24,24>>^ Filho do homem, dize-lhe: Tu és uma terra que não está purificada e que não tem chuva no dia da indignação.

[[v26-22-25]]

^<<v26-22-25,25>>^ Conjuração dos seus profetas há  no meio dela, como um  leão que ruge, que arrebata a presa; eles devoram as almas; tesouros e coisas preciosas tomam, multiplicam as suas viúvas no meio dela.

[[v26-22-26]]

^<<v26-22-26,26>>^ Os seus sacerdotes transgridem a minha lei, e profanam as minhas coisas santas; entre o santo e o profano não fazem diferença, nem discernem o impuro do puro; e de meus sábados escondem os seus olhos, e assim  sou profanado no meio deles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Os seus príncipes no meio dela são como lobos que arrebatam a presa, para derramarem o sangue, para destruírem as almas, para seguirem a avareza.

[[v26-22-28]]

^<<v26-22-28,28>>^ E os seus profetas têm feito para eles reboco de cal não adubada, vendo vaidade, e predizendo-lhes mentira e dizendo: Assim diz o Senhor Jeová ; sem que o SENHOR tivesse falado.

[[v26-22-29]]

^<<v26-22-29,29>>^ Ao povo da terra oprimem gravemente, e andam roubando, e fazem violência ao aflito e ao necessitado, e ao estrangeiro oprimem sem razão.

[[v26-22-30]]

^<<v26-22-30,30>>^ E busquei dentre eles um  homem que estivesse tapando o muro e estivesse na brecha perante mim por esta terra, para que eu não a destruísse; mas a ninguém achei.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso, eu derramei sobre eles a minha indignação; com o fogo do meu furor os consumi; fiz que o seu caminho recaísse sobre a sua cabeça, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]