include::./index.adoc[]

[[v26-10-0]]
=== Ezequiel, 10
// arc ?, ARC - Almeida Revista e Corrigida

[[v26-10-1]]

^<<v26-10-1,1>>^ Depois, olhei, e eis que no firmamento, que estava por cima da cabeça dos querubins, apareceu sobre eles como uma pedra de safira, como o aspecto da semelhança de um trono.

[[v26-10-2]]

^<<v26-10-2,2>>^ E falou ao homem vestido de linho, dizendo: Vai por entre as rodas, até debaixo do querubim, e enche as mãos de brasas acesas dentre os querubins, e espalha-as sobre a cidade. E ele entrou à minha vista.

[[v26-10-3]]

^<<v26-10-3,3>>^ E os querubins estavam ao lado direito da casa, quando entrou aquele homem; e uma nuvem encheu o átrio interior.

[[v26-10-4]]

^<<v26-10-4,4>>^ Então, se levantou a glória do SENHOR de sobre o querubim para a entrada da casa; e encheu-se a casa de uma nuvem, e o átrio se encheu do resplendor da glória do SENHOR.

[[v26-10-5]]

^<<v26-10-5,5>>^ E o estrondo das asas dos querubins se ouviu até ao átrio exterior, como a voz do Deus Todo-Poderoso, quando fala.

[[v26-10-6]]

^<<v26-10-6,6>>^ E sucedeu, pois, dando ele ordem ao homem vestido de linho, dizendo: Toma fogo dentre as rodas, dentre os querubins, que entrou ele e se pôs junto às rodas.

[[v26-10-7]]

^<<v26-10-7,7>>^ Então, estendeu um querubim a mão de entre os querubins para o fogo que estava  entre os querubins; e tirou e o pôs nas mãos do que estava vestido de linho, o qual o tomou e saiu.

[[v26-10-8]]

^<<v26-10-8,8>>^ E apareceu nos querubins uma semelhança de mão de homem debaixo das suas asas.

[[v26-10-9]]

^<<v26-10-9,9>>^ Então, olhei, e eis quatro rodas junto aos querubins, uma roda junto a cada querubim; e o aspecto das rodas era como cor de pedra de turquesa.

[[v26-10-10]]

^<<v26-10-10,10>>^ E, quanto ao seu aspecto, as quatro tinham uma mesma semelhança; eram como se estivesse uma  roda no meio de outra roda.

[[v26-10-11]]

^<<v26-10-11,11>>^ Andando eles, andavam elas pelos seus quatro lados; não se viravam quando andavam, mas para o lugar para onde olhava a cabeça, para esse andavam; não se viravam quando andavam.

[[v26-10-12]]

^<<v26-10-12,12>>^ E todo o seu corpo, e as suas costas, e as suas mãos, e as suas asas, e as rodas, as rodas que os quatro tinham, estavam cheias de olhos em redor.

[[v26-10-13]]

^<<v26-10-13,13>>^ E, quanto às rodas, elas foram chamadas, ouvindo eu, Galgal.

[[v26-10-14]]

^<<v26-10-14,14>>^ E cada um tinha quatro rostos: o rosto do primeiro era rosto de querubim, e o rosto do segundo era rosto de homem, e do terceiro era rosto de leão, e do quarto, rosto de águia.

[[v26-10-15]]

^<<v26-10-15,15>>^ E os querubins se elevaram ao alto; estes são os mesmos animais que vi junto ao rio Quebar.

[[v26-10-16]]

^<<v26-10-16,16>>^ E, andando os querubins, andavam as rodas juntamente com eles; e, levantando os querubins as suas asas, para se elevarem de sobre a terra, também as rodas não se separavam deles.

[[v26-10-17]]

^<<v26-10-17,17>>^ Parando eles, paravam elas, e, elevando-se eles, elevavam-se elas, porque o espírito de vida estava  nelas.

[[v26-10-18]]

^<<v26-10-18,18>>^ Então, saiu a glória do SENHOR da entrada da casa e parou sobre os querubins.

[[v26-10-19]]

^<<v26-10-19,19>>^ E os querubins alçaram as suas asas e se elevaram da terra aos meus olhos, quando saíram; e as rodas os acompanhavam e pararam à entrada da porta oriental da Casa do SENHOR; e a glória do Deus de Israel estava no alto, sobre eles.

[[v26-10-20]]

^<<v26-10-20,20>>^ Estes são  os animais que vi debaixo do Deus de Israel, junto ao rio Quebar, e conheci que eram  querubins.

[[v26-10-21]]

^<<v26-10-21,21>>^ Cada um tinha quatro rostos e quatro asas e a semelhança de mãos de homem debaixo das suas asas.

[[v26-10-22]]

^<<v26-10-22,22>>^ E a semelhança dos seus rostos era a dos  rostos que eu tinha visto junto ao rio Quebar; tinham o mesmo aspecto, eram os próprios; cada um andava ao direito do seu rosto.

'''

xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]