include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// arc ?, ARC - Almeida Revista e Corrigida

[[v26-14-1]]

^<<v26-14-1,1>>^ E vieram a mim alguns  homens dos anciãos de Israel e se assentaram diante de mim.

[[v26-14-2]]

^<<v26-14-2,2>>^ Então, veio a mim a palavra do SENHOR, dizendo:

[[v26-14-3]]

^<<v26-14-3,3>>^ Filho do homem, estes homens levantaram os seus ídolos no seu coração e o tropeço da sua maldade puseram diante da sua face; devo eu de alguma maneira ser interrogado por eles?

[[v26-14-4]]

^<<v26-14-4,4>>^ Portanto, fala com eles e dize-lhes: Assim diz o Senhor Jeová : Qualquer homem da casa de Israel que levantar os seus ídolos no seu coração, e puser o tropeço da sua maldade diante da sua face, e vier ao profeta, eu, o SENHOR, vindo ele, lhe responderei conforme a multidão dos seus ídolos;

[[v26-14-5]]

^<<v26-14-5,5>>^ para que possa apanhar a casa de Israel no seu coração, porquanto todos se apartaram de mim para seguirem  os seus ídolos.

[[v26-14-6]]

^<<v26-14-6,6>>^ Portanto, dize à casa de Israel: Assim diz o Senhor Jeová : Convertei-vos, e deixai os vossos ídolos, e desviai o vosso rosto de todas as vossas abominações.

[[v26-14-7]]

^<<v26-14-7,7>>^ Porque qualquer homem da casa de Israel, ou dos estrangeiros que peregrinam em Israel que se alienar de mim, e levantar os seus ídolos no seu coração, e puser o tropeço da sua maldade diante do seu rosto, e vier ao profeta, para me consultar por meio dele, a esse, eu, o SENHOR, responderei por mim mesmo.

[[v26-14-8]]

^<<v26-14-8,8>>^ E porei o rosto contra o tal homem, e o farei um espanto, um sinal, e um provérbio, e arrancá-lo-ei do meio do meu povo; e sabereis que eu sou  o SENHOR.

[[v26-14-9]]

^<<v26-14-9,9>>^ E, se o profeta for enganado e falar alguma coisa, eu, o SENHOR, persuadi esse profeta; e estenderei a mão contra ele e destruí-lo-ei do meio do meu povo de Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ E levarão a sua maldade; como a maldade do que pergunta será a maldade do profeta;

[[v26-14-11]]

^<<v26-14-11,11>>^ para que a casa de Israel não se desvie mais de mim, nem se contamine mais com todas as suas transgressões; então, eles serão o meu povo, e eu serei o seu Deus, diz o Senhor Jeová .

[[v26-14-12]]

^<<v26-14-12,12>>^ Veio ainda a mim a palavra do SENHOR, dizendo:

[[v26-14-13]]

^<<v26-14-13,13>>^ Filho do homem, quando uma terra pecar contra mim, gravemente se rebelando, então, estenderei a mão contra ela, e tornarei instável o sustento do pão, e enviarei contra ela fome, e arrancarei dela homens e animais;

[[v26-14-14]]

^<<v26-14-14,14>>^ ainda que estivessem no meio dela estes três homens, Noé, Daniel e Jó, eles, pela sua justiça, livrariam apenas a sua alma, diz o Senhor Jeová .

[[v26-14-15]]

^<<v26-14-15,15>>^ Se eu fizer passar pela terra nocivas alimárias, e elas  a assolarem, que fique assolada, e ninguém possa passar por  ela por causa das feras;

[[v26-14-16]]

^<<v26-14-16,16>>^ ainda que esses três homens estivessem  no meio dela, vivo eu, diz o Senhor Jeová , que nem a filhos nem a filhas livrariam; só eles ficariam livres, e a terra seria assolada.

[[v26-14-17]]

^<<v26-14-17,17>>^ Ou, se  eu trouxer a espada sobre a tal terra, e disser: Espada, passa pela terra: e eu arrancar dela homens e animais;

[[v26-14-18]]

^<<v26-14-18,18>>^ ainda que aqueles três homens estivessem  nela, vivo eu, diz o Senhor Jeová , que nem filhos nem filhas livrariam, mas eles só ficariam livres.

[[v26-14-19]]

^<<v26-14-19,19>>^ Ou se  eu enviar a peste sobre a tal terra e derramar o meu furor sobre ela com sangue, para arrancar dela homens e animais;

[[v26-14-20]]

^<<v26-14-20,20>>^ ainda que Noé, Daniel e Jó estivessem  no meio dela, vivo eu, diz o Senhor Jeová , que nem filho nem filha eles livrariam, mas só livrariam a sua própria alma pela sua justiça.

[[v26-14-21]]

^<<v26-14-21,21>>^ Porque assim diz o Senhor Jeová : Quanto mais, se eu enviar os meus quatro maus juízos, a espada, e a fome, e as nocivas alimárias, e a peste, contra Jerusalém para arrancar dela homens e animais?

[[v26-14-22]]

^<<v26-14-22,22>>^ Mas eis que alguns  restarão nela, que serão levados para fora, assim filhos como filhas; eis que eles virão a vós, e vereis o seu caminho e os seus feitos; e ficareis consolados do mal que eu trouxe sobre Jerusalém e  de tudo o que trouxe sobre ela.

[[v26-14-23]]

^<<v26-14-23,23>>^ E sereis consolados, quando virdes o seu caminho e os seus feitos; e sabereis que não fiz sem razão tudo quanto tenho feito nela, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]