include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v61-3-1]]

^<<v61-3-1,1>>^ Amados, escrevo-vos, agora, esta segunda carta, em ambas  as quais desperto com exortação o vosso ânimo sincero,

[[v61-3-2]]

^<<v61-3-2,2>>^ para que vos lembreis das palavras que primeiramente foram ditas pelos santos profetas e do mandamento do Senhor e Salvador, mediante os vossos apóstolos,

[[v61-3-3]]

^<<v61-3-3,3>>^ sabendo primeiro isto: que nos últimos dias virão escarnecedores, andando segundo as suas próprias concupiscências

[[v61-3-4]]

^<<v61-3-4,4>>^ e dizendo: Onde está a promessa da sua vinda? Porque desde que os pais dormiram todas as coisas permanecem como desde o princípio da criação.

[[v61-3-5]]

^<<v61-3-5,5>>^ Eles voluntariamente ignoram isto: que pela palavra de Deus já desde a antiguidade existiram os céus e a terra, que foi tirada da água e no meio da água subsiste;

[[v61-3-6]]

^<<v61-3-6,6>>^ pelas quais coisas  pereceu o mundo de então, coberto com as águas do dilúvio.

[[v61-3-7]]

^<<v61-3-7,7>>^ Mas os céus e a terra que agora existem pela mesma palavra se reservam como tesouro e se guardam para o fogo, até o Dia do Juízo e da perdição dos homens ímpios.

[[v61-3-8]]

^<<v61-3-8,8>>^ Mas, amados, não ignoreis uma coisa: que um dia para o Senhor é  como mil anos, e mil anos, como um dia.

[[v61-3-9]]

^<<v61-3-9,9>>^ O Senhor não retarda a sua  promessa, ainda que alguns a  têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.

[[v61-3-10]]

^<<v61-3-10,10>>^ Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande  estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão.

[[v61-3-11]]

^<<v61-3-11,11>>^ Havendo, pois, de perecer todas estas coisas,  que pessoas vos convém ser em santo trato e piedade,

[[v61-3-12]]

^<<v61-3-12,12>>^ aguardando e apressando- vos  para a vinda do Dia de Deus, em que os céus, em fogo, se desfarão, e os elementos, ardendo, se fundirão?

[[v61-3-13]]

^<<v61-3-13,13>>^ Mas nós, segundo a sua promessa, aguardamos novos céus e nova terra, em que habita a justiça.

[[v61-3-14]]

^<<v61-3-14,14>>^ Pelo que, amados, aguardando estas coisas,  procurai que dele sejais achados imaculados e irrepreensíveis em paz

[[v61-3-15]]

^<<v61-3-15,15>>^ e tende por salvação a longanimidade de nosso Senhor, como também o nosso amado irmão Paulo vos escreveu, segundo a sabedoria que lhe foi dada,

[[v61-3-16]]

^<<v61-3-16,16>>^ falando disto, como em todas as suas  epístolas, entre as quais há pontos difíceis de entender, que os indoutos e inconstantes torcem e igualmente as outras Escrituras, para sua própria perdição.

[[v61-3-17]]

^<<v61-3-17,17>>^ Vós, portanto, amados, sabendo isto  de antemão, guardai-vos de que, pelo engano dos homens abomináveis, sejais juntamente arrebatados e descaiais da vossa firmeza;

[[v61-3-18]]

^<<v61-3-18,18>>^ antes, crescei na graça e conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja  dada a glória, assim agora como no dia da eternidade. Amém!

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]