include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// arc ?, ARC - Almeida Revista e Corrigida

[[v38-2-1]]

^<<v38-2-1,1>>^ Tornei a levantar os meus olhos, e olhei, e vi um homem em cuja mão estava um cordel de medir.

[[v38-2-2]]

^<<v38-2-2,2>>^ E eu disse: Para onde vais tu? E ele me disse: Medir Jerusalém, para ver qual é  a sua largura e qual o seu comprimento.

[[v38-2-3]]

^<<v38-2-3,3>>^ E eis que saiu o anjo que falava comigo, e outro anjo lhe saiu ao encontro

[[v38-2-4]]

^<<v38-2-4,4>>^ e lhe disse: Corre, fala a este jovem, dizendo: Jerusalém será habitada como as aldeias sem muros, por causa da multidão, nela, dos homens e dos animais.

[[v38-2-5]]

^<<v38-2-5,5>>^ E eu, diz o SENHOR, serei para ela um muro de fogo em redor e eu mesmo serei, no meio dela, a sua glória.

[[v38-2-6]]

^<<v38-2-6,6>>^ Olá! Oh! Fugi, agora, da terra do Norte, diz o SENHOR, porque vos espalhei como os quatro ventos do céu, diz o SENHOR.

[[v38-2-7]]

^<<v38-2-7,7>>^ Oh! Sião! Livra-te tu que habitas com  a filha da Babilônia.

[[v38-2-8]]

^<<v38-2-8,8>>^ Porque assim diz o SENHOR dos Exércitos: Depois da glória, ele me enviou às nações que vos despojaram; porque aquele que tocar em vós toca na menina do seu olho.

[[v38-2-9]]

^<<v38-2-9,9>>^ Porque eis aí levantarei a minha mão sobre eles, e eles virão a ser a presa daqueles que os serviram; assim, sabereis vós que o SENHOR dos Exércitos me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ Exulta e alegra-te, ó filha de Sião, porque eis que venho e habitarei no meio de ti, diz o SENHOR.

[[v38-2-11]]

^<<v38-2-11,11>>^ E, naquele dia, muitas nações se ajuntarão ao SENHOR e serão o meu povo; e habitarei no meio de ti, e saberás que o SENHOR dos Exércitos me enviou a ti.

[[v38-2-12]]

^<<v38-2-12,12>>^ Então, o SENHOR possuirá a Judá como sua porção na terra santa e ainda escolherá a Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Cale-se, toda a carne, diante do SENHOR, porque ele despertou na sua santa morada.

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]