include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v38-3-1]]

^<<v38-3-1,1>>^ E me mostrou o sumo sacerdote Josué, o qual estava diante do anjo do SENHOR, e Satanás estava à sua mão direita, para se lhe opor.

[[v38-3-2]]

^<<v38-3-2,2>>^ Mas o SENHOR disse a Satanás: O SENHOR te repreende, ó Satanás, sim, o SENHOR, que escolheu Jerusalém, te repreende; não é este um tição tirado do fogo?

[[v38-3-3]]

^<<v38-3-3,3>>^ Ora, Josué, vestido de vestes sujas, estava diante do anjo.

[[v38-3-4]]

^<<v38-3-4,4>>^ Então, falando, ordenou aos que estavam diante dele, dizendo: Tirai-lhe estas vestes sujas. E a ele lhe disse: Eis que tenho feito com que passe de ti a tua iniquidade e te vestirei de vestes novas.

[[v38-3-5]]

^<<v38-3-5,5>>^ E disse eu: Ponham-lhe uma mitra limpa sobre a sua cabeça. E puseram uma mitra limpa sobre sua cabeça e o vestiram de vestes; e o anjo do SENHOR estava ali.

[[v38-3-6]]

^<<v38-3-6,6>>^ E o anjo do SENHOR protestou a Josué, dizendo:

[[v38-3-7]]

^<<v38-3-7,7>>^ Assim diz o SENHOR dos Exércitos: Se andares nos meus caminhos e se observares as minhas ordenanças, também tu julgarás a minha casa e também guardarás os meus átrios, e te darei lugar entre os que estão aqui.

[[v38-3-8]]

^<<v38-3-8,8>>^ Ouve, pois, Josué, sumo sacerdote, tu e os teus companheiros que se assentam diante de ti, porque são  homens portentosos; eis que eu farei vir o meu servo, o Renovo.

[[v38-3-9]]

^<<v38-3-9,9>>^ Porque eis aqui a pedra que pus diante de Josué; sobre esta pedra única estão sete olhos; eis que eu esculpirei a sua escultura, diz o SENHOR dos Exércitos, e tirarei a iniquidade desta terra, em um dia.

[[v38-3-10]]

^<<v38-3-10,10>>^ Naquele dia, diz o SENHOR dos Exércitos, cada um de vós convidará o seu companheiro para debaixo da videira e para debaixo da figueira.

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]