include::./index.adoc[]

[[v13-1-0]]
=== 1 Crônicas, 1
// arc ?, ARC - Almeida Revista e Corrigida

[[v13-1-1]]

^<<v13-1-1,1>>^ Adão, Sete, Enos,

[[v13-1-2]]

^<<v13-1-2,2>>^ Cainã, Maalalel, Jarede,

[[v13-1-3]]

^<<v13-1-3,3>>^ Enoque, Metusalém, Lameque,

[[v13-1-4]]

^<<v13-1-4,4>>^ Noé, Sem, Cam e Jafé.

[[v13-1-5]]

^<<v13-1-5,5>>^ Os filhos de Jafé foram:  Gomer, e Magogue, e Madai, e Javã, e Tubal, e Meseque, e Tiras.

[[v13-1-6]]

^<<v13-1-6,6>>^ E os filhos de Gomer: Asquenaz, e Rifate, e Togarma.

[[v13-1-7]]

^<<v13-1-7,7>>^ E os filhos de Javã: Elisá, e Társis, e Quitim, e Dodanim.

[[v13-1-8]]

^<<v13-1-8,8>>^ Os filhos de Cam: Cuxe, e Mizraim, e Pute e Canaã.

[[v13-1-9]]

^<<v13-1-9,9>>^ E os filhos de Cuxe eram  Sebá, e Havilá, e Sabtá, e Raamá, e Sabtecá; e os filhos de Raamá eram  Sabá e Dedã.

[[v13-1-10]]

^<<v13-1-10,10>>^ E Cuxe gerou a Ninrode, que começou a ser poderoso na terra.

[[v13-1-11]]

^<<v13-1-11,11>>^ E Mizraim gerou os ludeus, e os anameus, e os leabeus, e os naftueus,

[[v13-1-12]]

^<<v13-1-12,12>>^ e os patruseus, e os caslueus (dos quais procederam os filisteus), e os caftoreus.

[[v13-1-13]]

^<<v13-1-13,13>>^ E Canaã gerou a Sidom, seu primogênito, e a Hete,

[[v13-1-14]]

^<<v13-1-14,14>>^ e os jebuseus, e os amorreus, e os girgaseus,

[[v13-1-15]]

^<<v13-1-15,15>>^ e os heveus, e os arqueus, e os sineus,

[[v13-1-16]]

^<<v13-1-16,16>>^ e os arvadeus, e os zemareus, e os hamateus.

[[v13-1-17]]

^<<v13-1-17,17>>^ E foram os filhos de Sem: Elão, e Assur, e Arfaxade, e Lude, e Arã, e Uz, e Hul, e Geter, e Meseque.

[[v13-1-18]]

^<<v13-1-18,18>>^ E Arfaxade gerou a Selá, e Selá gerou a Héber.

[[v13-1-19]]

^<<v13-1-19,19>>^ E a Héber nasceram dois filhos: o nome de um foi  Pelegue, porquanto nos seus dias se repartiu a terra; e o nome de seu irmão era  Joctã.

[[v13-1-20]]

^<<v13-1-20,20>>^ E Joctã gerou a Almodá, e a Selefe, e a Hazar-Mavé, e a Jerá,

[[v13-1-21]]

^<<v13-1-21,21>>^ e a Hadorão, e a Uzal, e a Dicla,

[[v13-1-22]]

^<<v13-1-22,22>>^ e a Ebal, e a Abimael, e a Sabá,

[[v13-1-23]]

^<<v13-1-23,23>>^ e a Ofir, e a Havilá, e a Jobabe; todos estes foram  filhos de Joctã.

[[v13-1-24]]

^<<v13-1-24,24>>^ Sem, Arfaxade, Selá,

[[v13-1-25]]

^<<v13-1-25,25>>^ Héber, Pelegue, Reú,

[[v13-1-26]]

^<<v13-1-26,26>>^ Serugue, Naor, Tera,

[[v13-1-27]]

^<<v13-1-27,27>>^ Abrão, que é  Abraão.

[[v13-1-28]]

^<<v13-1-28,28>>^ Os filhos de Abraão foram  Isaque e Ismael.

[[v13-1-29]]

^<<v13-1-29,29>>^ Estas são  as suas gerações: o primogênito de Ismael foi  Nebaiote, e Quedar, e Adbeel, e Mibsão,

[[v13-1-30]]

^<<v13-1-30,30>>^ Misma, Dumá, Massá, Hadade, Temá,

[[v13-1-31]]

^<<v13-1-31,31>>^ Jetur, Nafis e Quedemá; estes foram  os filhos de Ismael.

[[v13-1-32]]

^<<v13-1-32,32>>^ Quanto aos filhos de Quetura, concubina de Abraão, esta deu à luz a Zinrã, e a Jocsã, e a Medã, e a Midiã, e a Isbaque, e a Sua; e os filhos de Jocsã foram  Sabá e Dedã.

[[v13-1-33]]

^<<v13-1-33,33>>^ E os filhos de Midiã: Efá, e Efer, e Enoque, e Abida, e Elda; todos estes foram  filhos de Quetura.

[[v13-1-34]]

^<<v13-1-34,34>>^ Abraão, pois, gerou a Isaque; e foram  os filhos de Isaque: Esaú e Israel.

[[v13-1-35]]

^<<v13-1-35,35>>^ Os filhos de Esaú: Elifaz, e Reuel, e Jeús, e Jalão, e Corá.

[[v13-1-36]]

^<<v13-1-36,36>>^ Os filhos de Elifaz: Temã, e Omar, e Zefi, e Gaetã, e Quenaz, e Timna, e Amaleque.

[[v13-1-37]]

^<<v13-1-37,37>>^ Os filhos de Reuel: Naate, Zerá, Samá e Mizá.

[[v13-1-38]]

^<<v13-1-38,38>>^ E os filhos de Seir: Lotã, e Sobal, e Zibeão, e Aná, e Disom, e Eser, e Disã.

[[v13-1-39]]

^<<v13-1-39,39>>^ E os filhos de Lotã: Hori e Homã; e a irmã de Lotã foi  Timna.

[[v13-1-40]]

^<<v13-1-40,40>>^ Os filhos de Sobal eram  Aliã, e Manaate, e Ebal, Sefô, e Onã; e os filhos de Zibeão eram  Aías e Aná.

[[v13-1-41]]

^<<v13-1-41,41>>^ O filho de Aná foi  Disom; e os filhos de Disom foram  Hanrão, e Esbã, e Itrã, e Querã.

[[v13-1-42]]

^<<v13-1-42,42>>^ Os filhos de Eser eram  Bilã, e Zaavã, e  Jaacã; os filhos de Disã eram  Uz e Arã.

[[v13-1-43]]

^<<v13-1-43,43>>^ E estes são  os reis que reinaram na terra de Edom, antes que reinasse rei sobre os filhos de Israel: Belá, filho de Beor; e era  o nome da sua cidade Dinabá.

[[v13-1-44]]

^<<v13-1-44,44>>^ E morreu Belá, e reinou em seu lugar Jobabe, filho de Zerá, de Bozra.

[[v13-1-45]]

^<<v13-1-45,45>>^ E morreu Jobabe, e reinou em seu lugar Husão, da terra dos temanitas.

[[v13-1-46]]

^<<v13-1-46,46>>^ E morreu Husão, e reinou em seu lugar Hadade, filho de Bedade; este feriu os midianitas no campo de Moabe; e era  o nome da sua cidade Avite.

[[v13-1-47]]

^<<v13-1-47,47>>^ E morreu Hadade, e reinou em seu lugar Samlá, de Masreca.

[[v13-1-48]]

^<<v13-1-48,48>>^ E morreu Samlá, e reinou em seu lugar Saul, de Reobote, junto ao rio Eufrates.

[[v13-1-49]]

^<<v13-1-49,49>>^ E morreu Saul, e reinou em seu lugar Baal-Hanã, filho de Acbor.

[[v13-1-50]]

^<<v13-1-50,50>>^ E, morrendo Baal-Hanã, Hadade reinou em seu lugar; e era  o nome da sua cidade Paú; e o nome de sua mulher era  Meetabel, filha de Matrede, a filha de Me-Zaabe.

[[v13-1-51]]

^<<v13-1-51,51>>^ E, morrendo Hadade, foram príncipes em Edom o príncipe Timna, o príncipe Alva, o príncipe Jetete,

[[v13-1-52]]

^<<v13-1-52,52>>^ o príncipe Oolibama, o príncipe Elá, o príncipe Pinom,

[[v13-1-53]]

^<<v13-1-53,53>>^ o príncipe Quenaz, o príncipe Temã, o príncipe Mibzar,

[[v13-1-54]]

^<<v13-1-54,54>>^ o príncipe Magdiel e o príncipe Irão; estes foram  os príncipes de Edom.

'''

xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[&#60; Capítulo Anterior] | <<v13-1-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[Próximo Capítulo &#62;]