include::./index.adoc[]

[[v13-12-0]]
=== 1 Crônicas, 12
// arc ?, ARC - Almeida Revista e Corrigida

[[v13-12-1]]

^<<v13-12-1,1>>^ Estes, porém, são  os que vieram a Davi, a Ziclague, sendo ele ainda fugitivo, por causa de Saul, filho de Quis; e eram dos valentes que ajudaram nesta guerra.

[[v13-12-2]]

^<<v13-12-2,2>>^ Armados de arco, usavam da mão direita e esquerda em atirar pedras e em despedir  flechas com o arco; eram estes  dos irmãos de Saul, benjamitas:

[[v13-12-3]]

^<<v13-12-3,3>>^ Aiezer, o chefe, e Joás, filhos de Semaá, o gibeatita; Jeziel e Pelete, filhos de Azmavete; e Beraca, e Jeú, o anatotita;

[[v13-12-4]]

^<<v13-12-4,4>>^ e Ismaías, o gibeonita, valente entre os trinta e capitão dos trinta; Jeremias, e Jaaziel, e Joanã, e Jozabade, o gederatita;

[[v13-12-5]]

^<<v13-12-5,5>>^ Eluzai, e Jerimote, e Bealias, e Semarias, e Sefatias, o harufita;

[[v13-12-6]]

^<<v13-12-6,6>>^ Elcana, e Issias, e Azarel, e Joezer, e Jasobeão, os coraítas;

[[v13-12-7]]

^<<v13-12-7,7>>^ e Joela, e Zebadias, filhos de Jeroão, de Gedor.

[[v13-12-8]]

^<<v13-12-8,8>>^ E dos gaditas se retiraram a Davi, ao lugar forte no deserto, varões valentes, homens de guerra para pelejar, armados com rodela e lança; e seus rostos eram  como rostos de leões, e eles eram ligeiros como corças sobre os montes;

[[v13-12-9]]

^<<v13-12-9,9>>^ Eser, o cabeça, Obadias, o segundo, Eliabe, o terceiro,

[[v13-12-10]]

^<<v13-12-10,10>>^ Mismana, o quarto, Jeremias, o quinto,

[[v13-12-11]]

^<<v13-12-11,11>>^ Atai, o sexto, Eliel, o sétimo,

[[v13-12-12]]

^<<v13-12-12,12>>^ Joanã, o oitavo, Elzabade, o nono,

[[v13-12-13]]

^<<v13-12-13,13>>^ Jeremias, o décimo, Macbanai, o undécimo;

[[v13-12-14]]

^<<v13-12-14,14>>^ estes, dos filhos de Gade, foram  os capitães do exército; um dos menores tinha  o cargo de cem, e o maior, de mil.

[[v13-12-15]]

^<<v13-12-15,15>>^ Estes são  os que passaram o Jordão no mês primeiro, quando ele transbordava por todas as suas ribanceiras, e fizeram fugir a todos os dos vales para o oriente e para o ocidente.

[[v13-12-16]]

^<<v13-12-16,16>>^ Também vieram alguns dos filhos de Benjamim e de Judá a Davi, ao lugar forte.

[[v13-12-17]]

^<<v13-12-17,17>>^ E Davi lhes saiu ao encontro e lhes falou, dizendo: Se vós vindes a mim pacificamente e para me ajudar, o meu coração se unirá convosco; porém, se é  para me entregardes aos meus inimigos, sem que haja deslealdade nas minhas mãos, o Deus de nossos pais o veja e o repreenda.

[[v13-12-18]]

^<<v13-12-18,18>>^ Então, entrou o Espírito em Amasai, chefe de trinta, e disse:  Nós somos teus, ó Davi! E contigo estamos, ó filho de Jessé! Paz, paz seja contigo! E paz com quem te ajuda! Pois que teu Deus te ajuda. E Davi os recebeu e os fez capitães das tropas.

[[v13-12-19]]

^<<v13-12-19,19>>^ Também de Manassés alguns  passaram a Davi, quando veio com os filisteus para a batalha contra Saul, ainda que não ajudaram os filisteus; porque os príncipes dos filisteus, com conselho, o despediram, dizendo: À custa de  nossa cabeça passará a Saul, seu senhor.

[[v13-12-20]]

^<<v13-12-20,20>>^ Voltando ele, pois, a Ziclague, passaram para ele, de Manassés, Adna, e Jozabade, e Jediael, e Micael, e Jozabade, e Eliú, e Ziletai, chefes de milhares dos de Manassés.

[[v13-12-21]]

^<<v13-12-21,21>>^ E estes ajudaram a Davi contra aquela tropa, porque todos eles eram  heróis valentes e foram capitães no exército.

[[v13-12-22]]

^<<v13-12-22,22>>^ Porque, naquele tempo, de dia em dia, vinham a Davi para o ajudar, até que se fez  um grande exército, como exército de Deus.

[[v13-12-23]]

^<<v13-12-23,23>>^ Ora, este é  o número dos chefes armados para a peleja, que vieram a Davi em Hebrom, para transferir a ele o reino de Saul, conforme a palavra do SENHOR:

[[v13-12-24]]

^<<v13-12-24,24>>^ dos filhos de Judá, que traziam rodela e lança, seis mil e oitocentos, armados para a peleja;

[[v13-12-25]]

^<<v13-12-25,25>>^ dos filhos de Simeão, varões valentes para pelejar, sete mil e cem;

[[v13-12-26]]

^<<v13-12-26,26>>^ dos filhos de Levi, quatro mil e seiscentos.

[[v13-12-27]]

^<<v13-12-27,27>>^ Joiada, porém, era  o chefe dos de Arão, e com ele vieram três mil e setecentos;

[[v13-12-28]]

^<<v13-12-28,28>>^ Zadoque, sendo ainda jovem, varão valente, da família de seu pai, trouxe vinte e dois príncipes.

[[v13-12-29]]

^<<v13-12-29,29>>^ E dos filhos de Benjamim, irmãos de Saul, vieram três mil, porque até então havia ainda muitos deles que eram pela casa de Saul;

[[v13-12-30]]

^<<v13-12-30,30>>^ dos filhos de Efraim, vinte mil e oitocentos varões valentes, homens de nome em casa de seus pais;

[[v13-12-31]]

^<<v13-12-31,31>>^ da meia tribo de Manassés, dezoito mil, que foram apontados pelos seus nomes para vir a fazer rei a Davi;

[[v13-12-32]]

^<<v13-12-32,32>>^ dos filhos de Issacar, destros na ciência dos tempos, para saberem o que Israel devia fazer, duzentos de seus chefes e todos os seus irmãos, que seguiam a sua palavra;

[[v13-12-33]]

^<<v13-12-33,33>>^ de Zebulom, dos que saíam ao exército, ordenados para a peleja com todas as armas de guerra, cinquenta mil, também destros, para ordenarem uma batalha com coração constante;

[[v13-12-34]]

^<<v13-12-34,34>>^ de Naftali, mil capitães e com eles trinta e sete mil com rodela e lança;

[[v13-12-35]]

^<<v13-12-35,35>>^ dos danitas, ordenados para a peleja, vinte e oito mil e seiscentos;

[[v13-12-36]]

^<<v13-12-36,36>>^ de Aser, dos que saíam para o exército, para ordenarem a batalha, quarenta mil;

[[v13-12-37]]

^<<v13-12-37,37>>^ da banda dalém do Jordão, dos rubenitas e gaditas e da meia tribo de Manassés, com toda sorte de instrumentos de guerra para pelejar, cento e vinte mil.

[[v13-12-38]]

^<<v13-12-38,38>>^ Todos estes homens de guerra, postos em ordem de batalha, com coração inteiro, vieram a Hebrom para levantar a Davi rei sobre todo o Israel; e também todo o resto de Israel tinha  o mesmo coração para levantar a Davi rei.

[[v13-12-39]]

^<<v13-12-39,39>>^ E estiveram ali com Davi três dias, comendo e bebendo; porque seus irmãos lhes tinham preparado as provisões.

[[v13-12-40]]

^<<v13-12-40,40>>^ E também seus vizinhos de mais perto, até Issacar, e Zebulom, e Naftali, trouxeram pão sobre jumentos, e sobre camelos, e sobre mulos, e sobre bois, provisões de farinha, pastas de figos, e cachos de passas, e vinho, e azeite, e bois, e gado miúdo em abundância; porque havia  alegria em Israel.

'''

xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[Próximo Capítulo &#62;]