include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// arc ?, ARC - Almeida Revista e Corrigida

[[v13-15-1]]

^<<v13-15-1,1>>^ Fez também Davi casa para si na Cidade de Davi; e preparou um lugar para a arca de Deus e armou-lhe uma tenda.

[[v13-15-2]]

^<<v13-15-2,2>>^ Então, disse Davi: Ninguém pode levar a arca do SENHOR, senão os levitas; porque o SENHOR os elegeu, para levarem a arca do SENHOR e para o servirem eternamente.

[[v13-15-3]]

^<<v13-15-3,3>>^ E Davi ajuntou a todo o Israel em Jerusalém, para fazerem subir a arca do SENHOR ao seu lugar, que lhe tinha preparado.

[[v13-15-4]]

^<<v13-15-4,4>>^ E Davi ajuntou os filhos de Arão e os levitas:

[[v13-15-5]]

^<<v13-15-5,5>>^ dos filhos de Coate: Uriel, o príncipe, e seus irmãos, cento e vinte;

[[v13-15-6]]

^<<v13-15-6,6>>^ dos filhos de Merari: Asaías, o príncipe, e seus irmãos, duzentos e vinte;

[[v13-15-7]]

^<<v13-15-7,7>>^ dos filhos de Gérson: Joel, o príncipe, e seus irmãos, cento e trinta;

[[v13-15-8]]

^<<v13-15-8,8>>^ dos filhos de Elisafã: Semaías, o príncipe, e seus irmãos, duzentos;

[[v13-15-9]]

^<<v13-15-9,9>>^ dos filhos de Hebrom: Eliel, o príncipe, e seus irmãos, oitenta;

[[v13-15-10]]

^<<v13-15-10,10>>^ dos filhos de Uziel: Aminadabe, o príncipe, e seus irmãos, cento e doze.

[[v13-15-11]]

^<<v13-15-11,11>>^ E chamou Davi os sacerdotes Zadoque e Abiatar e os levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe

[[v13-15-12]]

^<<v13-15-12,12>>^ e disse-lhes: Vós sois  os chefes dos pais entre os levitas; santificai-vos, vós e vossos irmãos, para que façais subir a arca do SENHOR, Deus de Israel, ao lugar  que lhe tenho preparado.

[[v13-15-13]]

^<<v13-15-13,13>>^ Pois que, porquanto primeiro vós assim o  não fizestes,  o SENHOR fez rotura em nós, porque o não buscamos segundo a ordenança.

[[v13-15-14]]

^<<v13-15-14,14>>^ Santificaram-se, pois, os sacerdotes e levitas, para fazerem subir a arca do SENHOR, Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ E os filhos dos levitas trouxeram a arca de Deus aos ombros, como Moisés tinha ordenado, conforme a palavra do SENHOR, com as varas que tinham sobre si.

[[v13-15-16]]

^<<v13-15-16,16>>^ E disse Davi aos príncipes dos levitas que constituíssem a seus irmãos, os cantores, com instrumentos músicos, com alaúdes, harpas e címbalos, para que se fizessem ouvir, levantando a voz com alegria.

[[v13-15-17]]

^<<v13-15-17,17>>^ Ordenaram, pois, os levitas a Hemã, filho de Joel; e dos seus irmãos a Asafe, filho de Berequias; e dos filhos de Merari, seus irmãos, a Etã, filho de Cusaías.

[[v13-15-18]]

^<<v13-15-18,18>>^ E com eles a seus irmãos da segunda ordem:  Zacarias, e Bene, e Jaaziel, e Semiramote, e Jeiel, e Uni, e Eliabe, e Benaia, e Maaseias, e Matitias, e Elifeleu, e Micneias, e Obede-Edom, e Jeiel, os porteiros.

[[v13-15-19]]

^<<v13-15-19,19>>^ E os cantores, Hemã, Asafe e Etã se faziam  ouvir com címbalos de metal;

[[v13-15-20]]

^<<v13-15-20,20>>^ e Zacarias, e Aziel, e Semiramote, e Jeiel, e Uni, e Eliabe, e Maaseias, e Benaia, com alaúdes, sobre Alamote;

[[v13-15-21]]

^<<v13-15-21,21>>^ e Matitias, e Elifeleu, e Micneias, e Obede-Edom, e Jeiel, e Azazias, com harpas, sobre Seminite, para esforçar o tom.

[[v13-15-22]]

^<<v13-15-22,22>>^ E Quenanias, príncipe dos levitas, tinha cargo  de entoar o canto; ensinava-os a entoá-lo, porque era  entendido nisso.

[[v13-15-23]]

^<<v13-15-23,23>>^ E Berequias e Elcana eram  porteiros da arca.

[[v13-15-24]]

^<<v13-15-24,24>>^ E Sebanias, e Josafá, e Netanel, e Amasai, e Zacarias, e Benaia, e Eliézer, os sacerdotes, tocavam as trombetas perante a arca de Deus; e Obede-Edom e Jeías eram  porteiros da arca.

[[v13-15-25]]

^<<v13-15-25,25>>^ Sucedeu, pois, que Davi, e os anciãos de Israel, e os capitães dos milhares foram para fazerem subir, com alegria, a arca do concerto do SENHOR, da casa de Obede-Edom.

[[v13-15-26]]

^<<v13-15-26,26>>^ E sucedeu que, ajudando Deus os levitas que levavam a arca do concerto do SENHOR, sacrificaram sete novilhos e sete carneiros.

[[v13-15-27]]

^<<v13-15-27,27>>^ E Davi ia  vestido de um roupão de linho fino, como também todos os levitas que levavam a arca, e os cantores, e Quenanias, chefe dos que levavam a arca e  dos cantores; também Davi levava  sobre si um  éfode de linho.

[[v13-15-28]]

^<<v13-15-28,28>>^ E todo o Israel fez subir a arca do concerto do SENHOR, com júbilo, e com sonido de buzinas, e com trombetas, e com címbalos, fazendo sonido com alaúdes e com harpas.

[[v13-15-29]]

^<<v13-15-29,29>>^ E sucedeu que, chegando a arca do concerto do SENHOR à Cidade de Davi, Mical, filha de Saul, olhou de uma janela e, vendo a Davi dançar e tocar, o desprezou no seu coração.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]