include::./index.adoc[]

[[v13-7-0]]
=== 1 Crônicas, 7
// arc ?, ARC - Almeida Revista e Corrigida

[[v13-7-1]]

^<<v13-7-1,1>>^ E, quanto aos filhos de Issacar, foram:  Tola, e Puva, Jasube, e Sinrom, quatro.

[[v13-7-2]]

^<<v13-7-2,2>>^ E os filhos de Tola foram:  Uzi, e Refaías, e Jeriel, e Jamai, e Ibsão, e Samuel, chefes das casas de seus pais, e descendentes de Tola, varões de valor nas suas gerações; o seu número, nos dias de Davi, foi de vinte e dois mil e seiscentos.

[[v13-7-3]]

^<<v13-7-3,3>>^ E, quanto aos filhos de Uzi, houve  Izraías; e os filhos de Izraías foram  Micael, e Obadias, e Joel, e Issias; todos estes cinco foram chefes.

[[v13-7-4]]

^<<v13-7-4,4>>^ E houve  com eles, nas suas gerações, segundo as suas casas paternas, em  tropas de gente de guerra, trinta e seis mil; porque tiveram muitas mulheres e filhos.

[[v13-7-5]]

^<<v13-7-5,5>>^ E seus irmãos, em todas as famílias de Issacar, varões de valor, foram oitenta e sete mil, todos contados pelas suas genealogias.

[[v13-7-6]]

^<<v13-7-6,6>>^ Os filhos  de Benjamim foram:  Belá, e Bequer, e Jediael, três.

[[v13-7-7]]

^<<v13-7-7,7>>^ E os filhos de Belá: Esbom, e Uzi, e Uziel, e Jerimote, e Iri, cinco chefes da casa dos pais, varões de valor, que foram contados pelas suas genealogias, vinte e dois mil e trinta e quatro.

[[v13-7-8]]

^<<v13-7-8,8>>^ E os filhos de Bequer: Zemira, e Joás, e Eliézer, e Elioenai, e Onri, e Jerimote, e Abias, e Anatote, e Alemete; todos estes foram  filhos de Bequer.

[[v13-7-9]]

^<<v13-7-9,9>>^ E foram  contados pelas suas genealogias, segundo as suas gerações, e  chefes das casas de seus pais, varões de valor, vinte mil e duzentos.

[[v13-7-10]]

^<<v13-7-10,10>>^ E foram  os filhos de Jediael, Bilã; e os filhos de Bilã foram  Jeús, e Benjamim, e Eúde, e Quenaana, e Zetã, e Társis, e Aisaar.

[[v13-7-11]]

^<<v13-7-11,11>>^ Todos estes filhos de Jediael foram  chefes das famílias  dos pais, varões de valor, dezessete mil e duzentos, que saíam no exército à peleja.

[[v13-7-12]]

^<<v13-7-12,12>>^ E Supim, e Hupim, filho de Ir; e  Husim, dos filhos de Aer.

[[v13-7-13]]

^<<v13-7-13,13>>^ Os filhos de Naftali: Jaziel, e Guni, e Jezer, e Salum, filhos de Bila.

[[v13-7-14]]

^<<v13-7-14,14>>^ Os filhos de Manassés: Asriel, que a mulher de Gileade  teve (porém  a sua concubina, a sira, teve a Maquir, pai de Gileade;

[[v13-7-15]]

^<<v13-7-15,15>>^ e Maquir tomou a irmã  de Hupim e Supim por mulher; e era  o seu nome Maaca), e foi  o nome do segundo Zelofeade; e Zelofeade teve filhas.

[[v13-7-16]]

^<<v13-7-16,16>>^ E Maaca, mulher de Maquir, teve um filho e chamou o seu nome Perez; e o nome de seu irmão foi  Seres; e foram  seus filhos Ulão e Requém.

[[v13-7-17]]

^<<v13-7-17,17>>^ E o filho de Ulão: Bedã; estes foram  os filhos de Gileade, filho de Maquir, filho de Manassés.

[[v13-7-18]]

^<<v13-7-18,18>>^ E, quanto à sua irmã Hamolequete, teve a Isode, e a Abiezer, e a Macla.

[[v13-7-19]]

^<<v13-7-19,19>>^ E foram os filhos de Semida: Aiã, e Siquém, e Liqui, e Anião.

[[v13-7-20]]

^<<v13-7-20,20>>^ E os filhos de Efraim: Sutela, e seu filho Berede, e seu filho Taate, e seu filho Eleada e seu filho Taate,

[[v13-7-21]]

^<<v13-7-21,21>>^ e seu filho Zabade, e seu filho Sutela, e Eser, e Eleade; e os homens de Gate, naturais da terra, os mataram, porque desceram para tomar os seus gados.

[[v13-7-22]]

^<<v13-7-22,22>>^ Pelo que Efraim, seu pai, por muitos dias os chorou; e vieram seus irmãos para o consolar.

[[v13-7-23]]

^<<v13-7-23,23>>^ Depois, entrou à sua mulher, e ela  concebeu e teve um filho; e chamou o seu nome Berias, porque as coisas iam mal na sua casa.

[[v13-7-24]]

^<<v13-7-24,24>>^ E sua filha foi  Seerá, que edificou a Bete-Horom, a baixa e a alta, como também a Uzém-Seerá.

[[v13-7-25]]

^<<v13-7-25,25>>^ E foi  seu filho Refa, e Resefe, e Tela, seu filho, e Taã, seu filho,

[[v13-7-26]]

^<<v13-7-26,26>>^ seu filho Ladã, seu filho Amiúde, seu filho Elisama,

[[v13-7-27]]

^<<v13-7-27,27>>^ seu filho Num, seu filho Josué.

[[v13-7-28]]

^<<v13-7-28,28>>^ E foi  a sua possessão e habitação Betel, e os lugares da sua jurisdição; e ao oriente Naarã; e ao ocidente Gezer, e os lugares da sua jurisdição, e Siquém, e os lugares da sua jurisdição, até Aia, e os lugares da sua jurisdição;

[[v13-7-29]]

^<<v13-7-29,29>>^ e da banda dos filhos de Manassés, Bete-Seã, e os lugares da sua jurisdição, Megido, e os lugares da sua jurisdição, Taanaque, e os lugares da sua jurisdição, Dor, e os lugares da sua jurisdição; nestas habitaram os filhos de José, filho de Israel.

[[v13-7-30]]

^<<v13-7-30,30>>^ Os filhos de Aser foram:  Imna, e Isvá, e Isvi, e Berias, e Sera, sua irmã.

[[v13-7-31]]

^<<v13-7-31,31>>^ E os filhos de Berias: Héber e Malquiel; este foi o pai de Birzavite.

[[v13-7-32]]

^<<v13-7-32,32>>^ E Héber gerou a Jaflete, e a Somer, e a Hotão, e a Suá, sua irmã.

[[v13-7-33]]

^<<v13-7-33,33>>^ E foram  os filhos de Jaflete: Pasaque, e Bimal, e Asvate; estes foram  os filhos de Jaflete.

[[v13-7-34]]

^<<v13-7-34,34>>^ E os filhos de Semer: Aí, e Roga, e Jeubá, e Arã.

[[v13-7-35]]

^<<v13-7-35,35>>^ E os filhos de seu irmão Helém: Zofa, e Imna, e Seles, e Amal.

[[v13-7-36]]

^<<v13-7-36,36>>^ Os filhos de Zofa: Suá, e Harnefer, e Sual, e Beri, e Inra,

[[v13-7-37]]

^<<v13-7-37,37>>^ e Bezer, e Hode, e Samá, e Silsa, e Itrã, e Beera.

[[v13-7-38]]

^<<v13-7-38,38>>^ E os filhos de Jéter: Jefoné, e Pispa, e Ara.

[[v13-7-39]]

^<<v13-7-39,39>>^ E os filhos de Ula: Ara, e Haniel, e Rizia.

[[v13-7-40]]

^<<v13-7-40,40>>^ Todos estes foram  filhos de Aser, chefes das casas paternas, escolhidos varões de valor, chefes dos príncipes, e contados nas suas genealogias, no exército para a guerra; foi seu número de vinte e seis mil homens.

'''

xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[&#60; Capítulo Anterior] | <<v13-7-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[Próximo Capítulo &#62;]