include::./index.adoc[]

[[v13-22-0]]
=== 1 Crônicas, 22
// arc ?, ARC - Almeida Revista e Corrigida

[[v13-22-1]]

^<<v13-22-1,1>>^ E disse Davi: Esta será  a Casa do SENHOR Deus, e este será  o altar do holocausto para Israel.

[[v13-22-2]]

^<<v13-22-2,2>>^ E deu ordem Davi que se ajuntassem os estranhos que estavam  na terra de Israel; e ordenou cortadores de pedras, para que lavrassem pedras de cantaria, para edificar a Casa de Deus.

[[v13-22-3]]

^<<v13-22-3,3>>^ E aparelhou Davi ferro em abundância, para os pregos das portas das entradas e para as junturas, como também cobre em abundância, que nem foi pesado;

[[v13-22-4]]

^<<v13-22-4,4>>^ e madeira de cedro sem conta, porque os sidônios e tírios traziam a Davi madeira de cedro em abundância.

[[v13-22-5]]

^<<v13-22-5,5>>^ Porque dizia Davi: Salomão, meu filho, ainda é  moço e tenro, e a casa que se há de edificar para o Senhor se há de  fazer magnífica em excelência, para nome e glória em todas as terras; eu, pois,  agora, lhe prepararei materiais.  Assim, preparou Davi materiais  em abundância, antes da sua morte.

[[v13-22-6]]

^<<v13-22-6,6>>^ Então, chamou a Salomão, seu filho, e lhe ordenou que edificasse uma  Casa ao SENHOR, Deus de Israel.

[[v13-22-7]]

^<<v13-22-7,7>>^ E disse Davi a Salomão: Filho meu, quanto a mim, tive em meu coração o edificar casa ao nome do SENHOR, meu Deus.

[[v13-22-8]]

^<<v13-22-8,8>>^ Porém a mim a palavra do SENHOR veio, dizendo: Tu derramaste sangue em abundância e fizeste grandes guerras; não edificarás casa ao meu nome; porquanto muito sangue tens derramado na terra, perante a minha face.

[[v13-22-9]]

^<<v13-22-9,9>>^ Eis que o filho que te nascer será homem de repouso; porque repouso lhe hei de dar de todos os seus inimigos em redor; portanto, Salomão será o seu nome, e paz e descanso darei a Israel nos seus dias.

[[v13-22-10]]

^<<v13-22-10,10>>^ Este edificará casa ao meu nome; ele me será por  filho, e eu a ele por  pai; e confirmarei o trono de seu reino sobre Israel, para sempre.

[[v13-22-11]]

^<<v13-22-11,11>>^ Agora, pois, meu filho, o SENHOR seja contigo, e prospera e edifica a Casa do SENHOR, teu Deus, como ele disse de ti.

[[v13-22-12]]

^<<v13-22-12,12>>^ O SENHOR te dê tão somente prudência e entendimento e te instrua acerca de Israel; e isso para guardar a Lei do SENHOR, teu Deus.

[[v13-22-13]]

^<<v13-22-13,13>>^ Então, prosperarás, se tiveres cuidado de fazer os estatutos e os juízos, que o SENHOR mandou a Moisés acerca de Israel; esforça-te, e tem bom ânimo, e não temas, nem tenhas pavor.

[[v13-22-14]]

^<<v13-22-14,14>>^ Eis que na minha opressão preparei para a Casa do SENHOR cem mil talentos de ouro, e um milhão de talentos de prata, e de cobre e de ferro que nem foi pesado, porque em abundância é; também madeira e pedras preparei, e tu, supre o que faltar.

[[v13-22-15]]

^<<v13-22-15,15>>^ Também tens  contigo oficiais mecânicos em multidão, e cortadores, e artífices em obra  de pedra e madeira, e toda sorte de sábios em toda sorte de obra.

[[v13-22-16]]

^<<v13-22-16,16>>^ Do ouro, e da prata, e do cobre, e do ferro não há  número; levanta-te, pois,  e faze a obra,  e o SENHOR seja contigo.

[[v13-22-17]]

^<<v13-22-17,17>>^ E Davi deu ordem a todos os príncipes de Israel que ajudassem a Salomão, seu filho, dizendo:

[[v13-22-18]]

^<<v13-22-18,18>>^ Porventura,  não está  convosco o SENHOR, vosso Deus, e não  vos deu repouso em roda? Porque tem entregado na minha mão os moradores da terra; e a terra foi sujeita perante o SENHOR e perante o seu povo.

[[v13-22-19]]

^<<v13-22-19,19>>^ Disponde, pois, agora, o vosso coração e a vossa alma para buscardes ao SENHOR, vosso Deus; e levantai-vos e edificai o santuário do SENHOR Deus, para que a arca do concerto do SENHOR e os utensílios sagrados de Deus se tragam a esta casa, que se há de edificar ao nome do SENHOR.

'''

xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[Próximo Capítulo &#62;]