include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// arc ?, ARC - Almeida Revista e Corrigida

[[v62-1-1]]

^<<v62-1-1,1>>^ O que era desde o princípio, o que vimos com os nossos olhos, o que temos contemplado, e as nossas mãos tocaram da Palavra da vida

[[v62-1-2]]

^<<v62-1-2,2>>^ (porque a vida foi manifestada, e nós a vimos, e testificamos dela, e vos anunciamos a vida eterna, que estava com o Pai e nos foi manifestada),

[[v62-1-3]]

^<<v62-1-3,3>>^ o que vimos e ouvimos, isso vos anunciamos, para que também tenhais comunhão conosco; e a nossa comunhão é com o Pai e com seu Filho Jesus Cristo.

[[v62-1-4]]

^<<v62-1-4,4>>^ Estas coisas  vos escrevemos, para que o vosso gozo se cumpra.

[[v62-1-5]]

^<<v62-1-5,5>>^ E esta é a mensagem que dele ouvimos e vos anunciamos: que Deus é luz, e não há nele treva nenhuma.

[[v62-1-6]]

^<<v62-1-6,6>>^ Se dissermos que temos comunhão com ele e andarmos em trevas, mentimos e não praticamos a verdade.

[[v62-1-7]]

^<<v62-1-7,7>>^ Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se dissermos que não temos pecado, enganamo-nos a nós mesmos, e não há verdade em nós.

[[v62-1-9]]

^<<v62-1-9,9>>^ Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se dissermos que não pecamos, fazemo-lo mentiroso, e a sua palavra não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]