include::./index.adoc[]

[[v16-3-0]]
=== Neemias, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v16-3-1]]

^<<v16-3-1,1>>^ E levantou-se Eliasibe, o sumo sacerdote, com os seus irmãos, os sacerdotes, edificaram a Porta do Gado, a qual consagraram, e levantaram as suas portas; e até a Torre de Meá consagraram e  até a Torre de Hananel.

[[v16-3-2]]

^<<v16-3-2,2>>^ E, junto a ele, edificaram os homens de Jericó; também, ao seu lado, edificou Zacur, filho de Inri.

[[v16-3-3]]

^<<v16-3-3,3>>^ E a Porta do Peixe edificaram os filhos de Hassenaá, a qual emadeiraram, e levantaram as suas portas com  as suas fechaduras e os seus ferrolhos.

[[v16-3-4]]

^<<v16-3-4,4>>^ E, ao seu lado, reparou Meremote, filho de Urias, filho de Coz; e, ao seu lado, reparou Mesulão, filho de Berequias, filho de Mesezabel; e, ao seu lado, reparou Zadoque, filho de Baaná.

[[v16-3-5]]

^<<v16-3-5,5>>^ E, ao seu lado, repararam os tecoítas; porém os seus nobres não meteram o seu pescoço ao serviço de seu senhor.

[[v16-3-6]]

^<<v16-3-6,6>>^ E a Porta Velha repararam- na  Joiada, filho de Paseia; e Mesulão, filho de Besodias; estes a emadeiraram e levantaram as suas portas com as  suas fechaduras e os seus ferrolhos.

[[v16-3-7]]

^<<v16-3-7,7>>^ E, ao seu lado, repararam Melatias, o gibeonita, e Jadom, meronotita, homens de Gibeão e Mispa, que pertenciam  ao domínio do governador daquém do rio.

[[v16-3-8]]

^<<v16-3-8,8>>^ Ao seu lado, reparou Uziel, filho de Haraías, um dos ourives; e, ao seu lado, reparou Hananias, filho de um dos boticários; e fortificaram a Jerusalém até ao Muro Largo.

[[v16-3-9]]

^<<v16-3-9,9>>^ E, ao seu lado, reparou Refaías, filho de Hur, maioral da metade de Jerusalém.

[[v16-3-10]]

^<<v16-3-10,10>>^ E, ao seu lado, reparou Jedaías, filho de Harumafe, e defronte de sua casa; e, ao seu lado, reparou Hatus, filho de Hasabneias.

[[v16-3-11]]

^<<v16-3-11,11>>^ A outra porção reparou Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, como também a Torre dos Fornos.

[[v16-3-12]]

^<<v16-3-12,12>>^ E, ao seu lado, reparou Salum, filho de Haloés, maioral da outra  meia parte de Jerusalém, ele e suas filhas.

[[v16-3-13]]

^<<v16-3-13,13>>^ A Porta do Vale, reparou-a Hanum e os moradores de Zanoa; estes a edificaram e lhe levantaram as portas com  fechaduras e os seus ferrolhos, como também mil côvados do muro, até à Porta do Monturo.

[[v16-3-14]]

^<<v16-3-14,14>>^ E a Porta do Monturo, reparou-a Malquias, filho de Recabe, maioral do distrito de Bete-Haquerém; este a edificou e lhe levantou as portas com  as suas fechaduras e os seus ferrolhos.

[[v16-3-15]]

^<<v16-3-15,15>>^ E a Porta da Fonte reparou-a Salum, filho de Col-Hozé, maioral do distrito de Mispa; este a edificou, e a cobriu, e lhe levantou as portas com  as suas fechaduras e os seus ferrolhos, como também o muro do viveiro de Selá, ao pé do jardim do rei, mesmo até aos degraus que descem da Cidade de Davi.

[[v16-3-16]]

^<<v16-3-16,16>>^ Depois dele, edificou Neemias, filho de Azbuque, maioral da metade de Bete-Zur, até defronte dos sepulcros de Davi, e até ao viveiro artificial, e até à casa dos varões.

[[v16-3-17]]

^<<v16-3-17,17>>^ Depois dele, repararam os levitas, Reum, filho de Bani, e, ao seu lado, reparou Hasabias, maioral da metade de Queila, no seu distrito.

[[v16-3-18]]

^<<v16-3-18,18>>^ Depois dele, repararam seus irmãos: Bavai, filho de Henadade, maioral da outra  meia parte de Queila;

[[v16-3-19]]

^<<v16-3-19,19>>^ ao seu lado, reparou Ezer, filho de Jesua, maioral de Mispa, outra porção, defronte da subida para a casa das armas, à esquina.

[[v16-3-20]]

^<<v16-3-20,20>>^ Depois dele, reparou com grande ardor Baruque, filho de Zabai, outra medida, desde a esquina até à porta da casa de Eliasibe, o sumo sacerdote.

[[v16-3-21]]

^<<v16-3-21,21>>^ Depois dele, reparou Meremote, filho de Urias, filho de Coz, outra porção, desde a porta da casa de Eliasibe até à extremidade da casa de Eliasibe.

[[v16-3-22]]

^<<v16-3-22,22>>^ E, depois dele, repararam os sacerdotes que habitavam na campina.

[[v16-3-23]]

^<<v16-3-23,23>>^ Depois, repararam Benjamim e Hassube, defronte da sua casa; depois deles, reparou Azarias, filho de Maaseias, filho de Ananias, junto à sua casa.

[[v16-3-24]]

^<<v16-3-24,24>>^ Depois dele, reparou Binui, filho de Henadade, outra porção, desde a casa de Azarias até à esquina e até ao canto.

[[v16-3-25]]

^<<v16-3-25,25>>^ Palal, filho de Uzai, reparou defronte da esquina e a torre que sai da casa real superior, que está junto ao pátio da prisão; depois dele, reparou Pedaías, filho de Parós,

[[v16-3-26]]

^<<v16-3-26,26>>^ e os netineus, que habitavam em Ofel, até defronte da Porta das Águas, para o oriente, e até à torre alta.

[[v16-3-27]]

^<<v16-3-27,27>>^ Depois, repararam os tecoítas outra porção, defronte da torre grande e  alta e até ao Muro de Ofel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Desde a Porta dos Cavalos, repararam os sacerdotes, cada um defronte da sua casa.

[[v16-3-29]]

^<<v16-3-29,29>>^ Depois deles, reparou Zadoque, filho de Imer, defronte de sua casa, e, depois dele, reparou Semaías, filho de Secanias, guarda da Porta Oriental.

[[v16-3-30]]

^<<v16-3-30,30>>^ Depois dele, reparou Hananias, filho de Selemias, e Hanum, filho de Zalafe, o sexto, outra porção; depois deles reparou Mesulão, filho de Berequias, defronte da sua câmara.

[[v16-3-31]]

^<<v16-3-31,31>>^ Depois dele, reparou Malquias, filho de um ourives, até à casa dos netineus e mercadores, defronte da Porta de Mifcade, e até à câmara do canto.

[[v16-3-32]]

^<<v16-3-32,32>>^ E, entre a câmara do canto e a Porta do Gado, repararam os ourives e os mercadores.

'''

xref:016-neemias/016-neemias-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-neemias/016-neemias-004.adoc#v16-4-0[Próximo Capítulo &#62;]