include::./index.adoc[]

[[v16-12-0]]
=== Neemias, 12
// arc ?, ARC - Almeida Revista e Corrigida

[[v16-12-1]]

^<<v16-12-1,1>>^ Estes são  os sacerdotes e levitas que subiram com Zorobabel, filho de Sealtiel, e com  Jesua: Seraías, Jeremias, Esdras,

[[v16-12-2]]

^<<v16-12-2,2>>^ Amarias, Maluque, Hatus,

[[v16-12-3]]

^<<v16-12-3,3>>^ Secanias, Reum, Meremote,

[[v16-12-4]]

^<<v16-12-4,4>>^ Ido, Ginetoi, Abias,

[[v16-12-5]]

^<<v16-12-5,5>>^ Miamim, Maadias, Bilga,

[[v16-12-6]]

^<<v16-12-6,6>>^ Semaías, Joiaribe, Jedaías,

[[v16-12-7]]

^<<v16-12-7,7>>^ Salu, Amoque, Hilquias e Jedaías; estes foram  os chefes dos sacerdotes e de seus irmãos, nos dias de Jesua.

[[v16-12-8]]

^<<v16-12-8,8>>^ E foram  os levitas: Jesua, Binui, Cadmiel, Serebias, Judá e Matanias; este e seus irmãos presidiam  sobre os louvores.

[[v16-12-9]]

^<<v16-12-9,9>>^ E Baquebuquias e Uni, seus irmãos, estavam defronte dele nas guardas.

[[v16-12-10]]

^<<v16-12-10,10>>^ E Jesua gerou a Joiaquim, e Joiaquim gerou a Eliasibe, e Eliasibe gerou a Joiada,

[[v16-12-11]]

^<<v16-12-11,11>>^ e Joiada gerou a Jônatas, e Jônatas gerou a Jadua.

[[v16-12-12]]

^<<v16-12-12,12>>^ E, nos dias de Joiaquim, foram  sacerdotes, chefes das casas dos pais: de Seraías, Meraías; de Jeremias, Hananias;

[[v16-12-13]]

^<<v16-12-13,13>>^ de Esdras, Mesulão; de Amarias, Joanã;

[[v16-12-14]]

^<<v16-12-14,14>>^ de Maluqui, Jônatas; de Sebanias, José;

[[v16-12-15]]

^<<v16-12-15,15>>^ de Harim, Adna; de Meraiote, Helcai;

[[v16-12-16]]

^<<v16-12-16,16>>^ de Ido, Zacarias; de Ginetom, Mesulão;

[[v16-12-17]]

^<<v16-12-17,17>>^ de Abias, Zicri; de Miniamim e  de Moadias, Piltai;

[[v16-12-18]]

^<<v16-12-18,18>>^ de Bilga, Samua; de Semaías, Jônatas;

[[v16-12-19]]

^<<v16-12-19,19>>^ e de Joiaribe, Matenai; de Jedaías, Uzi;

[[v16-12-20]]

^<<v16-12-20,20>>^ de Salai, Calai; de Amoque, Héber;

[[v16-12-21]]

^<<v16-12-21,21>>^ de Hilquias, Hasabias; de Jedaías, Netanel.

[[v16-12-22]]

^<<v16-12-22,22>>^ Dos levitas foram,  nos dias de Eliasibe, inscritos como chefes das casas dos pais, Joiada, e Jonã, e Jadua, como também os sacerdotes, até ao reinado de Dario, o persa.

[[v16-12-23]]

^<<v16-12-23,23>>^ Os filhos de Levi foram inscritos como chefes das casas dos pais no livro das crônicas, até aos dias de Joanã, filho de Eliasibe.

[[v16-12-24]]

^<<v16-12-24,24>>^ Foram,  pois, os chefes dos levitas: Hasabias, Serebias e Jesua, filho de Cadmiel; e seus irmãos estavam defronte deles para louvarem e  darem graças, segundo o mandado de Davi, homem de Deus, guarda contra guarda.

[[v16-12-25]]

^<<v16-12-25,25>>^ Matanias, Baquebuquias, Obadias, Mesulão, Talmom e  Acube eram  porteiros que faziam a guarda às tesourarias das portas.

[[v16-12-26]]

^<<v16-12-26,26>>^ Estes foram  nos dias de Joiaquim, filho de Jesua, filho de Jozadaque, como também nos dias de Neemias, o governador, e do sacerdote Esdras, o escriba.

[[v16-12-27]]

^<<v16-12-27,27>>^ E, na dedicação dos muros de Jerusalém, buscaram os levitas de todos os seus lugares, para os trazerem, a fim de fazerem a dedicação com alegria, louvores, canto, saltérios, alaúdes e harpas.

[[v16-12-28]]

^<<v16-12-28,28>>^ E se ajuntaram os filhos dos cantores, tanto da campina dos arredores de Jerusalém como das aldeias de Netofa,

[[v16-12-29]]

^<<v16-12-29,29>>^ como também da casa de Gilgal e dos campos de Gibeá e Azmavete; porque os cantores tinham edificado para si aldeias nos arredores de Jerusalém.

[[v16-12-30]]

^<<v16-12-30,30>>^ E purificaram-se os sacerdotes e os levitas; e logo  purificaram o povo, e as portas, e o muro.

[[v16-12-31]]

^<<v16-12-31,31>>^ Então, fiz subir os príncipes de Judá sobre o muro e ordenei dois grandes coros e procissões, sendo um  à mão direita sobre o muro da banda da Porta do Monturo.

[[v16-12-32]]

^<<v16-12-32,32>>^ E, após eles, ia Hosaías, e a metade dos príncipes de Judá,

[[v16-12-33]]

^<<v16-12-33,33>>^ e Azarias, Esdras, Mesulão,

[[v16-12-34]]

^<<v16-12-34,34>>^ Judá, Benjamim, Semaías e Jeremias;

[[v16-12-35]]

^<<v16-12-35,35>>^ e dos filhos dos sacerdotes, com trombetas: Zacarias, filho de Jônatas, filho de Semaías, filho de Matanias, filho de Micaías, filho de Zacur, filho de Asafe,

[[v16-12-36]]

^<<v16-12-36,36>>^ e seus irmãos, Semaías, Azarel, Milalai, Gilalai, Maai, Netanel, Judá e Hanani, com os instrumentos músicos de Davi, homem de Deus; e Esdras, o escriba, ia  adiante deles.

[[v16-12-37]]

^<<v16-12-37,37>>^ Indo  assim para a Porta da Fonte e defronte deles, subiram as escadas da Cidade de Davi pela subida do muro, desde cima da casa de Davi até à Porta das Águas, da banda  do oriente.

[[v16-12-38]]

^<<v16-12-38,38>>^ E o segundo coro ia em frente, e eu, após ele; e a metade do povo ia  sobre o muro, desde a Torre dos Fornos até à Muralha Larga;

[[v16-12-39]]

^<<v16-12-39,39>>^ e desde a Porta de Efraim, e desde a Porta Velha, e desde a Porta do Peixe e a Torre de Hananel e a Torre de Meá até à Porta do Gado; e pararam à Porta da Prisão.

[[v16-12-40]]

^<<v16-12-40,40>>^ Então, ambos os coros pararam na Casa de Deus, como também eu e a metade dos magistrados comigo.

[[v16-12-41]]

^<<v16-12-41,41>>^ E os sacerdotes Eliaquim, Maaseias, Miniamim, Micaías, Elioenai, Zacarias e  Hananias iam com trombetas,

[[v16-12-42]]

^<<v16-12-42,42>>^ como também Maaseias, e Semaías, e Eleazar, e Uzi, e Joanã, e Malquias, e Elão, e Ezer; e faziam-se ouvir os cantores, juntamente  com Jezraías, o superintendente.

[[v16-12-43]]

^<<v16-12-43,43>>^ E sacrificaram, no mesmo dia, grandes sacrifícios e se alegraram, porque Deus os alegrara com grande alegria; e até as mulheres e os meninos se alegraram, de modo que a alegria de Jerusalém se ouviu até de longe.

[[v16-12-44]]

^<<v16-12-44,44>>^ Também, no mesmo dia, se nomearam homens sobre as câmaras, para os tesouros, para as ofertas alçadas, para as primícias e para os dízimos, para ajuntarem nelas, das terras das cidades, as porções designadas pela Lei para os sacerdotes e para os levitas; porque Judá estava alegre por causa dos sacerdotes e dos levitas que assistiam ali.

[[v16-12-45]]

^<<v16-12-45,45>>^ E faziam a guarda do seu Deus e a guarda da purificação; como também os cantores e porteiros, conforme o mandado de Davi e  de seu filho Salomão.

[[v16-12-46]]

^<<v16-12-46,46>>^ Porque, já nos dias de Davi e de Asafe, desde a antiguidade, havia  chefes dos cantores, e cânticos de louvores, e ação de graças a Deus.

[[v16-12-47]]

^<<v16-12-47,47>>^ Pelo que todo o Israel, já  nos dias de Zorobabel e nos dias de Neemias, dava as porções dos cantores e dos porteiros, a cada um no seu dia; e santificavam as porções  para os levitas, e os levitas santificavam para os filhos de Arão.

'''

xref:016-neemias/016-neemias-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-neemias/016-neemias-013.adoc#v16-13-0[Próximo Capítulo &#62;]