include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// arc ?, ARC - Almeida Revista e Corrigida

[[v16-2-1]]

^<<v16-2-1,1>>^ Sucedeu, pois, no mês de nisã, no ano vigésimo do rei Artaxerxes, que estava posto  vinho diante dele, e eu tomei o vinho e o dei ao rei; porém nunca, antes, estivera triste diante dele.

[[v16-2-2]]

^<<v16-2-2,2>>^ E o rei me disse: Por que está triste o teu rosto, pois não estás doente? Não é  isso senão tristeza de coração. Então, temi muito  em grande maneira

[[v16-2-3]]

^<<v16-2-3,3>>^ e disse ao rei: Viva o rei para sempre! Como não estaria triste o meu rosto, estando a cidade, o lugar dos sepulcros de meus pais, assolada, e tendo sido consumidas as suas portas a fogo?

[[v16-2-4]]

^<<v16-2-4,4>>^ E o rei me disse: Que me pedes agora? Então, orei ao Deus dos céus

[[v16-2-5]]

^<<v16-2-5,5>>^ e disse ao rei: Se é do agrado do rei, e se o teu servo é aceito em tua presença, peço-te  que me envies a Judá, à cidade dos sepulcros de meus pais, para que eu a edifique.

[[v16-2-6]]

^<<v16-2-6,6>>^ Então, o rei me disse, estando a rainha assentada junto a ele: Quanto durará a tua viagem, e quando voltarás? E aprouve ao rei enviar-me, apontando-lhe eu um certo tempo.

[[v16-2-7]]

^<<v16-2-7,7>>^ Disse mais ao rei: Se ao rei parece bem, deem-se-me cartas para os governadores dalém do rio, para que me deem passagem até que chegue a Judá;

[[v16-2-8]]

^<<v16-2-8,8>>^ como também uma carta para Asafe, guarda do jardim do rei, para que me dê madeira para cobrir as portas do paço da casa, e para o muro da cidade, e para a casa em que eu houver de entrar. E o rei mas deu, segundo a boa mão de Deus sobre mim.

[[v16-2-9]]

^<<v16-2-9,9>>^ Então, vim aos governadores dalém do rio e dei-lhes as cartas do rei; e o rei tinha enviado comigo chefes do exército e cavaleiros.

[[v16-2-10]]

^<<v16-2-10,10>>^ O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, lhes desagradou com grande desagrado que alguém viesse a procurar o bem dos filhos de Israel.

[[v16-2-11]]

^<<v16-2-11,11>>^ E cheguei a Jerusalém e estive ali três dias.

[[v16-2-12]]

^<<v16-2-12,12>>^ E, de noite, me levantei, eu e poucos homens comigo, e não declarei a ninguém o que o meu Deus me pôs no coração para fazer em Jerusalém; e não havia  comigo animal algum, senão aquele em que estava montado.

[[v16-2-13]]

^<<v16-2-13,13>>^ E, de noite, saí pela Porta do Vale, para a banda da Fonte do Dragão e para a Porta do Monturo e contemplei os muros de Jerusalém, que estavam fendidos, e as suas portas, que tinham sido  consumidas pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ E passei à Porta da Fonte e ao viveiro do rei; e não havia  lugar por onde pudesse passar a cavalgadura que estava debaixo de mim.

[[v16-2-15]]

^<<v16-2-15,15>>^ Então, de noite, subi pelo ribeiro e contemplei o muro; e voltei, e entrei pela Porta do Vale, e assim  voltei.

[[v16-2-16]]

^<<v16-2-16,16>>^ E não souberam os magistrados aonde eu fui nem o que eu fazia; porque ainda até então nem aos judeus, nem aos nobres, nem aos magistrados, nem aos mais que faziam a obra tinha declarado coisa alguma.

[[v16-2-17]]

^<<v16-2-17,17>>^ Então, lhes disse: Bem vedes vós a miséria em que estamos, que Jerusalém está  assolada e que as suas portas têm sido  queimadas; vinde, pois,  e reedifiquemos o muro de Jerusalém e não estejamos mais em opróbrio.

[[v16-2-18]]

^<<v16-2-18,18>>^ Então, lhes declarei como a mão do meu Deus me fora favorável, como também as palavras do rei, que ele me tinha dito. Então, disseram: Levantemo-nos e edifiquemos. E esforçaram as suas mãos para o bem.

[[v16-2-19]]

^<<v16-2-19,19>>^ O que  ouvindo Sambalate, o horonita, e Tobias, o servo amonita, e Gesém, o arábio, zombaram de nós, e desprezaram-nos, e disseram: Que é isso que fazeis? Quereis rebelar-vos contra o rei?

[[v16-2-20]]

^<<v16-2-20,20>>^ Então, lhes respondi e disse: O Deus dos céus é o que nos fará prosperar; e nós, seus servos, nos levantaremos e edificaremos; mas vós não tendes parte, nem justiça, nem memória em Jerusalém.

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]