include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-22-1]]

^<<v4-22-1,1>>^ Depois, partiram os filhos de Israel e acamparam-se nas campinas de Moabe, desta banda do Jordão, de  Jericó.

[[v4-22-2]]

^<<v4-22-2,2>>^ Viu, pois, Balaque, filho de Zipor, tudo o que Israel fizera aos amorreus.

[[v4-22-3]]

^<<v4-22-3,3>>^ E Moabe temeu muito diante deste povo, porque era muito; e Moabe andava angustiado por causa dos filhos de Israel.

[[v4-22-4]]

^<<v4-22-4,4>>^ Pelo que Moabe disse aos anciãos dos midianitas: Agora lamberá esta congregação tudo quanto houver  ao redor de nós, como o boi lambe a erva do campo. Naquele tempo, Balaque, filho de Zipor, era  rei dos moabitas.

[[v4-22-5]]

^<<v4-22-5,5>>^ Este enviou mensageiros a Balaão, filho de Beor, a Petor, que está  junto ao rio, na terra dos filhos do seu povo, a chamá-lo, dizendo: Eis que um povo saiu do Egito; eis que cobre a face da terra e parado está defronte de mim.

[[v4-22-6]]

^<<v4-22-6,6>>^ Vem, pois, agora, rogo-te, amaldiçoa-me este povo, pois mais poderoso é do que eu; para ver se o poderei ferir e o lançarei fora da terra; porque eu sei que a quem tu abençoares será abençoado e a quem tu amaldiçoares será amaldiçoado.

[[v4-22-7]]

^<<v4-22-7,7>>^ Então, foram-se os anciãos dos moabitas e os anciãos dos midianitas com o preço  dos encantamentos nas mãos; e chegaram a Balaão e lhe disseram as palavras de Balaque.

[[v4-22-8]]

^<<v4-22-8,8>>^ E ele  lhes disse: Passai aqui esta noite, e vos trarei a resposta, como o SENHOR me falar; então, os príncipes dos moabitas ficaram com Balaão.

[[v4-22-9]]

^<<v4-22-9,9>>^ E veio Deus a Balaão e disse: Quem são  estes homens que estão  contigo?

[[v4-22-10]]

^<<v4-22-10,10>>^ E Balaão disse a Deus: Balaque, filho de Zipor, rei dos moabitas, m os  enviou, dizendo:

[[v4-22-11]]

^<<v4-22-11,11>>^ Eis que o povo que saiu do Egito cobriu a face da terra; vem, agora, amaldiçoa-mo; porventura, poderei pelejar contra ele e o lançarei fora.

[[v4-22-12]]

^<<v4-22-12,12>>^ Então, disse Deus a Balaão: Não irás com eles, nem amaldiçoarás a este povo, porquanto bendito é.

[[v4-22-13]]

^<<v4-22-13,13>>^ Então, Balaão levantou-se pela manhã e disse aos príncipes de Balaque: Ide à vossa terra, porque o SENHOR recusa deixar-me ir convosco.

[[v4-22-14]]

^<<v4-22-14,14>>^ E levantaram-se os príncipes dos moabitas, e vieram a Balaque, e disseram: Balaão recusou vir conosco.

[[v4-22-15]]

^<<v4-22-15,15>>^ Porém Balaque prosseguiu ainda em enviar mais príncipes e mais honrados do que aqueles,

[[v4-22-16]]

^<<v4-22-16,16>>^ os quais vieram a Balaão e lhe disseram: Assim diz Balaque, filho de Zipor: Rogo-te que não te demores em vir a mim,

[[v4-22-17]]

^<<v4-22-17,17>>^ porque grandemente te honrarei e farei tudo o que me disseres; vem, pois, rogo-te, amaldiçoa-me este povo.

[[v4-22-18]]

^<<v4-22-18,18>>^ Então, Balaão respondeu e disse aos servos de Balaque: Ainda que Balaque me desse a sua casa cheia de prata e de ouro, eu não poderia traspassar o mandado do SENHOR, meu Deus, para fazer coisa pequena ou grande;

[[v4-22-19]]

^<<v4-22-19,19>>^ agora, pois, rogo-vos que também aqui fiqueis esta noite, para que eu saiba o que o SENHOR me dirá mais.

[[v4-22-20]]

^<<v4-22-20,20>>^ Veio, pois, o Senhor a Balaão, de noite, e disse-lhe: Se aqueles homens te vieram chamar, levanta-te, vai com eles; todavia, farás o que eu te disser.

[[v4-22-21]]

^<<v4-22-21,21>>^ Então, Balaão levantou-se pela manhã, e albardou a sua jumenta, e foi-se com os príncipes de Moabe.

[[v4-22-22]]

^<<v4-22-22,22>>^ E a ira de Deus acendeu-se, porque ele se ia; e o Anjo do SENHOR pôs-se-lhe no caminho por adversário; e ele ia caminhando, montado na sua jumenta, e dois de seus moços com ele.

[[v4-22-23]]

^<<v4-22-23,23>>^ Viu, pois, a jumenta o Anjo do SENHOR que estava no caminho, com a sua espada desembainhada na mão; pelo que desviou-se a jumenta do caminho e foi-se pelo campo; então, Balaão espancou a jumenta para fazê-la tornar ao caminho.

[[v4-22-24]]

^<<v4-22-24,24>>^ Mas o Anjo do SENHOR pôs-se numa vereda de vinhas, havendo  uma parede desta banda e uma parede da outra.

[[v4-22-25]]

^<<v4-22-25,25>>^ Vendo, pois, a jumenta o Anjo do SENHOR, apertou-se contra a parede e apertou contra a parede o pé de Balaão; pelo que tornou a espancá-la.

[[v4-22-26]]

^<<v4-22-26,26>>^ Então, o Anjo do SENHOR passou mais adiante e pôs-se num lugar estreito, onde não havia  caminho para se desviar nem para a direita nem para a esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ E, vendo a jumenta o Anjo do SENHOR, deitou-se debaixo de Balaão; e a ira de Balaão acendeu-se, e espancou a jumenta com o bordão.

[[v4-22-28]]

^<<v4-22-28,28>>^ Então, o SENHOR abriu a boca da jumenta, a qual disse a Balaão: Que te fiz eu, que me espancaste estas três vezes?

[[v4-22-29]]

^<<v4-22-29,29>>^ E Balaão disse à jumenta: Porque zombaste de mim; tomara que tivera eu uma espada na mão, porque agora te mataria.

[[v4-22-30]]

^<<v4-22-30,30>>^ E a jumenta disse a Balaão: Porventura,  não sou  a tua jumenta, em que cavalgaste desde o tempo que eu fui  tua até hoje? Costumei eu alguma vez fazer assim contigo? E ele  respondeu: Não.

[[v4-22-31]]

^<<v4-22-31,31>>^ Então, o SENHOR abriu os olhos a Balaão, e ele viu o Anjo do SENHOR, que estava no caminho, e a sua espada desembainhada na mão; pelo que inclinou a cabeça e prostrou-se sobre a sua face.

[[v4-22-32]]

^<<v4-22-32,32>>^ Então, o Anjo do SENHOR lhe disse: Por que já três vezes espancaste a tua jumenta? Eis que eu saí para ser teu  adversário, porquanto o teu  caminho é perverso diante de mim;

[[v4-22-33]]

^<<v4-22-33,33>>^ porém a jumenta me viu e já três vezes se desviou de diante de mim; se ela se não desviara de diante de mim, na verdade que eu  agora te mataria e a ela deixaria com vida.

[[v4-22-34]]

^<<v4-22-34,34>>^ Então, Balaão disse ao Anjo do SENHOR: Pequei, que não soube que estavas neste caminho para te opores a mim; e, agora, se parece  mal aos teus olhos, tornar-me-ei.

[[v4-22-35]]

^<<v4-22-35,35>>^ E disse o Anjo do SENHOR a Balaão: Vai-te com estes homens, mas somente a palavra que eu falar a ti, esta falarás. Assim, Balaão foi-se com os príncipes de Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Ouvindo, pois, Balaque que Balaão vinha, saiu-lhe ao encontro até à cidade de Moabe, que está  no termo de Arnom, na extremidade do termo dele.

[[v4-22-37]]

^<<v4-22-37,37>>^ E Balaque disse a Balaão: Porventura,  não enviei diligentemente a chamar-te? Por que não vieste a mim? Não posso eu na verdade honrar-te?

[[v4-22-38]]

^<<v4-22-38,38>>^ Então, Balaão disse a Balaque: Eis que eu tenho vindo a ti; porventura, poderei eu agora de alguma forma falar alguma coisa? A palavra que Deus puser na minha boca, esta falarei.

[[v4-22-39]]

^<<v4-22-39,39>>^ E Balaão foi com Balaque, e vieram a Quiriate-Huzote.

[[v4-22-40]]

^<<v4-22-40,40>>^ Então, Balaque matou bois e ovelhas; e deles  enviou a Balaão e aos príncipes que estavam  com ele.

[[v4-22-41]]

^<<v4-22-41,41>>^ E sucedeu que, pela manhã, Balaque tomou a Balaão e o fez subir aos altos de Baal. E viu Balaão  dali a última parte  do povo.

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]