include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-30-1]]

^<<v4-30-1,1>>^ E falou Moisés aos cabeças das tribos dos filhos de Israel, dizendo: Esta é  a palavra que o SENHOR tem ordenado:

[[v4-30-2]]

^<<v4-30-2,2>>^ Quando um homem fizer voto ao SENHOR ou fizer juramento, ligando a sua alma com obrigação, não violará a sua palavra; segundo tudo o que saiu da sua boca, fará.

[[v4-30-3]]

^<<v4-30-3,3>>^ Também quando uma mulher fizer voto ao SENHOR, e com obrigação se  ligar em casa de seu pai na sua mocidade;

[[v4-30-4]]

^<<v4-30-4,4>>^ e seu pai ouvir o seu voto e a sua obrigação, com que ligou a sua alma, e seu pai se calar para com ela, todos os seus votos serão válidos, e toda obrigação, com que ligou a sua alma, será valiosa.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas, se seu pai se opuser no dia em que tal ouvir, todos os seus votos e as suas obrigações, com que tiver ligado a sua alma, não serão válidos; mas o SENHOR lho perdoará, porquanto seu pai lhos vedou.

[[v4-30-6]]

^<<v4-30-6,6>>^ E, se ela tiver marido e for obrigada a alguns votos ou dito irrefletido dos seus lábios, com que tiver ligado a sua alma;

[[v4-30-7]]

^<<v4-30-7,7>>^ e seu marido o ouvir e se calar para com ela no dia em que o ouvir, os seus votos serão válidos; e as suas obrigações, com que ligou a sua alma, serão valiosas.

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas, se seu marido lho vedar no dia em que o ouvir e anular o seu voto a que estava obrigada, como também a declaração dos seus lábios, com que ligou a sua alma, o SENHOR lho perdoará.

[[v4-30-9]]

^<<v4-30-9,9>>^ No tocante ao voto da viúva ou da repudiada, tudo com que ligar a sua alma sobre ela será válido.

[[v4-30-10]]

^<<v4-30-10,10>>^ Porém, se fez voto na casa de seu marido ou ligou a sua alma com obrigação de juramento,

[[v4-30-11]]

^<<v4-30-11,11>>^ e seu marido o ouviu, e se calou para com ela, e lho não vedou, todos os seus votos serão válidos, e toda obrigação, com que ligou a sua alma, será valiosa.

[[v4-30-12]]

^<<v4-30-12,12>>^ Porém, se seu marido lhos anulou no dia em que os  ouviu, tudo quanto saiu dos seus lábios, quer dos seus votos, quer da obrigação da sua alma, não será válido; seu marido lhos anulou, e o SENHOR lho perdoará.

[[v4-30-13]]

^<<v4-30-13,13>>^ Todo voto e todo juramento de obrigação, para humilhar a alma, seu marido o confirmará ou anulará.

[[v4-30-14]]

^<<v4-30-14,14>>^ Porém, se seu marido de dia em dia se calar inteiramente para com ela, então, confirmará todos os seus votos e todas as suas obrigações que estiverem sobre ela; confirmado lhos tem, porquanto se calou para com ela no dia em que o ouviu.

[[v4-30-15]]

^<<v4-30-15,15>>^ Porém, se de todo lhos anular depois que o  ouviu, então, ele levará a iniquidade dela.

[[v4-30-16]]

^<<v4-30-16,16>>^ Estes são  os estatutos que o SENHOR ordenou a Moisés entre o marido e sua mulher, entre o pai e a sua filha, na sua mocidade, em casa de seu pai.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]