include::./index.adoc[]

[[v4-17-0]]
=== Números, 17
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-17-1]]

^<<v4-17-1,1>>^ Então, falou o SENHOR a Moisés, dizendo:

[[v4-17-2]]

^<<v4-17-2,2>>^ Fala aos filhos de Israel e toma deles uma vara para cada casa paterna de todos os seus príncipes, segundo as casas de seus pais, doze varas; e  escreverás o nome de cada um sobre a sua vara.

[[v4-17-3]]

^<<v4-17-3,3>>^ Porém o nome de Arão escreverás sobre a vara de Levi; porque cada  cabeça da casa de seus pais terá uma vara.

[[v4-17-4]]

^<<v4-17-4,4>>^ E as porás na tenda da congregação, perante o Testemunho, onde eu virei a vós.

[[v4-17-5]]

^<<v4-17-5,5>>^ E será que  a vara do homem que eu tiver escolhido florescerá; assim, farei cessar as murmurações dos filhos de Israel contra mim, com que murmuram contra vós.

[[v4-17-6]]

^<<v4-17-6,6>>^ Falou, pois, Moisés aos filhos de Israel; e todos os seus maiorais deram-lhe, cada um,  uma vara, para cada maioral uma vara, segundo as casas de seus pais, doze varas; e a vara de Arão estava  entre as suas varas.

[[v4-17-7]]

^<<v4-17-7,7>>^ E Moisés pôs estas varas perante o SENHOR na tenda do Testemunho.

[[v4-17-8]]

^<<v4-17-8,8>>^ Sucedeu, pois, que no dia seguinte Moisés entrou na tenda do Testemunho, e eis que a vara de Arão, pela casa de Levi, florescia; porque produzira flores, e brotara renovos, e dera amêndoas.

[[v4-17-9]]

^<<v4-17-9,9>>^ Então, Moisés trouxe todas as varas de diante do SENHOR a todos os filhos de Israel; e eles o viram e tomaram cada um a sua vara.

[[v4-17-10]]

^<<v4-17-10,10>>^ Então, o SENHOR disse a Moisés: Torna a pôr a vara de Arão perante o Testemunho, para que se guarde por sinal para os filhos rebeldes; assim, farás acabar as suas murmurações contra mim, e não morrerão.

[[v4-17-11]]

^<<v4-17-11,11>>^ E Moisés fez assim; como lhe ordenara o SENHOR, assim fez.

[[v4-17-12]]

^<<v4-17-12,12>>^ Então, falaram os filhos de Israel a Moisés, dizendo: Eis aqui, nós expiramos, perecemos, nós perecemos todos.

[[v4-17-13]]

^<<v4-17-13,13>>^ Todo aquele que se aproximar do tabernáculo do SENHOR, morrerá; seremos, pois, todos consumidos?

'''

xref:004-numeros/004-numeros-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numeros/004-numeros-018.adoc#v4-18-0[Próximo Capítulo &#62;]