include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-33-1]]

^<<v4-33-1,1>>^ Estas são  as jornadas dos filhos de Israel, que saíram da terra do Egito, segundo os seus exércitos, pela mão de Moisés e Arão.

[[v4-33-2]]

^<<v4-33-2,2>>^ E escreveu Moisés as suas saídas, segundo as suas jornadas, conforme o mandado do SENHOR; e estas são  as suas jornadas, segundo as suas saídas.

[[v4-33-3]]

^<<v4-33-3,3>>^ Partiram, pois, de Ramessés no primeiro mês, no dia quinze do primeiro mês; no seguinte dia da Páscoa, saíram os filhos de Israel por alta mão aos olhos de todos os egípcios,

[[v4-33-4]]

^<<v4-33-4,4>>^ enterrando os egípcios os que o SENHOR tinha ferido entre eles, a todo primogênito, e havendo o SENHOR executado os seus  juízos nos seus deuses.

[[v4-33-5]]

^<<v4-33-5,5>>^ Partidos, pois, os filhos de Israel de Ramessés, acamparam-se em Sucote.

[[v4-33-6]]

^<<v4-33-6,6>>^ E partiram de Sucote e acamparam-se em Etã, que está  no fim do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ E partiram de Etã, e voltaram a Pi-Hairote, que está  defronte de Baal-Zefom, e acamparam-se diante de Migdol.

[[v4-33-8]]

^<<v4-33-8,8>>^ E partiram de Pi-Hairote, e passaram pelo meio do mar ao deserto, e andaram caminho de três dias no deserto de Etã, e acamparam-se em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ E partiram de Mara e vieram a Elim; e em Elim havia  doze fontes de águas e setenta palmeiras, e acamparam-se ali.

[[v4-33-10]]

^<<v4-33-10,10>>^ E partiram de Elim e acamparam-se junto ao mar Vermelho.

[[v4-33-11]]

^<<v4-33-11,11>>^ E partiram do mar Vermelho e acamparam-se no deserto de Sim.

[[v4-33-12]]

^<<v4-33-12,12>>^ E partiram do deserto de Sim e acamparam-se em Dofca.

[[v4-33-13]]

^<<v4-33-13,13>>^ E partiram de Dofca e acamparam-se em Alus.

[[v4-33-14]]

^<<v4-33-14,14>>^ E partiram de Alus e acamparam-se em Refidim; porém não havia ali água, para que o povo bebesse.

[[v4-33-15]]

^<<v4-33-15,15>>^ Partiram, pois, de Refidim e acamparam-se no deserto do Sinai.

[[v4-33-16]]

^<<v4-33-16,16>>^ Partiram do deserto do Sinai e acamparam-se em Quibrote-Hataavá.

[[v4-33-17]]

^<<v4-33-17,17>>^ E partiram de Quibrote-Hataavá e acamparam-se em Hazerote.

[[v4-33-18]]

^<<v4-33-18,18>>^ E partiram de Hazerote e acamparam-se em Ritma.

[[v4-33-19]]

^<<v4-33-19,19>>^ E partiram de Ritma e acamparam-se em Rimom-Perez.

[[v4-33-20]]

^<<v4-33-20,20>>^ E partiram de Rimom-Perez e acamparam-se em Libna.

[[v4-33-21]]

^<<v4-33-21,21>>^ E partiram de Libna e acamparam-se em Rissa.

[[v4-33-22]]

^<<v4-33-22,22>>^ E partiram de Rissa e acamparam-se em Queelata.

[[v4-33-23]]

^<<v4-33-23,23>>^ E partiram de Queelata e acamparam-se no monte Sefer.

[[v4-33-24]]

^<<v4-33-24,24>>^ E partiram do monte Sefer e acamparam-se em Harada.

[[v4-33-25]]

^<<v4-33-25,25>>^ E partiram de Harada e acamparam-se em Maquelote.

[[v4-33-26]]

^<<v4-33-26,26>>^ E partiram de Maquelote e acamparam-se em Taate.

[[v4-33-27]]

^<<v4-33-27,27>>^ E partiram de Taate e acamparam-se em Tera.

[[v4-33-28]]

^<<v4-33-28,28>>^ E partiram de Tera e acamparam-se em Mitca.

[[v4-33-29]]

^<<v4-33-29,29>>^ E partiram de Mitca e acamparam-se em Hasmona.

[[v4-33-30]]

^<<v4-33-30,30>>^ E partiram de Hasmona e acamparam-se em Moserote.

[[v4-33-31]]

^<<v4-33-31,31>>^ E partiram de Moserote e acamparam-se em Benê-Jaacã.

[[v4-33-32]]

^<<v4-33-32,32>>^ E partiram de Benê-Jaacã e acamparam-se em Hor-Hagidgade.

[[v4-33-33]]

^<<v4-33-33,33>>^ E partiram de Hor-Hagidgade e acamparam-se em Jotbatá.

[[v4-33-34]]

^<<v4-33-34,34>>^ E partiram de Jotbatá e acamparam-se em Abrona.

[[v4-33-35]]

^<<v4-33-35,35>>^ E partiram de Abrona e acamparam-se em Eziom-Geber.

[[v4-33-36]]

^<<v4-33-36,36>>^ E partiram de Eziom-Geber e acamparam-se no deserto de Zim, que é  Cades.

[[v4-33-37]]

^<<v4-33-37,37>>^ E partiram de Cades e acamparam-se no monte Hor, no fim da terra de Edom.

[[v4-33-38]]

^<<v4-33-38,38>>^ Então, Arão, o sacerdote, subiu ao monte Hor, conforme o mandado do SENHOR; e morreu ali, no quinto mês do ano quadragésimo da saída dos filhos de Israel da terra do Egito, no primeiro dia  do mês.

[[v4-33-39]]

^<<v4-33-39,39>>^ E era  Arão da idade de cento e vinte três anos, quando morreu no monte Hor.

[[v4-33-40]]

^<<v4-33-40,40>>^ E ouviu o cananeu, rei de Arade, que habitava o sul da terra de Canaã, que chegavam os filhos de Israel.

[[v4-33-41]]

^<<v4-33-41,41>>^ E partiram de Hor e acamparam-se em Zalmona.

[[v4-33-42]]

^<<v4-33-42,42>>^ E partiram de Zalmona e acamparam-se em Punom.

[[v4-33-43]]

^<<v4-33-43,43>>^ E partiram de Punom e acamparam-se em Obote.

[[v4-33-44]]

^<<v4-33-44,44>>^ E partiram de Obote e acamparam-se nos outeirinhos de Abarim, no termo de Moabe.

[[v4-33-45]]

^<<v4-33-45,45>>^ E partiram dos outeirinhos de Abarim  e acamparam-se em Dibom-Gade.

[[v4-33-46]]

^<<v4-33-46,46>>^ E partiram de Dibom-Gade e acamparam-se em Almom-Diblataim.

[[v4-33-47]]

^<<v4-33-47,47>>^ E partiram de Almom-Diblataim e acamparam-se nos montes de Abarim, defronte de Nebo.

[[v4-33-48]]

^<<v4-33-48,48>>^ E partiram dos montes de Abarim e acamparam-se nas campinas dos moabitas, junto ao Jordão, de  Jericó.

[[v4-33-49]]

^<<v4-33-49,49>>^ E acamparam-se junto ao Jordão, desde Bete-Jesimote até Abel-Sitim, nas campinas dos moabitas.

[[v4-33-50]]

^<<v4-33-50,50>>^ E falou o SENHOR a Moisés, nas campinas dos moabitas, junto ao Jordão, de  Jericó, dizendo:

[[v4-33-51]]

^<<v4-33-51,51>>^ Fala aos filhos de Israel e dize-lhes: Quando houverdes passado o Jordão para a terra de Canaã,

[[v4-33-52]]

^<<v4-33-52,52>>^ lançareis fora todos os moradores da terra diante de vós e destruireis todas as suas figuras; também destruireis todas as suas imagens de fundição e desfareis todos os seus altos;

[[v4-33-53]]

^<<v4-33-53,53>>^ e tomareis a terra em possessão e nela habitareis; porquanto vos tenho dado esta terra, para possuí-la.

[[v4-33-54]]

^<<v4-33-54,54>>^ E por sortes herdareis a terra segundo as vossas famílias; aos muitos, a herança multiplicareis, e, aos poucos, a herança diminuireis; onde a sorte sair a alguém, ali a terá; segundo as tribos de vossos pais, tomareis as heranças.

[[v4-33-55]]

^<<v4-33-55,55>>^ Mas, se não lançardes fora os moradores da terra de diante de vós, então, os que deixardes ficar deles vos serão  por espinhos nos vossos olhos e por aguilhões nas vossas costas e apertar-vos-ão na terra em que habitardes.

[[v4-33-56]]

^<<v4-33-56,56>>^ E será que  farei a vós como pensei fazer-lhes a eles.

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]