include::./index.adoc[]

[[v4-3-0]]
=== Números, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-3-1]]

^<<v4-3-1,1>>^ E estas são  as gerações de Arão e de Moisés, no dia em que  o SENHOR falou com Moisés no monte Sinai.

[[v4-3-2]]

^<<v4-3-2,2>>^ E estes são  os nomes dos filhos de Arão: o primogênito, Nadabe; depois, Abiú, Eleazar e Itamar.

[[v4-3-3]]

^<<v4-3-3,3>>^ Estes são  os nomes dos filhos de Arão, dos sacerdotes ungidos, cujas mãos foram sagradas para administrar o sacerdócio.

[[v4-3-4]]

^<<v4-3-4,4>>^ Mas Nadabe e Abiú morreram perante o SENHOR, quando ofereceram fogo estranho perante o SENHOR no deserto do Sinai, e não tiveram filhos; porém Eleazar e Itamar administraram o sacerdócio diante de Arão, seu pai.

[[v4-3-5]]

^<<v4-3-5,5>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-3-6]]

^<<v4-3-6,6>>^ Faze chegar a tribo de Levi e põe-na diante de Arão, o sacerdote, para que o sirvam,

[[v4-3-7]]

^<<v4-3-7,7>>^ e tenham cuidado da sua guarda e da guarda de toda a congregação, diante da tenda da congregação, para administrar o ministério do tabernáculo,

[[v4-3-8]]

^<<v4-3-8,8>>^ e tenham cuidado de todos os utensílios da tenda da congregação e da guarda dos filhos de Israel, para administrar o ministério do tabernáculo.

[[v4-3-9]]

^<<v4-3-9,9>>^ Darás, pois, os levitas a Arão e a seus filhos; dentre os filhos de Israel lhes são  dados em dádiva.

[[v4-3-10]]

^<<v4-3-10,10>>^ Mas a Arão e a seus filhos ordenarás que guardem o seu sacerdócio, e o estranho que se chegar morrerá.

[[v4-3-11]]

^<<v4-3-11,11>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-3-12]]

^<<v4-3-12,12>>^ E eu, eis que tenho tomado os levitas do meio dos filhos de Israel, em lugar de todo o primogênito que abre a madre, entre os filhos de Israel; e os levitas serão meus.

[[v4-3-13]]

^<<v4-3-13,13>>^ Porque todo primogênito meu é;  desde o dia em que feri a todo o primogênito na terra do Egito, santifiquei para mim todo o primogênito em Israel, desde o homem até ao animal; meus serão; eu sou  o SENHOR.

[[v4-3-14]]

^<<v4-3-14,14>>^ E falou o SENHOR a Moisés no deserto do Sinai, dizendo:

[[v4-3-15]]

^<<v4-3-15,15>>^ Conta os filhos de Levi, segundo a casa de seus pais, pelas suas gerações; contarás a todo varão da idade de um mês para cima.

[[v4-3-16]]

^<<v4-3-16,16>>^ E Moisés os contou conforme o mandado do SENHOR, como lhe foi ordenado.

[[v4-3-17]]

^<<v4-3-17,17>>^ Estes, pois, foram os filhos de Levi pelos seus nomes: Gérson, e Coate, e Merari.

[[v4-3-18]]

^<<v4-3-18,18>>^ E estes são  os nomes dos filhos de Gérson pelas suas gerações: Libni e Simei.

[[v4-3-19]]

^<<v4-3-19,19>>^ E os filhos de Coate pelas suas gerações: Anrão, e Izar, e Hebrom, e Uziel.

[[v4-3-20]]

^<<v4-3-20,20>>^ E os filhos de Merari pelas suas gerações: Mali e Musi: estas são  as gerações dos levitas, segundo a casa de seus pais.

[[v4-3-21]]

^<<v4-3-21,21>>^ De Gérson é  a geração dos libnitas e a geração dos simeítas; estas são  as gerações dos gersonitas.

[[v4-3-22]]

^<<v4-3-22,22>>^ Os que  deles foram  contados pelo número de todo varão da idade de um mês para cima, os que deles foram contados foram  sete mil e quinhentos.

[[v4-3-23]]

^<<v4-3-23,23>>^ As gerações dos gersonitas assentarão as suas  tendas atrás do tabernáculo, ao ocidente.

[[v4-3-24]]

^<<v4-3-24,24>>^ E o príncipe da casa paterna dos gersonitas será  Eliasafe, filho de Lael.

[[v4-3-25]]

^<<v4-3-25,25>>^ E a guarda dos filhos de Gérson na tenda da congregação será  o tabernáculo, e a tenda, e a sua coberta, e o véu da porta da tenda da congregação,

[[v4-3-26]]

^<<v4-3-26,26>>^ e as cortinas do pátio, e o pavilhão da porta do pátio, que estão  junto ao tabernáculo e junto ao altar, em redor; como também as suas cordas para todo o seu serviço.

[[v4-3-27]]

^<<v4-3-27,27>>^ E de Coate é  a geração dos anramitas, e a geração dos izaritas, e a geração dos hebronitas, e a geração dos uzielitas; estas são  as gerações dos coatitas.

[[v4-3-28]]

^<<v4-3-28,28>>^ Pelo número contado de todo varão da idade de um mês para cima, foram  oito mil e seiscentos, que tinham cuidado da guarda do santuário.

[[v4-3-29]]

^<<v4-3-29,29>>^ As gerações dos filhos de Coate assentarão as suas  tendas ao lado do tabernáculo, da banda do sul.

[[v4-3-30]]

^<<v4-3-30,30>>^ E o príncipe da casa paterna das gerações dos coatitas será  Elisafã, filho de Uziel.

[[v4-3-31]]

^<<v4-3-31,31>>^ E a sua guarda será  a arca, e a mesa, e o castiçal, e os altares, e os utensílios do santuário com que ministram, e o véu com todo o seu serviço.

[[v4-3-32]]

^<<v4-3-32,32>>^ E o príncipe dos príncipes de Levi será  Eleazar, filho de Arão, o sacerdote; terá  a superintendência sobre os que têm cuidado da guarda do santuário.

[[v4-3-33]]

^<<v4-3-33,33>>^ De Merari é  a geração dos malitas e a geração dos musitas; estas são  as gerações de Merari.

[[v4-3-34]]

^<<v4-3-34,34>>^ E os que  deles foram  contados pelo número de todo varão de um mês para cima foram  seis mil e duzentos.

[[v4-3-35]]

^<<v4-3-35,35>>^ E o príncipe da casa paterna das gerações de Merari será  Zuriel, filho de Abiail; assentarão as suas  tendas ao lado do tabernáculo, da banda do norte.

[[v4-3-36]]

^<<v4-3-36,36>>^ E o cargo da guarda dos filhos de Merari serão  as tábuas do tabernáculo, e os seus varais, e as suas colunas, e as suas bases, e todos os seus utensílios, com todo o seu serviço,

[[v4-3-37]]

^<<v4-3-37,37>>^ e as colunas do pátio em redor, e as suas bases, e as suas estacas e as suas cordas.

[[v4-3-38]]

^<<v4-3-38,38>>^ E os que assentarão as suas  tendas diante do tabernáculo, ao oriente, diante da tenda da congregação, para a banda do nascente, serão  Moisés e Arão, com seus filhos, tendo o cuidado da guarda do santuário, para guarda dos filhos de Israel; e o estranho que se chegar morrerá.

[[v4-3-39]]

^<<v4-3-39,39>>^ Todos os que foram  contados dos levitas, que contou Moisés e Arão, por mandado do SENHOR, segundo as suas gerações, todo varão de um mês para cima foram  vinte e dois mil.

[[v4-3-40]]

^<<v4-3-40,40>>^ E disse o SENHOR a Moisés: Conta todo primogênito varão dos filhos de Israel da idade de um mês para cima e toma o número dos seus nomes.

[[v4-3-41]]

^<<v4-3-41,41>>^ E para mim tomarás os levitas (eu sou o SENHOR) em lugar de todo primogênito dos filhos de Israel e os animais dos levitas em lugar de todo primogênito entre os animais dos filhos de Israel.

[[v4-3-42]]

^<<v4-3-42,42>>^ E contou Moisés, como o SENHOR lhe ordenara, todo primogênito entre os filhos de Israel.

[[v4-3-43]]

^<<v4-3-43,43>>^ E todos os primogênitos dos varões, pelo número dos nomes dos da idade de um mês para cima, segundo os que foram  contados deles, foram vinte e dois mil e duzentos e setenta e três.

[[v4-3-44]]

^<<v4-3-44,44>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-3-45]]

^<<v4-3-45,45>>^ Toma os levitas em lugar de todo primogênito entre os filhos de Israel e os animais dos levitas em lugar dos seus animais; porquanto os levitas serão meus. Eu sou  o SENHOR.

[[v4-3-46]]

^<<v4-3-46,46>>^ Quanto aos duzentos e setenta e três, que se houverem de resgatar, que sobrepujam aos levitas dos primogênitos dos filhos de Israel,

[[v4-3-47]]

^<<v4-3-47,47>>^ tomarás para cada cabeça cinco siclos; conforme o siclo do santuário os  tomarás, a vinte geras o siclo.

[[v4-3-48]]

^<<v4-3-48,48>>^ E a Arão e a seus filhos darás o dinheiro dos resgatados, dos que sobejam entre eles.

[[v4-3-49]]

^<<v4-3-49,49>>^ Então, Moisés tomou o dinheiro do resgate dos que sobejaram sobre os resgatados pelos levitas.

[[v4-3-50]]

^<<v4-3-50,50>>^ Dos primogênitos dos filhos de Israel tomou o dinheiro, mil e trezentos e sessenta e cinco siclos,  segundo o siclo do santuário.

[[v4-3-51]]

^<<v4-3-51,51>>^ E Moisés deu o dinheiro dos resgatados a Arão e a seus filhos, segundo o mandado do SENHOR, como o SENHOR ordenara a Moisés.

'''

xref:004-numeros/004-numeros-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numeros/004-numeros-004.adoc#v4-4-0[Próximo Capítulo &#62;]