include::./index.adoc[]

[[v4-9-0]]
=== Números, 9
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-9-1]]

^<<v4-9-1,1>>^ E falou o SENHOR a Moisés no deserto do Sinai, no segundo ano da sua saída da terra do Egito, no primeiro mês, dizendo:

[[v4-9-2]]

^<<v4-9-2,2>>^ Que os filhos de Israel celebrem a Páscoa a seu tempo determinado.

[[v4-9-3]]

^<<v4-9-3,3>>^ No dia catorze deste mês, pela tarde, a seu tempo determinado a celebrareis; segundo todos os seus estatutos e segundo todos os seus ritos, a celebrareis.

[[v4-9-4]]

^<<v4-9-4,4>>^ Disse, pois, Moisés aos filhos de Israel que celebrassem a Páscoa.

[[v4-9-5]]

^<<v4-9-5,5>>^ Então, celebraram a Páscoa no dia catorze do primeiro mês, pela tarde, no deserto do Sinai; conforme tudo o que o SENHOR ordenara a Moisés, assim fizeram os filhos de Israel.

[[v4-9-6]]

^<<v4-9-6,6>>^ E houve alguns que estavam imundos pelo corpo de um homem morto; e no mesmo dia não podiam celebrar a Páscoa; pelo que se chegaram perante Moisés e perante Arão aquele mesmo dia.

[[v4-9-7]]

^<<v4-9-7,7>>^ E aqueles homens disseram-lhe: Imundos estamos  nós pelo corpo de um homem morto; por que seríamos privados de oferecer a oferta do SENHOR a seu tempo determinado no meio dos filhos de Israel?

[[v4-9-8]]

^<<v4-9-8,8>>^ E disse-lhes Moisés: Esperai, e ouvirei o que o SENHOR vos ordenará.

[[v4-9-9]]

^<<v4-9-9,9>>^ Então, falou o SENHOR a Moisés, dizendo:

[[v4-9-10]]

^<<v4-9-10,10>>^ Fala aos filhos de Israel, dizendo: Quando alguém entre vós ou entre as vossas gerações for imundo por corpo morto ou se achar em jornada longe de vós, contudo, ainda celebrará a Páscoa ao SENHOR.

[[v4-9-11]]

^<<v4-9-11,11>>^ No segundo mês, no dia catorze, de tarde, a celebrarão: Com pães  asmos e ervas  amargas a comerão.

[[v4-9-12]]

^<<v4-9-12,12>>^ Dela nada deixarão até à manhã e dela não quebrarão osso algum; segundo todo o estatuto da Páscoa, a celebrarão.

[[v4-9-13]]

^<<v4-9-13,13>>^ Porém, quando um homem for limpo, e não estiver de caminho, e deixar de celebrar a Páscoa, tal alma do seu povo será extirpada; porquanto não ofereceu a oferta do SENHOR a seu tempo determinado; tal homem levará o seu pecado.

[[v4-9-14]]

^<<v4-9-14,14>>^ E, quando um estrangeiro peregrinar entre vós e também celebrar a Páscoa ao SENHOR, segundo o estatuto da Páscoa e segundo o seu rito, assim a celebrará; um mesmo estatuto haverá para vós, assim para o estrangeiro como para o natural da terra.

[[v4-9-15]]

^<<v4-9-15,15>>^ E, no dia de levantar o tabernáculo, a nuvem cobriu o tabernáculo sobre a tenda do Testemunho; e, à tarde, estava sobre o tabernáculo como uma aparência de fogo até à manhã.

[[v4-9-16]]

^<<v4-9-16,16>>^ Assim era de contínuo: a nuvem o cobria, e, de noite, havia  aparência de fogo.

[[v4-9-17]]

^<<v4-9-17,17>>^ Mas, sempre que a nuvem se alçava sobre a tenda, os filhos de Israel após ela partiam; e, no lugar onde a nuvem parava, ali os filhos de Israel assentavam o seu arraial.

[[v4-9-18]]

^<<v4-9-18,18>>^ Segundo o dito do SENHOR, os filhos de Israel partiam e segundo o dito do SENHOR assentavam o arraial; todos os dias em que a nuvem parava sobre o tabernáculo, assentavam o arraial.

[[v4-9-19]]

^<<v4-9-19,19>>^ E, quando a nuvem se detinha muitos dias sobre o tabernáculo, então, os filhos de Israel tinham cuidado da guarda do SENHOR e não partiam.

[[v4-9-20]]

^<<v4-9-20,20>>^ E era que, quando a nuvem poucos dias estava sobre o tabernáculo, segundo o dito do SENHOR, se alojavam e, segundo o dito do SENHOR, partiam.

[[v4-9-21]]

^<<v4-9-21,21>>^ Porém era que, quando a nuvem desde a tarde até à manhã ficava ali  e a nuvem se alçava pela manhã, então, partiam; quer de dia quer de noite, alçando-se a nuvem, partiam.

[[v4-9-22]]

^<<v4-9-22,22>>^ Ou, quando a nuvem sobre o tabernáculo se detinha dois dias, ou um mês, ou um ano, ficando sobre ele, então, os filhos de Israel se alojavam e não partiam; e, alçando-se ela, partiam.

[[v4-9-23]]

^<<v4-9-23,23>>^ Segundo o dito do SENHOR, se alojavam e, segundo o dito do SENHOR, partiam; da guarda do SENHOR tinham cuidado, segundo o dito do SENHOR pela mão de Moisés.

'''

xref:004-numeros/004-numeros-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numeros/004-numeros-010.adoc#v4-10-0[Próximo Capítulo &#62;]