include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-20-1]]

^<<v4-20-1,1>>^ Chegando os filhos de Israel, toda a congregação, ao deserto de Zim, no mês primeiro, o povo ficou em Cades; e Miriã morreu ali e ali foi sepultada.

[[v4-20-2]]

^<<v4-20-2,2>>^ E não havia água para a congregação; então, se congregaram contra Moisés e contra Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ E o povo contendeu com Moisés, e falaram, dizendo: Antes tivéssemos expirado quando expiraram nossos irmãos perante o SENHOR!

[[v4-20-4]]

^<<v4-20-4,4>>^ E por que trouxestes a congregação do SENHOR a este deserto, para que morramos ali, nós e os nossos animais?

[[v4-20-5]]

^<<v4-20-5,5>>^ E por que nos fizestes subir do Egito, para nos trazer a este lugar mau? Lugar não de semente, nem de figos, nem de vides, nem de romãs, nem de água para beber.

[[v4-20-6]]

^<<v4-20-6,6>>^ Então, Moisés e Arão se foram de diante da congregação, à porta da tenda da congregação e se lançaram sobre o seu rosto; e a glória do SENHOR lhes apareceu.

[[v4-20-7]]

^<<v4-20-7,7>>^ E o SENHOR falou a Moisés, dizendo:

[[v4-20-8]]

^<<v4-20-8,8>>^ Toma a vara e ajunta a congregação, tu e Arão, teu irmão, e falai à rocha perante os seus olhos, e dará a sua água; assim, lhes tirarás água da rocha e darás a beber à congregação e aos seus animais.

[[v4-20-9]]

^<<v4-20-9,9>>^ Então, Moisés tomou a vara de diante do SENHOR, como lhe tinha ordenado.

[[v4-20-10]]

^<<v4-20-10,10>>^ E Moisés e Arão reuniram a congregação diante da rocha, e Moisés  disse-lhes: Ouvi agora, rebeldes: porventura, tiraremos água desta rocha para vós?

[[v4-20-11]]

^<<v4-20-11,11>>^ Então, Moisés levantou a sua mão e feriu a rocha duas vezes com a sua vara, e saíram muitas águas; e bebeu a congregação e os seus animais.

[[v4-20-12]]

^<<v4-20-12,12>>^ E o SENHOR disse a Moisés e a Arão: Porquanto não me crestes a mim, para me santificar diante dos filhos de Israel, por isso não metereis esta congregação na terra que lhes tenho dado.

[[v4-20-13]]

^<<v4-20-13,13>>^ Estas são as águas de Meribá, porque os filhos de Israel contenderam com o SENHOR; e o SENHOR se santificou neles.

[[v4-20-14]]

^<<v4-20-14,14>>^ Depois, Moisés desde Cades mandou mensageiros ao rei de Edom, dizendo:  Assim diz teu irmão Israel: Sabes todo o trabalho que nos sobreveio;

[[v4-20-15]]

^<<v4-20-15,15>>^ como nossos pais desceram ao Egito, e nós no Egito habitamos muitos dias; e como  os egípcios nos maltrataram, a nós e a nossos pais;

[[v4-20-16]]

^<<v4-20-16,16>>^ e clamamos ao SENHOR, e ele  ouviu a nossa voz, e mandou um anjo, e nos tirou do Egito; e eis que estamos em Cades, cidade na extremidade dos teus termos.

[[v4-20-17]]

^<<v4-20-17,17>>^ Deixa-nos, pois,  passar pela tua terra; não passaremos pelo campo, nem pelas vinhas, nem beberemos a água dos poços; iremos pela estrada real; não nos desviaremos para a direita nem para a esquerda, até que passemos pelos teus termos.

[[v4-20-18]]

^<<v4-20-18,18>>^ Porém Edom lhe disse: Não passarás por mim, para que, porventura, eu  não saia à espada ao teu encontro.

[[v4-20-19]]

^<<v4-20-19,19>>^ Então, os filhos de Israel lhe disseram: Subiremos pelo caminho igualado, e, se eu e o meu gado bebermos das tuas águas, darei o preço delas; sem fazer alguma outra coisa, deixa-me somente passar a pé.

[[v4-20-20]]

^<<v4-20-20,20>>^ Porém ele  disse: Não passarás. E saiu-lhe Edom ao encontro com muita gente e com mão forte.

[[v4-20-21]]

^<<v4-20-21,21>>^ Assim, recusou Edom deixar passar a Israel pelo seu termo; pelo que Israel se desviou dele.

[[v4-20-22]]

^<<v4-20-22,22>>^ Então, partiram de Cades; e os filhos de Israel, toda a congregação, vieram ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ E falou o SENHOR a Moisés e a Arão no monte Hor, nos termos da terra de Edom, dizendo:

[[v4-20-24]]

^<<v4-20-24,24>>^ Arão recolhido será a seu povo, porque não entrará na terra que tenho dado aos filhos de Israel, porquanto rebeldes fostes à minha palavra, nas águas de Meribá.

[[v4-20-25]]

^<<v4-20-25,25>>^ Toma a Arão e a Eleazar, seu filho, e faze-os subir ao monte Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ E despe a Arão as suas vestes e veste-as a Eleazar, seu filho, porque Arão será recolhido e morrerá ali.

[[v4-20-27]]

^<<v4-20-27,27>>^ Fez, pois, Moisés como o SENHOR lhe ordenara; porque subiram ao monte Hor perante os olhos de toda a congregação.

[[v4-20-28]]

^<<v4-20-28,28>>^ E Moisés despiu a Arão as vestes e as vestiu a Eleazar, seu filho; e morreu Arão ali sobre o cume do monte; e desceram Moisés e Eleazar do monte.

[[v4-20-29]]

^<<v4-20-29,29>>^ Vendo, pois, toda a congregação que Arão era morto, choraram a Arão trinta dias, isto é, toda a casa de Israel.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]