include::./index.adoc[]

[[v4-8-0]]
=== Números, 8
// arc ?, ARC - Almeida Revista e Corrigida

[[v4-8-1]]

^<<v4-8-1,1>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-8-2]]

^<<v4-8-2,2>>^ Fala a Arão e dize-lhe: Quando acenderes as lâmpadas, defronte do candeeiro alumiarão as sete lâmpadas.

[[v4-8-3]]

^<<v4-8-3,3>>^ E Arão fez assim; defronte da face do candeeiro acendeu as suas lâmpadas, como o SENHOR ordenara a Moisés.

[[v4-8-4]]

^<<v4-8-4,4>>^ E era  esta obra do candeeiro de ouro batido; desde o seu pé até às suas flores era  batido; conforme o modelo que o SENHOR mostrara a Moisés, assim ele  fez o candeeiro.

[[v4-8-5]]

^<<v4-8-5,5>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-8-6]]

^<<v4-8-6,6>>^ Toma os levitas do meio dos filhos de Israel e purifica-os;

[[v4-8-7]]

^<<v4-8-7,7>>^ e assim lhes farás, para os purificar: Esparge sobre eles a água da expiação; e sobre toda a sua carne farão passar a navalha, e lavarão as suas vestes, e se purificarão.

[[v4-8-8]]

^<<v4-8-8,8>>^ Então, tomarão um novilho, com a sua oferta de manjares de  flor de farinha amassada com azeite; e tomarás outro novilho, para expiação do pecado.

[[v4-8-9]]

^<<v4-8-9,9>>^ E farás chegar os levitas perante a tenda da congregação; e farás ajuntar toda a congregação dos filhos de Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ Farás, pois, chegar os levitas perante o SENHOR; e os filhos de Israel porão as suas mãos sobre os levitas.

[[v4-8-11]]

^<<v4-8-11,11>>^ E Arão moverá os levitas por  oferta de movimento perante o SENHOR pelos filhos de Israel; e serão para servirem no ministério do SENHOR.

[[v4-8-12]]

^<<v4-8-12,12>>^ E os levitas porão as suas mãos sobre a cabeça dos novilhos; então, sacrifica tu um para  expiação do pecado e o outro, para  holocausto ao SENHOR, para fazer expiação pelos levitas.

[[v4-8-13]]

^<<v4-8-13,13>>^ E porás os levitas perante Arão, e perante os seus filhos, e os moverás por  oferta de movimento ao SENHOR.

[[v4-8-14]]

^<<v4-8-14,14>>^ E separarás os levitas do meio dos filhos de Israel, para que os levitas meus sejam.

[[v4-8-15]]

^<<v4-8-15,15>>^ E, depois, os levitas entrarão para fazerem o serviço da tenda da congregação; e tu os purificarás e, por  oferta de movimento, os moverás.

[[v4-8-16]]

^<<v4-8-16,16>>^ Porquanto eles, do meio dos filhos de Israel, me são dados; em lugar de todo aquele que abre a madre, do primogênito de cada um dos filhos de Israel, para mim os tenho tomado.

[[v4-8-17]]

^<<v4-8-17,17>>^ Porque meu é  todo primogênito entre os filhos de Israel, entre os homens e entre os animais; no dia em que, na terra do Egito, feri a todo primogênito, os santifiquei para mim.

[[v4-8-18]]

^<<v4-8-18,18>>^ E tomei os levitas em lugar de todo primogênito entre os filhos de Israel.

[[v4-8-19]]

^<<v4-8-19,19>>^ E os levitas, dados a Arão e a seus filhos, do meio dos filhos de Israel, tenho dado para exercerem o ministério dos filhos de Israel na tenda da congregação e para fazerem expiação pelos filhos de Israel, para que não haja praga entre os filhos de Israel, chegando-se os filhos de Israel ao santuário.

[[v4-8-20]]

^<<v4-8-20,20>>^ E assim fez Moisés, e Arão, e toda a congregação dos filhos de Israel com os levitas; conforme tudo o que o SENHOR ordenara a Moisés acerca dos levitas, assim os filhos de Israel lhes fizeram.

[[v4-8-21]]

^<<v4-8-21,21>>^ E os levitas se purificaram e lavaram as suas vestes, e Arão os moveu por  oferta movida perante o SENHOR, e Arão fez expiação por eles, para purificá-los.

[[v4-8-22]]

^<<v4-8-22,22>>^ E, depois, vieram os levitas, para exercerem o seu ministério na tenda da congregação, perante Arão e perante os seus filhos; como o SENHOR ordenara a Moisés acerca dos levitas, assim lhes fizeram.

[[v4-8-23]]

^<<v4-8-23,23>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-8-24]]

^<<v4-8-24,24>>^ Este é o ofício  dos levitas: Da idade de vinte e cinco anos para cima entrarão, para fazerem o serviço no ministério da tenda da congregação;

[[v4-8-25]]

^<<v4-8-25,25>>^ mas, desde a idade de cinquenta anos, sairão da milícia deste ministério e nunca mais servirão.

[[v4-8-26]]

^<<v4-8-26,26>>^ Porém com os seus irmãos servirão na tenda da congregação, para terem cuidado da guarda; mas o ministério não exercerão; assim farás com os levitas nas suas guardas.

'''

xref:004-numeros/004-numeros-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numeros/004-numeros-009.adoc#v4-9-0[Próximo Capítulo &#62;]