include::./index.adoc[]

[[v11-4-0]]
=== 1 Reis, 4
// arc ?, ARC - Almeida Revista e Corrigida

[[v11-4-1]]

^<<v11-4-1,1>>^ Assim, foi Salomão rei sobre todo o Israel.

[[v11-4-2]]

^<<v11-4-2,2>>^ E estes eram  os príncipes que tinha: Azarias, filho de Zadoque, sacerdote;

[[v11-4-3]]

^<<v11-4-3,3>>^ Eliorefe e Aías, filhos de Sisa, secretários; Josafá, filho de Ailude, chanceler;

[[v11-4-4]]

^<<v11-4-4,4>>^ Benaia, filho de Joiada, era comandante do exército; Zadoque e Abiatar eram  sacerdotes.

[[v11-4-5]]

^<<v11-4-5,5>>^ E Azarias, filho de Natã, estava sobre os provedores; e Zabude, filho de Natã, oficial-mor, amigo do rei;

[[v11-4-6]]

^<<v11-4-6,6>>^ e Aisar, mordomo; Adonirão, filho de Abda, sobre o tributo.

[[v11-4-7]]

^<<v11-4-7,7>>^ E tinha Salomão doze provedores sobre todo o Israel, que proviam ao rei e à sua casa; e cada um tinha a prover um  mês no ano.

[[v11-4-8]]

^<<v11-4-8,8>>^ E estes são  os seus nomes: Ben-Hur, nas montanhas de Efraim;

[[v11-4-9]]

^<<v11-4-9,9>>^ Ben-Dequer, em Macaz, e em Saalabim, e em Bete-Semes, e em Elom, e em Bete-Hanã;

[[v11-4-10]]

^<<v11-4-10,10>>^ Ben-Hesede, em Arubote; também  este tinha a Socó e a toda a terra de Héfer;

[[v11-4-11]]

^<<v11-4-11,11>>^ Ben-Abinadabe, em todo o termo de Dor; tinha este a Tafate, filha de Salomão, por mulher;

[[v11-4-12]]

^<<v11-4-12,12>>^ Baaná, filho de Ailude, tinha  a Taanaque, e a Megido, e a toda a Bete-Seã, que está  junto a Zaretã, abaixo de Jezreel, desde Bete-Seã até Abel-Meolá, até dalém de Jocmeão.

[[v11-4-13]]

^<<v11-4-13,13>>^ O filho de Geber, em Ramote-Gileade; tinha este as aldeias de Jair, filho de Manassés, as quais estão  em Gileade; também  tinha o termo de Argobe, o qual está  em Basã, sessenta grandes cidades com muros e ferrolhos de cobre;

[[v11-4-14]]

^<<v11-4-14,14>>^ Ainadabe, filho de Ido, em Maanaim;

[[v11-4-15]]

^<<v11-4-15,15>>^ Aimaás, em Naftali; também este tomou a Basemate, filha de Salomão, por mulher;

[[v11-4-16]]

^<<v11-4-16,16>>^ Baaná, filho de Husai, em Aser e em Bealote;

[[v11-4-17]]

^<<v11-4-17,17>>^ Josafá, filho de Parua, em Issacar;

[[v11-4-18]]

^<<v11-4-18,18>>^ Simei, filho de Elá, em Benjamim;

[[v11-4-19]]

^<<v11-4-19,19>>^ Geber, filho de Uri, na terra de Gileade, a terra de Seom, rei dos amorreus, e de Ogue, rei de Basã; e só uma guarnição havia  naquela terra.

[[v11-4-20]]

^<<v11-4-20,20>>^ Eram, pois,  os de Judá e Israel muitos, como a areia que está  ao pé do mar em multidão, comendo, e bebendo, e alegrando-se.

[[v11-4-21]]

^<<v11-4-21,21>>^ E dominava Salomão sobre todos os reinos desde o rio Eufrates até  à terra dos filisteus, e até ao termo do Egito; os quais traziam presentes e serviram a Salomão todos os dias da sua vida.

[[v11-4-22]]

^<<v11-4-22,22>>^ Era, pois, o provimento de Salomão, cada dia, trinta coros de flor de farinha e sessenta coros de farinha;

[[v11-4-23]]

^<<v11-4-23,23>>^ dez vacas gordas, e vinte vacas de pasto, e cem carneiros, afora os veados, e as cabras monteses, e os corços, e as aves cevadas.

[[v11-4-24]]

^<<v11-4-24,24>>^ Porque dominava sobre tudo quanto havia da banda de cá do rio Eufrates, de Tifsa até Gaza, sobre todos os reis da banda de cá do rio; e tinha paz de todas as bandas em roda dele.

[[v11-4-25]]

^<<v11-4-25,25>>^ Judá e Israel habitavam seguros, cada um debaixo da sua videira e debaixo da sua figueira, desde Dã até Berseba, todos os dias de Salomão.

[[v11-4-26]]

^<<v11-4-26,26>>^ Tinha também Salomão quarenta mil estrebarias de cavalos para os seus carros e doze mil cavaleiros.

[[v11-4-27]]

^<<v11-4-27,27>>^ Proviam, pois, estes provedores, cada um no  seu mês, ao rei Salomão e a todos quantos se chegavam à mesa do rei Salomão: coisa nenhuma deixavam faltar.

[[v11-4-28]]

^<<v11-4-28,28>>^ E traziam a cevada e a palha para os cavalos e para os ginetes, para o lugar onde estava cada um, segundo o seu cargo.

[[v11-4-29]]

^<<v11-4-29,29>>^ E deu Deus a Salomão sabedoria, e muitíssimo entendimento, e largueza de coração, como a areia que está  na praia do mar.

[[v11-4-30]]

^<<v11-4-30,30>>^ E era a sabedoria de Salomão maior do que a sabedoria de todos os do Oriente e do que toda a sabedoria dos egípcios.

[[v11-4-31]]

^<<v11-4-31,31>>^ E era ele ainda  mais sábio do que todos os homens, e do  que Etã, ezraíta, e do que Hemã, e Calcol, e Darda, filhos de Maol; e correu o seu nome por todas as nações em redor.

[[v11-4-32]]

^<<v11-4-32,32>>^ E disse três mil provérbios, e foram os seus cânticos mil e cinco.

[[v11-4-33]]

^<<v11-4-33,33>>^ Também falou das árvores, desde o cedro que está  no Líbano até ao hissopo que nasce na parede; também falou dos animais, e das aves, e dos répteis, e dos peixes.

[[v11-4-34]]

^<<v11-4-34,34>>^ E vinham de todos os povos a ouvir a sabedoria de Salomão e de todos os reis da terra que tinham ouvido da sua sabedoria.

'''

xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[Próximo Capítulo &#62;]