include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// arc ?, ARC - Almeida Revista e Corrigida

[[v11-22-1]]

^<<v11-22-1,1>>^ E estiveram quietos três anos, não havendo guerra entre a Síria e Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ Porém, no terceiro ano, sucedeu que Josafá, rei de Judá, desceu para o rei de Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ E o rei de Israel disse aos seus servos: Não sabeis vós que Ramote-Gileade é nossa, e nós estamos  quietos, sem a tomar da mão do rei da Síria?

[[v11-22-4]]

^<<v11-22-4,4>>^ Então, disse a Josafá: Irás tu comigo à peleja a Ramote-Gileade? E disse Josafá ao rei de Israel: Serei como tu és, e  o meu povo, como o teu povo, e  os meus cavalos, como os teus cavalos.

[[v11-22-5]]

^<<v11-22-5,5>>^ Disse mais Josafá ao rei de Israel: Consulta, porém, primeiro hoje a palavra do SENHOR.

[[v11-22-6]]

^<<v11-22-6,6>>^ Então, o rei de Israel ajuntou os profetas até quase quatrocentos homens e disse-lhes: Irei à peleja contra Ramote-Gileade ou deixarei de ir? E eles disseram: Sobe, porque o Senhor a  entregará na mão do rei.

[[v11-22-7]]

^<<v11-22-7,7>>^ Disse, porém, Josafá: Não há  aqui ainda algum  profeta do SENHOR, ao qual possamos consultar?

[[v11-22-8]]

^<<v11-22-8,8>>^ Então, disse o rei de Israel a Josafá: Ainda há  um homem por quem podemos consultar ao SENHOR; porém eu o aborreço, porque nunca profetiza de mim bem, mas só mal; este é  Micaías, filho de Inlá. E disse Josafá: Não fale o rei assim.

[[v11-22-9]]

^<<v11-22-9,9>>^ Então, o rei de Israel chamou um eunuco e disse: Traze- me  depressa a Micaías, filho de Inlá.

[[v11-22-10]]

^<<v11-22-10,10>>^ E o rei de Israel e Josafá, rei de Judá, estavam assentados cada um no seu trono, vestidos de vestiduras reais,  na praça, à entrada da porta de Samaria; e todos os profetas profetizavam na sua presença.

[[v11-22-11]]

^<<v11-22-11,11>>^ E Zedequias, filho de Quenaana, fez para si uns  chifres de ferro e disse: Assim diz o SENHOR: Com estes ferirás aos siros até de todo os consumir.

[[v11-22-12]]

^<<v11-22-12,12>>^ E todos os profetas profetizaram assim, dizendo: Sobe a Ramote-Gileade e prosperarás, porque o Senhor a  entregará na mão do rei.

[[v11-22-13]]

^<<v11-22-13,13>>^ E o mensageiro que foi chamar a Micaías falou-lhe, dizendo: Vês aqui que  as palavras dos profetas, a uma voz, predizem coisas  boas para o rei; seja, pois, a tua palavra como a palavra de um deles, e fala bem.

[[v11-22-14]]

^<<v11-22-14,14>>^ Porém Micaías disse: Vive o SENHOR, que o que o SENHOR me disser isso falarei.

[[v11-22-15]]

^<<v11-22-15,15>>^ E, vindo ele ao rei, o rei lhe disse: Micaías, iremos a Ramote-Gileade à peleja ou deixaremos de ir? E ele  lhe disse: Sobe e serás próspero, porque o SENHOR a entregará na mão do rei.

[[v11-22-16]]

^<<v11-22-16,16>>^ E o rei lhe disse: Até quantas vezes te conjurarei, que me não fales senão a verdade em nome do SENHOR?

[[v11-22-17]]

^<<v11-22-17,17>>^ Então, disse ele: Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor; e disse o SENHOR: Estes não têm senhor; torne cada um em paz para sua casa.

[[v11-22-18]]

^<<v11-22-18,18>>^ Então, o rei de Israel disse a Josafá: Não te disse eu que ele nunca profetizará de mim bem, senão só mal?

[[v11-22-19]]

^<<v11-22-19,19>>^ Então, disse ele: Ouve, pois, a palavra do SENHOR: Vi o SENHOR assentado sobre o seu trono, e todo o exército do céu estava junto a ele, à sua mão direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ E disse o SENHOR: Quem induzirá Acabe, a que suba e caia em Ramote-Gileade? E um dizia desta maneira, e outro, de outra.

[[v11-22-21]]

^<<v11-22-21,21>>^ Então, saiu um espírito, e se apresentou diante do SENHOR, e disse: Eu o induzirei. E o SENHOR lhe disse: Com quê?

[[v11-22-22]]

^<<v11-22-22,22>>^ E disse ele: Eu sairei e serei um espírito da mentira na boca de todos os seus profetas. E ele disse: Tu o induzirás e ainda prevalecerás; sai e faze assim.

[[v11-22-23]]

^<<v11-22-23,23>>^ Agora, pois, eis que o SENHOR pôs o espírito da mentira na boca de todos estes teus profetas, e o SENHOR falou mal contra ti.

[[v11-22-24]]

^<<v11-22-24,24>>^ Então, Zedequias, filho de Quenaana, chegou, e feriu a Micaías no queixo, e disse: Por onde passou de mim o Espírito do SENHOR para falar a ti?

[[v11-22-25]]

^<<v11-22-25,25>>^ E disse Micaías: Eis que o verás naquele mesmo dia, quando entrares de  câmara em câmara, para te esconderes.

[[v11-22-26]]

^<<v11-22-26,26>>^ Então, disse o rei de Israel: Tomai a Micaías e tornai a trazê-lo a Amom, o chefe da cidade, e a Joás, filho do rei,

[[v11-22-27]]

^<<v11-22-27,27>>^ e direis: Assim diz o rei: Metei este homem na casa do cárcere e sustentai-o com o pão de angústia e com a água de amargura, até que eu venha em paz.

[[v11-22-28]]

^<<v11-22-28,28>>^ E disse Micaías: Se tu voltares em paz, o SENHOR não tem falado por mim. Disse mais: Ouvi todos os povos!

[[v11-22-29]]

^<<v11-22-29,29>>^ Assim, o rei de Israel e Josafá, rei de Judá, subiram a Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ E disse o rei de Israel a Josafá: Eu me disfarçarei e entrarei na peleja; tu, porém, veste as tuas vestes. Disfarçou-se, pois, o rei de Israel e entrou na peleja.

[[v11-22-31]]

^<<v11-22-31,31>>^ E o rei da Síria deu ordem aos chefes dos carros, que eram trinta e dois, dizendo: Não pelejareis nem contra pequeno nem contra grande, mas só contra o rei de Israel.

[[v11-22-32]]

^<<v11-22-32,32>>^ Sucedeu, pois, que, vendo os chefes dos carros Josafá, disseram eles: Certamente, este é o rei de Israel. E chegaram-se a ele, para pelejar com ele;  porém Josafá gritou.

[[v11-22-33]]

^<<v11-22-33,33>>^ E sucedeu que, vendo os chefes dos carros que  não era  o rei de Israel, deixaram de segui-lo.

[[v11-22-34]]

^<<v11-22-34,34>>^ Então, um homem entesou o arco, na sua simplicidade, e feriu o rei de Israel por entre as fivelas e as couraças; então, ele disse ao seu carreteiro: Vira a tua mão e tira-me do exército, porque estou gravemente ferido.

[[v11-22-35]]

^<<v11-22-35,35>>^ E a peleja foi crescendo naquele dia, e o rei parou no carro defronte dos siros; porém ele morreu à tarde; e o sangue da ferida corria no fundo do carro.

[[v11-22-36]]

^<<v11-22-36,36>>^ E, depois do sol posto, passou um pregão pelo exército, dizendo: Cada um para a sua cidade, e cada um para a sua terra!

[[v11-22-37]]

^<<v11-22-37,37>>^ E morreu o rei, e o levaram a Samaria e sepultaram o rei em Samaria.

[[v11-22-38]]

^<<v11-22-38,38>>^ E, lavando-se o carro no tanque de Samaria, os cães lamberam o seu sangue (ora, as prostitutas se lavavam ali), conforme a palavra que o SENHOR tinha dito.

[[v11-22-39]]

^<<v11-22-39,39>>^ Quanto ao mais dos atos de Acabe, e a tudo quanto fez, e à casa de marfim que edificou, e a todas as cidades que edificou, porventura,  não está  escrito no Livro das Crônicas dos Reis de Israel?

[[v11-22-40]]

^<<v11-22-40,40>>^ Assim, dormiu Acabe com seus pais; e Acazias, seu filho, reinou em seu lugar.

[[v11-22-41]]

^<<v11-22-41,41>>^ E Josafá, filho de Asa, começou a reinar sobre Judá no quarto ano de Acabe, rei de Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ E era  Josafá da idade de trinta e cinco anos quando começou a reinar; e vinte e cinco anos reinou em Jerusalém; e era  o nome de sua mãe Azuba, filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ E andou em todos os caminhos de Asa, seu pai, não se desviou deles, fazendo o que era  reto aos olhos do SENHOR.

[[v11-22-44]]

^<<v11-22-44,44>>^ Todavia, os altos não se tiraram; ainda o povo sacrificava e queimava incenso nos altos.

[[v11-22-45]]

^<<v11-22-45,45>>^ E Josafá esteve em paz com o rei de Israel.

[[v11-22-46]]

^<<v11-22-46,46>>^ Quanto ao mais dos atos de Josafá, e ao poder que mostrou, e como guerreou, porventura,  não está  escrito no Livro das Crônicas dos Reis de Judá?

[[v11-22-47]]

^<<v11-22-47,47>>^ Também desterrou da terra o resto dos rapazes escandalosos que ficaram nos dias de Asa, seu pai.

[[v11-22-48]]

^<<v11-22-48,48>>^ Então, não havia  rei em Edom, porém  um vice-rei.

[[v11-22-49]]

^<<v11-22-49,49>>^ E  fez Josafá navios de Társis, para irem a Ofir por causa do ouro; porém não foram, porque os navios se quebraram em Eziom-Geber.

[[v11-22-50]]

^<<v11-22-50,50>>^ Então, Acazias, filho de Acabe, disse a Josafá: Vão os meus servos com os teus servos nos navios. Porém Josafá não quis.

[[v11-22-51]]

^<<v11-22-51,51>>^ E Josafá dormiu com seus pais e foi sepultado junto a seus pais, na Cidade de Davi, seu pai; e Jeorão, seu filho, reinou em seu lugar.

[[v11-22-52]]

^<<v11-22-52,52>>^ E Acazias, filho de Acabe, começou a reinar em Samaria, no ano dezessete de Josafá, rei de Judá; e reinou dois anos sobre Israel.

[[v11-22-53]]

^<<v11-22-53,53>>^ E fez o que era  mau aos olhos do SENHOR; porque andou nos caminhos de seu pai, como também nos caminhos de sua mãe, e nos caminhos de Jeroboão, filho de Nebate, que fez pecar a Israel.

[[v11-22-54]]

^<<v11-22-54,54>>^ E serviu a Baal, e se inclinou diante dele, e indignou ao SENHOR, Deus de Israel, conforme tudo quanto fizera seu pai.

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]