include::./index.adoc[]

[[v11-8-0]]
=== 1 Reis, 8
// arc ?, ARC - Almeida Revista e Corrigida

[[v11-8-1]]

^<<v11-8-1,1>>^ Então, congregou Salomão os anciãos de Israel e todos os cabeças das tribos, os príncipes dos pais, dentre os filhos de Israel, diante de si em Jerusalém, para fazerem subir a arca do concerto do SENHOR da Cidade de Davi, que é  Sião.

[[v11-8-2]]

^<<v11-8-2,2>>^ E todos os homens de Israel se juntaram, na festa, ao rei Salomão, no mês de etanim, que é  o sétimo mês.

[[v11-8-3]]

^<<v11-8-3,3>>^ E vieram todos os anciãos de Israel, e os sacerdotes alçaram a arca.

[[v11-8-4]]

^<<v11-8-4,4>>^ E trouxeram a arca do SENHOR para cima e o tabernáculo da congregação, juntamente com todos os utensílios sagrados que havia no tabernáculo; assim os trouxeram para cima os sacerdotes e os levitas.

[[v11-8-5]]

^<<v11-8-5,5>>^ E o rei Salomão e toda a congregação de Israel que se congregara a ele estavam  todos diante da arca, sacrificando ovelhas e vacas, que se não podiam contar, nem numerar pela multidão.

[[v11-8-6]]

^<<v11-8-6,6>>^ Assim trouxeram os sacerdotes a arca do concerto do SENHOR ao seu lugar, ao oráculo da casa, ao Lugar  Santíssimo, até  debaixo das asas dos querubins.

[[v11-8-7]]

^<<v11-8-7,7>>^ Porque os querubins estendiam ambas  as asas sobre o lugar da arca e cobriam a arca e os seus varais por cima.

[[v11-8-8]]

^<<v11-8-8,8>>^ E os varais sobressaíram tanto,  que as pontas dos varais se viam desde o santuário diante do oráculo; porém de fora não se viam; e ficaram ali até ao dia de  hoje.

[[v11-8-9]]

^<<v11-8-9,9>>^ Na arca, nada havia,  senão só as duas tábuas de pedra que Moisés ali pusera junto a Horebe, quando o SENHOR fez aliança com os filhos de Israel, saindo eles da terra do Egito.

[[v11-8-10]]

^<<v11-8-10,10>>^ E sucedeu que, saindo os sacerdotes do santuário, uma nuvem encheu a Casa do SENHOR.

[[v11-8-11]]

^<<v11-8-11,11>>^ E não podiam ter-se em pé os sacerdotes para ministrar, por causa da nuvem, porque a glória do SENHOR enchera a Casa do SENHOR.

[[v11-8-12]]

^<<v11-8-12,12>>^ Então, disse Salomão: O SENHOR disse que habitaria nas trevas.

[[v11-8-13]]

^<<v11-8-13,13>>^ Certamente, te edifiquei uma casa para morada, assento para a tua eterna habitação.

[[v11-8-14]]

^<<v11-8-14,14>>^ Então, virou o rei o rosto e abençoou toda a congregação de Israel; e toda a congregação de Israel estava em pé.

[[v11-8-15]]

^<<v11-8-15,15>>^ E disse: Bendito seja  o SENHOR, o Deus de Israel, que falou pela sua boca a Davi, meu pai, e pela sua mão o  cumpriu, dizendo:

[[v11-8-16]]

^<<v11-8-16,16>>^ Desde o dia em que eu tirei o meu povo de Israel do Egito, não escolhi cidade alguma  de todas as tribos de Israel para edificar alguma casa, para ali estabelecer o meu nome; porém escolhi a Davi, para que governasse sobre o meu povo de Israel.

[[v11-8-17]]

^<<v11-8-17,17>>^ Também Davi, meu pai, propusera em seu coração o edificar casa ao nome do SENHOR, o Deus de Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ Porém o SENHOR disse a Davi, meu pai: Porquanto propuseste no teu coração o edificar casa ao meu nome, bem fizeste em o propor no teu coração.

[[v11-8-19]]

^<<v11-8-19,19>>^ Todavia, tu não edificarás esta casa, porém teu filho, que descender de ti, edificará esta casa ao meu nome.

[[v11-8-20]]

^<<v11-8-20,20>>^ Assim confirmou o SENHOR a sua palavra que tinha dito; porque me levantei em lugar de Davi, meu pai, e me assentei no trono de Israel, como tem dito o SENHOR; e edifiquei uma casa ao nome do SENHOR, o Deus de Israel.

[[v11-8-21]]

^<<v11-8-21,21>>^ E constituí ali lugar para a arca em que está  o concerto que o SENHOR fez com nossos pais, quando os tirou da terra do Egito.

[[v11-8-22]]

^<<v11-8-22,22>>^ E pôs-se Salomão diante do altar do SENHOR, em frente de toda a congregação de Israel, e estendeu as mãos para os céus,

[[v11-8-23]]

^<<v11-8-23,23>>^ e disse: Ó SENHOR, Deus de Israel, não há  Deus como tu, em cima nos céus nem embaixo na terra, que guardas o concerto e a beneficência a teus servos que andam de todo o seu coração diante de ti;

[[v11-8-24]]

^<<v11-8-24,24>>^ que cumpriste com teu servo Davi, meu pai, o que lhe disseras; porque, com a tua boca, o disseste e, com a tua mão, o cumpriste, como neste  dia se vê.

[[v11-8-25]]

^<<v11-8-25,25>>^ Agora, pois, ó SENHOR, Deus de Israel, faze a teu servo Davi, meu pai, o que lhe falaste, dizendo: Não te faltará sucessor diante de mim, que se assente no trono de Israel; somente que teus filhos guardem o seu caminho, para andarem diante de mim como tu andaste diante de mim.

[[v11-8-26]]

^<<v11-8-26,26>>^ Agora, também, ó Deus de Israel, cumpra-se a tua palavra que disseste a teu servo Davi, meu pai.

[[v11-8-27]]

^<<v11-8-27,27>>^ Mas, na verdade, habitaria Deus na terra? Eis que os céus e até o céu dos céus te não poderiam conter, quanto menos esta casa que eu tenho edificado.

[[v11-8-28]]

^<<v11-8-28,28>>^ Volve-te, pois, para a oração de teu servo e para a sua súplica, ó SENHOR, meu Deus, para ouvires o clamor e a oração que o teu servo, hoje, faz diante de ti.

[[v11-8-29]]

^<<v11-8-29,29>>^ Para que os teus olhos, noite e dia, estejam abertos sobre esta casa, sobre este lugar, do qual disseste: O meu nome estará ali; para ouvires a oração que o teu servo fizer neste lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ Ouve, pois, a súplica do teu servo e do teu povo de Israel, quando orarem neste lugar; também ouve tu, no lugar da tua habitação nos céus; ouve também e perdoa.

[[v11-8-31]]

^<<v11-8-31,31>>^ Quando alguém pecar contra o seu próximo, e puserem sobre ele juramento, para o ajuramentarem, e vier o juramento diante do teu altar, nesta casa,

[[v11-8-32]]

^<<v11-8-32,32>>^ ouve tu, então, nos céus, e age, e julga os teus servos, condenando ao injusto, fazendo recair o seu proceder sobre a sua cabeça, e justificando ao justo, e fazendo-lhe segundo a sua justiça.

[[v11-8-33]]

^<<v11-8-33,33>>^ Quando o teu povo de Israel for ferido diante do inimigo, por ter pecado contra ti, e se converterem a ti, e confessarem o teu nome, e orarem, e suplicarem a ti nesta casa,

[[v11-8-34]]

^<<v11-8-34,34>>^ ouve tu, então, nos céus, e perdoa o pecado do teu povo de Israel, e torna a levá-lo à terra que tens dado a seus pais.

[[v11-8-35]]

^<<v11-8-35,35>>^ Quando os céus se cerrarem, e não houver chuva, por terem pecado contra ti, e orarem neste lugar, e confessarem o teu nome, e se converterem dos seus pecados, havendo-os tu afligido,

[[v11-8-36]]

^<<v11-8-36,36>>^ ouve tu, então, nos céus, e perdoa o pecado de teus servos e do teu povo de Israel, ensinando-lhes o bom caminho em que andem, e dá chuva na terra que deste ao teu povo em herança.

[[v11-8-37]]

^<<v11-8-37,37>>^ Quando houver fome na terra, quando houver peste, quando houver queima de searas, ferrugem, gafanhotos e  pulgão, quando o seu inimigo o cercar na terra das suas portas ou houver  alguma praga ou  doença,

[[v11-8-38]]

^<<v11-8-38,38>>^ toda oração, toda súplica que qualquer homem de todo o teu povo de Israel fizer,  conhecendo cada um a chaga do seu coração e estendendo as mãos para esta casa,

[[v11-8-39]]

^<<v11-8-39,39>>^ ouve tu, então, nos céus, assento da tua habitação, e perdoa, e faze, e dá a cada um conforme todos os seus caminhos e segundo vires o seu coração, porque só tu conheces o coração de todos os filhos dos homens.

[[v11-8-40]]

^<<v11-8-40,40>>^ Para que te temam todos os dias que viverem na terra que deste a nossos pais.

[[v11-8-41]]

^<<v11-8-41,41>>^ E também ouve  ao estrangeiro que não for  do teu povo Israel, porém vier de terras remotas, por amor do teu nome

[[v11-8-42]]

^<<v11-8-42,42>>^ (porque ouvirão do teu grande nome, e da tua forte mão, e do teu braço estendido), e vier orar a esta casa.

[[v11-8-43]]

^<<v11-8-43,43>>^ Ouve tu nos céus, assento da tua habitação, e faze conforme tudo o que o estrangeiro a ti clamar, a fim de que todos os povos da terra conheçam o teu nome, para te temerem como o teu povo de Israel e para saberem que o teu nome é invocado sobre esta casa que tenho edificado.

[[v11-8-44]]

^<<v11-8-44,44>>^ Quando o teu povo sair à guerra contra o seu inimigo, pelo caminho por que os enviares, e orarem ao SENHOR, para a banda desta cidade que tu elegeste e desta casa que edifiquei ao teu nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ ouve, então, nos céus a sua oração e a sua súplica e faze-lhes justiça.

[[v11-8-46]]

^<<v11-8-46,46>>^ Quando pecarem contra ti (pois não há  homem que não peque), e tu te indignares contra eles, e os entregares nas mãos do inimigo, para que os que os cativarem os levem em cativeiro à terra do inimigo, quer  longe ou perto esteja;

[[v11-8-47]]

^<<v11-8-47,47>>^ e, na terra aonde forem levados em cativeiro, tornarem em si, e se converterem, e na terra do seu cativeiro te suplicarem, dizendo: Pecamos, e perversamente agimos, e  cometemos iniquidade;

[[v11-8-48]]

^<<v11-8-48,48>>^ e, se converterem a ti de todo o seu coração e de toda a sua alma, na terra de seus inimigos que os levaram em cativeiro, e orarem a ti para a banda da terra que deste a seus pais, para  esta cidade que elegeste e para  esta casa que edifiquei ao teu nome;

[[v11-8-49]]

^<<v11-8-49,49>>^ ouve, então, nos céus, assento da tua habitação, a sua oração e a sua súplica, e faze-lhes justiça,

[[v11-8-50]]

^<<v11-8-50,50>>^ e perdoa ao teu povo que houver pecado contra ti todas as suas prevaricações com que houverem prevaricado contra ti; e faze-lhes misericórdia perante aqueles que os têm cativos, para que deles tenham compaixão.

[[v11-8-51]]

^<<v11-8-51,51>>^ Porque são  o teu povo e a tua herança que tiraste da terra do Egito, do meio do forno de ferro,

[[v11-8-52]]

^<<v11-8-52,52>>^ para que teus olhos estejam abertos à súplica do teu servo e à súplica do teu povo de Israel, a fim de os ouvires em tudo quanto clamarem a ti.

[[v11-8-53]]

^<<v11-8-53,53>>^ Pois tu, para tua herança, os elegeste de todos os povos da terra, como tens dito pelo ministério de Moisés, teu servo, quando tiraste os nossos pais do Egito, Senhor Jeová .

[[v11-8-54]]

^<<v11-8-54,54>>^ Sucedeu, pois, que, acabando Salomão de fazer ao SENHOR esta oração e esta súplica, estando de joelhos e com as mãos estendidas para os céus, se levantou de diante do altar do SENHOR,

[[v11-8-55]]

^<<v11-8-55,55>>^ e pôs-se em pé, e abençoou a toda a congregação de Israel em alta voz, dizendo:

[[v11-8-56]]

^<<v11-8-56,56>>^ Bendito seja  o SENHOR, que deu repouso ao seu povo de Israel, segundo tudo o que disse; nem uma só palavra caiu de todas as suas boas palavras que falou pelo ministério de Moisés, seu servo.

[[v11-8-57]]

^<<v11-8-57,57>>^ O SENHOR, nosso Deus, seja conosco, como foi com nossos pais; não nos desampare e não nos deixe,

[[v11-8-58]]

^<<v11-8-58,58>>^ inclinando a si o nosso coração, para andar em todos os seus caminhos e para guardar os seus mandamentos, e os seus estatutos, e os seus juízos que ordenou a nossos pais.

[[v11-8-59]]

^<<v11-8-59,59>>^ E que estas minhas palavras com que supliquei perante o SENHOR estejam perto, diante do SENHOR, nosso Deus, de dia e de noite, para que execute o juízo do seu servo e o juízo do seu povo de Israel, a cada qual no seu dia,

[[v11-8-60]]

^<<v11-8-60,60>>^ para que todos os povos da terra saibam que o Senhor é  Deus e que  não há  outro.

[[v11-8-61]]

^<<v11-8-61,61>>^ E seja o vosso coração perfeito para com o SENHOR, nosso Deus, para andardes nos seus estatutos e guardardes os seus mandamentos, como hoje.

[[v11-8-62]]

^<<v11-8-62,62>>^ E o rei e todo o Israel com ele sacrificaram sacrifícios perante a face do SENHOR.

[[v11-8-63]]

^<<v11-8-63,63>>^ E ofereceu Salomão em sacrifício pacífico o que sacrificou ao SENHOR, vinte e duas mil vacas e cento e vinte mil ovelhas; assim o rei e todos os filhos de Israel consagraram a Casa do SENHOR.

[[v11-8-64]]

^<<v11-8-64,64>>^ No mesmo dia, santificou o rei o meio do átrio que estava  diante da Casa do SENHOR; porquanto ali preparara os holocaustos e as ofertas com a gordura dos sacrifícios pacíficos; porque o altar de cobre que estava  diante da face do Senhor era  muito pequeno para nele caberem os holocaustos, e as ofertas, e a gordura dos sacrifícios pacíficos.

[[v11-8-65]]

^<<v11-8-65,65>>^ No mesmo tempo, celebrou Salomão a festa, e todo o Israel, com ele, uma grande congregação, desde a entrada de Hamate até ao rio do Egito, perante a face do SENHOR, nosso Deus, por sete dias e mais  sete dias, catorze dias.

[[v11-8-66]]

^<<v11-8-66,66>>^ E, no oitavo dia, despediu o povo, e eles abençoaram o rei; então, se foram às suas tendas, alegres e contentes de coração, por causa de todo o bem que o SENHOR fizera a Davi, seu servo, e a Israel, seu povo.

'''

xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]