include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// arc ?, ARC - Almeida Revista e Corrigida

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquele tempo, adoeceu Abias, filho de Jeroboão.

[[v11-14-2]]

^<<v11-14-2,2>>^ E disse Jeroboão à sua mulher: Levanta-te, agora, e disfarça-te, para que não conheçam que és mulher de Jeroboão, e vai a Siló. Eis que lá está  o profeta Aías o qual falou de mim, que eu seria  rei sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ E toma na tua mão dez pães, e bolos, e uma botija de mel e vai a ele; ele te declarará o que há de suceder a este menino.

[[v11-14-4]]

^<<v11-14-4,4>>^ E a mulher de Jeroboão assim fez, e se levantou, e foi a Siló, e entrou na casa de Aías; e já Aías não podia ver, porque os seus olhos estavam já escurecidos por causa da sua velhice.

[[v11-14-5]]

^<<v11-14-5,5>>^ Porém o SENHOR disse a Aías: Eis que a mulher de Jeroboão vem consultar-te sobre seu filho, porque está doente; assim e assim lhe falarás, e há de ser que, entrando ela, fingirá ser  outra.

[[v11-14-6]]

^<<v11-14-6,6>>^ E sucedeu que, ouvindo Aías o ruído de seus pés, entrando ela pela porta, disse ele: Entra, mulher de Jeroboão! Por que te disfarças assim? Pois eu sou  enviado a ti com  duras novas.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai e dize a Jeroboão: Assim diz o SENHOR, Deus de Israel: Visto que te levantei do meio do povo, e te pus por chefe sobre o meu povo de Israel,

[[v11-14-8]]

^<<v11-14-8,8>>^ e rasguei o reino da casa de Davi, e a ti to dei, e tu não foste como o meu servo Davi, que guardou os meus mandamentos e que andou após mim com todo o seu coração para fazer somente o que era  reto aos meus olhos;

[[v11-14-9]]

^<<v11-14-9,9>>^ antes, tu fizeste o mal, pior do que todos os que foram antes de ti, e foste, e fizeste outros deuses e imagens de fundição, para provocar-me à ira, e me lançaste para trás das tuas costas,

[[v11-14-10]]

^<<v11-14-10,10>>^ portanto, eis que trarei mal sobre a casa de Jeroboão, e separarei de Jeroboão todo homem até ao menino, tanto o escravo como o livre em Israel, e lançarei fora os descendentes da casa de Jeroboão, como se lança fora o esterco, até que de todo se acabe.

[[v11-14-11]]

^<<v11-14-11,11>>^ Quem morrer a Jeroboão na cidade, os cães o comerão, e o que morrer no campo, as aves do céu o comerão, porque o Senhor o  disse.

[[v11-14-12]]

^<<v11-14-12,12>>^ Tu, pois, levanta-te e  vai-te para tua casa; entrando os teus pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ E todo o Israel o pranteará e o sepultará, porque de Jeroboão só este entrará em sepultura, porquanto se achou nele coisa boa para com o SENHOR, Deus de Israel, em casa de Jeroboão.

[[v11-14-14]]

^<<v11-14-14,14>>^ O SENHOR, porém, levantará para si um rei sobre Israel, que destruirá a casa de Jeroboão no mesmo dia; mas que será também agora!

[[v11-14-15]]

^<<v11-14-15,15>>^ Também o SENHOR ferirá a Israel, como se move a cana nas águas, e arrancará a Israel desta boa terra que tinha dado a seus pais, e o espalhará para além do rio, porquanto fizeram os seus bosques, provocando o SENHOR à ira.

[[v11-14-16]]

^<<v11-14-16,16>>^ E entregará Israel por causa dos pecados de Jeroboão, o qual pecou e fez pecar a Israel.

[[v11-14-17]]

^<<v11-14-17,17>>^ Então, a mulher de Jeroboão se levantou, e foi, e veio a Tirza; chegando ela ao limiar da porta, morreu o menino.

[[v11-14-18]]

^<<v11-14-18,18>>^ E o sepultaram, e todo o Israel o pranteou, conforme a palavra do SENHOR, a qual dissera pelo ministério de seu servo Aías, o profeta.

[[v11-14-19]]

^<<v11-14-19,19>>^ Quanto ao mais dos atos de Jeroboão, como guerreou e como reinou, eis que tudo está  escrito no Livro das Crônicas dos Reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ E foram  os dias que Jeroboão reinou vinte e dois anos, e dormiu com seus pais; e Nadabe, seu filho, reinou em seu lugar.

[[v11-14-21]]

^<<v11-14-21,21>>^ E Roboão, filho de Salomão, reinava em Judá; de quarenta e um anos de idade era  Roboão quando começou a reinar e dezessete anos reinou em Jerusalém, na cidade que o SENHOR elegera de todas as tribos de Israel para pôr ali o seu nome; e era  o nome de sua mãe Naamá, amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ E fez Judá o que era  mau aos olhos do SENHOR; e o provocaram a zelo, mais do que todos os seus pais fizeram com os seus pecados que cometeram.

[[v11-14-23]]

^<<v11-14-23,23>>^ Porque também eles edificaram altos, e estátuas, e imagens do bosque sobre todo alto outeiro e debaixo de toda árvore verde.

[[v11-14-24]]

^<<v11-14-24,24>>^ Havia também rapazes escandalosos na terra; fizeram conforme todas as abominações das nações que o SENHOR tinha expulsado de diante dos filhos de Israel.

[[v11-14-25]]

^<<v11-14-25,25>>^ Sucedeu, pois, que,  no quinto ano do rei Roboão, Sisaque, rei do Egito, subiu contra Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ E tomou os tesouros da Casa do SENHOR e os tesouros da casa do rei, e ainda tomou tudo, e também tomou todos os escudos de ouro que Salomão tinha feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ E, em lugar deles, fez o rei Roboão escudos de cobre e os entregou nas mãos dos capitães da guarda, que guardavam a porta da casa do rei.

[[v11-14-28]]

^<<v11-14-28,28>>^ E sucedeu que,  quando o rei entrava na Casa do SENHOR, os da guarda os levavam e os tornavam a trazer à câmara dos da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ Quanto ao mais dos atos de Roboão e a tudo quanto fez, porventura,  não está  tudo escrito no Livro das Crônicas dos Reis de Judá?

[[v11-14-30]]

^<<v11-14-30,30>>^ E houve guerra entre Roboão e Jeroboão todos os seus  dias.

[[v11-14-31]]

^<<v11-14-31,31>>^ E Roboão dormiu com seus pais e foi sepultado com seus pais na Cidade de Davi; e era  o nome de sua mãe Naamá, amonita; e Abias, seu filho, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]