include::./index.adoc[]

[[v20-31-0]]
=== Provérbios, 31
// arc ?, ARC - Almeida Revista e Corrigida

[[v20-31-1]]

^<<v20-31-1,1>>^ Palavras do rei Lemuel, a profecia que lhe ensinou sua mãe.

[[v20-31-2]]

^<<v20-31-2,2>>^ Como, filho meu? E como, ó filho do meu ventre? E como, ó filho das minhas promessas?

[[v20-31-3]]

^<<v20-31-3,3>>^ Não dês às mulheres a tua força, nem os teus caminhos, ao que destrói os reis.

[[v20-31-4]]

^<<v20-31-4,4>>^ Não é  próprio dos reis, ó Lemuel, não é  próprio dos reis beber vinho, nem dos príncipes desejar  bebida forte.

[[v20-31-5]]

^<<v20-31-5,5>>^ Para que não bebam, e se esqueçam do estatuto, e pervertam o juízo de todos os aflitos.

[[v20-31-6]]

^<<v20-31-6,6>>^ Dai bebida forte aos que perecem, e o vinho, aos amargosos de espírito;

[[v20-31-7]]

^<<v20-31-7,7>>^ para que bebam, e se esqueçam da sua pobreza, e do seu trabalho não se lembrem mais.

[[v20-31-8]]

^<<v20-31-8,8>>^ Abre a tua boca a favor do mudo, pelo direito de todos os que se acham em desolação.

[[v20-31-9]]

^<<v20-31-9,9>>^ Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados. Álefe.

[[v20-31-10]]

^<<v20-31-10,10>>^ Mulher virtuosa, quem a achará? O seu valor muito excede o de rubins. Bete.

[[v20-31-11]]

^<<v20-31-11,11>>^ O coração do seu marido está nela confiado, e a ela nenhuma fazenda faltará. Guímel.

[[v20-31-12]]

^<<v20-31-12,12>>^ Ela lhe faz bem e não mal, todos os dias da sua vida. Dálete.

[[v20-31-13]]

^<<v20-31-13,13>>^ Busca lã e linho e trabalha de boa vontade com as suas mãos. Hê.

[[v20-31-14]]

^<<v20-31-14,14>>^ É como o navio mercante: de longe traz o seu pão. Vau.

[[v20-31-15]]

^<<v20-31-15,15>>^ Ainda de noite, se levanta e dá mantimento à sua casa e a tarefa às suas servas. Zain.

[[v20-31-16]]

^<<v20-31-16,16>>^ Examina uma  herdade e adquire-a; planta uma  vinha com o fruto de suas mãos. Hete.

[[v20-31-17]]

^<<v20-31-17,17>>^ Cinge os lombos de força e fortalece os braços. Tete.

[[v20-31-18]]

^<<v20-31-18,18>>^ Prova e vê  que é  boa sua mercadoria; e  a sua lâmpada não se apaga de noite. Jode.

[[v20-31-19]]

^<<v20-31-19,19>>^ Estende as mãos ao fuso, e as palmas das suas mãos pegam na roca. Cafe.

[[v20-31-20]]

^<<v20-31-20,20>>^ Abre a mão ao aflito; e ao necessitado estende as mãos. Lâmede.

[[v20-31-21]]

^<<v20-31-21,21>>^ Não temerá, por causa da neve, porque toda a sua casa anda forrada de roupa dobrada. Mem.

[[v20-31-22]]

^<<v20-31-22,22>>^ Faz para si tapeçaria; de linho fino e de púrpura é a sua veste. Nun.

[[v20-31-23]]

^<<v20-31-23,23>>^ Conhece-se o seu marido nas portas, quando se assenta com os anciãos da terra. Sâmeque.

[[v20-31-24]]

^<<v20-31-24,24>>^ Faz panos de linho fino, e vende-os, e dá cintas aos mercadores. Ain.

[[v20-31-25]]

^<<v20-31-25,25>>^ A força e a glória são as suas vestes, e ri-se do dia futuro. Pê.

[[v20-31-26]]

^<<v20-31-26,26>>^ Abre a boca com sabedoria, e a lei da beneficência está  na sua língua. Tsadê.

[[v20-31-27]]

^<<v20-31-27,27>>^ Olha pelo governo de sua casa e não come o pão da preguiça. Cofe.

[[v20-31-28]]

^<<v20-31-28,28>>^ Levantam-se seus filhos, e chamam-na bem-aventurada; como também  seu marido, que a louva, dizendo: Rexe.

[[v20-31-29]]

^<<v20-31-29,29>>^ Muitas filhas agiram virtuosamente, mas tu a todas és superior. Chim.

[[v20-31-30]]

^<<v20-31-30,30>>^ Enganosa é  a graça, e vaidade, a formosura, mas  a mulher que teme ao SENHOR, essa será louvada. Tau.

[[v20-31-31]]

^<<v20-31-31,31>>^ Dai-lhe do fruto das suas mãos, e louvem-na nas portas as suas obras.

'''

xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[&#60; Capítulo Anterior] | <<v20-31-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[Próximo Capítulo &#62;]