include::./index.adoc[]

[[v40-1-0]]
=== Mateus, 1
// arc ?, ARC - Almeida Revista e Corrigida

[[v40-1-1]]

^<<v40-1-1,1>>^ Livro da geração de Jesus Cristo, Filho de Davi, Filho de Abraão.

[[v40-1-2]]

^<<v40-1-2,2>>^ Abraão gerou a Isaque, e Isaque gerou a Jacó, e Jacó gerou a Judá e a seus irmãos,

[[v40-1-3]]

^<<v40-1-3,3>>^ e Judá gerou de Tamar a Perez e a Zerá, e Perez gerou a Esrom, e Esrom gerou a Arão.

[[v40-1-4]]

^<<v40-1-4,4>>^ Arão gerou a Aminadabe, e Aminadabe gerou a Naassom, e Naassom gerou a Salmom,

[[v40-1-5]]

^<<v40-1-5,5>>^ e Salmom gerou de Raabe a Boaz, e Boaz gerou de Rute a Obede, e Obede gerou a Jessé.

[[v40-1-6]]

^<<v40-1-6,6>>^ Jessé gerou ao rei Davi, e o rei Davi gerou a Salomão da que foi mulher  de Urias.

[[v40-1-7]]

^<<v40-1-7,7>>^ Salomão gerou a Roboão, e Roboão gerou a Abias, e Abias gerou a Asa,

[[v40-1-8]]

^<<v40-1-8,8>>^ e Asa gerou a Josafá, e Josafá gerou a Jorão, e Jorão gerou a Uzias,

[[v40-1-9]]

^<<v40-1-9,9>>^ e Uzias gerou a Jotão, e Jotão gerou a Acaz, e Acaz gerou a Ezequias.

[[v40-1-10]]

^<<v40-1-10,10>>^ Ezequias gerou a Manassés, e Manassés gerou a Amom, e Amom gerou a Josias,

[[v40-1-11]]

^<<v40-1-11,11>>^ e Josias gerou a Jeconias e a seus irmãos na deportação para a Babilônia.

[[v40-1-12]]

^<<v40-1-12,12>>^ E, depois da deportação para a Babilônia, Jeconias gerou a Salatiel, e Salatiel gerou a Zorobabel,

[[v40-1-13]]

^<<v40-1-13,13>>^ e Zorobabel gerou a Abiúde, e Abiúde gerou a Eliaquim, e Eliaquim gerou a Azor,

[[v40-1-14]]

^<<v40-1-14,14>>^ e Azor gerou a Sadoque, e Sadoque gerou a Aquim, e Aquim gerou a Eliúde,

[[v40-1-15]]

^<<v40-1-15,15>>^ e Eliúde gerou a Eleazar, e Eleazar gerou a Matã, e Matã gerou a Jacó,

[[v40-1-16]]

^<<v40-1-16,16>>^ e Jacó gerou a José, marido de Maria, da qual nasceu Jesus , que se chama o Cristo.

[[v40-1-17]]

^<<v40-1-17,17>>^ De sorte que todas as gerações, desde Abraão até Davi, são  catorze gerações; e, desde Davi até a deportação para a Babilônia, catorze gerações; e, desde a deportação para a Babilônia até Cristo, catorze gerações.

[[v40-1-18]]

^<<v40-1-18,18>>^ Ora, o nascimento de Jesus Cristo foi assim: Estando Maria, sua mãe, desposada com José, antes de se ajuntarem, achou-se ter concebido do Espírito Santo.

[[v40-1-19]]

^<<v40-1-19,19>>^ Então, José, seu marido, como era justo e a não queria infamar, intentou deixá-la secretamente.

[[v40-1-20]]

^<<v40-1-20,20>>^ E, projetando ele isso, eis que, em sonho, lhe apareceu um anjo do Senhor, dizendo: José, filho de Davi, não temas receber a Maria, tua mulher, porque o que nela está gerado é do Espírito Santo.

[[v40-1-21]]

^<<v40-1-21,21>>^ E ela dará à luz um  filho, e lhe porás o nome de Jesus , porque ele salvará o seu povo dos seus pecados.

[[v40-1-22]]

^<<v40-1-22,22>>^ Tudo isso aconteceu para que se cumprisse o que foi dito da parte do Senhor pelo profeta, que diz:

[[v40-1-23]]

^<<v40-1-23,23>>^ Eis que a virgem conceberá e dará à luz um  filho, e ele será chamado pelo nome de Emanuel . ( Emanuel  traduzido é: Deus conosco).

[[v40-1-24]]

^<<v40-1-24,24>>^ E José, despertando do sonho, fez como o anjo do Senhor lhe ordenara, e recebeu a sua mulher,

[[v40-1-25]]

^<<v40-1-25,25>>^ e não a conheceu até que deu à luz seu filho, o primogênito; e pôs-lhe o nome de Jesus .

'''

xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[&#60; Capítulo Anterior] | <<v40-1-0,Topo>> | xref:040-mateus/040-mateus-002.adoc#v40-2-0[Próximo Capítulo &#62;]