include::./index.adoc[]

[[v3-15-0]]
=== Levítico, 15
// arc ?, ARC - Almeida Revista e Corrigida

[[v3-15-1]]

^<<v3-15-1,1>>^ Falou mais o SENHOR a Moisés e a Arão, dizendo:

[[v3-15-2]]

^<<v3-15-2,2>>^ Falai aos filhos de Israel e dizei-lhes: Qualquer homem que tiver fluxo de sua carne será imundo por causa do  seu fluxo.

[[v3-15-3]]

^<<v3-15-3,3>>^ Esta, pois, será a sua imundícia por causa do seu fluxo: se a sua carne vaza o seu fluxo ou se a sua carne estanca o seu fluxo, esta é a sua imundícia.

[[v3-15-4]]

^<<v3-15-4,4>>^ Toda cama em que se deitar o que tiver fluxo será imunda; e toda coisa sobre o que se assentar será imunda.

[[v3-15-5]]

^<<v3-15-5,5>>^ E qualquer que tocar a sua cama lavará as suas vestes, e se banhará em água, e será imundo até à tarde.

[[v3-15-6]]

^<<v3-15-6,6>>^ E aquele que se assentar sobre aquilo em que se assentou o que tem o fluxo lavará as suas vestes, e se banhará em água, e será imundo até à tarde.

[[v3-15-7]]

^<<v3-15-7,7>>^ E aquele que tocar a carne do que tem o fluxo lavará as suas vestes, e se banhará em água, e será imundo até à tarde.

[[v3-15-8]]

^<<v3-15-8,8>>^ Quando também o que tem o fluxo cuspir sobre um limpo, então, lavará este as suas vestes, e se banhará em água, e será imundo até à tarde.

[[v3-15-9]]

^<<v3-15-9,9>>^ Também toda sela em que cavalgar o que tem o fluxo será imunda.

[[v3-15-10]]

^<<v3-15-10,10>>^ E qualquer que tocar em alguma coisa que estiver debaixo dele será imundo até à tarde; e aquele que a levar lavará as suas vestes, e se banhará em água, e será imundo até à tarde.

[[v3-15-11]]

^<<v3-15-11,11>>^ Também todo aquele em quem tocar o que tem o fluxo, sem haver lavado as suas mãos com água, lavará as suas vestes, e se banhará em água, e será imundo até à tarde.

[[v3-15-12]]

^<<v3-15-12,12>>^ E o vaso de barro em que tocar o que tem o fluxo será quebrado; porém todo vaso de madeira será lavado com água.

[[v3-15-13]]

^<<v3-15-13,13>>^ Quando, pois, o que tem o fluxo estiver limpo do seu fluxo, contar-se-ão sete dias para a sua purificação; e lavará as suas vestes, e banhará a sua carne em águas vivas, e será limpo.

[[v3-15-14]]

^<<v3-15-14,14>>^ E, ao dia oitavo, tomará duas rolas ou dois pombinhos, e virá perante o SENHOR, à porta da tenda da congregação, e os dará ao sacerdote.

[[v3-15-15]]

^<<v3-15-15,15>>^ E o sacerdote oferecerá um para  expiação do pecado e o outro, para  holocausto; e, assim,  o sacerdote fará por ele expiação do seu fluxo perante o SENHOR.

[[v3-15-16]]

^<<v3-15-16,16>>^ Também o homem, quando sair dele a semente da cópula, toda a sua carne banhará com água e será imundo até à tarde.

[[v3-15-17]]

^<<v3-15-17,17>>^ Também toda veste e toda pele em que houver semente da cópula se lavarão com água e serão imundas até à tarde.

[[v3-15-18]]

^<<v3-15-18,18>>^ E também a mulher com quem homem se deitar com semente da cópula, ambos se banharão com água e serão imundos até à tarde.

[[v3-15-19]]

^<<v3-15-19,19>>^ Mas a mulher, quando tiver fluxo, e o seu fluxo de sangue estiver na sua carne, estará sete dias na sua separação, e qualquer que a tocar será imundo até à tarde.

[[v3-15-20]]

^<<v3-15-20,20>>^ E tudo aquilo sobre o que ela se deitar durante a sua separação será imundo; e tudo sobre o que se assentar será imundo.

[[v3-15-21]]

^<<v3-15-21,21>>^ E qualquer que tocar a sua cama lavará as suas vestes, e se banhará com água, e será imundo até à tarde.

[[v3-15-22]]

^<<v3-15-22,22>>^ E qualquer que tocar alguma coisa sobre o que ela se tiver assentado lavará as suas vestes, e se banhará com água, e será imundo até à tarde.

[[v3-15-23]]

^<<v3-15-23,23>>^ Se também alguma coisa estiver  sobre a cama ou sobre aquilo em que ela se assentou, se alguém a tocar, será imundo até à tarde.

[[v3-15-24]]

^<<v3-15-24,24>>^ E, se, com efeito, qualquer homem se deitar com ela, e a sua imundícia estiver sobre ele, imundo será por sete dias; também toda cama sobre que se deitar será imunda.

[[v3-15-25]]

^<<v3-15-25,25>>^ Também a mulher, quando manar o fluxo do seu sangue, por muitos dias fora do tempo da sua separação ou quando tiver fluxo de sangue por mais tempo do que a sua separação, todos os dias do fluxo da sua imundícia será imunda, como nos dias da sua separação.

[[v3-15-26]]

^<<v3-15-26,26>>^ Toda cama sobre que se deitar todos os dias do seu fluxo ser-lhe-á como a cama da sua separação; e toda coisa sobre que se assentar será imunda, conforme a imundícia da sua separação.

[[v3-15-27]]

^<<v3-15-27,27>>^ E qualquer que as tocar será imundo; portanto, lavará as suas vestes, e se banhará com água, e será imundo até à tarde.

[[v3-15-28]]

^<<v3-15-28,28>>^ Porém, quando for limpa do seu fluxo, então, se contarão sete dias, e depois será limpa.

[[v3-15-29]]

^<<v3-15-29,29>>^ E, ao oitavo dia, tomará duas rolas ou dois pombinhos e os trará ao sacerdote, à porta da tenda da congregação.

[[v3-15-30]]

^<<v3-15-30,30>>^ Então, o sacerdote oferecerá um para  expiação do pecado e o outro, para  holocausto; e o sacerdote fará por ela expiação do fluxo da sua imundícia, perante o SENHOR.

[[v3-15-31]]

^<<v3-15-31,31>>^ Assim, separareis os filhos de Israel das suas imundícias, para que não morram nas suas imundícias, contaminando o meu tabernáculo, que está no meio deles.

[[v3-15-32]]

^<<v3-15-32,32>>^ Esta é  a lei daquele que tem o fluxo e daquele  de quem sai a semente da cópula e que fica por ela  imundo;

[[v3-15-33]]

^<<v3-15-33,33>>^ como também da mulher enferma na sua separação, e daquele que padece do seu fluxo, seja  varão ou fêmea, e do homem que se deita com mulher  imunda.

'''

xref:003-levitico/003-levitico-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-levitico/003-levitico-016.adoc#v3-16-0[Próximo Capítulo &#62;]