include::./index.adoc[]

[[v3-9-0]]
=== Levítico, 9
// arc ?, ARC - Almeida Revista e Corrigida

[[v3-9-1]]

^<<v3-9-1,1>>^ E aconteceu, ao dia oitavo, que  Moisés chamou a Arão, e a seus filhos, e aos anciãos de Israel

[[v3-9-2]]

^<<v3-9-2,2>>^ e disse a Arão: Toma um bezerro, para expiação do  pecado, e um carneiro, para holocausto, sem mancha, e traze- os  perante o SENHOR.

[[v3-9-3]]

^<<v3-9-3,3>>^ Depois, falarás aos filhos de Israel, dizendo: Tomai um bode, para expiação do  pecado, e um bezerro e um cordeiro de um ano, sem mancha, para holocausto;

[[v3-9-4]]

^<<v3-9-4,4>>^ também um boi e um carneiro, por sacrifício  pacífico, para sacrificar perante o SENHOR, e oferta de manjares, amassada com azeite; porquanto hoje o SENHOR vos aparecerá.

[[v3-9-5]]

^<<v3-9-5,5>>^ Então, trouxeram o que ordenara Moisés, diante da tenda da congregação, e chegou-se toda a congregação e se pôs perante o SENHOR.

[[v3-9-6]]

^<<v3-9-6,6>>^ E disse Moisés: Esta coisa que o SENHOR ordenou fareis; e a glória do SENHOR vos aparecerá.

[[v3-9-7]]

^<<v3-9-7,7>>^ E disse Moisés a Arão: Chega-te ao altar e faze a tua expiação de pecado e o teu holocausto; e faze expiação por ti e pelo povo; depois, faze a oferta do povo e faze expiação por ele, como ordenou o SENHOR.

[[v3-9-8]]

^<<v3-9-8,8>>^ Então, Arão se chegou ao altar e degolou o bezerro da expiação que era  por si mesmo.

[[v3-9-9]]

^<<v3-9-9,9>>^ E os filhos de Arão trouxeram-lhe o sangue; e molhou o dedo no sangue e o  pôs sobre as pontas do altar; e o resto do  sangue derramou à base do altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ Mas a gordura, e os rins, e o redenho do fígado de expiação do pecado queimou sobre o altar, como o SENHOR ordenara a Moisés.

[[v3-9-11]]

^<<v3-9-11,11>>^ Porém a carne e o couro queimou com fogo fora do arraial.

[[v3-9-12]]

^<<v3-9-12,12>>^ Depois, degolou o holocausto, e os filhos de Arão lhe entregaram o sangue, e ele espargiu-o sobre o altar em redor.

[[v3-9-13]]

^<<v3-9-13,13>>^ Também lhe entregaram o holocausto nos seus pedaços, com a cabeça; e queimou-o sobre o altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ E lavou a fressura e as pernas e as queimou sobre o holocausto no altar.

[[v3-9-15]]

^<<v3-9-15,15>>^ Depois, fez chegar a oferta do povo, e tomou o bode da expiação do pecado, que era  pelo povo, e o degolou, e o preparou por expiação do pecado, como o primeiro.

[[v3-9-16]]

^<<v3-9-16,16>>^ Fez também chegar o holocausto e o preparou segundo o rito.

[[v3-9-17]]

^<<v3-9-17,17>>^ E fez chegar a oferta de manjares, e a sua mão encheu dela, e a queimou sobre o altar, além do holocausto da manhã.

[[v3-9-18]]

^<<v3-9-18,18>>^ Depois, degolou o boi e o carneiro em sacrifício pacífico, que era  pelo povo; e os filhos de Arão entregaram-lhe o sangue, que espargiu sobre o altar, em redor,

[[v3-9-19]]

^<<v3-9-19,19>>^ como também a gordura do boi e do carneiro, e a cauda, e o que cobre a fressura,  e os rins, e o redenho do fígado.

[[v3-9-20]]

^<<v3-9-20,20>>^ E puseram a gordura sobre o peito, e ele queimou a gordura sobre o altar;

[[v3-9-21]]

^<<v3-9-21,21>>^ mas o peito e a espádua direita Arão moveu por oferta de  movimento perante o SENHOR, como Moisés tinha ordenado.

[[v3-9-22]]

^<<v3-9-22,22>>^ Depois, Arão levantou as mãos ao povo e o abençoou; e desceu, havendo feito a expiação do pecado, e o holocausto, e a oferta pacífica.

[[v3-9-23]]

^<<v3-9-23,23>>^ Então, entraram Moisés e Arão na tenda da congregação; depois, saíram e abençoaram o povo; e a glória do SENHOR apareceu a todo o povo.

[[v3-9-24]]

^<<v3-9-24,24>>^ Porque o fogo saiu de diante do SENHOR e consumiu o holocausto e a gordura sobre o altar; o que vendo todo o povo, jubilou e caiu sobre as suas faces.

'''

xref:003-levitico/003-levitico-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-levitico/003-levitico-010.adoc#v3-10-0[Próximo Capítulo &#62;]