include::./index.adoc[]

[[v3-22-0]]
=== Levítico, 22
// arc ?, ARC - Almeida Revista e Corrigida

[[v3-22-1]]

^<<v3-22-1,1>>^ Depois, falou o SENHOR a Moisés, dizendo:

[[v3-22-2]]

^<<v3-22-2,2>>^ Dize a Arão e a seus filhos que se apartem das coisas santas dos filhos de Israel, que a mim me santificam, para que não profanem o nome da minha santidade. Eu sou  o SENHOR.

[[v3-22-3]]

^<<v3-22-3,3>>^ Dize-lhes: Todo homem, que entre as vossas gerações, de toda a vossa semente, se chegar às coisas santas que os filhos de Israel santificam ao SENHOR, tendo sobre si a sua imundícia, aquela alma será extirpada de diante da minha face. Eu sou  o SENHOR.

[[v3-22-4]]

^<<v3-22-4,4>>^ Ninguém da semente de Arão que for leproso ou tiver fluxo comerá das coisas santas, até que seja limpo; como também o que tocar alguma coisa imunda de cadáver ou aquele de que sair a semente da cópula;

[[v3-22-5]]

^<<v3-22-5,5>>^ ou qualquer que tocar a algum réptil, pelo que se fez imundo, ou a algum homem, pelo que se fez imundo, segundo toda a sua imundícia.

[[v3-22-6]]

^<<v3-22-6,6>>^ O homem que o tocar será imundo até à tarde e não comerá das coisas santas, mas banhará a sua carne em água.

[[v3-22-7]]

^<<v3-22-7,7>>^ E, havendo-se o sol já posto, então, será limpo e depois comerá das coisas santas; porque este é o seu pão.

[[v3-22-8]]

^<<v3-22-8,8>>^ O corpo morto e o dilacerado não comerá, para nele se não contaminar. Eu sou  o SENHOR.

[[v3-22-9]]

^<<v3-22-9,9>>^ Guardarão, pois, o meu mandamento, para que por isso não levem pecado e morram nele, havendo-o profanado. Eu sou  o Senhor que  os santifico.

[[v3-22-10]]

^<<v3-22-10,10>>^ Também nenhum estranho comerá das coisas santas; nem o hóspede do sacerdote, nem o jornaleiro comerão das coisas santas.

[[v3-22-11]]

^<<v3-22-11,11>>^ Mas, quando o sacerdote comprar alguma alma com o seu dinheiro, aquela comerá delas e o nascido na sua casa; estes comerão do seu pão.

[[v3-22-12]]

^<<v3-22-12,12>>^ E, quando a filha do sacerdote se casar  com homem estranho, ela não comerá da oferta movida das coisas santas.

[[v3-22-13]]

^<<v3-22-13,13>>^ Mas, quando a filha do sacerdote for viúva ou repudiada, e não tiver semente, e se houver tornado à casa de seu pai, como na sua mocidade, do pão de seu pai comerá; mas nenhum estranho comerá dele.

[[v3-22-14]]

^<<v3-22-14,14>>^ E, quando alguém, por erro, comer a coisa santa, sobre ela acrescentará seu quinto e o  dará ao sacerdote com a coisa santa.

[[v3-22-15]]

^<<v3-22-15,15>>^ Assim, não profanarão as coisas santas dos filhos de Israel, que oferecem ao SENHOR,

[[v3-22-16]]

^<<v3-22-16,16>>^ nem os farão levar a iniquidade da culpa, comendo as suas coisas santas; pois eu sou  o SENHOR que os santifico.

[[v3-22-17]]

^<<v3-22-17,17>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v3-22-18]]

^<<v3-22-18,18>>^ Fala a Arão, e a seus filhos, e a todos os filhos de Israel e dize-lhes: Qualquer que, da casa de Israel ou dos estrangeiros em Israel, oferecer a sua oferta, quer dos seus votos, quer das suas ofertas voluntárias, que oferecerem ao SENHOR em holocausto,

[[v3-22-19]]

^<<v3-22-19,19>>^ segundo a sua vontade, oferecerá macho sem mancha, das vacas, dos cordeiros ou das cabras.

[[v3-22-20]]

^<<v3-22-20,20>>^ Nenhuma coisa em que haja defeito oferecereis, porque não seria aceita a vosso favor.

[[v3-22-21]]

^<<v3-22-21,21>>^ E, quando alguém oferecer sacrifício pacífico ao SENHOR, separando das vacas ou das ovelhas um voto ou oferta voluntária, sem mancha será, para que seja aceito; nenhum defeito haverá nele.

[[v3-22-22]]

^<<v3-22-22,22>>^ O cego, ou quebrado, ou aleijado, ou verrugoso, ou sarnoso, ou cheio de impigens, este não oferecereis ao SENHOR e deles não poreis oferta queimada ao SENHOR sobre o altar.

[[v3-22-23]]

^<<v3-22-23,23>>^ Porém boi ou gado miúdo, comprido ou curto de membros, poderás oferecer por  oferta voluntária, mas por voto não será aceito.

[[v3-22-24]]

^<<v3-22-24,24>>^ O machucado, ou moído, ou despedaçado, ou cortado não oferecereis ao SENHOR; não fareis isto na vossa terra.

[[v3-22-25]]

^<<v3-22-25,25>>^ Também da mão do estrangeiro nenhum manjar oferecereis ao vosso Deus, de todas estas coisas, pois a sua corrupção está nelas; falta nelas há; não serão aceitas a vosso favor.

[[v3-22-26]]

^<<v3-22-26,26>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v3-22-27]]

^<<v3-22-27,27>>^ Quando nascer o boi, ou cordeiro, ou cabra, sete dias estará debaixo de sua mãe; depois, desde o dia oitavo em diante, será aceito por oferta queimada ao SENHOR.

[[v3-22-28]]

^<<v3-22-28,28>>^ Também boi ou gado miúdo, a ele e a seu filho não degolareis num dia.

[[v3-22-29]]

^<<v3-22-29,29>>^ E, quando sacrificardes sacrifício de louvores ao SENHOR, o sacrificareis de vossa vontade.

[[v3-22-30]]

^<<v3-22-30,30>>^ No mesmo dia se comerá; nada deixareis ficar até à manhã. Eu sou  o SENHOR.

[[v3-22-31]]

^<<v3-22-31,31>>^ Pelo que guardareis os meus mandamentos e os fareis. Eu sou  o SENHOR.

[[v3-22-32]]

^<<v3-22-32,32>>^ E não profanareis o meu santo nome, para que eu seja santificado no meio dos filhos de Israel. Eu sou  o SENHOR que vos santifico,

[[v3-22-33]]

^<<v3-22-33,33>>^ que vos tirei da terra do Egito, para vos ser por Deus. Eu sou  o SENHOR.

'''

xref:003-levitico/003-levitico-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-levitico/003-levitico-023.adoc#v3-23-0[Próximo Capítulo &#62;]