include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// arc ?, ARC - Almeida Revista e Corrigida

[[v3-11-1]]

^<<v3-11-1,1>>^ E falou o SENHOR a Moisés e a Arão, dizendo-lhes:

[[v3-11-2]]

^<<v3-11-2,2>>^ Falai aos filhos de Israel, dizendo: Estes são  os animais que comereis de todos os animais que há sobre a terra:

[[v3-11-3]]

^<<v3-11-3,3>>^ tudo o que tem unhas fendidas, e a fenda das unhas se divide em duas, e  remói, entre os animais, aquilo comereis.

[[v3-11-4]]

^<<v3-11-4,4>>^ Destes, porém, não comereis: dos que remoem ou dos que têm unhas fendidas: o camelo, que remói, mas não tem unhas fendidas; este vos será  imundo;

[[v3-11-5]]

^<<v3-11-5,5>>^ o coelho, porque remói, mas não tem as unhas fendidas; este vos será  imundo;

[[v3-11-6]]

^<<v3-11-6,6>>^ a lebre, porque remói, mas não tem as unhas fendidas; esta vos será  imunda.

[[v3-11-7]]

^<<v3-11-7,7>>^ Também o porco, porque tem unhas fendidas, e a fenda das unhas se divide em duas, mas não remói; este vos será  imundo;

[[v3-11-8]]

^<<v3-11-8,8>>^ da sua carne não comereis, nem tocareis no seu cadáver. Estes vos serão  imundos.

[[v3-11-9]]

^<<v3-11-9,9>>^ Isto comereis de tudo o que há nas águas: tudo o que tem barbatanas e escamas nas águas, nos mares e nos rios; aquilo comereis.

[[v3-11-10]]

^<<v3-11-10,10>>^ Mas tudo o que não tem barbatanas nem escamas, nos mares e nos rios, todo réptil das águas e toda alma vivente que há nas águas, estes serão  para vós abominação.

[[v3-11-11]]

^<<v3-11-11,11>>^ Ser-vos-ão, pois, por abominação; da sua carne não comereis e abominareis o seu cadáver.

[[v3-11-12]]

^<<v3-11-12,12>>^ Tudo o que não tem barbatanas ou escamas, nas águas, será  para vós abominação.

[[v3-11-13]]

^<<v3-11-13,13>>^ E, das aves, estas abominareis; não se comerão, serão  abominação: a águia, e o quebrantosso, e o xofrango,

[[v3-11-14]]

^<<v3-11-14,14>>^ e o milhano, e o abutre segundo a sua espécie,

[[v3-11-15]]

^<<v3-11-15,15>>^ todo corvo segundo a sua espécie,

[[v3-11-16]]

^<<v3-11-16,16>>^ e o avestruz, e o mocho, e o cuco, e o gavião segundo a sua espécie,

[[v3-11-17]]

^<<v3-11-17,17>>^ e o bufo, e o corvo-marinho, e a coruja,

[[v3-11-18]]

^<<v3-11-18,18>>^ e a gralha, e o cisne, e o pelicano,

[[v3-11-19]]

^<<v3-11-19,19>>^ e a cegonha, e a garça segundo a sua espécie, e a poupa, e o morcego.

[[v3-11-20]]

^<<v3-11-20,20>>^ Todo réptil que voa, que anda sobre quatro pés, será  para vós uma abominação.

[[v3-11-21]]

^<<v3-11-21,21>>^ Mas isto comereis de todo o réptil que voa, que anda sobre quatro pés:  o que tiver pernas sobre os seus pés, para saltar com elas sobre a terra.

[[v3-11-22]]

^<<v3-11-22,22>>^ Deles comereis estes: a locusta segundo a sua espécie, e o gafanhoto devorador segundo a sua espécie, e o grilo segundo a sua espécie, e o gafanhoto segundo a sua espécie.

[[v3-11-23]]

^<<v3-11-23,23>>^ E todo réptil que voa, que tem quatro pés, será  para vós uma abominação.

[[v3-11-24]]

^<<v3-11-24,24>>^ E por estes sereis imundos: qualquer que tocar o seu cadáver imundo será até à tarde.

[[v3-11-25]]

^<<v3-11-25,25>>^ Qualquer que levar os seus cadáveres lavará as suas vestes e será imundo até à tarde.

[[v3-11-26]]

^<<v3-11-26,26>>^ Todo animal que tem unhas fendidas, mas a fenda não se divide em duas e que não remói vos será  por imundo; qualquer que tocar neles será imundo.

[[v3-11-27]]

^<<v3-11-27,27>>^ E tudo o que anda sobre as suas patas, isto é,  todo animal que anda a quatro pés,  vos será  por imundo; qualquer que tocar no seu cadáver será imundo até à tarde.

[[v3-11-28]]

^<<v3-11-28,28>>^ E o que levar o seu cadáver lavará as suas vestes e será imundo até à tarde; eles vos serão  por imundos.

[[v3-11-29]]

^<<v3-11-29,29>>^ Estes também vos serão  por imundos entre os répteis que se arrastam sobre a terra: a doninha, e o rato, e o cágado segundo a sua espécie,

[[v3-11-30]]

^<<v3-11-30,30>>^ e o ouriço cacheiro, e o lagarto, e a lagartixa, e a lesma, e a toupeira.

[[v3-11-31]]

^<<v3-11-31,31>>^ Estes vos serão  por imundos entre todo o réptil; qualquer que os tocar, estando eles mortos, será imundo até à tarde.

[[v3-11-32]]

^<<v3-11-32,32>>^ E tudo aquilo sobre o que deles cair alguma coisa,  estando eles mortos, será imundo; seja vaso de madeira, ou veste, ou pele, ou saco, ou qualquer instrumento com que se faz alguma  obra, será metido na água e será imundo até à tarde; depois, será limpo.

[[v3-11-33]]

^<<v3-11-33,33>>^ E todo vaso de barro, em que cair alguma coisa  deles, tudo o que houver nele será imundo; e o vaso  quebrareis.

[[v3-11-34]]

^<<v3-11-34,34>>^ Todo manjar que se come, sobre o que vier tal água, será imundo; e toda bebida que se bebe, em todo vaso, será imunda.

[[v3-11-35]]

^<<v3-11-35,35>>^ E aquilo sobre o que cair alguma coisa de seu corpo morto será imundo: o forno e o vaso de barro serão quebrados; imundos são;  portanto, vos serão por imundos.

[[v3-11-36]]

^<<v3-11-36,36>>^ Porém a fonte ou cisterna, em que se  recolhem águas, será limpa, mas quem tocar no seu cadáver será imundo.

[[v3-11-37]]

^<<v3-11-37,37>>^ E, se do seu cadáver cair alguma coisa  sobre alguma  semente de semear, esta será  limpa;

[[v3-11-38]]

^<<v3-11-38,38>>^ mas, se for deitada água sobre a semente, e, se do cadáver cair alguma coisa  sobre ela, vos será  por imunda.

[[v3-11-39]]

^<<v3-11-39,39>>^ E, se morrer algum  dos animais, que vos servem  de mantimento, quem tocar no seu cadáver será imundo até à tarde;

[[v3-11-40]]

^<<v3-11-40,40>>^ quem comer do seu cadáver lavará as suas vestes e será imundo até à tarde; e quem levar o seu corpo morto lavará as suas vestes e será imundo até à tarde.

[[v3-11-41]]

^<<v3-11-41,41>>^ Também todo réptil que se arrasta sobre a terra será  abominação; não se comerá.

[[v3-11-42]]

^<<v3-11-42,42>>^ Tudo o que anda sobre o ventre, e tudo o que anda sobre quatro pés,  ou que tem mais pés, entre todo o réptil que se arrasta sobre a terra, não comereis, porquanto são  uma abominação.

[[v3-11-43]]

^<<v3-11-43,43>>^ Não façais a vossa alma abominável por nenhum réptil que se arrasta, nem neles vos contamineis, para não serdes imundos por eles.

[[v3-11-44]]

^<<v3-11-44,44>>^ Porque eu sou  o SENHOR, vosso Deus; portanto, vós vos santificareis e sereis santos, porque eu sou  santo; e não contaminareis a vossa alma por nenhum réptil que se arrasta sobre a terra.

[[v3-11-45]]

^<<v3-11-45,45>>^ Porque eu sou  o SENHOR, que vos faço subir da terra do Egito, para que eu seja vosso Deus, e para que sejais santos; porque eu sou  santo.

[[v3-11-46]]

^<<v3-11-46,46>>^ Esta é a lei dos animais, e das aves, e de toda alma vivente que se move nas águas, e de toda alma que se arrasta sobre a terra,

[[v3-11-47]]

^<<v3-11-47,47>>^ para fazer diferença entre o imundo e o limpo, e entre os animais que se podem comer e os animais que não se podem comer.

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]