include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// arc ?, ARC - Almeida Revista e Corrigida

[[v3-27-1]]

^<<v3-27-1,1>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v3-27-2]]

^<<v3-27-2,2>>^ Fala aos filhos de Israel e dize-lhes: Quando alguém fizer particular voto, segundo a tua avaliação serão  as pessoas ao SENHOR.

[[v3-27-3]]

^<<v3-27-3,3>>^ Se for a tua avaliação dum varão, da idade de vinte anos até à idade de sessenta, será a tua avaliação de cinquenta siclos de prata, segundo o siclo do santuário.

[[v3-27-4]]

^<<v3-27-4,4>>^ Porém, se for fêmea, a tua avaliação será de trinta siclos.

[[v3-27-5]]

^<<v3-27-5,5>>^ E, se for  de cinco anos até vinte, a tua avaliação dum varão será de vinte siclos, e a da fêmea, de dez siclos.

[[v3-27-6]]

^<<v3-27-6,6>>^ E, se for  de um mês até cinco anos, a tua avaliação dum varão será de cinco siclos de prata, e a tua avaliação da fêmea será  de três siclos de prata.

[[v3-27-7]]

^<<v3-27-7,7>>^ E, se for  de sessenta anos e acima, do varão a tua avaliação será de quinze siclos, e a da fêmea, de dez siclos.

[[v3-27-8]]

^<<v3-27-8,8>>^ Mas, se for  mais pobre do que a tua avaliação, então, apresentar-se-á diante do sacerdote, para que o sacerdote o avalie; conforme o que alcançar a mão do que fez o voto, o avaliará o sacerdote.

[[v3-27-9]]

^<<v3-27-9,9>>^ E, se for  animal de que se oferece oferta ao SENHOR, tudo quanto der dele ao SENHOR será santo.

[[v3-27-10]]

^<<v3-27-10,10>>^ Não o mudará, nem o trocará bom por mau ou mau por bom; se, porém, em alguma maneira trocar animal por animal, o tal e o trocado serão ambos  santos.

[[v3-27-11]]

^<<v3-27-11,11>>^ E, se for  algum animal imundo, dos que se não oferecem em oferta ao SENHOR, então, apresentará o animal diante do sacerdote.

[[v3-27-12]]

^<<v3-27-12,12>>^ E o sacerdote o avaliará, seja bom ou seja mau; segundo a avaliação do sacerdote, assim será.

[[v3-27-13]]

^<<v3-27-13,13>>^ Porém, se em alguma maneira o resgatar, então, acrescentará o seu quinto além da tua avaliação.

[[v3-27-14]]

^<<v3-27-14,14>>^ E, quando algum santificar a sua casa para ser  santa ao SENHOR, o sacerdote a avaliará, seja boa, seja má; como o sacerdote a avaliar, assim será.

[[v3-27-15]]

^<<v3-27-15,15>>^ Mas, se o que santificou resgatar a sua casa, então, acrescentará o quinto a mais do dinheiro da tua avaliação, e será sua.

[[v3-27-16]]

^<<v3-27-16,16>>^ Se também alguém santificar ao SENHOR uma parte do campo da sua possessão, então, a tua avaliação será segundo a sua semente: um gômer de semente de cevada será avaliado  por cinquenta siclos de prata.

[[v3-27-17]]

^<<v3-27-17,17>>^ Se santificar o seu campo desde o Ano do Jubileu, conforme a tua avaliação ficará.

[[v3-27-18]]

^<<v3-27-18,18>>^ Mas, se santificar o seu campo depois do Ano do Jubileu, então, o sacerdote lhe contará o dinheiro conforme os anos restantes até ao Ano do Jubileu, e isto  se abaterá da tua avaliação.

[[v3-27-19]]

^<<v3-27-19,19>>^ E, se aquele que santificou o campo de alguma maneira o resgatar, então, acrescentará o quinto a mais do dinheiro da tua avaliação, e ficará seu.

[[v3-27-20]]

^<<v3-27-20,20>>^ E, se não resgatar o campo ou se vender o campo a outro homem, nunca mais se resgatará.

[[v3-27-21]]

^<<v3-27-21,21>>^ Porém, havendo o campo saído no Ano do  Jubileu, será santo ao SENHOR, como campo consagrado; a possessão dele será do sacerdote.

[[v3-27-22]]

^<<v3-27-22,22>>^ E, se santificar ao SENHOR o campo que comprou, e não for  do campo da sua possessão,

[[v3-27-23]]

^<<v3-27-23,23>>^ então, o sacerdote lhe contará a soma da tua avaliação até ao Ano do Jubileu; e, no mesmo dia, dará a tua avaliação por santidade ao SENHOR.

[[v3-27-24]]

^<<v3-27-24,24>>^ No Ano do Jubileu, o campo tornará àquele de quem o comprou, àquele de quem era a possessão do campo.

[[v3-27-25]]

^<<v3-27-25,25>>^ E toda a tua avaliação se fará conforme o siclo do santuário; o siclo será de vinte geras.

[[v3-27-26]]

^<<v3-27-26,26>>^ Mas o primogênito de um animal, por já ser do SENHOR, ninguém o santificará; seja boi ou gado miúdo, do SENHOR é.

[[v3-27-27]]

^<<v3-27-27,27>>^ Mas, se for  de um animal imundo, o resgatará, segundo a tua estimação, e sobre ele acrescentará o seu quinto; e, se não se resgatar, vender-se-á segundo a tua estimação.

[[v3-27-28]]

^<<v3-27-28,28>>^ Todavia, nenhuma coisa consagrada que alguém consagrar ao SENHOR de tudo o que tem, de homem, ou de animal, ou do campo da sua possessão, se venderá nem resgatará; toda coisa consagrada será uma coisa santíssima ao SENHOR.

[[v3-27-29]]

^<<v3-27-29,29>>^ Toda coisa consagrada que for consagrada do homem não será resgatada; certamente morrerá.

[[v3-27-30]]

^<<v3-27-30,30>>^ Também todas as dízimas do campo, da semente do campo, do fruto das árvores são do SENHOR; santas são  ao SENHOR.

[[v3-27-31]]

^<<v3-27-31,31>>^ Porém, se alguém das suas dízimas resgatar alguma coisa,  acrescentará o seu quinto sobre ela.

[[v3-27-32]]

^<<v3-27-32,32>>^ No tocante a todas as dízimas de vacas e ovelhas, de tudo o que passar debaixo da vara, o dízimo será santo ao SENHOR.

[[v3-27-33]]

^<<v3-27-33,33>>^ Não esquadrinhará entre o bom e o mau, nem o trocará; mas, se em alguma maneira o trocar, o tal e o trocado serão santos; não serão resgatados.

[[v3-27-34]]

^<<v3-27-34,34>>^ Estes são  os mandamentos que o SENHOR ordenou a Moisés, para os filhos de Israel, no monte Sinai.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]