include::./index.adoc[]

[[v41-10-0]]
=== Marcos, 10
// arc ?, ARC - Almeida Revista e Corrigida

[[v41-10-1]]

^<<v41-10-1,1>>^ E, levantando-se dali, foi para o território da Judeia, além do Jordão, e a multidão se reuniu em torno dele; e tornou a ensiná-los, como tinha por costume.

[[v41-10-2]]

^<<v41-10-2,2>>^ E, aproximando-se dele  os fariseus, perguntaram-lhe, tentando-o: É lícito ao homem repudiar sua  mulher?

[[v41-10-3]]

^<<v41-10-3,3>>^ Mas ele, respondendo, disse-lhes: Que vos mandou Moisés?

[[v41-10-4]]

^<<v41-10-4,4>>^ E eles disseram: Moisés permitiu escrever carta de divórcio e repudiar.

[[v41-10-5]]

^<<v41-10-5,5>>^ E Jesus, respondendo, disse-lhes: Pela dureza do vosso coração vos deixou ele escrito esse mandamento;

[[v41-10-6]]

^<<v41-10-6,6>>^ porém, desde o princípio da criação, Deus os fez macho e fêmea.

[[v41-10-7]]

^<<v41-10-7,7>>^ Por isso, deixará o homem a seu pai e a sua mãe e unir-se-á a sua mulher.

[[v41-10-8]]

^<<v41-10-8,8>>^ E serão os dois uma só carne e, assim, já  não serão dois, mas uma só carne.

[[v41-10-9]]

^<<v41-10-9,9>>^ Portanto, o que Deus ajuntou, não o separe o homem.

[[v41-10-10]]

^<<v41-10-10,10>>^ E em casa tornaram os discípulos a interrogá-lo acerca disso mesmo.

[[v41-10-11]]

^<<v41-10-11,11>>^ E ele lhes disse: Qualquer que deixar a sua mulher e casar com outra adultera contra ela.

[[v41-10-12]]

^<<v41-10-12,12>>^ E, se a mulher deixar a seu marido e casar com outro, adultera.

[[v41-10-13]]

^<<v41-10-13,13>>^ E traziam-lhe crianças para que lhes tocasse, mas os discípulos repreendiam aos que lhas  traziam.

[[v41-10-14]]

^<<v41-10-14,14>>^ Jesus, porém, vendo isso,  indignou-se e disse-lhes: Deixai vir os pequeninos a mim e não os impeçais, porque dos tais é o Reino de Deus.

[[v41-10-15]]

^<<v41-10-15,15>>^ Em verdade vos digo que qualquer que não receber o Reino de Deus como uma criança de maneira nenhuma entrará nele.

[[v41-10-16]]

^<<v41-10-16,16>>^ E, tomando-as nos seus braços e impondo-lhes as mãos, as abençoou.

[[v41-10-17]]

^<<v41-10-17,17>>^ E, pondo-se a caminho, correu para ele um homem, o qual se ajoelhou diante dele e lhe perguntou: Bom Mestre, que farei para herdar a vida eterna?

[[v41-10-18]]

^<<v41-10-18,18>>^ E Jesus lhe disse: Por que me chamas bom? Ninguém há  bom senão um, que é  Deus.

[[v41-10-19]]

^<<v41-10-19,19>>^ Tu sabes os mandamentos: Não adulterarás; não matarás; não furtarás; não dirás falsos testemunhos; não defraudarás alguém; honra a teu pai e a tua  mãe.

[[v41-10-20]]

^<<v41-10-20,20>>^ Ele, porém, respondendo, lhe disse: Mestre, tudo isso guardei desde a minha mocidade.

[[v41-10-21]]

^<<v41-10-21,21>>^ E Jesus, olhando para ele, o amou e lhe disse: Falta-te uma coisa:  vai, e vende tudo quanto tens, e dá-o aos pobres, e terás um  tesouro no céu; e vem e segue-me.

[[v41-10-22]]

^<<v41-10-22,22>>^ Mas ele, contrariado com essa palavra, retirou-se triste, porque possuía muitas propriedades.

[[v41-10-23]]

^<<v41-10-23,23>>^ Então, Jesus, olhando ao redor, disse aos seus discípulos: Quão dificilmente entrarão no Reino de Deus os que têm riquezas!

[[v41-10-24]]

^<<v41-10-24,24>>^ E os discípulos se admiraram destas suas palavras; mas Jesus, tornando a falar, disse-lhes: Filhos, quão difícil é, para os que confiam nas riquezas, entrar no Reino de Deus!

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais fácil passar um camelo pelo fundo de uma agulha do que entrar um rico no Reino de Deus.

[[v41-10-26]]

^<<v41-10-26,26>>^ E eles se admiravam ainda mais, dizendo entre si: Quem poderá, pois, salvar-se?

[[v41-10-27]]

^<<v41-10-27,27>>^ Jesus, porém, olhando para eles, disse: Para os homens é  impossível, mas não para Deus, porque para Deus todas as coisas  são possíveis.

[[v41-10-28]]

^<<v41-10-28,28>>^ E Pedro começou a dizer-lhe: Eis que nós tudo deixamos e te seguimos.

[[v41-10-29]]

^<<v41-10-29,29>>^ E Jesus, respondendo, disse: Em verdade vos digo que ninguém há, que tenha deixado casa, ou  irmãos, ou irmãs, ou pai, ou mãe, ou mulher, ou filhos, ou campos, por amor de mim e do evangelho,

[[v41-10-30]]

^<<v41-10-30,30>>^ que não receba cem vezes tanto, já neste tempo, em casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições, e, no século futuro, a vida eterna.

[[v41-10-31]]

^<<v41-10-31,31>>^ Porém muitos primeiros serão derradeiros, e muitos  derradeiros serão primeiros.

[[v41-10-32]]

^<<v41-10-32,32>>^ E iam no caminho, subindo para Jerusalém; e Jesus ia adiante deles. E eles maravilhavam-se e seguiam-no atemorizados. E, tornando a tomar consigo  os doze, começou a dizer-lhes as coisas  que lhe deviam sobrevir,

[[v41-10-33]]

^<<v41-10-33,33>>^ dizendo: Eis que nós subimos a Jerusalém, e o Filho do Homem será entregue aos príncipes dos sacerdotes e aos escribas, e o condenarão à morte, e o entregarão aos gentios,

[[v41-10-34]]

^<<v41-10-34,34>>^ e o escarnecerão, e açoitarão, e cuspirão nele, e o matarão; mas, ao terceiro dia, ressuscitará.

[[v41-10-35]]

^<<v41-10-35,35>>^ E aproximaram-se dele Tiago e João, filhos de Zebedeu, dizendo: Mestre, queremos que nos faças o que pedirmos.

[[v41-10-36]]

^<<v41-10-36,36>>^ E ele lhes disse: Que quereis que vos faça?

[[v41-10-37]]

^<<v41-10-37,37>>^ E eles lhe disseram: Concede-nos que, na tua glória, nos assentemos, um à tua direita, e outro à tua esquerda.

[[v41-10-38]]

^<<v41-10-38,38>>^ Mas Jesus lhes disse: Não sabeis o que pedis; podeis vós beber o cálice que eu bebo e ser batizados com o batismo com que eu sou batizado?

[[v41-10-39]]

^<<v41-10-39,39>>^ E eles lhe disseram: Podemos. Jesus, porém, disse-lhes: Em verdade vós bebereis o cálice que eu beber e sereis batizados com o batismo com que eu sou batizado,

[[v41-10-40]]

^<<v41-10-40,40>>^ mas o assentar-se à minha direita ou à minha esquerda não me pertence a mim concedê-lo, mas isso é para aqueles a quem está reservado.

[[v41-10-41]]

^<<v41-10-41,41>>^ E os dez, tendo ouvido isso,  começaram a indignar-se contra Tiago e João.

[[v41-10-42]]

^<<v41-10-42,42>>^ Mas Jesus, chamando-os a si,  disse-lhes: Sabeis que os que julgam ser príncipes das gentes delas se assenhoreiam, e os seus grandes usam de autoridade sobre elas;

[[v41-10-43]]

^<<v41-10-43,43>>^ mas entre vós não será assim; antes, qualquer que, entre vós, quiser ser grande será vosso serviçal.

[[v41-10-44]]

^<<v41-10-44,44>>^ E qualquer que, dentre vós, quiser ser o primeiro será servo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.

[[v41-10-46]]

^<<v41-10-46,46>>^ Depois, foram para Jericó. E, saindo ele de Jericó com seus discípulos e uma grande multidão, Bartimeu, o cego, filho de Timeu, estava assentado junto ao caminho, mendigando.

[[v41-10-47]]

^<<v41-10-47,47>>^ E, ouvindo que era Jesus de Nazaré, começou a clamar e a dizer: Jesus, Filho de Davi, tem misericórdia de mim!

[[v41-10-48]]

^<<v41-10-48,48>>^ E muitos o repreendiam, para que se calasse; mas ele clamava cada vez mais: Filho de Davi, tem misericórdia de mim!

[[v41-10-49]]

^<<v41-10-49,49>>^ E Jesus, parando, disse que o chamassem; e chamaram o cego, dizendo-lhe: Tem bom ânimo; levanta-te, que  ele te chama.

[[v41-10-50]]

^<<v41-10-50,50>>^ E ele, lançando de si  a sua capa, levantou-se e foi ter com Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ E Jesus, falando, disse-lhe: Que queres que  te faça?  E o cego lhe disse: Mestre, que eu tenha vista.

[[v41-10-52]]

^<<v41-10-52,52>>^ E Jesus lhe disse: Vai, a tua fé te salvou.  E logo viu, e seguiu a Jesus pelo caminho.

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]