include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// arc ?, ARC - Almeida Revista e Corrigida

[[v47-8-1]]

^<<v47-8-1,1>>^ Também, irmãos, vos fazemos conhecer a graça de Deus dada às igrejas da Macedônia;

[[v47-8-2]]

^<<v47-8-2,2>>^ como, em muita prova de tribulação, houve abundância do seu gozo, e como a sua profunda pobreza superabundou em riquezas da sua generosidade.

[[v47-8-3]]

^<<v47-8-3,3>>^ Porque, segundo o seu  poder (o que eu mesmo  testifico) e ainda acima do seu  poder, deram  voluntariamente,

[[v47-8-4]]

^<<v47-8-4,4>>^ pedindo-nos com muitos rogos a graça e a comunicação deste serviço, que se fazia  para com os santos.

[[v47-8-5]]

^<<v47-8-5,5>>^ E não somente fizeram  como nós esperávamos, mas também a si mesmos se deram primeiramente ao Senhor e depois  a nós, pela vontade de Deus;

[[v47-8-6]]

^<<v47-8-6,6>>^ de maneira que exortamos a Tito que, assim como antes tinha começado, assim também acabe essa graça entre vós.

[[v47-8-7]]

^<<v47-8-7,7>>^ Portanto, assim como em tudo sois abundantes na fé, e na palavra, e na ciência, e em toda diligência, e em vosso amor para conosco, assim também abundeis nessa graça.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não digo isso como quem manda, mas para provar, pela diligência dos outros, a sinceridade do vosso amor;

[[v47-8-9]]

^<<v47-8-9,9>>^ porque já  sabeis a graça de nosso Senhor Jesus Cristo, que, sendo rico, por amor de vós se fez pobre, para que, pela sua pobreza, enriquecêsseis.

[[v47-8-10]]

^<<v47-8-10,10>>^ E nisso dou o meu  parecer; pois isso vos convém a vós, que desde o ano passado começastes; e não foi só praticar, mas também querer.

[[v47-8-11]]

^<<v47-8-11,11>>^ Agora, porém, completai também o já começado, para que, assim como houve a prontidão de vontade, haja também o cumprimento, segundo  o que tendes.

[[v47-8-12]]

^<<v47-8-12,12>>^ Porque, se há prontidão de vontade, será aceita segundo o que qualquer tem e  não segundo o que não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Mas não digo isso  para que os outros tenham alívio, e vós, opressão;

[[v47-8-14]]

^<<v47-8-14,14>>^ mas para  igualdade; neste tempo presente, a vossa abundância supra  a falta dos outros, para que também a sua abundância supra  a vossa falta, e haja igualdade,

[[v47-8-15]]

^<<v47-8-15,15>>^ como está escrito: O que muito colheu  não teve de mais; e o que pouco, não teve de menos.

[[v47-8-16]]

^<<v47-8-16,16>>^ Mas graças a Deus, que pôs a mesma solicitude por vós no coração de Tito;

[[v47-8-17]]

^<<v47-8-17,17>>^ pois ele aceitou a exortação e, muito diligente, partiu voluntariamente para vós.

[[v47-8-18]]

^<<v47-8-18,18>>^ E com ele enviamos aquele irmão cujo louvor no evangelho está espalhado  em todas as igrejas.

[[v47-8-19]]

^<<v47-8-19,19>>^ E não só isso,  mas foi também escolhido pelas igrejas para companheiro da nossa viagem, nessa graça que por nós é ministrada para glória do mesmo Senhor e prontidão do vosso ânimo;

[[v47-8-20]]

^<<v47-8-20,20>>^ evitando isto: que alguém nos vitupere por essa abundância, que por nós é ministrada;

[[v47-8-21]]

^<<v47-8-21,21>>^ pois zelamos o que é honesto, não só diante do Senhor, mas também diante dos homens.

[[v47-8-22]]

^<<v47-8-22,22>>^ Com eles, enviamos também outro  nosso irmão, o qual, muitas vezes e em muitas coisas,  já experimentamos ser diligente e agora muito mais diligente ainda pela muita confiança que em vós tem.

[[v47-8-23]]

^<<v47-8-23,23>>^ Quanto a Tito, é  meu companheiro e cooperador para convosco; quanto a nossos irmãos, são  embaixadores das igrejas e  glória de Cristo.

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, mostrai para com eles, perante a face das igrejas, a prova do vosso amor e da nossa glória acerca de vós.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]