include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v47-3-1]]

^<<v47-3-1,1>>^ Porventura, começamos outra vez a louvar-nos a nós mesmos? Ou necessitamos, como alguns, de cartas de recomendação para vós ou de recomendação de vós?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vós sois a nossa carta, escrita em nossos corações, conhecida e lida por todos os homens,

[[v47-3-3]]

^<<v47-3-3,3>>^ porque já  é manifesto que vós sois a carta de Cristo, ministrada por nós e escrita não com tinta, mas com o Espírito do Deus vivo, não em tábuas de pedra, mas nas tábuas de carne do coração.

[[v47-3-4]]

^<<v47-3-4,4>>^ E é por Cristo que temos tal confiança em Deus;

[[v47-3-5]]

^<<v47-3-5,5>>^ não que sejamos capazes, por nós, de pensar alguma coisa, como de nós mesmos; mas a nossa capacidade vem  de Deus,

[[v47-3-6]]

^<<v47-3-6,6>>^ o qual nos fez também capazes de ser  ministros dum Novo Testamento, não da letra, mas do Espírito; porque a letra mata, e o Espírito vivifica.

[[v47-3-7]]

^<<v47-3-7,7>>^ E, se o ministério da morte, gravado com letras em pedras, veio em glória, de maneira que os filhos de Israel não podiam fitar os olhos na face de Moisés, por causa da glória do seu rosto, a qual era transitória,

[[v47-3-8]]

^<<v47-3-8,8>>^ como não será de maior glória o ministério do Espírito?

[[v47-3-9]]

^<<v47-3-9,9>>^ Porque, se o ministério da condenação foi  glorioso, muito mais excederá em glória o ministério da justiça.

[[v47-3-10]]

^<<v47-3-10,10>>^ Porque também o que foi glorificado, nesta parte, não foi glorificado, por causa desta excelente glória.

[[v47-3-11]]

^<<v47-3-11,11>>^ Porque, se o que era transitório foi  para glória, muito mais é em glória o que permanece.

[[v47-3-12]]

^<<v47-3-12,12>>^ Tendo, pois, tal esperança, usamos de muita ousadia no falar.

[[v47-3-13]]

^<<v47-3-13,13>>^ E não somos como Moisés, que  punha um véu sobre a sua face, para que os filhos de Israel não olhassem firmemente para o fim daquilo que era transitório.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas os seus sentidos foram endurecidos; porque até hoje o mesmo véu está por levantar na lição do Velho Testamento, o qual foi por Cristo abolido.

[[v47-3-15]]

^<<v47-3-15,15>>^ E até hoje, quando é lido Moisés, o véu está posto sobre o coração deles.

[[v47-3-16]]

^<<v47-3-16,16>>^ Mas, quando se converterem ao Senhor, então,  o véu se tirará.

[[v47-3-17]]

^<<v47-3-17,17>>^ Ora, o Senhor é Espírito; e onde está  o Espírito do Senhor, aí há  liberdade.

[[v47-3-18]]

^<<v47-3-18,18>>^ Mas todos nós, com cara descoberta, refletindo, como um espelho, a glória do Senhor, somos transformados de glória em glória, na mesma imagem, como pelo Espírito do Senhor.

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]