include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// arc ?, ARC - Almeida Revista e Corrigida

[[v10-6-1]]

^<<v10-6-1,1>>^ E tornou Davi a ajuntar todos os escolhidos de Israel, em número  de trinta mil.

[[v10-6-2]]

^<<v10-6-2,2>>^ E levantou-se Davi e partiu com todo o povo que tinha  consigo de Baalá de Judá, para levarem dali para cima a arca de Deus, sobre a qual se invoca o Nome, o nome do SENHOR dos Exércitos, que se assenta entre  os querubins.

[[v10-6-3]]

^<<v10-6-3,3>>^ E puseram a arca de Deus em um carro novo e a levaram da casa de Abinadabe, que está  em Geba; e Uzá e Aiô, filhos de Abinadabe, guiavam o carro novo.

[[v10-6-4]]

^<<v10-6-4,4>>^ E, levando-o da casa de Abinadabe, que está  em Geba, com a arca de Deus, Aiô ia adiante da arca.

[[v10-6-5]]

^<<v10-6-5,5>>^ E Davi e toda a casa de Israel alegravam-se perante o SENHOR, com toda sorte de instrumentos de  madeira de faia, com harpas, e com saltérios, e com tamboris, e com pandeiros, e com címbalos.

[[v10-6-6]]

^<<v10-6-6,6>>^ E, chegando à eira de Nacom, estendeu Uzá a mão  à arca de Deus e segurou-a, porque os bois a  deixavam pender.

[[v10-6-7]]

^<<v10-6-7,7>>^ Então, a ira do SENHOR se acendeu contra Uzá, e Deus o feriu ali por esta imprudência; e morreu ali junto à arca de Deus.

[[v10-6-8]]

^<<v10-6-8,8>>^ E Davi se contristou, porque o SENHOR abrira rotura em Uzá; e chamou aquele lugar Perez-Uzá, até ao dia de hoje.

[[v10-6-9]]

^<<v10-6-9,9>>^ E temeu Davi ao SENHOR naquele dia e disse: Como virá a mim a arca do SENHOR?

[[v10-6-10]]

^<<v10-6-10,10>>^ E não quis Davi retirar para si a arca do SENHOR, para a Cidade de Davi; mas Davi a fez levar à casa de Obede-Edom, o geteu.

[[v10-6-11]]

^<<v10-6-11,11>>^ E ficou a arca do SENHOR em casa de Obede-Edom, o geteu, três meses; e abençoou o SENHOR a Obede-Edom e a toda a sua casa.

[[v10-6-12]]

^<<v10-6-12,12>>^ Então, avisaram a Davi, dizendo: Abençoou o SENHOR a casa de Obede-Edom e tudo quanto tem, por amor da arca de Deus; foi, pois, Davi e trouxe a arca de Deus para cima, da casa de Obede-Edom, à Cidade de Davi, com alegria.

[[v10-6-13]]

^<<v10-6-13,13>>^ E sucedeu que, quando os que levavam a arca do SENHOR tinham dado seis passos, sacrificava ele bois e carneiros  cevados.

[[v10-6-14]]

^<<v10-6-14,14>>^ E Davi saltava com todas as suas forças diante do SENHOR; e estava  Davi cingido de um éfode de linho.

[[v10-6-15]]

^<<v10-6-15,15>>^ Assim subindo, levavam Davi e todo o Israel a arca do SENHOR, com júbilo e ao som das trombetas.

[[v10-6-16]]

^<<v10-6-16,16>>^ E sucedeu que, entrando a arca do SENHOR na Cidade de Davi, Mical, filha de Saul, estava olhando pela janela e, vendo o rei Davi, que ia  bailando e saltando diante do SENHOR, o desprezou no seu coração.

[[v10-6-17]]

^<<v10-6-17,17>>^ E, introduzindo a arca do SENHOR, a puseram no seu lugar, na tenda que Davi lhe armara; e ofereceu Davi holocaustos e ofertas pacíficas perante o SENHOR.

[[v10-6-18]]

^<<v10-6-18,18>>^ E, acabando Davi de oferecer os holocaustos e ofertas pacíficas, abençoou o povo em nome do SENHOR dos Exércitos.

[[v10-6-19]]

^<<v10-6-19,19>>^ E repartiu a todo o povo e a toda a multidão de Israel, desde os homens até às mulheres, a cada um, um bolo de pão, e um  bom pedaço de carne,  e um  frasco de vinho;  então, foi-se todo o povo, cada um para sua casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ E, voltando Davi para abençoar a sua casa, Mical, filha de Saul, saiu a encontrar-se com Davi e disse: Quão honrado foi o rei de Israel, descobrindo-se hoje aos olhos das servas de seus servos, como sem vergonha se descobre qualquer dos vadios.

[[v10-6-21]]

^<<v10-6-21,21>>^ Disse, porém, Davi a Mical: Perante o SENHOR que me escolheu a mim antes do que a teu pai e a toda a sua casa, mandando-me que fosse  chefe sobre o povo do SENHOR, sobre Israel, perante o SENHOR me tenho alegrado.

[[v10-6-22]]

^<<v10-6-22,22>>^ E ainda mais do que isto me envilecerei e me humilharei aos meus olhos; e das servas, de quem falaste, delas serei honrado.

[[v10-6-23]]

^<<v10-6-23,23>>^ E Mical, filha de Saul, não teve filhos, até ao dia da sua morte.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]