include::./index.adoc[]

[[v66-10-0]]
=== Apocalipse, 10
// arc ?, ARC - Almeida Revista e Corrigida

[[v66-10-1]]

^<<v66-10-1,1>>^ E vi outro anjo forte, que descia do céu, vestido de uma nuvem; e por cima da sua  cabeça estava o arco celeste, e o rosto era  como o sol, e os pés, como colunas de fogo;

[[v66-10-2]]

^<<v66-10-2,2>>^ e tinha na mão um livrinho aberto e pôs o pé direito sobre o mar e o esquerdo sobre a terra;

[[v66-10-3]]

^<<v66-10-3,3>>^ e clamou com grande voz, como quando  brama o leão; e, havendo clamado, os sete trovões fizeram soar as suas vozes.

[[v66-10-4]]

^<<v66-10-4,4>>^ E, sendo ouvidas dos sete trovões as suas vozes, eu ia escrevê-las, mas ouvi uma voz do céu, que dizia: Sela o que os sete trovões falaram e não o escrevas.

[[v66-10-5]]

^<<v66-10-5,5>>^ E o anjo que vi estar sobre o mar e sobre a terra levantou a mão ao céu

[[v66-10-6]]

^<<v66-10-6,6>>^ e jurou por aquele que vive para todo o sempre, o qual criou o céu e o que nele há, e a terra e o que nela há, e o mar e o que nele há, que não haveria mais demora;

[[v66-10-7]]

^<<v66-10-7,7>>^ mas nos dias da voz do sétimo anjo, quando tocar a sua trombeta, se cumprirá o segredo de Deus, como anunciou aos profetas, seus servos.

[[v66-10-8]]

^<<v66-10-8,8>>^ E a voz que eu do céu tinha ouvido tornou a falar comigo e disse: Vai e toma o livrinho aberto da mão do anjo que está em pé sobre o mar e sobre a terra.

[[v66-10-9]]

^<<v66-10-9,9>>^ E fui ao anjo, dizendo-lhe: Dá-me o livrinho. E ele disse-me: Toma-o e come-o, e ele fará amargo o teu ventre, mas na tua boca será doce como mel.

[[v66-10-10]]

^<<v66-10-10,10>>^ E tomei o livrinho da mão do anjo e comi-o; e na minha boca era doce como mel; e, havendo-o comido, o meu ventre ficou amargo.

[[v66-10-11]]

^<<v66-10-11,11>>^ E ele disse-me: Importa que profetizes outra vez a muitos povos, e nações, e línguas, e reis.

'''

xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[Próximo Capítulo &#62;]