include::./index.adoc[]

[[v9-27-0]]
=== 1 Samuel, 27
// arc ?, ARC - Almeida Revista e Corrigida

[[v9-27-1]]

^<<v9-27-1,1>>^ Disse, porém, Davi no seu coração: Ora, ainda  algum dia perecerei pela mão de Saul; não há coisa melhor para mim do que escapar apressadamente para a terra dos filisteus; para que Saul perca a esperança de mim e cesse de me buscar por todos os termos de Israel; e assim  escaparei da sua mão.

[[v9-27-2]]

^<<v9-27-2,2>>^ Então, Davi se levantou e passou com os seiscentos homens que com ele estavam  a Aquis, filho de Maoque, rei de Gate.

[[v9-27-3]]

^<<v9-27-3,3>>^ E Davi ficou com Aquis em Gate, ele e os seus homens, cada um com a sua casa; Davi, com ambas as suas mulheres, Ainoã, a jezreelita, e Abigail, a mulher de Nabal, o carmelita.

[[v9-27-4]]

^<<v9-27-4,4>>^ E, sendo Saul avisado de que Davi tinha fugido para Gate, não cuidou mais em o buscar.

[[v9-27-5]]

^<<v9-27-5,5>>^ E disse Davi a Aquis: Se eu tenho achado graça aos teus olhos, dá-me lugar numa das cidades da terra, para que ali habite; pois por que razão habitaria o teu servo contigo na cidade real?

[[v9-27-6]]

^<<v9-27-6,6>>^ Então, lhe deu Aquis, naquele dia, a cidade de  Ziclague (pelo que Ziclague pertence aos reis de Judá, até ao dia de hoje).

[[v9-27-7]]

^<<v9-27-7,7>>^ E foi o número dos dias que Davi habitou na terra dos filisteus um ano e quatro meses.

[[v9-27-8]]

^<<v9-27-8,8>>^ E subia Davi com os seus homens, e deram sobre os gesuritas, e os gersitas, e os amalequitas; porque antigamente eram estes os moradores da terra desde como quem vai para Sur até à terra do Egito.

[[v9-27-9]]

^<<v9-27-9,9>>^ E Davi feria aquela terra, e não dava vida nem a homem nem a mulher, e tomava ovelhas, e vacas, e jumentos, e camelos, e vestes; e voltava e vinha a Aquis.

[[v9-27-10]]

^<<v9-27-10,10>>^ E dizendo Aquis: Sobre onde destes hoje? Davi dizia: Sobre o Sul de Judá, e sobre o Sul dos jerameleus, e sobre o Sul dos queneus.

[[v9-27-11]]

^<<v9-27-11,11>>^ E Davi não dava vida nem a homem nem a mulher, para trazê-los a Gate, dizendo: Para que, porventura,  não nos denunciem, dizendo: Assim Davi o fazia. E este era  o seu costume por todos os dias que habitou na terra dos filisteus.

[[v9-27-12]]

^<<v9-27-12,12>>^ E Aquis confiava em Davi, dizendo: Fez-se ele por certo aborrecível para com o seu povo em Israel; pelo que me será por servo para sempre.

'''

xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[&#60; Capítulo Anterior] | <<v9-27-0,Topo>> | xref:009-1-samuel/009-1-samuel-028.adoc#v9-28-0[Próximo Capítulo &#62;]