include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// arc ?, ARC - Almeida Revista e Corrigida

[[v12-24-1]]

^<<v12-24-1,1>>^ Nos dias de Jeoaquim, subiu Nabucodonosor, rei de Babilônia, contra ele, e Jeoaquim ficou três anos seu servo; depois,  se virou e se revoltou contra ele.

[[v12-24-2]]

^<<v12-24-2,2>>^ E Deus enviou contra Jeoaquim as tropas dos caldeus, e as tropas dos siros, e as tropas dos moabitas, e as tropas dos filhos de Amom; e as enviou contra Judá, para o destruir, conforme a palavra que o SENHOR falara pelo ministério de seus servos, os profetas.

[[v12-24-3]]

^<<v12-24-3,3>>^ E,  na verdade, conforme o mandado do SENHOR, assim  sucedeu a Judá, que o tirou de diante da sua face, por causa  dos pecados de Manassés, conforme tudo quanto fizera,

[[v12-24-4]]

^<<v12-24-4,4>>^ como também por causa do  sangue inocente que derramou, enchendo a Jerusalém de sangue inocente; por isso, o SENHOR não o  quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ Ora, o mais dos atos de Jeoaquim e tudo quanto fez, porventura,  não estão  escritos no livro das Crônicas dos Reis de Judá?

[[v12-24-6]]

^<<v12-24-6,6>>^ E Jeoaquim dormiu com seus pais; e Joaquim, seu filho, reinou em seu lugar.

[[v12-24-7]]

^<<v12-24-7,7>>^ E o rei do Egito nunca mais saiu da sua terra; porque o rei de Babilônia tomou tudo quanto era do rei do Egito, desde o rio do Egito até ao rio Eufrates.

[[v12-24-8]]

^<<v12-24-8,8>>^ Tinha Joaquim dezoito anos de idade quando começou a reinar e reinou três meses em Jerusalém; e era  o nome de sua mãe Neústa, filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ E fez o que era  mal aos olhos do SENHOR, conforme tudo quanto fizera seu pai.

[[v12-24-10]]

^<<v12-24-10,10>>^ Naquele tempo, subiram os servos de Nabucodonosor, rei de Babilônia, a Jerusalém, e a cidade foi cercada.

[[v12-24-11]]

^<<v12-24-11,11>>^ Também veio Nabucodonosor, rei de Babilônia, contra a cidade, quando já os seus servos a estavam cercando.

[[v12-24-12]]

^<<v12-24-12,12>>^ Então, saiu Joaquim, rei de Judá, ao rei de Babilônia, ele, e sua mãe, e seus servos, e seus príncipes, e seus eunucos; e o rei de Babilônia o levou preso,  no ano oitavo de seu reinado.

[[v12-24-13]]

^<<v12-24-13,13>>^ E tirou dali todos os tesouros da Casa do SENHOR e os tesouros da casa do rei; e fendeu todos os utensílios de ouro que fizera Salomão, rei de Israel, no templo do SENHOR, como o SENHOR tinha dito.

[[v12-24-14]]

^<<v12-24-14,14>>^ E transportou a toda a Jerusalém, como também todos os príncipes, e todos os homens valorosos, dez mil presos, e todos os carpinteiros e ferreiros; ninguém ficou, senão o povo pobre da terra.

[[v12-24-15]]

^<<v12-24-15,15>>^ Assim, transportou Joaquim para a Babilônia, como também a mãe do rei, e as mulheres do rei, e os seus eunucos, e os poderosos da terra levou presos de Jerusalém a Babilônia.

[[v12-24-16]]

^<<v12-24-16,16>>^ E todos os homens, valentes, até sete mil, e carpinteiros, e ferreiros, até mil, todos eles destros na guerra, a estes o rei de Babilônia levou presos para Babilônia.

[[v12-24-17]]

^<<v12-24-17,17>>^ E o rei de Babilônia estabeleceu rei, em lugar de Joaquim, ao tio deste, Matanias, e lhe mudou o nome para  Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Tinha Zedequias vinte e um anos de idade quando começou a reinar e reinou onze anos em Jerusalém; e era  o nome de sua mãe Hamutal, filha de Jeremias, de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ E fez o que era  mal aos olhos do SENHOR, conforme tudo quanto fizera Jeoaquim.

[[v12-24-20]]

^<<v12-24-20,20>>^ Pois assim  sucedeu por causa da ira do SENHOR contra Jerusalém e contra Judá, até os rejeitar de diante da sua face; e Zedequias se revoltou contra o rei de Babilônia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]