include::./index.adoc[]

[[v12-17-0]]
=== 2 Reis, 17
// arc ?, ARC - Almeida Revista e Corrigida

[[v12-17-1]]

^<<v12-17-1,1>>^ No ano duodécimo de Acaz, rei de Judá, começou a reinar Oseias, filho de Elá, e reinou sobre Israel, em Samaria, nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ E fez o que era  mal aos olhos do SENHOR; contudo, não como os reis de Israel que foram antes dele.

[[v12-17-3]]

^<<v12-17-3,3>>^ Contra ele subiu Salmaneser, rei da Assíria; e Oseias ficou sendo servo dele e dava-lhe presentes.

[[v12-17-4]]

^<<v12-17-4,4>>^ Porém o rei da Assíria achou em Oseias conspiração, porque enviara mensageiros a Sô, rei do Egito, e não pagava presentes ao rei da Assíria cada ano, como dantes; então, o rei da Assíria o encerrou e aprisionou na casa do cárcere.

[[v12-17-5]]

^<<v12-17-5,5>>^ Porque o rei da Assíria subiu por toda a terra, e veio até Samaria, e a cercou três anos.

[[v12-17-6]]

^<<v12-17-6,6>>^ No ano nono de Oseias, o rei da Assíria tomou a Samaria, e transportou a Israel para a Assíria, e fê-los habitar em Hala e em Habor, junto  ao rio Gozã, e nas cidades dos medos.

[[v12-17-7]]

^<<v12-17-7,7>>^ E sucedeu assim por os filhos de Israel pecarem contra o SENHOR, seu Deus, que os fizera subir da terra do Egito, de debaixo da mão de Faraó, rei do Egito; e temeram a outros deuses.

[[v12-17-8]]

^<<v12-17-8,8>>^ E andaram nos estatutos das nações que o SENHOR lançara fora de diante dos filhos de Israel e nos  costumes dos reis de Israel.

[[v12-17-9]]

^<<v12-17-9,9>>^ E os filhos de Israel fizeram secretamente coisas que não eram  retas, contra o SENHOR, seu Deus; e edificaram altos em todas as suas cidades, desde a torre dos atalaias até à cidade forte.

[[v12-17-10]]

^<<v12-17-10,10>>^ E levantaram estátuas e imagens do bosque, em todos os altos outeiros e debaixo de todas as árvores verdes.

[[v12-17-11]]

^<<v12-17-11,11>>^ E queimaram ali incenso em todos os altos, como as nações que o SENHOR transportara de diante deles; e fizeram coisas ruins, para provocarem à ira o SENHOR.

[[v12-17-12]]

^<<v12-17-12,12>>^ E serviram os ídolos, dos quais o SENHOR lhes dissera: Não fareis estas coisas.

[[v12-17-13]]

^<<v12-17-13,13>>^ E o SENHOR protestou a Israel e a Judá, pelo ministério de todos os profetas e  de todos os videntes, dizendo: Convertei-vos de vossos maus caminhos e guardai os meus mandamentos e  os meus estatutos, conforme toda a Lei que ordenei a vossos pais e que eu vos enviei pelo ministério de meus servos, os profetas.

[[v12-17-14]]

^<<v12-17-14,14>>^ Porém não deram ouvidos; antes, endureceram a sua cerviz, como a cerviz de seus pais, que não creram no SENHOR, seu Deus.

[[v12-17-15]]

^<<v12-17-15,15>>^ E rejeitaram os estatutos e o concerto que fizera com seus pais, como também os testemunhos com que protestara contra eles; e andaram após a vaidade e ficaram vãos, como também após as nações que estavam  em roda deles, das quais o SENHOR lhes tinha dito que não fizessem como elas.

[[v12-17-16]]

^<<v12-17-16,16>>^ E deixaram todos os mandamentos do SENHOR, seu Deus, e fizeram imagens de fundição, dois bezerros; e fizeram um  ídolo do bosque, e se prostraram perante todo o exército do céu, e serviram a Baal.

[[v12-17-17]]

^<<v12-17-17,17>>^ Também fizeram passar pelo fogo a seus filhos e suas filhas, e deram-se a adivinhações, e criam em agouros; e venderam-se para fazer o que era  mal aos olhos do SENHOR, para o provocarem à ira.

[[v12-17-18]]

^<<v12-17-18,18>>^ Pelo que o SENHOR muito se indignou contra Israel e os tirou de diante da sua face; nada mais ficou, senão a tribo de Judá.

[[v12-17-19]]

^<<v12-17-19,19>>^ Até Judá não guardou os mandamentos do SENHOR, seu Deus; antes, andaram nos estatutos que Israel fizera.

[[v12-17-20]]

^<<v12-17-20,20>>^ Pelo que o SENHOR rejeitou a toda semente de Israel, e os oprimiu, e os deu nas mãos dos despojadores, até que os tirou de diante da sua presença.

[[v12-17-21]]

^<<v12-17-21,21>>^ Porque, depois que o Senhor rasgou a Israel da casa de Davi, e eles fizeram rei a Jeroboão, filho de Nebate, Jeroboão apartou a Israel de seguir o SENHOR e os fez pecar um grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ Assim, andaram os filhos de Israel em todos os pecados que Jeroboão tinha feito; nunca se apartaram deles.

[[v12-17-23]]

^<<v12-17-23,23>>^ Até que o SENHOR tirou a Israel de diante da sua presença, como falara pelo ministério de todos os seus servos, os profetas; assim, foi Israel transportado da sua terra à Assíria, onde permanece até ao dia de  hoje.

[[v12-17-24]]

^<<v12-17-24,24>>^ E o rei da Assíria trouxe gente  de Babel, e de Cuta, e de Ava, e de Hamate, e de Sefarvaim e a fez habitar nas cidades de Samaria, em lugar dos filhos de Israel; e tomaram a Samaria em herança e habitaram nas suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ E sucedeu que, no princípio da sua habitação ali, não temeram ao SENHOR; e mandou o SENHOR entre eles leões, que mataram a alguns  deles.

[[v12-17-26]]

^<<v12-17-26,26>>^ Pelo que falaram ao rei da Assíria, dizendo: A gente que transportaste e fizeste habitar nas cidades de Samaria não sabe o costume do Deus da terra; pelo que ele mandou leões entre ela, e eis que a matam, porquanto não sabe o culto do Deus da terra.

[[v12-17-27]]

^<<v12-17-27,27>>^ Então, o rei da Assíria mandou dizer: Levai ali um dos sacerdotes que transportastes de lá; que ele vá, e habite lá, e lhes ensine o costume do Deus da terra.

[[v12-17-28]]

^<<v12-17-28,28>>^ Veio, pois, um dos sacerdotes que transportaram de Samaria, e habitou em Betel, e lhes ensinou como deviam temer ao SENHOR.

[[v12-17-29]]

^<<v12-17-29,29>>^ Porém cada nação fez os seus deuses, e os puseram nas casas dos altos que os samaritanos fizeram, cada nação nas suas cidades, nas quais habitavam.

[[v12-17-30]]

^<<v12-17-30,30>>^ E os de Babel fizeram Sucote-Benote; e os de Cuta fizeram Nergal; e os de Hamate fizeram Asima;

[[v12-17-31]]

^<<v12-17-31,31>>^ E os aveus fizeram Nibaz e Tartaque; e os sefarvitas queimavam seus filhos no fogo a Adrameleque e a Anameleque, deuses de Sefarvaim.

[[v12-17-32]]

^<<v12-17-32,32>>^ Assim temiam ao SENHOR e dos mais humildes se fizeram sacerdotes dos lugares altos, os quais exerciam o ministério  nas casas dos lugares altos.

[[v12-17-33]]

^<<v12-17-33,33>>^ Assim,  ao SENHOR temiam e também  a seus deuses serviam, segundo o costume das nações dentre as quais tinham sido transportados.

[[v12-17-34]]

^<<v12-17-34,34>>^ Até ao dia de  hoje fazem segundo os primeiros costumes; não temem ao SENHOR, nem fazem segundo os seus estatutos, e segundo as suas ordenanças e segundo a lei, e segundo o mandamento que o SENHOR ordenou aos filhos de Jacó, a quem deu o nome de Israel.

[[v12-17-35]]

^<<v12-17-35,35>>^ Contudo, o SENHOR tinha feito um  concerto com eles e lhes ordenara, dizendo: Não temereis a outros deuses, nem vos inclinareis diante deles, nem os servireis, nem lhes sacrificareis.

[[v12-17-36]]

^<<v12-17-36,36>>^ Mas ao SENHOR, que vos fez subir da terra do Egito com grande força e com braço estendido, a este temereis, e a ele vos inclinareis, e a ele sacrificareis.

[[v12-17-37]]

^<<v12-17-37,37>>^ E os estatutos, e as ordenanças, e a lei, e o mandamento que vos escreveu, tereis cuidado de os observar todos os dias; e não temereis a outros deuses.

[[v12-17-38]]

^<<v12-17-38,38>>^ E do concerto que fiz convosco vos não esquecereis; e não temereis a outros deuses.

[[v12-17-39]]

^<<v12-17-39,39>>^ Mas ao SENHOR, vosso Deus, temereis, e ele vos livrará das mãos de todos os vossos inimigos.

[[v12-17-40]]

^<<v12-17-40,40>>^ Porém eles não ouviram; antes, fizeram segundo o seu primeiro costume.

[[v12-17-41]]

^<<v12-17-41,41>>^ Assim, estas nações temiam ao SENHOR e serviam as suas imagens de escultura; como fizeram seus pais, assim  fazem também seus filhos e os filhos de seus filhos, até ao dia de hoje.

'''

xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]