include::./index.adoc[]

[[v12-19-0]]
=== 2 Reis, 19
// arc ?, ARC - Almeida Revista e Corrigida

[[v12-19-1]]

^<<v12-19-1,1>>^ E aconteceu que Ezequias, tendo-o ouvido, rasgou as suas vestes, e se cobriu de pano de saco, e entrou na Casa do SENHOR.

[[v12-19-2]]

^<<v12-19-2,2>>^ Então, enviou a Eliaquim, o mordomo, e a Sebna, o escrivão, e aos anciãos dos sacerdotes cobertos de pano de saco, ao profeta Isaías, filho de Amoz;

[[v12-19-3]]

^<<v12-19-3,3>>^ os quais disseram-lhe: Assim diz Ezequias: Este dia é  dia de angústia, e de vituperação, e de blasfêmia; porque os filhos chegaram ao parto, e não há  força para os ter.

[[v12-19-4]]

^<<v12-19-4,4>>^ Bem pode ser que o SENHOR, teu Deus, ouça todas as palavras de Rabsaqué, a quem enviou o seu senhor, o rei da Assíria, para afrontar o Deus vivo e para vituperá-lo com as palavras que o SENHOR, teu Deus, tem ouvido; faze, pois, oração pelo resto que se acha.

[[v12-19-5]]

^<<v12-19-5,5>>^ E os servos do rei Ezequias vieram a Isaías.

[[v12-19-6]]

^<<v12-19-6,6>>^ E Isaías lhes disse: Assim direis a vosso senhor: Assim diz o SENHOR: Não temas as palavras que ouviste, com as quais os servos do rei da Assíria me blasfemaram.

[[v12-19-7]]

^<<v12-19-7,7>>^ Eis que meterei nele um espírito e ele ouvirá um  ruído e voltará para a sua terra; à espada o farei cair na sua terra.

[[v12-19-8]]

^<<v12-19-8,8>>^ Voltou, pois, Rabsaqué e achou o rei da Assíria pelejando contra Libna, porque tinha ouvido que se havia partido de Laquis.

[[v12-19-9]]

^<<v12-19-9,9>>^ E, ouvindo ele dizer de Tiraca, rei de Cuxe: Eis que há saído para te fazer guerra; tornou a enviar mensageiros a Ezequias, dizendo:

[[v12-19-10]]

^<<v12-19-10,10>>^ Assim falareis a Ezequias, rei de Judá, dizendo: Não te engane o teu Deus, em quem confias, dizendo: Jerusalém não será entregue na mão do rei da Assíria.

[[v12-19-11]]

^<<v12-19-11,11>>^ Eis que já tens ouvido o que fizeram os reis da Assíria a todas as terras, destruindo-as totalmente; e tu te livrarás?

[[v12-19-12]]

^<<v12-19-12,12>>^ Porventura,  as livraram os deuses das nações, a quem destruíram, como  a Gozã e a Harã, e a Rezefe, e aos filhos de Éden, que estavam  em Telassar?

[[v12-19-13]]

^<<v12-19-13,13>>^ Que é feito  do rei de Hamate, e do rei de Arpade, e do rei da cidade de Sefarvaim, de Hena e de Iva?

[[v12-19-14]]

^<<v12-19-14,14>>^ Recebendo, pois, Ezequias as cartas das mãos dos mensageiros e lendo-as, subiu à Casa do SENHOR; e Ezequias as estendeu perante o SENHOR.

[[v12-19-15]]

^<<v12-19-15,15>>^ E orou Ezequias perante o SENHOR e disse: Ó SENHOR, Deus de Israel, que habitas entre  os querubins, tu mesmo, só tu és Deus de todos os reinos da terra; tu fizeste os céus e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Inclina, SENHOR, o teu ouvido e ouve; abre, SENHOR, os teus olhos e olha: e ouve as palavras de Senaqueribe, que ele enviou para afrontar o Deus vivo.

[[v12-19-17]]

^<<v12-19-17,17>>^ Verdade é, ó SENHOR, que os reis da Assíria assolaram as nações e as suas terras.

[[v12-19-18]]

^<<v12-19-18,18>>^ E lançaram os seus deuses no fogo, porquanto deuses não eram,  mas obra de mãos de homens, madeira e pedra; por isso, os destruíram.

[[v12-19-19]]

^<<v12-19-19,19>>^ Agora, pois, ó SENHOR, nosso Deus, sê servido de nos livrar da sua mão; e, assim,  saberão todos os reinos da terra que só tu és  o SENHOR Deus.

[[v12-19-20]]

^<<v12-19-20,20>>^ Então, Isaías, filho de Amoz, mandou dizer a Ezequias: Assim diz o SENHOR, Deus de Israel: O que me pediste acerca de Senaqueribe, rei da Assíria, eu  o ouvi.

[[v12-19-21]]

^<<v12-19-21,21>>^ Esta é  a palavra que o SENHOR falou dele: A virgem, a filha de Sião, te despreza, de ti zomba; a filha de Jerusalém meneia a cabeça por detrás de ti.

[[v12-19-22]]

^<<v12-19-22,22>>^ A quem afrontaste e blasfemaste? E contra quem alçaste a voz e ergueste os teus olhos ao alto? Contra o Santo de Israel?

[[v12-19-23]]

^<<v12-19-23,23>>^ Por meio de teus mensageiros, afrontaste o SENHOR e disseste: Com a multidão de meus carros, subo eu ao alto dos montes, aos lados do Líbano, e cortarei os seus altos cedros e  as suas mais formosas faias, e entrarei nas suas pousadas extremas, até  no bosque do seu campo fértil.

[[v12-19-24]]

^<<v12-19-24,24>>^ Eu cavei, e bebi águas estranhas, e com as plantas de meus pés secarei todos os rios dos lugares fortes.

[[v12-19-25]]

^<<v12-19-25,25>>^ Porventura,  não ouviste que já dantes fiz isso e já  desde os dias antigos o formei? Agora, porém,  o fiz vir, para que fosses tu que reduzisses as cidades fortes a montões desertos.

[[v12-19-26]]

^<<v12-19-26,26>>^ Por isso, os moradores delas, com as mãos encolhidas, ficaram pasmados e confundidos; eram como  a erva do campo, e a hortaliça verde, e  o feno dos telhados, e o trigo  queimado, antes que se levante.

[[v12-19-27]]

^<<v12-19-27,27>>^ Porém o teu assentar, e o teu sair, e o teu entrar, e o  teu furor contra mim, eu o sei.

[[v12-19-28]]

^<<v12-19-28,28>>^ Por causa do teu furor contra mim e porque a tua revolta subiu aos meus ouvidos, portanto, porei o meu anzol no teu nariz e o meu freio, nos teus lábios e te farei voltar pelo caminho por onde vieste.

[[v12-19-29]]

^<<v12-19-29,29>>^ E isto te será  por sinal: Este ano se comerá o que nascer por si mesmo, e no ano seguinte o que daí proceder; porém, no terceiro ano, semeai, e segai, e plantai vinhas, e comei os seus frutos.

[[v12-19-30]]

^<<v12-19-30,30>>^ Porque o que escapou da casa de Judá e ficou de resto tornará a lançar raízes para baixo e dará fruto para cima.

[[v12-19-31]]

^<<v12-19-31,31>>^ Porque de Jerusalém sairá o restante, e do monte de Sião, o que escapou; o zelo do SENHOR fará isso.

[[v12-19-32]]

^<<v12-19-32,32>>^ Portanto, assim diz o SENHOR acerca do rei da Assíria: Não entrará nesta cidade, nem lançará nela flecha alguma;  nem tampouco virá perante ela com escudo, nem levantará contra ela tranqueira alguma.

[[v12-19-33]]

^<<v12-19-33,33>>^ Pelo caminho por onde vier, por ele voltará; porém nesta cidade não entrará, diz o SENHOR.

[[v12-19-34]]

^<<v12-19-34,34>>^ Porque eu ampararei a esta cidade, para a livrar, por amor de mim e por amor do meu servo Davi.

[[v12-19-35]]

^<<v12-19-35,35>>^ Sucedeu, pois, que naquela mesma noite, saiu o anjo do SENHOR e feriu no arraial dos assírios a cento e oitenta e cinco mil deles;  e, levantando-se pela manhã cedo, eis que todos eram  corpos mortos.

[[v12-19-36]]

^<<v12-19-36,36>>^ Então, Senaqueribe, rei da Assíria, partiu, e foi; e voltou e ficou em Nínive.

[[v12-19-37]]

^<<v12-19-37,37>>^ E sucedeu que, estando ele prostrado na casa de Nisroque, seu deus, Adrameleque e Sarezer, seus filhos, o feriram à espada; porém eles escaparam para a terra de Ararate; e Esar-Hadom, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]