include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// arc ?, ARC - Almeida Revista e Corrigida

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois destas coisas veio a palavra do SENHOR a Abrão em visão, dizendo: Não temas, Abrão, eu sou o teu escudo, o teu grandíssimo galardão.

[[v1-15-2]]

^<<v1-15-2,2>>^ Então, disse Abrão: Senhor Jeová , que me hás de dar? Pois ando sem filhos, e o mordomo da minha casa é o damasceno Eliézer.

[[v1-15-3]]

^<<v1-15-3,3>>^ Disse mais Abrão: Eis que me não tens dado semente, e eis que um nascido na minha casa será o meu herdeiro.

[[v1-15-4]]

^<<v1-15-4,4>>^ E eis que veio  a palavra do SENHOR a ele, dizendo: Este não será o teu herdeiro; mas aquele que de ti será gerado, esse será o teu herdeiro.

[[v1-15-5]]

^<<v1-15-5,5>>^ Então, o levou fora e disse: Olha, agora, para os céus e conta as estrelas, se as podes contar. E disse-lhe: Assim será a tua semente.

[[v1-15-6]]

^<<v1-15-6,6>>^ E creu ele no SENHOR, e foi-lhe imputado isto por  justiça.

[[v1-15-7]]

^<<v1-15-7,7>>^ Disse-lhe mais: Eu sou  o SENHOR, que te tirei de Ur dos caldeus, para dar-te a ti esta terra, para a herdares.

[[v1-15-8]]

^<<v1-15-8,8>>^ E disse ele: Senhor Jeová , como saberei que hei de herdá-la?

[[v1-15-9]]

^<<v1-15-9,9>>^ E disse-lhe: Toma-me uma bezerra de três anos, e uma cabra de três anos, e um carneiro de três anos, e uma rola, e um pombinho.

[[v1-15-10]]

^<<v1-15-10,10>>^ E trouxe-lhe todos estes, e partiu-os pelo meio, e pôs cada parte deles em frente da outra; mas as aves não partiu.

[[v1-15-11]]

^<<v1-15-11,11>>^ E as aves desciam sobre os cadáveres; Abrão, porém, as enxotava.

[[v1-15-12]]

^<<v1-15-12,12>>^ E, pondo-se o sol, um profundo sono caiu sobre Abrão; e eis que grande espanto e grande escuridão caíram sobre ele.

[[v1-15-13]]

^<<v1-15-13,13>>^ Então, disse a Abrão: Saibas, decerto, que peregrina será a tua semente em terra que  não é  sua; e servi-los-á e afligi-la-ão quatrocentos anos.

[[v1-15-14]]

^<<v1-15-14,14>>^ Mas também eu julgarei a gente à qual servirão, e depois sairão com grande fazenda.

[[v1-15-15]]

^<<v1-15-15,15>>^ E tu irás a teus pais em paz; em boa velhice serás sepultado.

[[v1-15-16]]

^<<v1-15-16,16>>^ E a quarta geração tornará para cá; porque a medida da injustiça dos amorreus não está  ainda cheia.

[[v1-15-17]]

^<<v1-15-17,17>>^ E sucedeu que, posto o sol, houve escuridão; e eis um forno de fumaça e uma tocha de fogo que passou por aquelas metades.

[[v1-15-18]]

^<<v1-15-18,18>>^ Naquele mesmo dia, fez o SENHOR um concerto com Abrão, dizendo: À tua semente tenho dado esta terra, desde o rio do Egito até ao grande rio Eufrates,

[[v1-15-19]]

^<<v1-15-19,19>>^ e o queneu, e o quenezeu, e o cadmoneu,

[[v1-15-20]]

^<<v1-15-20,20>>^ e o heteu, e o ferezeu, e os refains,

[[v1-15-21]]

^<<v1-15-21,21>>^ e o amorreu, e o cananeu, e o girgaseu, e o jebuseu.

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]