include::./index.adoc[]

[[v1-34-0]]
=== Gênesis, 34
// arc ?, ARC - Almeida Revista e Corrigida

[[v1-34-1]]

^<<v1-34-1,1>>^ E saiu Diná, filha de Leia, que esta dera a Jacó, a ver as filhas da terra.

[[v1-34-2]]

^<<v1-34-2,2>>^ E Siquém, filho de Hamor, heveu, príncipe daquela terra, viu-a, e tomou-a, e deitou-se com ela, e humilhou-a.

[[v1-34-3]]

^<<v1-34-3,3>>^ E apegou-se a sua alma com Diná, filha de Jacó, e amou a moça, e falou afetuosamente à moça.

[[v1-34-4]]

^<<v1-34-4,4>>^ Falou também Siquém a Hamor, seu pai, dizendo: Toma-me esta por mulher.

[[v1-34-5]]

^<<v1-34-5,5>>^ Quando Jacó ouviu que fora contaminada Diná, sua filha, estavam os seus filhos no campo com o gado; e calou-se Jacó até que viessem.

[[v1-34-6]]

^<<v1-34-6,6>>^ E saiu Hamor, pai de Siquém, a Jacó, para falar com ele.

[[v1-34-7]]

^<<v1-34-7,7>>^ E vieram os filhos de Jacó do campo; e, ouvindo isso, entristeceram-se os varões e iraram-se muito, pois aquele fizera doidice em Israel, deitando-se com a filha de Jacó, o que não se devia fazer assim.

[[v1-34-8]]

^<<v1-34-8,8>>^ Então, falou Hamor com eles, dizendo: A alma de Siquém, meu filho, está namorada da vossa filha; dai-lha, peço-vos, por mulher.

[[v1-34-9]]

^<<v1-34-9,9>>^ Aparentai-vos conosco, dai-nos as vossas filhas e tomai as nossas filhas para vós;

[[v1-34-10]]

^<<v1-34-10,10>>^ e habitareis conosco; e a terra estará diante da vossa face; habitai, e negociai nela, e tomai possessão nela.

[[v1-34-11]]

^<<v1-34-11,11>>^ E disse Siquém ao pai dela e aos irmãos dela: Ache eu graça a vossos olhos e darei o que me disserdes.

[[v1-34-12]]

^<<v1-34-12,12>>^ Aumentai muito sobre mim o dote e a dádiva, e darei o que me disserdes; dai-me somente a moça por mulher.

[[v1-34-13]]

^<<v1-34-13,13>>^ Então, responderam os filhos de Jacó a Siquém e a Hamor, seu pai, enganosamente, e falaram, porquanto havia contaminado a Diná, sua irmã.

[[v1-34-14]]

^<<v1-34-14,14>>^ E disseram-lhes: Não podemos fazer isso, que déssemos a nossa irmã a um varão não circuncidado; porque isso seria  uma vergonha para nós.

[[v1-34-15]]

^<<v1-34-15,15>>^ Nisso, porém, consentiremos a vós: se fordes como nós, que se circuncide todo macho entre vós;

[[v1-34-16]]

^<<v1-34-16,16>>^ então, dar-vos-emos as nossas filhas, e tomaremos nós as vossas filhas, e habitaremos convosco, e seremos um só povo.

[[v1-34-17]]

^<<v1-34-17,17>>^ Mas, se não nos ouvirdes e não vos circuncidardes, tomaremos a nossa filha e ir-nos-emos.

[[v1-34-18]]

^<<v1-34-18,18>>^ E suas palavras foram boas aos olhos de Hamor e aos olhos de Siquém, filho de Hamor.

[[v1-34-19]]

^<<v1-34-19,19>>^ E não tardou o jovem em fazer isto; porque a filha de Jacó lhe agradava, e ele era  o mais honrado de toda a casa de seu pai.

[[v1-34-20]]

^<<v1-34-20,20>>^ Vieram, pois, Hamor e Siquém, seu filho, à porta da sua cidade e falaram aos varões da sua cidade, dizendo:

[[v1-34-21]]

^<<v1-34-21,21>>^ Estes varões são  pacíficos conosco; portanto, habitarão nesta terra e negociarão nela; eis que a terra é larga de espaço diante da sua face; tomaremos nós as suas filhas por mulheres e lhes daremos as nossas filhas.

[[v1-34-22]]

^<<v1-34-22,22>>^ Mas somente consentirão aqueles varões habitar conosco, para que sejamos um só povo, se todo macho entre nós se circuncidar, como eles são  circuncidados.

[[v1-34-23]]

^<<v1-34-23,23>>^ O seu gado, e as suas possessões, e todos os seus animais não serão nossos? Consintamos somente com eles, e habitarão conosco.

[[v1-34-24]]

^<<v1-34-24,24>>^ E deram ouvidos a Hamor e a Siquém, seu filho, todos os que saíam da porta da cidade; e foi circuncidado todo macho, de todos os que saíam pela porta da sua cidade.

[[v1-34-25]]

^<<v1-34-25,25>>^ E aconteceu que, ao terceiro dia, quando estavam com a mais violenta  dor, dois filhos de Jacó, Simeão e Levi, irmãos de Diná, tomaram cada um a sua espada, e entraram afoitamente na cidade, e mataram todo macho.

[[v1-34-26]]

^<<v1-34-26,26>>^ Mataram também a fio de espada a Hamor, e a seu filho Siquém; e tomaram Diná da casa de Siquém e saíram.

[[v1-34-27]]

^<<v1-34-27,27>>^ Vieram os filhos de Jacó aos mortos e saquearam a cidade, porquanto haviam contaminado a sua irmã.

[[v1-34-28]]

^<<v1-34-28,28>>^ As suas ovelhas, e as suas vacas, e os seus jumentos, e o que na cidade e o que no campo havia  tomaram;

[[v1-34-29]]

^<<v1-34-29,29>>^ e toda a sua fazenda, e todos os seus meninos, e as suas mulheres levaram presos e despojaram-nos de tudo o que havia  em casa.

[[v1-34-30]]

^<<v1-34-30,30>>^ Então, disse Jacó a Simeão e a Levi: Tendes-me turbado, fazendo-me cheirar mal entre os moradores desta terra, entre os cananeus e ferezeus; sendo  eu pouco povo em número, ajuntar-se-ão, e ficarei destruído, eu e minha casa.

[[v1-34-31]]

^<<v1-34-31,31>>^ E eles disseram: Faria, pois, ele a nossa irmã, como a uma prostituta?

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]