include::./index.adoc[]

[[v33-6-0]]
=== Miquéias, 6
// arc ?, ARC - Almeida Revista e Corrigida

[[v33-6-1]]

^<<v33-6-1,1>>^ Ouvi, agora, o que diz o SENHOR: Levanta-te, contende com os montes, e ouçam os outeiros a tua voz.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ouvi, montes, a contenda do SENHOR, e vós, fortes fundamentos da terra; porque o SENHOR tem uma contenda com o seu povo e com Israel entrará em juízo.

[[v33-6-3]]

^<<v33-6-3,3>>^ Ó povo meu! Que te tenho feito? E em que te enfadei? Testifica contra mim.

[[v33-6-4]]

^<<v33-6-4,4>>^ Certamente, te fiz subir da terra do Egito e da casa da servidão te remi; e pus diante de ti a Moisés, Arão e Miriã.

[[v33-6-5]]

^<<v33-6-5,5>>^ Povo meu, ora, lembra-te da consulta de Balaque, rei de Moabe, e do que lhe respondeu Balaão, filho de Beor, desde Sitim até Gilgal; para que conheças as justiças do SENHOR.

[[v33-6-6]]

^<<v33-6-6,6>>^ Com que me apresentarei ao Senhor e  me inclinarei ante o Deus Altíssimo? Virei perante ele com holocaustos, com bezerros de um  ano?

[[v33-6-7]]

^<<v33-6-7,7>>^ Agradar-se-á o SENHOR de milhares de carneiros? De dez mil ribeiros de azeite? Darei o meu primogênito pela minha transgressão? O fruto do meu ventre, pelo  pecado da minha alma?

[[v33-6-8]]

^<<v33-6-8,8>>^ Ele te declarou, ó homem, o que é  bom; e que é o que o SENHOR pede de ti, senão que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus?

[[v33-6-9]]

^<<v33-6-9,9>>^ A voz do SENHOR clama à cidade, e o sábio verá o teu nome: Ouvi a vara e quem a ordenou.

[[v33-6-10]]

^<<v33-6-10,10>>^ Ainda há na  casa do ímpio tesouros de impiedade? E efa pequeno, que é detestável?

[[v33-6-11]]

^<<v33-6-11,11>>^ Seria eu limpo com balanças falsas? E com um saco de pesos enganosos?

[[v33-6-12]]

^<<v33-6-12,12>>^ Porque os seus ricos estão cheios de violência, e os seus habitantes falam mentiras; e a sua língua é  enganosa na sua boca.

[[v33-6-13]]

^<<v33-6-13,13>>^ Assim, eu também te  enfraquecerei, ferindo-te e  assolando- te  por causa dos teus pecados.

[[v33-6-14]]

^<<v33-6-14,14>>^ Tu comerás, mas não te fartarás; e a tua humilhação estará no meio de ti; removerás, mas não livrarás; e aquilo que livrares, eu o entregarei à espada.

[[v33-6-15]]

^<<v33-6-15,15>>^ Tu semearás, mas não segarás; pisarás a azeitona, mas não te ungirás com azeite; e o mosto, mas não beberás vinho.

[[v33-6-16]]

^<<v33-6-16,16>>^ Porque se observam os estatutos de Onri e toda a obra da casa de Acabe, e vós andais nos conselhos deles; para que eu faça de ti uma desolação e dos seus habitantes um assobio; assim, trareis sobre vós o opróbrio do meu povo.

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]