include::./index.adoc[]

[[v60-3-0]]
=== 1 Pedro, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v60-3-1]]

^<<v60-3-1,1>>^ Semelhantemente, vós,  mulheres, sede  sujeitas ao vosso próprio marido, para que também, se algum não obedece à palavra, pelo procedimento de sua mulher seja ganho sem palavra,

[[v60-3-2]]

^<<v60-3-2,2>>^ considerando a vossa vida casta, em temor.

[[v60-3-3]]

^<<v60-3-3,3>>^ O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de joias de ouro, na compostura de vestes,

[[v60-3-4]]

^<<v60-3-4,4>>^ mas o homem encoberto no coração, no incorruptível trajo  de um espírito manso e quieto, que é precioso diante de Deus.

[[v60-3-5]]

^<<v60-3-5,5>>^ Porque assim se adornavam também antigamente as santas mulheres que esperavam em Deus e estavam sujeitas ao seu próprio marido,

[[v60-3-6]]

^<<v60-3-6,6>>^ como Sara obedecia a Abraão, chamando-lhe senhor, da qual vós sois filhas, fazendo o bem e não temendo nenhum espanto.

[[v60-3-7]]

^<<v60-3-7,7>>^ Igualmente vós, maridos, coabitai com ela com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações.

[[v60-3-8]]

^<<v60-3-8,8>>^ E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis,

[[v60-3-9]]

^<<v60-3-9,9>>^ não tornando mal por mal ou injúria por injúria; antes, pelo contrário, bendizendo, sabendo que para isto fostes chamados, para que, por herança, alcanceis a bênção.

[[v60-3-10]]

^<<v60-3-10,10>>^ Porque quem quer amar a vida e ver os dias bons, refreie a sua língua do mal, e os seus lábios não falem engano;

[[v60-3-11]]

^<<v60-3-11,11>>^ aparte-se do mal e faça o bem; busque a paz e siga-a.

[[v60-3-12]]

^<<v60-3-12,12>>^ Porque os olhos do Senhor estão  sobre os justos, e os seus ouvidos, atentos  às suas orações; mas o rosto do Senhor é contra os que fazem males.

[[v60-3-13]]

^<<v60-3-13,13>>^ E qual é aquele que vos fará mal, se fordes zelosos do bem?

[[v60-3-14]]

^<<v60-3-14,14>>^ Mas também, se padecerdes por amor da justiça, sois bem-aventurados. E não temais com medo deles, nem vos turbeis;

[[v60-3-15]]

^<<v60-3-15,15>>^ antes, santificai a Cristo, como Senhor, em vosso coração; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós,

[[v60-3-16]]

^<<v60-3-16,16>>^ tendo uma boa consciência, para que, naquilo em que falam mal de vós, como de malfeitores, fiquem confundidos os que blasfemam do vosso bom procedimento em Cristo,

[[v60-3-17]]

^<<v60-3-17,17>>^ porque melhor é que padeçais fazendo o bem (se a vontade de Deus assim  o quer) do que fazendo o mal.

[[v60-3-18]]

^<<v60-3-18,18>>^ Porque também Cristo padeceu uma vez pelos pecados, o justo pelos injustos, para levar-nos a Deus; mortificado, na verdade, na carne, mas vivificado pelo Espírito,

[[v60-3-19]]

^<<v60-3-19,19>>^ no qual também foi e  pregou aos espíritos em prisão,

[[v60-3-20]]

^<<v60-3-20,20>>^ os quais em outro tempo foram rebeldes, quando a longanimidade de Deus esperava nos dias de Noé, enquanto se preparava a arca; na qual poucas (isto é, oito) almas se salvaram pela água,

[[v60-3-21]]

^<<v60-3-21,21>>^ que também, como uma verdadeira figura, agora vos salva, batismo, não do despojamento da imundícia da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo;

[[v60-3-22]]

^<<v60-3-22,22>>^ o qual está à destra de Deus, tendo subido ao céu, havendo-se-lhe sujeitado os anjos, e as autoridades, e as potências.

'''

xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[Próximo Capítulo &#62;]