include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// arc ?, ARC - Almeida Revista e Corrigida

[[v18-24-1]]

^<<v18-24-1,1>>^ Visto que do Todo-Poderoso se não encobriram os tempos, por que não veem os seus dias os que o conhecem?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há os que até os limites removem; roubam os rebanhos e os  apascentam.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam o jumento do órfão; tomam em penhor o boi da viúva.

[[v18-24-4]]

^<<v18-24-4,4>>^ Desviam do caminho os necessitados; e  os miseráveis da terra juntos se escondem.

[[v18-24-5]]

^<<v18-24-5,5>>^ Eis que, como  jumentos monteses no deserto, saem à sua obra, madrugando para a presa; o campo raso dá  mantimento a eles e aos seus  filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ No campo, segam o seu pasto e vindimam a vinha do ímpio.

[[v18-24-7]]

^<<v18-24-7,7>>^ Ao nu fazem passar a noite sem roupa, não tendo ele coberta contra o frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ Pelas correntes das montanhas são molhados e, não tendo refúgio, abraçam-se com as rochas.

[[v18-24-9]]

^<<v18-24-9,9>>^ Ao orfãozinho arrancam do peito e aceitam o penhor do pobre.

[[v18-24-10]]

^<<v18-24-10,10>>^ Fazem com que os nus vão sem veste e aos famintos tiram as espigas.

[[v18-24-11]]

^<<v18-24-11,11>>^ Dentro dos seus muros fazem o azeite; pisam os lagares e ainda  têm sede.

[[v18-24-12]]

^<<v18-24-12,12>>^ Desde as cidades gemem os homens, e a alma dos feridos clama; e, contudo, Deus lho  não imputa como  loucura.

[[v18-24-13]]

^<<v18-24-13,13>>^ Eles estão entre os que se opõem à luz; não conhecem os seus caminhos e não permanecem nas suas veredas.

[[v18-24-14]]

^<<v18-24-14,14>>^ De madrugada se levanta o homicida, mata o pobre e necessitado e de noite é como o ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ Assim como os olhos do adúltero aguardam o crepúsculo, dizendo: Não me verá olho nenhum, e oculta o rosto,

[[v18-24-16]]

^<<v18-24-16,16>>^ nas trevas minam as casas que  de dia assinalaram; não conhecem a luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ Porque a manhã, para todos  eles, é  como sombra de morte; porque,  sendo conhecidos, sentem os pavores da sombra da morte.

[[v18-24-18]]

^<<v18-24-18,18>>^ São ligeiros sobre a face das águas; maldita é  a sua porção sobre a terra; não voltam pelo caminho das vinhas.

[[v18-24-19]]

^<<v18-24-19,19>>^ A secura e o calor desfazem as águas da neve; assim desfará  a sepultura aos que  pecaram.

[[v18-24-20]]

^<<v18-24-20,20>>^ A madre se esquecerá deles, os vermes os comerão gostosamente; nunca mais haverá lembrança deles,  e a iniquidade se quebrará como a árvore.

[[v18-24-21]]

^<<v18-24-21,21>>^ Afligem a estéril que  não dá à luz e à viúva não fazem bem;

[[v18-24-22]]

^<<v18-24-22,22>>^ até aos poderosos arrastam com a sua força; se  eles se levantam, não há vida segura.

[[v18-24-23]]

^<<v18-24-23,23>>^ Se Deus  lhes dá descanso, estribam-se nisso; seus olhos, porém, estão  nos caminhos deles.

[[v18-24-24]]

^<<v18-24-24,24>>^ Por um pouco se alçam e logo desaparecem; são abatidos, encerrados como todos os outros e cortados como as pontas das espigas.

[[v18-24-25]]

^<<v18-24-25,25>>^ Se agora não é assim,  quem me desmentirá e desfará as minhas razões?

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]