include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// arc ?, ARC - Almeida Revista e Corrigida

[[v44-14-1]]

^<<v44-14-1,1>>^ E aconteceu que, em Icônio, entraram juntos na sinagoga dos judeus e falaram de tal modo, que creu uma grande multidão, não só de judeus, mas também  de gregos.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus incrédulos incitaram e irritaram, contra os irmãos, os ânimos dos gentios.

[[v44-14-3]]

^<<v44-14-3,3>>^ Detiveram-se, pois, muito tempo, falando ousadamente acerca do Senhor, o qual dava testemunho à palavra da sua graça, permitindo que por suas mãos se fizessem sinais e prodígios.

[[v44-14-4]]

^<<v44-14-4,4>>^ E dividiu-se a multidão da cidade: uns eram pelos judeus, e outros, pelos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ E, havendo um motim, tanto dos judeus como dos gentios com os seus principais, para os insultarem e apedrejarem,

[[v44-14-6]]

^<<v44-14-6,6>>^ sabendo-o eles, fugiram para Listra e Derbe, cidades da Licaônia, e para a província circunvizinha;

[[v44-14-7]]

^<<v44-14-7,7>>^ e ali pregavam o evangelho.

[[v44-14-8]]

^<<v44-14-8,8>>^ E estava assentado em Listra certo varão leso dos pés, coxo desde o seu nascimento, o qual nunca tinha andado.

[[v44-14-9]]

^<<v44-14-9,9>>^ Este ouviu falar Paulo, que, fixando nele os olhos e vendo que tinha fé para ser curado,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse em voz alta: Levanta-te direito sobre teus pés. E ele saltou e andou.

[[v44-14-11]]

^<<v44-14-11,11>>^ E as multidões, vendo o que Paulo fizera, levantaram a voz, dizendo em língua licaônica: Fizeram-se os deuses semelhantes aos homens e desceram até nós.

[[v44-14-12]]

^<<v44-14-12,12>>^ E chamavam Júpiter a Barnabé, e Mercúrio, a Paulo, porque este era o que falava.

[[v44-14-13]]

^<<v44-14-13,13>>^ E o sacerdote de Júpiter, cujo templo  estava em frente da cidade, trazendo para a entrada da porta touros e grinaldas, queria com a multidão sacrificar- lhes.

[[v44-14-14]]

^<<v44-14-14,14>>^ Ouvindo, porém, isto  os apóstolos Barnabé e Paulo, rasgaram as suas vestes e saltaram para o meio da multidão, clamando

[[v44-14-15]]

^<<v44-14-15,15>>^ e dizendo: Varões, por que fazeis essas coisas?  Nós também somos homens como vós, sujeitos às mesmas paixões, e vos anunciamos que vos convertais dessas vaidades ao Deus vivo, que fez o céu, e a terra, e o mar, e tudo quanto há neles;

[[v44-14-16]]

^<<v44-14-16,16>>^ o qual, nos tempos passados, deixou andar todos os povos em seus próprios caminhos;

[[v44-14-17]]

^<<v44-14-17,17>>^ contudo, não se deixou a si mesmo sem testemunho, beneficiando-vos lá do céu, dando-vos chuvas e tempos frutíferos, enchendo de mantimento e de alegria o vosso coração.

[[v44-14-18]]

^<<v44-14-18,18>>^ Dizendo isto, com dificuldade impediram que as multidões lhes sacrificassem.

[[v44-14-19]]

^<<v44-14-19,19>>^ Sobrevieram, porém, uns judeus de Antioquia e de Icônio, que, tendo convencido a multidão, apedrejaram a Paulo e o arrastaram para fora da cidade, cuidando que estava morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ Mas, rodeando-o os discípulos, levantou-se e entrou na cidade. E, no dia seguinte, saiu, com Barnabé, para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ E, tendo anunciado o evangelho naquela cidade e feito muitos discípulos, voltaram para Listra, e Icônio, e Antioquia,

[[v44-14-22]]

^<<v44-14-22,22>>^ confirmando o ânimo dos discípulos, exortando-os a permanecer na fé, pois que por muitas tribulações nos importa entrar no Reino de Deus.

[[v44-14-23]]

^<<v44-14-23,23>>^ E, havendo-lhes por comum consentimento eleito anciãos em cada igreja, orando com jejuns, os encomendaram ao Senhor em quem haviam crido.

[[v44-14-24]]

^<<v44-14-24,24>>^ Passando depois por Pisídia, dirigiram-se a Panfília.

[[v44-14-25]]

^<<v44-14-25,25>>^ E, tendo anunciado a palavra em Perge, desceram a Atália.

[[v44-14-26]]

^<<v44-14-26,26>>^ E dali navegaram para Antioquia, onde tinham sido recomendados à graça de Deus para a obra que já haviam cumprido.

[[v44-14-27]]

^<<v44-14-27,27>>^ E, quando chegaram e reuniram a igreja, relataram quão grandes coisas Deus fizera por eles e como abrira aos gentios a porta da fé.

[[v44-14-28]]

^<<v44-14-28,28>>^ E ficaram ali não pouco tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]