include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// arc ?, ARC - Almeida Revista e Corrigida

[[v14-25-1]]

^<<v14-25-1,1>>^ Era Amazias da idade de vinte e cinco anos quando começou a reinar e reinou vinte e nove anos em Jerusalém; e era  o nome de sua mãe Jeoadã, de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ E fez o que era  reto aos olhos do SENHOR, porém não com coração inteiro.

[[v14-25-3]]

^<<v14-25-3,3>>^ Sucedeu, pois, que, sendo-lhe o reino já confirmado, matou os seus servos que feriram o rei, seu pai;

[[v14-25-4]]

^<<v14-25-4,4>>^ porém não matou os seus filhos, mas fez como na Lei está  escrito, no livro de Moisés, como o SENHOR ordenou, dizendo: Não morrerão os pais pelos filhos, nem os filhos morrerão pelos pais; mas cada um morrerá pelo seu pecado.

[[v14-25-5]]

^<<v14-25-5,5>>^ E Amazias ajuntou a Judá e o pôs segundo as casas dos pais, por chefes de milhares e por chefes de centenas, por todo o Judá e Benjamim; e os numerou de vinte anos e daí  para cima e achou deles trezentos mil escolhidos que saíam ao exército e levavam lança e escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Também de Israel tomou a soldo cem mil varões valentes, por cem talentos de prata.

[[v14-25-7]]

^<<v14-25-7,7>>^ Porém um homem de Deus veio a ele, dizendo: Ó rei, não deixes ir contigo o exército de Israel, porque o SENHOR não é  com Israel, a saber, com  os filhos de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Se porém, fores, faze-o, esforça-te para a peleja; Deus te fará cair diante do inimigo, porque força há em Deus para ajudar e para fazer cair.

[[v14-25-9]]

^<<v14-25-9,9>>^ E disse Amazias ao homem de Deus: Que se fará, pois, dos cem talentos de prata que dei às tropas de Israel? E disse o homem de Deus: Mais tem o SENHOR que te dar do que isso.

[[v14-25-10]]

^<<v14-25-10,10>>^ Então, separou Amazias as tropas que lhe tinham vindo de Efraim, para que se fossem ao seu lugar; pelo que se acendeu a sua ira contra Judá, e voltaram para o seu lugar em ardor de ira.

[[v14-25-11]]

^<<v14-25-11,11>>^ Esforçou-se, pois, Amazias, e conduziu o seu povo, e foi-se ao vale do Sal; e feriu dos filhos de Seir dez mil.

[[v14-25-12]]

^<<v14-25-12,12>>^ Também os filhos de Judá prenderam vivos dez mil, e os trouxeram ao cume da rocha, e do mais alto da rocha os lançaram abaixo, e todos arrebentaram.

[[v14-25-13]]

^<<v14-25-13,13>>^ Porém os homens das tropas que Amazias despedira para que não fossem com ele à peleja deram sobre as cidades de Judá, desde Samaria até Bete-Horom; e feriram deles três mil e saquearam grande despojo.

[[v14-25-14]]

^<<v14-25-14,14>>^ E sucedeu que, depois que Amazias veio da matança dos edomitas, trouxe consigo os deuses dos filhos de Seir, tomou-os por seus deuses, e prostrou-se diante deles, e queimou-lhes incenso.

[[v14-25-15]]

^<<v14-25-15,15>>^ Então, a ira do SENHOR se acendeu contra Amazias, e mandou-lhe um  profeta, que lhe disse: Por que buscaste deuses do povo, que a seu povo não livraram das tuas mãos?

[[v14-25-16]]

^<<v14-25-16,16>>^ E sucedeu que, falando-lhe ele, lhe respondeu: Puseram-te por conselheiro do rei? Cala-te, por que te feririam? Então, o profeta parou e disse: Bem vejo eu que já Deus deliberou destruir-te, porquanto fizeste isso e não deste ouvidos a meu conselho.

[[v14-25-17]]

^<<v14-25-17,17>>^ E, tendo tomado conselho, Amazias, rei de Judá, enviou a Joás, filho de Jeoacaz, filho de Jeú, rei de Israel, a dizer: Vem, vejamo-nos face a face.

[[v14-25-18]]

^<<v14-25-18,18>>^ Porém Joás, rei de Israel, mandou dizer a Amazias, rei de Judá: O cardo que estava no Líbano mandou dizer ao cedro que estava no Líbano: Dá tua filha a meu filho por mulher; porém os animais do campo que estão  no Líbano passaram e pisaram o cardo.

[[v14-25-19]]

^<<v14-25-19,19>>^ Tu dizes: Eis que tenho ferido os edomitas, e elevou-se o teu coração, para te gloriares; agora, pois,  fica em tua casa; por que te meterias no mal, para caíres tu e Judá contigo?

[[v14-25-20]]

^<<v14-25-20,20>>^ Porém Amazias não lhe  deu ouvidos, porque isto vinha de Deus, para entregá-los nas mãos dos seus inimigos,  porquanto buscaram os deuses dos edomitas.

[[v14-25-21]]

^<<v14-25-21,21>>^ E Joás, rei de Israel, subiu; e ele e Amazias, rei de Judá, viram-se face a face em Bete-Semes, que está  em Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ E Judá foi ferido diante de Israel, e foi cada um para as suas tendas.

[[v14-25-23]]

^<<v14-25-23,23>>^ E Joás, rei de Israel, prendeu a Amazias, rei de Judá, filho de Joás, o filho de Jeoacaz, em Bete-Semes, e o trouxe a Jerusalém; e derribou o muro de Jerusalém, desde a Porta de Efraim até à Porta da Esquina, um trecho de quatrocentos côvados.

[[v14-25-24]]

^<<v14-25-24,24>>^ Também tomou  todo o ouro, e a prata, e todos os utensílios que se acharam na Casa de Deus com Obede-Edom, e os tesouros da casa do rei, e os reféns e voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ E viveu Amazias, filho de Joás, rei de Judá, depois da morte de Joás, filho de Jeoacaz, rei de Israel, quinze anos.

[[v14-25-26]]

^<<v14-25-26,26>>^ Quanto ao mais dos atos de Amazias, tanto os primeiros como os últimos, eis que, porventura,  não estão  escritos no livro da história dos reis de Judá e de Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ E, desde o tempo que Amazias se desviou do SENHOR, conspiraram contra ele em Jerusalém, porém ele fugiu para Laquis; mas enviaram após ele a Laquis e o mataram ali.

[[v14-25-28]]

^<<v14-25-28,28>>^ E o trouxeram sobre cavalos e o sepultaram com seus pais na Cidade de Davi.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]