include::./index.adoc[]

[[v14-20-0]]
=== 2 Crônicas, 20
// arc ?, ARC - Almeida Revista e Corrigida

[[v14-20-1]]

^<<v14-20-1,1>>^ E sucedeu que, depois disso, os filhos de Moabe, e os filhos de Amom, e, com eles, alguns outros  dos amonitas vieram à peleja contra Josafá.

[[v14-20-2]]

^<<v14-20-2,2>>^ Então, vieram alguns  que deram aviso a Josafá, dizendo: Vem contra ti uma  grande multidão dalém do mar e da Síria; e eis que já estão  em Hazazom-Tamar, que é  En-Gedi.

[[v14-20-3]]

^<<v14-20-3,3>>^ Então, Josafá temeu e pôs-se a buscar o SENHOR; e apregoou jejum em todo o Judá.

[[v14-20-4]]

^<<v14-20-4,4>>^ E Judá se ajuntou, para pedir socorro  ao SENHOR; também de todas as cidades de Judá vieram para buscarem o SENHOR.

[[v14-20-5]]

^<<v14-20-5,5>>^ E pôs-se Josafá em pé na congregação de Judá e de Jerusalém, na Casa do SENHOR, diante do pátio novo.

[[v14-20-6]]

^<<v14-20-6,6>>^ E disse: Ah! SENHOR, Deus de nossos pais, porventura,  não és  tu Deus nos céus? Pois tu és dominador sobre todos os reinos das gentes, e na tua mão há  força e poder, e não há quem te possa resistir.

[[v14-20-7]]

^<<v14-20-7,7>>^ Porventura,  ó Deus nosso, não lançaste tu fora os moradores desta terra, de diante do teu povo de Israel, e não a deste à semente de Abraão, teu amigo, para sempre?

[[v14-20-8]]

^<<v14-20-8,8>>^ E habitaram nela e edificaram nela um santuário ao teu nome, dizendo:

[[v14-20-9]]

^<<v14-20-9,9>>^ Se algum  mal nos sobrevier, espada, juízo, peste ou fome, nós nos apresentaremos diante desta casa e diante de ti; pois teu nome está  nesta casa; e clamaremos a ti na nossa angústia, e tu nos ouvirás e livrarás.

[[v14-20-10]]

^<<v14-20-10,10>>^ Agora, pois, eis que os filhos de Amom e de Moabe e os das montanhas de Seir, pelos quais não permitiste que passasse Israel, quando vinham da terra do Egito, mas deles se desviaram e não o destruíram,

[[v14-20-11]]

^<<v14-20-11,11>>^ eis que nos dão o pago, vindo para lançar-nos fora da herança que nos fizeste herdar.

[[v14-20-12]]

^<<v14-20-12,12>>^ Ah! Deus nosso, porventura,  não os julgarás? Porque em nós não há força perante esta grande multidão que vem contra nós, e não sabemos nós o que faremos; porém os nossos olhos estão postos  em ti.

[[v14-20-13]]

^<<v14-20-13,13>>^ E todo o Judá estava em pé perante o SENHOR, como também as suas crianças, as suas mulheres e os seus filhos.

[[v14-20-14]]

^<<v14-20-14,14>>^ Então, veio o Espírito do SENHOR, no meio da congregação, sobre Jaaziel, filho de Zacarias, filho de Benaías, filho de Jeiel, filho de Matanias, levita, dos filhos de Asafe,

[[v14-20-15]]

^<<v14-20-15,15>>^ e Jaaziel disse: Dai ouvidos todo o Judá, e vós,  moradores de Jerusalém, e tu,  ó rei Josafá. Assim o SENHOR vos diz: Não temais, nem vos assusteis por causa desta grande multidão, pois a peleja não é vossa, senão de Deus.

[[v14-20-16]]

^<<v14-20-16,16>>^ Amanhã, descereis contra eles; eis que sobem pela ladeira de Ziz, e os achareis no fim do vale, diante do deserto de Jeruel.

[[v14-20-17]]

^<<v14-20-17,17>>^ Nesta peleja,  não tereis de pelejar; parai, estai em pé e vede a salvação do SENHOR para convosco, ó Judá e Jerusalém; não temais, nem vos assusteis; amanhã, saí-lhes ao encontro, porque o Senhor será  convosco.

[[v14-20-18]]

^<<v14-20-18,18>>^ Então, Josafá se prostrou com o rosto em terra; e todo o Judá e os moradores de Jerusalém se lançaram perante o SENHOR, adorando o SENHOR.

[[v14-20-19]]

^<<v14-20-19,19>>^ E levantaram-se os levitas, dos filhos dos coatitas e dos filhos dos coraítas, para louvarem o SENHOR, Deus de Israel, com voz muito alta.

[[v14-20-20]]

^<<v14-20-20,20>>^ E, pela manhã cedo, se levantaram e saíram ao deserto de Tecoa; e, saindo eles, pôs-se em pé Josafá e disse: Ouvi-me, ó Judá e vós, moradores de Jerusalém: Crede no SENHOR, vosso Deus, e estareis seguros; crede nos seus profetas e prosperareis.

[[v14-20-21]]

^<<v14-20-21,21>>^ E aconselhou-se com o povo e ordenou cantores para o SENHOR, que louvassem a majestade santa, saindo diante dos armados e dizendo: Louvai o SENHOR, porque a sua benignidade dura  para sempre.

[[v14-20-22]]

^<<v14-20-22,22>>^ E, ao tempo em que começaram com júbilo e louvor, o SENHOR pôs emboscadas contra os filhos de Amom e de Moabe e os das montanhas de Seir, que vieram contra Judá e foram desbaratados.

[[v14-20-23]]

^<<v14-20-23,23>>^ Porque os filhos de Amom e de Moabe se levantaram contra os moradores das montanhas de Seir, para os destruir e exterminar; e, acabando eles com os moradores de Seir, ajudaram uns aos outros a destruir-se.

[[v14-20-24]]

^<<v14-20-24,24>>^ Entretanto, chegou Judá à atalaia do deserto; e olharam para a multidão, e eis que eram  corpos mortos, que jaziam em terra, e nenhum escapou.

[[v14-20-25]]

^<<v14-20-25,25>>^ E vieram Josafá e o seu povo para saquear os despojos e acharam neles fazenda e cadáveres em abundância, como também objetos preciosos; e tomaram para si tanto, que não podiam levar mais; três dias saquearam o despojo, porque era muito.

[[v14-20-26]]

^<<v14-20-26,26>>^ E, ao quarto dia, se ajuntaram no vale de Beraca, porque ali louvaram o SENHOR; por isso, chamaram àquele lugar vale de Beraca, até ao dia de hoje.

[[v14-20-27]]

^<<v14-20-27,27>>^ Então, voltaram todos os homens de Judá e de Jerusalém, e Josafá, à frente deles, para irem a Jerusalém com alegria, porque o SENHOR os alegrara acerca dos seus inimigos.

[[v14-20-28]]

^<<v14-20-28,28>>^ E foram a Jerusalém com alaúdes, e com harpas, e com trombetas, para a Casa do SENHOR.

[[v14-20-29]]

^<<v14-20-29,29>>^ E veio o temor de Deus sobre todos os reinos daquelas terras, ouvindo eles  que o SENHOR havia pelejado contra os inimigos de Israel.

[[v14-20-30]]

^<<v14-20-30,30>>^ E o reino de Josafá ficou quieto e o seu Deus lhe deu repouso em redor.

[[v14-20-31]]

^<<v14-20-31,31>>^ E Josafá reinou sobre Judá; era  da idade de trinta e cinco anos quando começou a reinar e vinte e cinco anos reinou em Jerusalém; e era o nome de sua mãe Azuba, filha de Sili.

[[v14-20-32]]

^<<v14-20-32,32>>^ E andou nos caminhos de Asa, seu pai, e não se desviou dele, fazendo o que era  reto aos olhos do SENHOR.

[[v14-20-33]]

^<<v14-20-33,33>>^ Contudo, os altos se não tiraram, porque o povo não tinha ainda preparado o coração para com o Deus de seus pais.

[[v14-20-34]]

^<<v14-20-34,34>>^ Ora, o resto dos atos de Josafá, tanto os primeiros como os últimos, eis que está  escrito nas notas de Jeú, filho de Hanani, que as inseriu no livro da história dos reis de Israel.

[[v14-20-35]]

^<<v14-20-35,35>>^ Porém, depois disso, Josafá, rei de Judá, se aliou com Acazias, rei de Israel, que procedeu com toda a impiedade.

[[v14-20-36]]

^<<v14-20-36,36>>^ E aliou-se com ele, para fazerem navios que fossem a Társis; e fizeram os navios em Eziom-Geber.

[[v14-20-37]]

^<<v14-20-37,37>>^ Porém Eliézer, filho de Dodavá, de Maressa, profetizou contra Josafá, dizendo: Visto que te aliaste com Acazias, o SENHOR despedaçou as tuas obras. E os navios se quebraram e não puderam ir a Társis.

'''

xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[Próximo Capítulo &#62;]