include::./index.adoc[]

[[v14-23-0]]
=== 2 Crônicas, 23
// arc ?, ARC - Almeida Revista e Corrigida

[[v14-23-1]]

^<<v14-23-1,1>>^ Porém, no sétimo ano, Joiada se esforçou e tomou consigo em aliança os chefes das centenas: Azarias, filho de Jeroão, e Ismael, filho de Joanã, e Azarias, filho de Obede, e Maaseias, filho de Adaías, e Elisafate, filho de Zicri.

[[v14-23-2]]

^<<v14-23-2,2>>^ Estes rodearam Judá, e ajuntaram os levitas de todas as cidades de Judá e os cabeças dos pais de Israel, e vieram para Jerusalém.

[[v14-23-3]]

^<<v14-23-3,3>>^ E toda aquela congregação fez aliança com o rei na Casa de Deus; e Joiada  lhes disse: Eis que o filho do rei reinará, como o SENHOR falou a respeito dos filhos de Davi.

[[v14-23-4]]

^<<v14-23-4,4>>^ Esta é  a coisa que haveis de fazer: uma terça parte de vós, sacerdotes e levitas que entram de sábado, será  formada de porteiros;

[[v14-23-5]]

^<<v14-23-5,5>>^ e uma terça parte estará  na casa do rei, e a outra terça parte, à porta do fundamento; e todo o povo estará  nos pátios da Casa do SENHOR.

[[v14-23-6]]

^<<v14-23-6,6>>^ Porém ninguém entre na Casa do SENHOR, senão os sacerdotes e os levitas que ministram; estes entrarão porque santos são; mas todo o povo guardará o preceito do SENHOR.

[[v14-23-7]]

^<<v14-23-7,7>>^ E os levitas rodearão ao rei, cada um com as armas na mão; e qualquer que entrar na casa morrerá; porém vós estareis com o rei quando entrar e quando sair.

[[v14-23-8]]

^<<v14-23-8,8>>^ E fizeram os levitas e todo o Judá conforme tudo o que ordenara o sacerdote Joiada; e tomou cada um os seus homens, os que entravam no sábado com os que saíam no sábado; porque o sacerdote Joiada não tinha despedido as turmas.

[[v14-23-9]]

^<<v14-23-9,9>>^ Também o sacerdote Joiada deu aos chefes das centenas as lanças, e os escudos, e as rodelas que foram  do rei Davi, os quais estavam  na Casa de Deus.

[[v14-23-10]]

^<<v14-23-10,10>>^ E dispôs todo o povo, e a cada um com as armas na mão, desde a banda direita da casa até à banda esquerda da casa, da banda do altar e da casa, à roda do rei.

[[v14-23-11]]

^<<v14-23-11,11>>^ Então, tiraram para fora ao filho do rei, e lhe puseram a coroa, e deram-lhe  o testemunho, e o fizeram rei; e Joiada e seus filhos o ungiram e disseram: Viva o rei!

[[v14-23-12]]

^<<v14-23-12,12>>^ Ouvindo, pois, Atalia a voz do povo, que corria para louvar o rei, veio ao povo à Casa do SENHOR.

[[v14-23-13]]

^<<v14-23-13,13>>^ E olhou, e eis que o rei estava perto da sua coluna, à entrada, e os chefes e as trombetas, junto ao rei; e todo o povo da terra estava alegre e tocava as trombetas; e também os cantores tocavam instrumentos músicos e davam a entender que se deviam cantar louvores; então, Atalia rasgou as suas vestes e clamou: Traição, traição!

[[v14-23-14]]

^<<v14-23-14,14>>^ Porém o sacerdote Joiada tirou para fora os capitães que estavam  postos sobre o exército e disse-lhes: Tirai-a para fora das fileiras, e o que a seguir morrerá à espada; porque dissera o sacerdote: Não a matareis na Casa do SENHOR.

[[v14-23-15]]

^<<v14-23-15,15>>^ E eles lhe lançaram as mãos, e ela foi à entrada da Porta dos Cavalos, da casa do rei; e ali a mataram.

[[v14-23-16]]

^<<v14-23-16,16>>^ E Joiada fez aliança entre si, e o povo, e o rei, para serem eles o povo do SENHOR.

[[v14-23-17]]

^<<v14-23-17,17>>^ Depois, todo o povo entrou na casa de Baal e a derribou; eles quebraram os seus altares e as suas imagens e a Matã, sacerdote de Baal, mataram diante dos altares.

[[v14-23-18]]

^<<v14-23-18,18>>^ E Joiada ordenou os ofícios na Casa do SENHOR, debaixo das mãos dos sacerdotes, os levitas a quem Davi designara na Casa do SENHOR para oferecerem os holocaustos do SENHOR, como está  escrito na Lei de Moisés, com alegria e com canto, conforme a instituição de Davi.

[[v14-23-19]]

^<<v14-23-19,19>>^ E pôs porteiros às portas da Casa do SENHOR, para que não entrasse nela ninguém imundo em coisa alguma.

[[v14-23-20]]

^<<v14-23-20,20>>^ E Joiada tomou os capitães de cem, e os poderosos, e os que tinham domínio entre o povo e todo o povo da terra, e conduziram o rei da Casa do SENHOR, e entraram na casa do rei pela porta maior, e assentaram o rei no trono do reino.

[[v14-23-21]]

^<<v14-23-21,21>>^ E todo o povo da terra se alegrou, e a cidade ficou em paz, depois que mataram Atalia à espada.

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]