include::./index.adoc[]

[[v14-12-0]]
=== 2 Crônicas, 12
// arc ?, ARC - Almeida Revista e Corrigida

[[v14-12-1]]

^<<v14-12-1,1>>^ Sucedeu, pois, que, havendo Roboão confirmado o reino e havendo-se fortalecido, deixou a lei do SENHOR, e, com ele, todo o Israel.

[[v14-12-2]]

^<<v14-12-2,2>>^ Pelo que sucedeu, no ano quinto do rei Roboão, que Sisaque, rei do Egito, subiu contra Jerusalém (porque tinham transgredido contra o SENHOR)

[[v14-12-3]]

^<<v14-12-3,3>>^ com mil e duzentos carros e com sessenta mil cavaleiros; e era inumerável a gente que vinha com ele do Egito, tanto de líbios como suquitas e etíopes.

[[v14-12-4]]

^<<v14-12-4,4>>^ E tomou as cidades fortes que Judá tinha e veio a Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ Então, veio Semaías, o profeta, a Roboão e aos príncipes de Judá que se ajuntaram em Jerusalém por causa de Sisaque e disse-lhes: Assim diz o SENHOR: Vós  me deixastes a mim, pelo que eu também vos deixei nas mãos de Sisaque.

[[v14-12-6]]

^<<v14-12-6,6>>^ Então, se humilharam os príncipes de Israel e o rei e disseram: O Senhor é  justo.

[[v14-12-7]]

^<<v14-12-7,7>>^ Vendo, pois, o SENHOR que se humilhavam, veio a palavra do SENHOR a Semaías, dizendo: Humilharam-se, não os destruirei; antes, em breve, lhes darei lugar de escaparem, para que o meu furor se não derrame sobre Jerusalém, pelas mãos de Sisaque.

[[v14-12-8]]

^<<v14-12-8,8>>^ Porém serão seus servos, para que conheçam a diferença da  minha servidão e da servidão dos reinos da terra.

[[v14-12-9]]

^<<v14-12-9,9>>^ Subiu, pois, Sisaque, rei do Egito, contra Jerusalém e tomou os tesouros da Casa do SENHOR e os tesouros da casa do rei; levou tudo e também tomou os escudos de ouro que Salomão fizera.

[[v14-12-10]]

^<<v14-12-10,10>>^ E fez o rei Roboão em lugar deles escudos de cobre e os entregou nas mãos dos capitães da guarda que guardavam a porta da casa do rei.

[[v14-12-11]]

^<<v14-12-11,11>>^ E sucedeu que, entrando o rei na Casa do SENHOR, vinham os da guarda, e os traziam, e os tornavam a pôr na câmara da guarda.

[[v14-12-12]]

^<<v14-12-12,12>>^ E, humilhando-se ele, a ira do SENHOR se desviou dele, para que o não destruísse de todo, porque ainda em Judá havia boas coisas.

[[v14-12-13]]

^<<v14-12-13,13>>^ Fortificou-se, pois, o rei Roboão em Jerusalém e reinou. Ora, Roboão era da idade de quarenta e um anos quando começou a reinar; e dezessete anos reinou em Jerusalém, a cidade que o SENHOR escolheu dentre todas as tribos de Israel, para pôr ali o seu nome; e era  o nome de sua mãe Naamá, amonita.

[[v14-12-14]]

^<<v14-12-14,14>>^ E fez o que era mau, porquanto não preparou o coração para buscar o SENHOR.

[[v14-12-15]]

^<<v14-12-15,15>>^ Os atos, pois, de Roboão, tanto os primeiros como os últimos, porventura,  não estão  escritos nos livros da história de Semaías, o profeta, e de Ido, o vidente, conforme a relação das genealogias? E houve guerras entre Roboão e Jeroboão em todos os seus  dias.

[[v14-12-16]]

^<<v14-12-16,16>>^ E Roboão dormiu com seus pais e foi sepultado na Cidade de Davi; e Abias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]