include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// arc ?, ARC - Almeida Revista e Corrigida

[[v14-33-1]]

^<<v14-33-1,1>>^ Tinha Manassés doze anos de idade quando começou a reinar e cinquenta e cinco anos reinou em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ E fez o que era  mal aos olhos do SENHOR, conforme as abominações dos gentios que o SENHOR lançara de diante dos filhos de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ Porque tornou a edificar os altos que Ezequias, seu pai, tinha derribado, e levantou altares a baalins, e fez bosques, e prostrou-se diante de todo o exército dos céus, e o serviu.

[[v14-33-4]]

^<<v14-33-4,4>>^ E edificou altares na Casa do SENHOR, da qual o SENHOR tinha dito: Em Jerusalém estará o meu nome eternamente.

[[v14-33-5]]

^<<v14-33-5,5>>^ Edificou altares a todo o exército dos céus, em ambos os pátios da Casa do SENHOR.

[[v14-33-6]]

^<<v14-33-6,6>>^ Fez ele também passar os seus filhos pelo fogo no vale do Filho de Hinom, e usou de adivinhações, e de agouros, e de feitiçarias, e consultou adivinhos e encantadores, e  fez muitíssimo mal aos olhos do SENHOR, para o provocar à ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Também pôs uma imagem esculpida, o ídolo que tinha feito, na Casa de Deus, da qual Deus tinha dito a Davi e a Salomão, seu filho: Nesta casa, em Jerusalém, que escolhi dentre todas as tribos de Israel, porei eu o meu nome para sempre;

[[v14-33-8]]

^<<v14-33-8,8>>^ e nunca mais removerei o pé de Israel da terra que destinei a vossos pais, contanto que tenham cuidado de fazer tudo o que eu lhes ordenei, conforme toda a lei, e estatutos, e juízos dados  pelas mãos de Moisés.

[[v14-33-9]]

^<<v14-33-9,9>>^ E Manassés tanto fez errar a Judá e aos moradores de Jerusalém, que fizeram pior do que as nações que o SENHOR tinha destruído de diante dos filhos de Israel.

[[v14-33-10]]

^<<v14-33-10,10>>^ E falou o SENHOR a Manassés e ao seu povo, porém não deram ouvidos.

[[v14-33-11]]

^<<v14-33-11,11>>^ Pelo que o SENHOR trouxe sobre eles os príncipes do exército do rei da Assíria, os quais prenderam Manassés entre os espinhais, e o amarraram com cadeias, e o levaram à Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ E ele, angustiado, orou deveras ao SENHOR, seu Deus, e humilhou-se muito perante o Deus de seus pais,

[[v14-33-13]]

^<<v14-33-13,13>>^ e lhe fez oração, e Deus se aplacou para com ele, e ouviu a sua súplica, e o tornou a trazer a Jerusalém, ao seu reino; então, reconheceu Manassés que o SENHOR é Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ E, depois disso edificou o muro de fora da Cidade de Davi, ao ocidente de Giom, no vale, e à entrada da Porta do Peixe, e à roda, até Ofel, e o levantou mui alto; também pôs oficiais valentes em todas as cidades fortes de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ E tirou da Casa do SENHOR os deuses estranhos e o ídolo, como também todos os altares que tinha edificado no monte da Casa do SENHOR e em Jerusalém e os lançou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ E reparou o altar do SENHOR, e ofereceu sobre ele ofertas pacíficas e de louvor, e mandou a Judá que servisse ao SENHOR, Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Mas ainda o povo sacrificava nos altos, mas somente ao SENHOR, seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ O resto, pois, dos atos de Manassés, e a sua oração ao seu Deus, e as palavras dos videntes que lhe falaram em nome do SENHOR, Deus de Israel, eis que estão  no livro da história dos reis de Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ E a sua oração, como Deus  se aplacou para com ele, e todo o seu pecado, e a sua transgressão, e os lugares onde edificou altos e pôs bosques e imagens de escultura, antes que se humilhasse, eis que está tudo  escrito nos livros dos videntes.

[[v14-33-20]]

^<<v14-33-20,20>>^ E dormiu Manassés com seus pais, e o sepultaram em sua casa; Amom, seu filho, reinou em seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Era  Amom da idade de vinte e dois anos quando começou a reinar e dois anos reinou em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ E fez o que era  mal aos olhos do SENHOR, como havia feito Manassés, seu pai, porque Amom sacrificou a todas as imagens de escultura que Manassés, seu pai, tinha feito e as serviu.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas não se humilhou perante o SENHOR, como Manassés, seu pai, se humilhara; antes, multiplicou Amom os seus delitos.

[[v14-33-24]]

^<<v14-33-24,24>>^ E conspiraram contra ele os seus servos e o mataram em sua casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Porém o povo da terra feriu todos quantos conspiraram contra o rei Amom e o povo da terra fez reinar em seu lugar a Josias, seu filho.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]