include::./index.adoc[]

[[v14-7-0]]
=== 2 Crônicas, 7
// arc ?, ARC - Almeida Revista e Corrigida

[[v14-7-1]]

^<<v14-7-1,1>>^ E, acabando Salomão de orar, desceu fogo do céu e consumiu o holocausto e os sacrifícios; e a glória do SENHOR encheu a casa.

[[v14-7-2]]

^<<v14-7-2,2>>^ E os sacerdotes não podiam entrar na Casa do SENHOR, porque a glória do SENHOR tinha enchido a Casa do SENHOR.

[[v14-7-3]]

^<<v14-7-3,3>>^ E todos os filhos de Israel, vendo descer o fogo e a glória do SENHOR sobre a casa, encurvaram-se com o rosto em terra sobre o pavimento, e adoraram, e louvaram o SENHOR, porque é  bom, porque a sua benignidade dura  para sempre.

[[v14-7-4]]

^<<v14-7-4,4>>^ E o rei e todo o povo ofereciam sacrifícios perante o SENHOR.

[[v14-7-5]]

^<<v14-7-5,5>>^ E o rei Salomão ofereceu sacrifícios de bois, vinte e dois mil, e de ovelhas, cento e vinte mil; e o rei e todo o povo consagraram a Casa de Deus.

[[v14-7-6]]

^<<v14-7-6,6>>^ E os sacerdotes, segundo as suas turmas, estavam em pé, como também os levitas com os instrumentos músicos do SENHOR, que o rei Davi tinha feito, para louvarem o SENHOR, porque a sua benignidade dura  para sempre, quando Davi o louvava pelo ministério deles; e os sacerdotes tocavam as trombetas defronte deles, e todo o Israel estava em pé.

[[v14-7-7]]

^<<v14-7-7,7>>^ E Salomão santificou o meio do pátio que estava  diante da Casa do SENHOR; porquanto ali tinha ele oferecido os holocaustos e a gordura dos sacrifícios pacíficos; porque no altar de metal, que Salomão tinha feito, não poderia caber o holocausto, e a oferta de manjares, e a gordura.

[[v14-7-8]]

^<<v14-7-8,8>>^ E, assim, naquele tempo, celebrou Salomão a festa sete dias, e todo o Israel com ele, uma muito grande congregação, desde a entrada de Hamate até ao rio do Egito.

[[v14-7-9]]

^<<v14-7-9,9>>^ E, ao dia oitavo, celebraram o dia da restrição, porque sete dias celebraram a consagração do altar e sete dias, a festa.

[[v14-7-10]]

^<<v14-7-10,10>>^ E, no dia vigésimo terceiro do sétimo mês, o rei deixou ir o povo para as suas tendas, alegres e de bom ânimo, pelo bem que o SENHOR tinha feito a Davi, e a Salomão, e a seu povo de Israel.

[[v14-7-11]]

^<<v14-7-11,11>>^ Assim, Salomão acabou a Casa do SENHOR e a casa do rei; e tudo quanto Salomão intentou fazer na Casa do SENHOR e na sua casa, prosperamente o efetuou.

[[v14-7-12]]

^<<v14-7-12,12>>^ E o SENHOR apareceu de noite a Salomão e disse-lhe: Ouvi tua oração e escolhi para mim este lugar para casa de sacrifício.

[[v14-7-13]]

^<<v14-7-13,13>>^ Se eu cerrar os céus, e não houver chuva, ou se ordenar aos gafanhotos que consumam a terra, ou se enviar a peste entre o meu povo;

[[v14-7-14]]

^<<v14-7-14,14>>^ e se  o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ Agora, estarão abertos os meus olhos e atentos os meus ouvidos à oração deste lugar.

[[v14-7-16]]

^<<v14-7-16,16>>^ Porque, agora, escolhi e santifiquei esta casa, para que o meu nome esteja nela perpetuamente; e nela estarão fixos os meus olhos e o meu coração todos os dias.

[[v14-7-17]]

^<<v14-7-17,17>>^ Quanto a ti, se andares diante de mim, como andou Davi, teu pai, e fizeres conforme tudo o que te ordenei, e guardares os meus estatutos e os meus juízos,

[[v14-7-18]]

^<<v14-7-18,18>>^ também confirmarei o trono do teu reino, conforme o concerto que fiz com Davi, teu pai, dizendo: Não te faltará varão que domine em Israel.

[[v14-7-19]]

^<<v14-7-19,19>>^ Porém, se vós vos desviardes, e deixardes os meus estatutos e os meus mandamentos, que vos tenho proposto, e fordes, e servirdes a outros deuses, e vos prostrardes a eles,

[[v14-7-20]]

^<<v14-7-20,20>>^ então, os arrancarei da minha terra que lhes dei, e lançarei da minha presença esta casa que consagrei ao meu nome, e farei com que seja por provérbio e mote entre todas as gentes.

[[v14-7-21]]

^<<v14-7-21,21>>^ E, desta casa, que fora tão exaltada, qualquer que passar por ela se espantará e dirá: Por que fez o SENHOR assim com esta terra e com esta casa?

[[v14-7-22]]

^<<v14-7-22,22>>^ E dirão: Porquanto deixaram o SENHOR, Deus de seus pais, que os tirou da terra do Egito, e se deram a outros deuses, e se prostraram a eles, e os serviram; por isso, ele trouxe sobre eles todo este mal.

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]