include::./index.adoc[]

[[v2-17-0]]
=== Êxodo, 17
// arc ?, ARC - Almeida Revista e Corrigida

[[v2-17-1]]

^<<v2-17-1,1>>^ Depois, toda a congregação dos filhos de Israel partiu do deserto de Sim pelas suas jornadas, segundo o mandamento do SENHOR, e acamparam em Refidim; e não havia ali  água para o povo beber.

[[v2-17-2]]

^<<v2-17-2,2>>^ Então, contendeu o povo com Moisés e disse: Dá-nos água para beber. E Moisés lhes disse: Por que contendeis comigo? Por que tentais ao SENHOR?

[[v2-17-3]]

^<<v2-17-3,3>>^ Tendo, pois, ali o povo sede de água, o povo murmurou contra Moisés e disse: Por que nos fizeste subir do Egito para nos matares de sede, a nós, e aos nossos filhos, e ao nosso gado?

[[v2-17-4]]

^<<v2-17-4,4>>^ E clamou Moisés ao SENHOR, dizendo: Que farei a este povo? Daqui a pouco me apedrejarão.

[[v2-17-5]]

^<<v2-17-5,5>>^ Então, disse o SENHOR a Moisés: Passa diante do povo e toma contigo alguns  dos anciãos de Israel; e toma na tua mão a tua vara, com que feriste o rio, e vai.

[[v2-17-6]]

^<<v2-17-6,6>>^ Eis que eu estarei ali diante de ti sobre a rocha, em Horebe, e tu ferirás a rocha, e dela sairão águas, e o povo beberá. E Moisés assim o fez, diante dos olhos dos anciãos de Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ E chamou o nome daquele lugar Massá e Meribá, por causa da contenda dos filhos de Israel, e porque tentaram ao SENHOR, dizendo: Está o SENHOR no meio de nós, ou não?

[[v2-17-8]]

^<<v2-17-8,8>>^ Então, veio Amaleque e pelejou contra Israel em Refidim.

[[v2-17-9]]

^<<v2-17-9,9>>^ Pelo que disse Moisés a Josué: Escolhe-nos homens, e sai, e peleja contra Amaleque; amanhã, eu estarei no cume do outeiro, e a vara de Deus estará na minha mão.

[[v2-17-10]]

^<<v2-17-10,10>>^ E fez Josué como Moisés lhe dissera, pelejando contra Amaleque; mas Moisés, Arão e Hur subiram ao cume do outeiro.

[[v2-17-11]]

^<<v2-17-11,11>>^ E acontecia que, quando Moisés levantava a sua mão, Israel prevalecia; mas, quando ele abaixava a sua mão, Amaleque prevalecia.

[[v2-17-12]]

^<<v2-17-12,12>>^ Porém as mãos de Moisés eram  pesadas; por isso, tomaram uma pedra e a puseram debaixo dele, para assentar-se sobre ela; e Arão e Hur sustentaram as suas mãos, um de um lado,  e o outro, do outro; assim ficaram as suas mãos firmes até que o sol se pôs.

[[v2-17-13]]

^<<v2-17-13,13>>^ E, assim, Josué desfez a Amaleque e a seu povo a fio de espada.

[[v2-17-14]]

^<<v2-17-14,14>>^ Então disse o SENHOR a Moisés: Escreve isto para memória num livro e relata-o aos ouvidos de Josué: que eu totalmente hei de riscar a memória de Amaleque de debaixo dos céus.

[[v2-17-15]]

^<<v2-17-15,15>>^ E Moisés edificou um altar e chamou o seu nome: O Senhor é  minha bandeira.

[[v2-17-16]]

^<<v2-17-16,16>>^ E disse: Porquanto jurou o SENHOR, haverá guerra do SENHOR contra Amaleque de geração em geração.

'''

xref:002-exodo/002-exodo-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodo/002-exodo-018.adoc#v2-18-0[Próximo Capítulo &#62;]