include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// arc ?, ARC - Almeida Revista e Corrigida

[[v2-10-1]]

^<<v2-10-1,1>>^ Depois, disse o SENHOR a Moisés: Entra a Faraó, porque tenho agravado o seu coração e o coração de seus servos, para fazer estes meus sinais no meio deles,

[[v2-10-2]]

^<<v2-10-2,2>>^ e para que contes aos ouvidos de teus filhos e dos filhos de teus filhos as coisas que fiz no Egito e os meus sinais que tenho feito entre eles; para que saibais que eu sou  o SENHOR.

[[v2-10-3]]

^<<v2-10-3,3>>^ Assim, foram Moisés e Arão a Faraó e disseram-lhe: Assim diz o SENHOR, o Deus dos hebreus: Até quando recusas humilhar-te diante de mim? Deixa ir o meu povo, para que me sirva.

[[v2-10-4]]

^<<v2-10-4,4>>^ Porque, se ainda  recusares deixar ir o meu povo, eis que trarei amanhã gafanhotos aos teus termos,

[[v2-10-5]]

^<<v2-10-5,5>>^ e cobrirão a face da terra, que a terra não se poderá ver; e eles comerão o resto do que escapou, o que ficou da saraiva; também comerão toda árvore que vos cresce no campo;

[[v2-10-6]]

^<<v2-10-6,6>>^ e encherão as tuas casas, e as casas de todos os teus servos, e as casas de todos os egípcios, como nunca viram teus pais, nem os pais de teus pais, desde o dia em que eles foram sobre a terra até o dia de hoje. E virou-se e saiu da presença de Faraó.

[[v2-10-7]]

^<<v2-10-7,7>>^ E os servos de Faraó disseram-lhe: Até quando este nos dá de ser por laço? Deixa ir os homens, para que sirvam ao SENHOR, seu Deus; ainda não sabes que o Egito está destruído?

[[v2-10-8]]

^<<v2-10-8,8>>^ Então, Moisés e Arão foram levados outra vez a Faraó, e ele  disse-lhes: Ide, servi ao SENHOR, vosso Deus. Quais são os que hão de ir?

[[v2-10-9]]

^<<v2-10-9,9>>^ E Moisés disse: Havemos de ir com nossos meninos e com os nossos velhos; com os nossos filhos, e com as nossas filhas, e com as nossas ovelhas, e com os nossos bois havemos de ir; porque festa do SENHOR temos.

[[v2-10-10]]

^<<v2-10-10,10>>^ Então, ele lhes disse: Seja o SENHOR assim convosco, como eu vos deixarei ir a vós e a vossos filhos; olhai que há mal diante da vossa face.

[[v2-10-11]]

^<<v2-10-11,11>>^ Não será  assim; andai agora vós, varões, e servi ao SENHOR; pois isso é o que pedistes. E os lançaram da face de Faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ Então, disse o SENHOR a Moisés: Estende a tua mão sobre a terra do Egito, para que os gafanhotos venham sobre a terra do Egito e comam toda a erva da terra, tudo o que deixou a saraiva.

[[v2-10-13]]

^<<v2-10-13,13>>^ Então, estendeu Moisés sua vara sobre a terra do Egito, e o SENHOR trouxe sobre a terra um vento oriental todo aquele dia e toda aquela noite; e aconteceu que pela manhã o vento oriental trouxe os gafanhotos.

[[v2-10-14]]

^<<v2-10-14,14>>^ E vieram os gafanhotos sobre toda a terra do Egito e assentaram-se sobre todos os ermos do Egito; mui gravosos foram;  antes destes nunca houve tais gafanhotos, nem depois deles virão outros tais.

[[v2-10-15]]

^<<v2-10-15,15>>^ Porque cobriram a face de toda a terra, de modo que a terra se escureceu; e comeram toda a erva da terra e todo o fruto das árvores, que deixara a saraiva; e não ficou verdura alguma nas árvores, nem erva do campo, em toda a terra do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ Então, Faraó se apressou a chamar a Moisés e a Arão e disse: Pequei contra o SENHOR, vosso Deus, e contra vós.

[[v2-10-17]]

^<<v2-10-17,17>>^ Agora, pois, peço-vos que perdoeis o meu pecado somente desta vez e que oreis ao SENHOR, vosso Deus, que tire de mim somente esta morte.

[[v2-10-18]]

^<<v2-10-18,18>>^ E saiu da presença de Faraó e orou ao SENHOR.

[[v2-10-19]]

^<<v2-10-19,19>>^ Então, o SENHOR trouxe um vento ocidental fortíssimo, o qual levantou os gafanhotos e os lançou no mar Vermelho; nem ainda um gafanhoto ficou em todos os termos do Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ O SENHOR, porém, endureceu o coração de Faraó, e este não deixou ir os filhos de Israel.

[[v2-10-21]]

^<<v2-10-21,21>>^ Então, disse o SENHOR a Moisés: Estende a tua mão para o céu, e virão trevas sobre a terra do Egito, trevas que se apalpem.

[[v2-10-22]]

^<<v2-10-22,22>>^ E Moisés estendeu a sua mão para o céu, e houve trevas espessas em toda a terra do Egito por três dias.

[[v2-10-23]]

^<<v2-10-23,23>>^ Não viu um ao outro, e ninguém se levantou do seu lugar por três dias; mas todos os filhos de Israel tinham luz em suas habitações.

[[v2-10-24]]

^<<v2-10-24,24>>^ Então, Faraó chamou a Moisés e disse: Ide, servi ao SENHOR; somente fiquem vossas ovelhas e vossas vacas; vão também convosco as vossas crianças.

[[v2-10-25]]

^<<v2-10-25,25>>^ Moisés, porém, disse: Tu também darás em nossas mãos sacrifícios e holocaustos, que ofereçamos ao SENHOR, nosso Deus.

[[v2-10-26]]

^<<v2-10-26,26>>^ E também o nosso gado há de ir conosco, nem uma unha ficará; porque daquele havemos de tomar para servir ao SENHOR, nosso Deus; porque não sabemos com que havemos de servir ao SENHOR, até que cheguemos lá.

[[v2-10-27]]

^<<v2-10-27,27>>^ O SENHOR, porém, endureceu o coração de Faraó, e este não os quis deixar ir.

[[v2-10-28]]

^<<v2-10-28,28>>^ E disse-lhe Faraó: Vai-te de mim e guarda-te que não mais vejas o meu rosto; porque, no dia em que vires o meu rosto, morrerás.

[[v2-10-29]]

^<<v2-10-29,29>>^ E disse Moisés: Bem disseste; eu nunca mais verei o teu rosto.

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]