include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// arc ?, ARC - Almeida Revista e Corrigida

[[v2-36-1]]

^<<v2-36-1,1>>^ Assim, trabalharam Bezalel, e Aoliabe, e todo homem sábio de coração a quem o SENHOR dera sabedoria e inteligência, para saberem como haviam de fazer toda obra para o serviço do santuário, conforme tudo o que o SENHOR tinha ordenado.

[[v2-36-2]]

^<<v2-36-2,2>>^ Porque Moisés chamara a Bezalel, e a Aoliabe, e a todo homem sábio de coração em cujo coração o SENHOR tinha dado sabedoria, isto é, a todo aquele a quem o seu coração movera que se chegasse à obra para fazê-la.

[[v2-36-3]]

^<<v2-36-3,3>>^ Tomaram, pois, de diante de Moisés toda oferta alçada que trouxeram os filhos de Israel para a obra do serviço do santuário, para fazê-la; e, ainda, eles lhe traziam cada manhã oferta voluntária.

[[v2-36-4]]

^<<v2-36-4,4>>^ E vieram todos os sábios que faziam toda a obra do santuário, cada um da obra que fazia,

[[v2-36-5]]

^<<v2-36-5,5>>^ e falaram a Moisés, dizendo: O povo traz muito mais do que basta para o serviço da obra que o SENHOR ordenou se fizesse.

[[v2-36-6]]

^<<v2-36-6,6>>^ Então, mandou Moisés que fizessem passar uma voz pelo arraial, dizendo: Nenhum homem nem mulher faça mais obra alguma para a oferta alçada do santuário. Assim, o povo foi proibido de trazer mais,

[[v2-36-7]]

^<<v2-36-7,7>>^ porque tinham material bastante para toda a obra que havia de fazer-se, e ainda sobejava.

[[v2-36-8]]

^<<v2-36-8,8>>^ Assim, todo sábio de coração, entre os que faziam a obra, fez o tabernáculo de dez cortinas, de linho fino torcido, e de pano  azul, e de púrpura, e de carmesim, com  querubins; da obra mais esmerada, as fez.

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de uma cortina era  de vinte e oito côvados, e a largura de outra cortina, de quatro côvados; todas as cortinas tinham  uma mesma medida.

[[v2-36-10]]

^<<v2-36-10,10>>^ E ligou cinco cortinas, uma com a outra; e outras  cinco cortinas ligou uma com a outra.

[[v2-36-11]]

^<<v2-36-11,11>>^ Depois, fez laçadas de fio  azul na borda da última cortina do primeiro agrupamento; assim também fez na borda da primeira cortina do segundo agrupamento.

[[v2-36-12]]

^<<v2-36-12,12>>^ Cinquenta laçadas fez numa cortina e cinquenta laçadas fez na cortina da extremidade do segundo agrupamento; estas laçadas eram contrapostas uma com a outra.

[[v2-36-13]]

^<<v2-36-13,13>>^ Também fez cinquenta colchetes de ouro e com estes colchetes uniu as cortinas uma com a outra; e foi feito, assim, um tabernáculo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fez também cortinas de pelos de  cabras para a tenda sobre o tabernáculo; de onze cortinas a fez.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de uma cortina era de trinta côvados, e a largura de uma cortina, de quatro côvados; estas onze cortinas tinham uma mesma medida.

[[v2-36-16]]

^<<v2-36-16,16>>^ E ele uniu cinco cortinas à parte, e seis cortinas à parte,

[[v2-36-17]]

^<<v2-36-17,17>>^ e fez cinquenta laçadas na borda da última cortina do agrupamento; também fez cinquenta laçadas na borda da cortina do outro agrupamento.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fez também cinquenta colchetes de metal para ajuntar a tenda, para que fosse uma.

[[v2-36-19]]

^<<v2-36-19,19>>^ Fez também para a tenda uma coberta de peles de carneiros tintas de vermelho; e, por cima, uma coberta de peles de texugo.

[[v2-36-20]]

^<<v2-36-20,20>>^ Também fez tábuas levantadas para o tabernáculo, de madeira de  cetim.

[[v2-36-21]]

^<<v2-36-21,21>>^ O comprimento de uma tábua era  de dez côvados, e a largura de cada tábua era  de um côvado e meio.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada tábua tinha duas coiceiras, pregadas uma com a outra; assim fez com todas as tábuas do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ Assim, pois, fez as tábuas para o tabernáculo; vinte tábuas para a banda do sul;

[[v2-36-24]]

^<<v2-36-24,24>>^ e fez quarenta bases de prata debaixo das vinte tábuas; duas bases debaixo de uma tábua para as suas duas coiceiras e duas bases debaixo de outra tábua para as suas duas coiceiras.

[[v2-36-25]]

^<<v2-36-25,25>>^ Também fez vinte tábuas ao outro lado do tabernáculo da banda do norte,

[[v2-36-26]]

^<<v2-36-26,26>>^ com as suas quarenta bases de prata; duas bases debaixo de uma tábua e duas bases debaixo de outra tábua.

[[v2-36-27]]

^<<v2-36-27,27>>^ E ao lado do tabernáculo para o ocidente fez seis tábuas.

[[v2-36-28]]

^<<v2-36-28,28>>^ Fez também duas tábuas para os cantos do tabernáculo aos dois lados,

[[v2-36-29]]

^<<v2-36-29,29>>^ as quais estavam juntas debaixo e também se ajuntavam por cima com uma argola; assim fez com elas ambas nos dois cantos.

[[v2-36-30]]

^<<v2-36-30,30>>^ Assim, eram oito tábuas com as suas bases de prata, a saber,  dezesseis bases; duas bases debaixo de cada tábua.

[[v2-36-31]]

^<<v2-36-31,31>>^ Fez também barras de madeira de cetim; cinco para as tábuas de um lado do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ e cinco barras para as tábuas do outro lado do tabernáculo; e outras  cinco barras para as tábuas do tabernáculo de ambas as bandas do ocidente.

[[v2-36-33]]

^<<v2-36-33,33>>^ E fez que a barra do meio passasse pelo meio das tábuas de uma extremidade até à outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ E cobriu as tábuas de ouro, e as suas argolas (os lugares das barras) fez de ouro; as barras também cobriu de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Depois, fez o véu de pano  azul, e de púrpura, e de carmesim, e de linho fino torcido; de obra esmerada o fez, com  querubins.

[[v2-36-36]]

^<<v2-36-36,36>>^ E fez-lhe quatro colunas de madeira de  cetim e as cobriu de ouro; e seus colchetes fez de ouro e fundiu-lhe quatro bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Fez também para a porta da tenda o véu de pano  azul, e de púrpura, e de carmesim, e de linho fino torcido, da obra de bordador,

[[v2-36-38]]

^<<v2-36-38,38>>^ com as suas cinco colunas e os seus colchetes; e as suas cabeças e as suas molduras cobriu de ouro; e as suas cinco bases eram  de cobre.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]