include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// arc ?, ARC - Almeida Revista e Corrigida

[[v2-16-1]]

^<<v2-16-1,1>>^ E, partidos de Elim, toda a congregação dos filhos de Israel veio ao deserto de Sim, que está  entre Elim e Sinai, aos quinze dias do mês segundo, depois que saíram da terra do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ E toda a congregação dos filhos de Israel murmurou contra Moisés e contra Arão no deserto.

[[v2-16-3]]

^<<v2-16-3,3>>^ E os filhos de Israel disseram-lhes: Quem dera que nós morrêssemos por mão do SENHOR na terra do Egito, quando estávamos sentados junto às panelas de carne, quando comíamos pão até fartar! Porque nos tendes tirado para este deserto, para matardes de fome a toda esta multidão.

[[v2-16-4]]

^<<v2-16-4,4>>^ Então, disse o SENHOR a Moisés: Eis que vos farei chover pão dos céus, e o povo sairá e colherá cada dia a porção para cada dia, para que eu veja se anda em minha lei ou não.

[[v2-16-5]]

^<<v2-16-5,5>>^ E acontecerá, ao sexto dia, que prepararão o que colherem; e será o dobro do que colhem cada dia.

[[v2-16-6]]

^<<v2-16-6,6>>^ Então, disse Moisés e Arão a todos os filhos de Israel: À tarde sabereis que o SENHOR vos tirou da terra do Egito,

[[v2-16-7]]

^<<v2-16-7,7>>^ e amanhã vereis a glória do SENHOR, porquanto ouviu as vossas murmurações contra o SENHOR; porque quem somos  nós para que murmureis contra nós?

[[v2-16-8]]

^<<v2-16-8,8>>^ Disse mais Moisés: Isso será  quando o SENHOR, à tarde, vos der carne para comer e, pela manhã, pão a fartar, porquanto o SENHOR ouviu as vossas murmurações, com que murmurais contra ele (porque quem somos  nós?). As vossas murmurações não são  contra nós, mas sim contra o SENHOR.

[[v2-16-9]]

^<<v2-16-9,9>>^ Depois, disse Moisés a Arão: Dize a toda a congregação dos filhos de Israel: Chegai-vos para diante do SENHOR, porque ouviu as vossas murmurações.

[[v2-16-10]]

^<<v2-16-10,10>>^ E aconteceu que, quando falou Arão a toda a congregação dos filhos de Israel, e eles se viraram para o deserto, eis que a glória do SENHOR apareceu na nuvem.

[[v2-16-11]]

^<<v2-16-11,11>>^ E o SENHOR falou a Moisés, dizendo:

[[v2-16-12]]

^<<v2-16-12,12>>^ Tenho ouvido as murmurações dos filhos de Israel; fala-lhes, dizendo: Entre as duas tardes, comereis carne, e, pela manhã, vos fartareis de pão, e sabereis que eu sou  o SENHOR, vosso Deus.

[[v2-16-13]]

^<<v2-16-13,13>>^ E aconteceu que, à tarde, subiram codornizes e cobriram o arraial; e, pela manhã, jazia o orvalho ao redor do arraial.

[[v2-16-14]]

^<<v2-16-14,14>>^ E, alçando-se o orvalho caído, eis que sobre a face do deserto estava  uma coisa miúda, redonda, miúda como a geada sobre a terra.

[[v2-16-15]]

^<<v2-16-15,15>>^ E, vendo-a os filhos de Israel, disseram uns aos outros: Que é  isto? Porque não sabiam o que era.  Disse-lhes, pois, Moisés: Este é  o pão que o SENHOR vos deu para comer.

[[v2-16-16]]

^<<v2-16-16,16>>^ Esta é  a palavra que o SENHOR tem mandado: Colhei dele cada um conforme o que pode comer, um gômer por cabeça, segundo  o número das vossas almas; cada um tomará para os que se acharem  na sua tenda.

[[v2-16-17]]

^<<v2-16-17,17>>^ E os filhos de Israel fizeram assim; e colheram, uns, mais, e outros, menos.

[[v2-16-18]]

^<<v2-16-18,18>>^ Porém, medindo-o com o gômer, não sobejava ao que colhera muito, nem faltava ao que colhera pouco; cada um colheu tanto quanto podia comer.

[[v2-16-19]]

^<<v2-16-19,19>>^ E disse-lhes Moisés: Ninguém deixe dele para amanhã.

[[v2-16-20]]

^<<v2-16-20,20>>^ Eles, porém, não deram ouvidos a Moisés; antes, alguns deles deixaram dele para o dia seguinte; e aquele criou bichos e cheirava mal; por isso, indignou-se Moisés contra eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Eles, pois, o colhiam cada manhã; cada um, conforme ao que podia comer; porque, aquecendo o sol, derretia-se.

[[v2-16-22]]

^<<v2-16-22,22>>^ E aconteceu que,  ao sexto dia, colheram pão em dobro, dois gômeres para cada um; e todos os príncipes da congregação vieram e contaram- no  a Moisés.

[[v2-16-23]]

^<<v2-16-23,23>>^ E ele  disse-lhes: Isto é  o que o SENHOR tem dito: Amanhã é  repouso, o santo sábado do SENHOR; o que quiserdes cozer no forno, cozei-o; e o que quiserdes cozer em água, cozei-o em água; e tudo o que sobejar ponde em guarda para vós até amanhã.

[[v2-16-24]]

^<<v2-16-24,24>>^ E guardaram-no até pela manhã, como Moisés tinha ordenado; e não cheirou mal, nem nele houve algum  bicho.

[[v2-16-25]]

^<<v2-16-25,25>>^ Então, disse Moisés: Comei-o hoje, porquanto hoje é o sábado do SENHOR; hoje não o achareis no campo.

[[v2-16-26]]

^<<v2-16-26,26>>^ Seis dias o colhereis, mas o sétimo dia é  o sábado; nele não haverá.

[[v2-16-27]]

^<<v2-16-27,27>>^ E aconteceu, ao sétimo dia, que alguns  do povo saíram para colher, mas não o acharam.

[[v2-16-28]]

^<<v2-16-28,28>>^ Então, disse o SENHOR a Moisés: Até quando recusareis guardar os meus mandamentos e as minhas leis?

[[v2-16-29]]

^<<v2-16-29,29>>^ Vede, visto que o SENHOR vos deu o sábado, por isso ele, no sexto dia, vos dá pão para dois dias; cada um fique no seu lugar, que ninguém saia do seu lugar no sétimo dia.

[[v2-16-30]]

^<<v2-16-30,30>>^ Assim, repousou o povo no sétimo dia.

[[v2-16-31]]

^<<v2-16-31,31>>^ E chamou a casa de Israel o seu nome Maná; e era como semente de coentro; era  branco, e o seu sabor, como bolos de mel.

[[v2-16-32]]

^<<v2-16-32,32>>^ E disse Moisés: Esta é  a palavra que o SENHOR tem mandado: Encherás um gômer dele e o guardarás para as vossas gerações, para que vejam o pão que vos tenho dado a comer neste deserto, quando eu vos tirei da terra do Egito.

[[v2-16-33]]

^<<v2-16-33,33>>^ Disse também Moisés a Arão: Toma um vaso, e mete nele um gômer cheio de maná, e põe-no diante do SENHOR, em guarda para as vossas gerações.

[[v2-16-34]]

^<<v2-16-34,34>>^ Como o SENHOR tinha ordenado a Moisés, assim Arão o pôs diante do Testemunho em guarda.

[[v2-16-35]]

^<<v2-16-35,35>>^ E comeram os filhos de Israel maná quarenta anos, até que entraram em terra habitada; comeram maná até que chegaram aos termos da terra de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ E um gômer é a décima parte  do efa.

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]