include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// arc ?, ARC - Almeida Revista e Corrigida

[[v7-17-1]]

^<<v7-17-1,1>>^ E havia um homem da montanha de Efraim cujo nome era  Mica,

[[v7-17-2]]

^<<v7-17-2,2>>^ o qual disse à sua mãe: As mil e cem moedas  de prata que te foram tiradas, por cuja causa  deitavas maldições e também as disseste em meus ouvidos, eis que esse dinheiro eu o tenho, eu o  tomei. Então, disse sua mãe: Bendito seja  meu filho do SENHOR.

[[v7-17-3]]

^<<v7-17-3,3>>^ Assim, restituiu as mil e cem moedas  de prata à sua mãe; porém sua mãe disse: Inteiramente tenho dedicado este dinheiro da minha mão ao SENHOR para meu filho, para fazer uma imagem de escultura e de fundição; de sorte que agora to tornarei a dar.

[[v7-17-4]]

^<<v7-17-4,4>>^ Porém ele restituiu aquele dinheiro a sua mãe, e sua mãe tomou duzentas moedas  de prata e as deu ao ourives, o qual fez delas uma imagem de escultura e de fundição, e esteve em casa de Mica.

[[v7-17-5]]

^<<v7-17-5,5>>^ E tinha este homem, Mica, uma casa de deuses, e fez um éfode e terafins, e consagrou a um de seus filhos, para que lhe fosse por sacerdote.

[[v7-17-6]]

^<<v7-17-6,6>>^ Naqueles dias, não havia  rei em Israel; cada qual fazia o que parecia  direito aos seus olhos.

[[v7-17-7]]

^<<v7-17-7,7>>^ E havia um jovem de Belém de Judá, da tribo de Judá, que era  levita e peregrinava ali.

[[v7-17-8]]

^<<v7-17-8,8>>^ E este homem partiu da cidade de Belém de Judá para peregrinar onde quer que achasse comodidade;  chegando ele, pois, à montanha de Efraim, até à casa de Mica, seguindo o seu caminho,

[[v7-17-9]]

^<<v7-17-9,9>>^ disse-lhe Mica: De onde vens? E ele lhe disse: Sou levita de Belém de Judá e vou peregrinar aonde quer que achar comodidade.

[[v7-17-10]]

^<<v7-17-10,10>>^ Então, lhe disse Mica: Fica comigo e sê-me por pai e sacerdote; e cada ano te darei dez moedas  de prata, e vestuário, e o teu sustento. E o levita entrou.

[[v7-17-11]]

^<<v7-17-11,11>>^ E consentiu o levita em ficar com aquele homem; e este jovem lhe foi como um de seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ E consagrou Mica ao levita, e aquele jovem lhe foi por sacerdote; e esteve em casa de Mica.

[[v7-17-13]]

^<<v7-17-13,13>>^ Então, disse Mica: Agora sei que o SENHOR me fará bem, porquanto tenho um levita por sacerdote.

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]