include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// arc ?, ARC - Almeida Revista e Corrigida

[[v7-4-1]]

^<<v7-4-1,1>>^ Porém os filhos de Israel tornaram a fazer o que parecia  mal aos olhos do SENHOR, depois de falecer Eúde.

[[v7-4-2]]

^<<v7-4-2,2>>^ E vendeu-os o SENHOR em mão de Jabim, rei de Canaã, que reinava em Hazor; e Sísera era  o capitão do seu exército, o qual, então, habitava em Harosete-Hagoim.

[[v7-4-3]]

^<<v7-4-3,3>>^ Então, os filhos de Israel clamaram ao SENHOR, porquanto Jabim tinha novecentos carros de ferro e por vinte anos oprimia os filhos de Israel violentamente.

[[v7-4-4]]

^<<v7-4-4,4>>^ E Débora, mulher profetisa, mulher de Lapidote, julgava a Israel naquele tempo.

[[v7-4-5]]

^<<v7-4-5,5>>^ E habitava debaixo das palmeiras de Débora, entre Ramá e Betel, nas montanhas de Efraim; e os filhos de Israel subiam a ela a juízo.

[[v7-4-6]]

^<<v7-4-6,6>>^ E enviou, e chamou a Baraque, filho de Abinoão, de Quedes de Naftali, e disse-lhe: Porventura  o SENHOR, Deus de Israel, não deu ordem, dizendo:  Vai, e atrai gente  ao monte de Tabor, e toma contigo dez mil homens dos filhos de Naftali e dos filhos de Zebulom?

[[v7-4-7]]

^<<v7-4-7,7>>^ E atrairei a ti para o ribeiro de Quisom a Sísera, capitão do exército de Jabim, com os seus carros e com a sua multidão, e o darei na tua mão.

[[v7-4-8]]

^<<v7-4-8,8>>^ Então, lhe disse Baraque: Se fores comigo, irei; porém, se não fores comigo, não irei.

[[v7-4-9]]

^<<v7-4-9,9>>^ E disse ela: Certamente irei contigo, porém não será tua a honra pelo caminho que levas; pois à mão de uma  mulher o SENHOR venderá a Sísera. E Débora se levantou e partiu com Baraque para Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Então, Baraque convocou a Zebulom e a Naftali em Quedes e subiu com dez mil homens após si; e Débora subiu com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ E Héber, queneu, se tinha apartado dos queneus dos filhos de Hobabe, sogro de Moisés, e tinha estendido as suas tendas até ao carvalho de Zaananim, que está  junto a Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ E anunciaram a Sísera que Baraque, filho de Abinoão, tinha subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ E Sísera convocou todos os seus carros, novecentos carros de ferro, e todo o povo que estava  com ele, desde Harosete-Hagoim até ao ribeiro de Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então, disse Débora a Baraque: Levanta-te, porque este é  o dia em que o SENHOR tem dado a Sísera na tua mão; porventura,  o SENHOR não saiu diante de ti? Baraque, pois, desceu do monte Tabor, e dez mil homens após ele.

[[v7-4-15]]

^<<v7-4-15,15>>^ E o SENHOR derrotou a Sísera, e todos os seus  carros, e todo o seu  exército a fio de espada, diante de Baraque; e Sísera desceu do carro e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ E Baraque os  seguiu após os carros e após o exército, até Harosete-Hagoim, e todo o exército de Sísera caiu a fio de espada, até  não ficar um só.

[[v7-4-17]]

^<<v7-4-17,17>>^ Porém Sísera fugiu a pé para a tenda de Jael, mulher de Héber, queneu, porquanto havia  paz entre Jabim, rei de Hazor, e a casa de Héber, queneu.

[[v7-4-18]]

^<<v7-4-18,18>>^ E Jael saiu ao encontro de Sísera e disse-lhe: Retira-te, senhor meu, retira-te para mim, não temas. Retirou-se para a sua tenda, e ela  cobriu-o com uma  coberta.

[[v7-4-19]]

^<<v7-4-19,19>>^ Então, ele lhe disse: Dá-me, peço-te, de beber um pouco de água; porque tenho sede. Então, ela abriu um odre de leite, e deu-lhe de beber, e o cobriu.

[[v7-4-20]]

^<<v7-4-20,20>>^ E ele lhe disse: Põe-te à porta da tenda; e há de ser que, se alguém vier, e te perguntar, e disser: Há aqui alguém? Responde tu,  então: Não.

[[v7-4-21]]

^<<v7-4-21,21>>^ Então, Jael, mulher de Héber, tomou uma estaca da tenda, e lançou mão de um martelo, e foi-se mansamente a ele, e lhe cravou a estaca na fonte, e a pregou na terra, estando  ele, porém, carregado de um  profundo sono e já  cansado; e assim  morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ E eis que, seguindo Baraque a Sísera, Jael lhe saiu ao encontro e disse-lhe: Vem, e mostrar-te-ei o homem que buscas. E veio a ela, e eis que Sísera jazia morto, e a estaca, na fonte.

[[v7-4-23]]

^<<v7-4-23,23>>^ Assim, Deus, naquele dia, sujeitou a Jabim, rei de Canaã, diante dos filhos de Israel.

[[v7-4-24]]

^<<v7-4-24,24>>^ E continuou a mão dos filhos de Israel a lutar e a endurecer-se sobre Jabim, rei de Canaã, até que exterminaram a Jabim, rei de Canaã.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]