include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// arc ?, ARC - Almeida Revista e Corrigida

[[v29-3-1]]

^<<v29-3-1,1>>^ Porquanto eis que, naqueles dias e naquele tempo, em que removerei o cativeiro de Judá e de Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ congregarei todas as nações e as farei descer ao vale de Josafá; e ali com elas entrarei em juízo, por causa do meu povo e da minha herança, Israel, a quem eles espalharam entre as nações, repartindo a minha terra.

[[v29-3-3]]

^<<v29-3-3,3>>^ E lançaram a sorte sobre o meu povo, e deram um menino por uma meretriz, e venderam uma menina por vinho, para beberem.

[[v29-3-4]]

^<<v29-3-4,4>>^ E também que tendes vós comigo, Tiro e Sidom e todos os termos da Fenícia? É tal  o pago que  vós me dais? Pois, se me pagais assim,  bem depressa farei cair a vossa paga sobre a vossa cabeça.

[[v29-3-5]]

^<<v29-3-5,5>>^ Visto como levastes a minha prata e o meu ouro e as minhas coisas desejáveis e formosas metestes nos vossos templos;

[[v29-3-6]]

^<<v29-3-6,6>>^ e vendestes os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos, para os apartar para longe dos seus termos;

[[v29-3-7]]

^<<v29-3-7,7>>^ eis que eu os moverei do lugar para onde os vendestes; e farei cair a vossa paga sobre a vossa própria cabeça.

[[v29-3-8]]

^<<v29-3-8,8>>^ E venderei vossos filhos e vossas filhas pela mão dos filhos de Judá, que os venderão aos de Seba, a uma nação remota, porque o SENHOR o disse.

[[v29-3-9]]

^<<v29-3-9,9>>^ Proclamai isso entre as nações, santificai uma guerra; suscitai os valentes; cheguem-se, subam todos os homens de guerra.

[[v29-3-10]]

^<<v29-3-10,10>>^ Forjai espadas das vossas enxadas e lanças das vossas foices; diga o fraco: Eu sou forte.

[[v29-3-11]]

^<<v29-3-11,11>>^ Ajuntai-vos, e vinde, todos os povos em redor, e congregai-vos (ó SENHOR, faze descer ali os teus fortes!);

[[v29-3-12]]

^<<v29-3-12,12>>^ movam-se as nações e subam ao vale de Josafá; porque ali me assentarei, para julgar todas as nações em redor.

[[v29-3-13]]

^<<v29-3-13,13>>^ Lançai a foice, porque já está madura a seara; vinde, descei, porque o lagar está cheio, os vasos dos lagares transbordam; porquanto a sua malícia é grande.

[[v29-3-14]]

^<<v29-3-14,14>>^ Multidões, multidões no vale da Decisão! Porque o dia do SENHOR está perto, no vale da Decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua se enegrecerão, e as estrelas retirarão o seu resplendor.

[[v29-3-16]]

^<<v29-3-16,16>>^ E o SENHOR bramará de Sião e dará a sua voz de Jerusalém, e os céus e a terra tremerão; mas o Senhor será  o refúgio do seu povo e a fortaleza dos filhos de Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ E vós sabereis que eu sou  o SENHOR, vosso Deus, que habito em Sião, o monte da minha santidade; e Jerusalém será santidade; estranhos não passarão mais por ela.

[[v29-3-18]]

^<<v29-3-18,18>>^ E há de ser que, naquele dia, os montes destilarão mosto, e dos outeiros manará leite, e todos os rios de Judá estarão cheios  de águas; e sairá uma fonte da Casa do SENHOR e regará o vale de Sitim.

[[v29-3-19]]

^<<v29-3-19,19>>^ O Egito se tornará uma assolação, e Edom se fará um deserto de solidão, por causa da violência que fizeram aos filhos de Judá, em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Mas Judá será habitada para sempre, e Jerusalém, de geração em geração.

[[v29-3-21]]

^<<v29-3-21,21>>^ E purificarei o sangue dos que  eu não tinha purificado, porque o SENHOR habitará em Sião.

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]