include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-65-1]]

^<<v23-65-1,1>>^ Fui buscado pelos que não perguntavam por mim;  fui achado por aqueles que me não buscavam; a um povo que se não chamava do meu nome eu disse: Eis-me aqui.

[[v23-65-2]]

^<<v23-65-2,2>>^ Estendi as mãos todo o dia a um povo rebelde, que caminha por caminho que não é bom, após os seus pensamentos;

[[v23-65-3]]

^<<v23-65-3,3>>^ povo que me irrita diante da minha face de contínuo, sacrificando em jardins e queimando incenso sobre tijolos;

[[v23-65-4]]

^<<v23-65-4,4>>^ assentando-se junto às sepulturas, e passando as noites junto aos lugares secretos, e comendo carne de porco e caldo de coisas abomináveis nos seus pratos.

[[v23-65-5]]

^<<v23-65-5,5>>^ E dizem: Retira-te, e não te chegues a mim, porque sou mais santo do que tu. Estes são  uma fumaça no meu nariz, um fogo que arde todo o dia.

[[v23-65-6]]

^<<v23-65-6,6>>^ Eis que está  escrito diante de mim: não me calarei; mas eu pagarei, sim, deitar-lhes-ei a recompensa no seu seio,

[[v23-65-7]]

^<<v23-65-7,7>>^ as vossas iniquidades e juntamente as iniquidades de vossos pais, diz o SENHOR, que queimaram incenso nos montes e me afrontaram nos outeiros; pelo que lhes tornarei a medir as suas obras antigas no seu seio.

[[v23-65-8]]

^<<v23-65-8,8>>^ Assim diz o SENHOR: Como quando se acha mosto em um cacho de uvas, dizem: Não o desperdices, pois há  bênção nele, assim farei por amor de  meus servos, para que os não destrua a todos.

[[v23-65-9]]

^<<v23-65-9,9>>^ E produzirei descendência a Jacó e a Judá, um  herdeiro que possua os meus montes; e os meus eleitos herdarão a terra,  e os meus servos habitarão ali.

[[v23-65-10]]

^<<v23-65-10,10>>^ E Sarom servirá de curral de ovelhas, e o vale de Acor, de lugar de repouso de gado, para o meu povo que me buscar.

[[v23-65-11]]

^<<v23-65-11,11>>^ Mas a vós que vos apartais do SENHOR, que vos esqueceis do meu santo monte, que preparais uma mesa para a Fortuna e que misturais vinho para o Destino,

[[v23-65-12]]

^<<v23-65-12,12>>^ também vos destinarei à espada, e todos vos encurvareis à matança, porquanto chamei, e não respondestes; falei, e não ouvistes, mas fizestes o que é  mal aos meus olhos e escolhestes aquilo em que eu não tinha prazer.

[[v23-65-13]]

^<<v23-65-13,13>>^ Pelo que assim diz o Senhor Jeová : Eis que os meus servos comerão, mas vós padecereis fome; eis que os meus servos beberão, mas vós tereis sede; eis que os meus servos se alegrarão, mas vós vos envergonhareis;

[[v23-65-14]]

^<<v23-65-14,14>>^ eis que os meus servos cantarão por terem o seu coração alegre, mas vós gritareis com tristeza de ânimo e uivareis pelo vosso quebrantamento de espírito;

[[v23-65-15]]

^<<v23-65-15,15>>^ e deixareis o vosso nome aos meus eleitos por maldição; e o Senhor Jeová  vos matará; e a seus servos chamará por outro nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ De sorte que aquele que se bendisser na terra será bendito no Deus da verdade; e aquele que jurar na terra jurará pelo Deus da verdade; porque já estão esquecidas as angústias passadas e estão encobertas diante dos meus olhos.

[[v23-65-17]]

^<<v23-65-17,17>>^ Porque eis que eu crio céus novos e nova terra; e não haverá lembrança das coisas passadas, nem mais se recordarão.

[[v23-65-18]]

^<<v23-65-18,18>>^ Mas vós folgareis e exultareis perpetuamente no que eu crio; porque eis que crio para Jerusalém alegria e para o seu povo, gozo.

[[v23-65-19]]

^<<v23-65-19,19>>^ E folgarei em Jerusalém e exultarei no meu povo; e nunca mais se ouvirá nela voz de choro nem voz de clamor.

[[v23-65-20]]

^<<v23-65-20,20>>^ Não haverá mais nela criança de poucos  dias, nem velho que não cumpra os seus dias; porque o jovem morrerá de cem anos, mas o pecador de cem anos será amaldiçoado.

[[v23-65-21]]

^<<v23-65-21,21>>^ E edificarão casas e as  habitarão; plantarão vinhas e comerão o seu fruto.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não edificarão para que outros habitem, não plantarão para que outros comam, porque os dias do meu povo serão  como os dias da árvore, e os meus eleitos gozarão das obras das suas mãos até à velhice.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não trabalharão debalde, nem terão filhos para a perturbação, porque são  a semente dos benditos do SENHOR, e os seus descendentes, com eles.

[[v23-65-24]]

^<<v23-65-24,24>>^ E será que, antes que clamem, eu responderei; estando eles ainda falando, eu os ouvirei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro se apascentarão juntos, e o leão comerá palha como o boi; e o pó será  a comida da serpente. Não farão mal nem dano algum em todo o meu santo monte, diz o SENHOR.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]