include::./index.adoc[]

[[v23-25-0]]
=== Isaías, 25
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-25-1]]

^<<v23-25-1,1>>^ Ó SENHOR, tu és o meu Deus; exaltar-te-ei e  louvarei o teu nome, porque fizeste maravilhas; os teus  conselhos antigos são  verdade e  firmeza.

[[v23-25-2]]

^<<v23-25-2,2>>^ Porque da cidade fizeste um montão de pedras, e  da cidade forte, uma ruína, e  do paço dos estranhos, que não seja mais cidade e jamais se torne a edificar.

[[v23-25-3]]

^<<v23-25-3,3>>^ Pelo que te glorificará um povo poderoso, e  a cidade das nações formidáveis te temerá.

[[v23-25-4]]

^<<v23-25-4,4>>^ Porque foste a fortaleza do pobre e  a fortaleza do necessitado na sua angústia; refúgio contra a tempestade e sombra contra o calor; porque o sopro dos opressores é  como a tempestade contra  o muro.

[[v23-25-5]]

^<<v23-25-5,5>>^ Como o calor em lugar seco, tu abaterás o ímpeto dos estranhos; como se  abranda o calor pela sombra da espessa nuvem, assim  o cântico dos tiranos será humilhado.

[[v23-25-6]]

^<<v23-25-6,6>>^ E o SENHOR dos Exércitos dará, neste monte, a todos os povos uma festa com animais gordos, uma festa com vinhos puros, com tutanos gordos e  com vinhos puros, bem  purificados.

[[v23-25-7]]

^<<v23-25-7,7>>^ E destruirá, neste monte, a máscara do rosto com que todos os povos andam cobertos e o véu com que todas as nações se escondem.

[[v23-25-8]]

^<<v23-25-8,8>>^ Aniquilará a morte para sempre, e assim  enxugará o Senhor Jeová  as lágrimas de todos os rostos, e tirará o opróbrio do seu povo de toda a terra; porque o SENHOR o disse.

[[v23-25-9]]

^<<v23-25-9,9>>^ E, naquele dia, se dirá: Eis que este é  o nosso Deus, a quem aguardávamos, e ele nos salvará; este é  o SENHOR, a quem aguardávamos; na sua salvação, exultaremos e nos alegraremos.

[[v23-25-10]]

^<<v23-25-10,10>>^ Porque a mão do SENHOR descansará neste monte; mas Moabe será trilhado debaixo dele, como se trilha a palha no monturo.

[[v23-25-11]]

^<<v23-25-11,11>>^ E Moabe estenderá as mãos por entre eles, como as  estende o nadador para nadar; mas o SENHOR abaterá a sua altivez, apesar da perícia das suas mãos.

[[v23-25-12]]

^<<v23-25-12,12>>^ E abaixará as altas fortalezas dos teus muros e abatê-las-á, e  derribá-las-á por terra, até ao pó.

'''

xref:023-isaias/023-isaias-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaias/023-isaias-026.adoc#v23-26-0[Próximo Capítulo &#62;]