include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-34-1]]

^<<v23-34-1,1>>^ Chegai-vos, nações, para ouvir; e vós, povos, escutai; ouça a terra, e a sua plenitude, o mundo e tudo quanto produz.

[[v23-34-2]]

^<<v23-34-2,2>>^ Porque a indignação do Senhor está  sobre todas as nações, e o seu  furor sobre todo o exército delas; ele as destruiu totalmente, entregou-as à matança.

[[v23-34-3]]

^<<v23-34-3,3>>^ E os mortos serão arremessados, e do seu corpo subirá o mau cheiro; e com o seu sangue os montes se derreterão.

[[v23-34-4]]

^<<v23-34-4,4>>^ E todo o exército dos céus se gastará, e os céus se enrolarão como um livro, e todo o seu exército cairá como cai a folha da vide e como cai o figo  da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ Porque a minha espada se embriagou nos céus; eis que sobre Edom descerá e sobre o povo do meu anátema, para exercer juízo.

[[v23-34-6]]

^<<v23-34-6,6>>^ A espada do SENHOR está cheia de sangue, está cheia da gordura de sangue de cordeiros e de bodes, da gordura dos rins de carneiros; porque o SENHOR tem sacrifício em Bozra e grande matança na terra de Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ E os unicórnios descerão com eles, e os bezerros, com os touros; e a sua terra beberá sangue até se fartar, e o seu pó de gordura se encherá.

[[v23-34-8]]

^<<v23-34-8,8>>^ Porque será  o dia da vingança do SENHOR, ano de retribuições, pela luta de Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ E os seus ribeiros se transformarão em pez, e o seu pó, em enxofre, e a sua terra, em pez ardente.

[[v23-34-10]]

^<<v23-34-10,10>>^ Nem de noite nem de dia, se apagará; para sempre a sua fumaça subirá; de geração em geração será assolada, e de século em século ninguém passará por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ Mas o pelicano e a coruja a possuirão, e o bufo e o corvo habitarão nela, e ele estenderá sobre ela cordel de confusão e nível de vaidade.

[[v23-34-12]]

^<<v23-34-12,12>>^ Eles chamarão ao reino os seus nobres, mas nenhum haverá, e todos os seus príncipes não serão coisa nenhuma.

[[v23-34-13]]

^<<v23-34-13,13>>^ E, nos seus palácios, crescerão espinhos, urtigas e cardos nas suas fortalezas; e será uma  habitação de dragões e  sala para os filhos do avestruz.

[[v23-34-14]]

^<<v23-34-14,14>>^ E os cães bravos se encontrarão com os gatos bravos; e o sátiro clamará ao seu companheiro; e os animais noturnos ali pousarão e acharão lugar de repouso para si.

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali, se aninhará a mélroa, e porá os seus ovos,  e tirará os seus filhotes, e os recolherá debaixo da sua sombra; também ali os abutres se ajuntarão uns com os outros.

[[v23-34-16]]

^<<v23-34-16,16>>^ Buscai no livro do SENHOR e lede; nenhuma dessas coisas  falhará, nem uma nem outra faltará; porque a sua própria boca o ordenou, e o seu espírito mesmo as ajuntará.

[[v23-34-17]]

^<<v23-34-17,17>>^ Porque ele mesmo lançou as sortes por eles, e a sua mão lhes repartiu a terra  com o cordel; para sempre a possuirão, de geração em geração habitarão nela.

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]