include::./index.adoc[]

[[v23-11-0]]
=== Isaías, 11
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-11-1]]

^<<v23-11-1,1>>^ Porque brotará um rebento do tronco de Jessé, e das suas raízes um  renovo frutificará.

[[v23-11-2]]

^<<v23-11-2,2>>^ E repousará sobre ele o Espírito do SENHOR, e o Espírito de sabedoria e de inteligência, e o Espírito de conselho e de fortaleza, e o Espírito de conhecimento e de temor do SENHOR.

[[v23-11-3]]

^<<v23-11-3,3>>^ E deleitar-se-á no temor do SENHOR e não julgará segundo a vista dos seus olhos, nem repreenderá segundo o ouvir dos seus ouvidos;

[[v23-11-4]]

^<<v23-11-4,4>>^ mas julgará com justiça os pobres, e repreenderá com equidade os mansos da terra, e ferirá a terra com a vara de sua boca, e com o sopro dos seus lábios matará o ímpio.

[[v23-11-5]]

^<<v23-11-5,5>>^ E a justiça será o cinto dos seus lombos, e a verdade, o cinto dos seus rins.

[[v23-11-6]]

^<<v23-11-6,6>>^ E morará o lobo com o cordeiro, e o leopardo com o cabrito se deitará, e o bezerro, e o filho de leão, e a nédia ovelha viverão juntos, e um menino pequeno os guiará.

[[v23-11-7]]

^<<v23-11-7,7>>^ A vaca e a ursa pastarão juntas, e seus filhos juntos se deitarão; e o leão comerá palha como o boi.

[[v23-11-8]]

^<<v23-11-8,8>>^ E brincará a criança de peito sobre a toca da áspide, e o já desmamado meterá a mão na cova do basilisco.

[[v23-11-9]]

^<<v23-11-9,9>>^ Não se fará mal nem dano algum em todo o monte da minha santidade, porque a terra se encherá do conhecimento do SENHOR, como as águas cobrem o mar.

[[v23-11-10]]

^<<v23-11-10,10>>^ E acontecerá, naquele dia, que as nações perguntarão pela raiz de Jessé, posta por pendão dos povos, e o lugar do seu repouso será glorioso.

[[v23-11-11]]

^<<v23-11-11,11>>^ Porque há de acontecer, naquele dia, que o Senhor tornará a estender a mão para adquirir outra vez os resíduos do seu povo que restarem da Assíria, e do Egito, e de Patros, e da Etiópia, e de Elão, e de Sinar, e de Hamate, e das ilhas do mar.

[[v23-11-12]]

^<<v23-11-12,12>>^ E levantará um pendão entre as nações, e ajuntará os desterrados de Israel, e os dispersos de Judá congregará desde os quatro confins da terra.

[[v23-11-13]]

^<<v23-11-13,13>>^ E desterrar-se-á a inveja de Efraim, e os adversários de Judá serão desarraigados; Efraim não invejará a Judá, e Judá não oprimirá a Efraim.

[[v23-11-14]]

^<<v23-11-14,14>>^ Antes, voarão sobre os ombros dos filisteus ao Ocidente; juntos, despojarão os filhos do Oriente; em  Edom e Moabe lançarão as mãos, e os filhos de Amom lhes obedecerão.

[[v23-11-15]]

^<<v23-11-15,15>>^ E o SENHOR destruirá totalmente o braço de mar do Egito, e moverá a sua mão contra o rio com a força do seu vento, e, ferindo-o, dividi-lo-á em sete correntes, que qualquer atravessará com calçados.

[[v23-11-16]]

^<<v23-11-16,16>>^ E haverá caminho plano para os resíduos do seu povo que restarem da Assíria, como sucedeu a Israel no dia em que subiu da terra do Egito.

'''

xref:023-isaias/023-isaias-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaias/023-isaias-012.adoc#v23-12-0[Próximo Capítulo &#62;]