include::./index.adoc[]

[[v23-33-0]]
=== Isaías, 33
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-33-1]]

^<<v23-33-1,1>>^ Ai de ti despojador que não foste despojado e que ages perfidamente contra  os que não agiram perfidamente contra ti! Acabando tu de despojar, serás despojado; e,  acabando tu de tratar perfidamente, perfidamente te tratarão.

[[v23-33-2]]

^<<v23-33-2,2>>^ SENHOR, tem misericórdia de nós! Por ti temos esperado; sê tu o nosso braço cada manhã, como também a nossa salvação em tempos de tribulação.

[[v23-33-3]]

^<<v23-33-3,3>>^ Ao ruído do tumulto, fugirão os povos; à tua exaltação as nações serão dispersas.

[[v23-33-4]]

^<<v23-33-4,4>>^ Então, ajuntar-se-á o vosso despojo como se apanha o pulgão; como os gafanhotos saltam, ali saltará.

[[v23-33-5]]

^<<v23-33-5,5>>^ O SENHOR é exalçado, pois habita nas  alturas; encheu a Sião de retidão e de justiça.

[[v23-33-6]]

^<<v23-33-6,6>>^ E haverá estabilidade nos teus tempos, abundância de salvação, sabedoria e ciência; e  o temor do Senhor será  o seu tesouro.

[[v23-33-7]]

^<<v23-33-7,7>>^ Eis que os seus embaixadores estão clamando de fora; e  os mensageiros de paz estão chorando amargamente.

[[v23-33-8]]

^<<v23-33-8,8>>^ As estradas estão desoladas, cessam os que passam pelas veredas; ele rompeu a aliança, desprezou as cidades e  a homem nenhum estima.

[[v23-33-9]]

^<<v23-33-9,9>>^ A terra geme e  pranteia, o Líbano se envergonha e  se murcha, Sarom se tornou como um  deserto, Basã e Carmelo foram sacudidos.

[[v23-33-10]]

^<<v23-33-10,10>>^ Agora, me levantarei, diz o SENHOR; agora, me levantarei a mim mesmo; agora, serei exaltado.

[[v23-33-11]]

^<<v23-33-11,11>>^ Concebestes palha, produzireis pragana, e o vosso espírito vos devorará como  fogo.

[[v23-33-12]]

^<<v23-33-12,12>>^ E os povos serão como  os incêndios de cal, como  espinhos cortados arderão no fogo.

[[v23-33-13]]

^<<v23-33-13,13>>^ Ouvi, vós os que estais longe, o que tenho feito; e vós que estais vizinhos, conhecei o meu poder.

[[v23-33-14]]

^<<v23-33-14,14>>^ Os pecadores de Sião se assombraram, o tremor  surpreendeu os hipócritas. Quem dentre nós habitará com o fogo consumidor? Quem dentre nós habitará com as labaredas eternas?

[[v23-33-15]]

^<<v23-33-15,15>>^ O que anda em justiça e que fala com retidão, que arremessa para longe de si o ganho de opressões, que sacode das suas mãos todo o presente; que tapa os ouvidos para não ouvir falar de  sangue e fecha os olhos para não ver o mal,

[[v23-33-16]]

^<<v23-33-16,16>>^ este habitará nas alturas; as fortalezas das rochas serão  o seu alto refúgio, o seu pão lhe será dado, e as suas águas serão certas.

[[v23-33-17]]

^<<v23-33-17,17>>^ Os teus olhos verão o Rei na sua formosura e  verão a terra que está longe.

[[v23-33-18]]

^<<v23-33-18,18>>^ O teu coração considerará em assombro, dizendo:  Onde está o escrivão? Onde está o pagador? Onde está o que conta as torres?

[[v23-33-19]]

^<<v23-33-19,19>>^ Não verás mais  aquele povo cruel, povo de fala tão profunda, que não se pode perceber, e  de língua tão estranha, que não se pode entender.

[[v23-33-20]]

^<<v23-33-20,20>>^ Olha para Sião, a cidade das nossas solenidades; os teus olhos verão a Jerusalém, habitação quieta, tenda que não será derribada, cujas estacas nunca serão arrancadas, e das suas cordas nenhuma se quebrará.

[[v23-33-21]]

^<<v23-33-21,21>>^ Mas o SENHOR ali nos será grandioso, lugar de rios e  correntes largas; barco nenhum de remo passará por eles, nem navio grande navegará por eles.

[[v23-33-22]]

^<<v23-33-22,22>>^ Porque o Senhor é  o nosso Juiz; o Senhor é  o nosso Legislador; o Senhor é  o nosso Rei; ele nos salvará.

[[v23-33-23]]

^<<v23-33-23,23>>^ As tuas cordas estão frouxas; não puderam ter firme o seu mastro, e  vela não estenderam; então, a presa de abundantes despojos se repartirá; e até  os coxos roubarão a presa.

[[v23-33-24]]

^<<v23-33-24,24>>^ E morador nenhum dirá: Enfermo estou; porque  o povo que habitar nela será  absolvido da sua iniquidade.

'''

xref:023-isaias/023-isaias-032.adoc#v23-32-0[&#60; Capítulo Anterior] | <<v23-33-0,Topo>> | xref:023-isaias/023-isaias-034.adoc#v23-34-0[Próximo Capítulo &#62;]