include::./index.adoc[]

[[v23-62-0]]
=== Isaías, 62
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-62-1]]

^<<v23-62-1,1>>^ Por amor de Sião, me não calarei e, por amor de Jerusalém, me não aquietarei, até que saia a sua justiça como um resplendor, e a sua salvação, como uma tocha acesa.

[[v23-62-2]]

^<<v23-62-2,2>>^ E as nações verão a tua justiça, e todos os reis, a tua glória; e chamar-te-ão por um nome novo, que a boca do SENHOR nomeará.

[[v23-62-3]]

^<<v23-62-3,3>>^ E serás uma coroa de glória na mão do SENHOR e um  diadema real na mão do teu Deus.

[[v23-62-4]]

^<<v23-62-4,4>>^ Nunca mais te chamarão Desamparada, nem a tua terra se denominará jamais Assolada; mas chamar-te-ão Hefzibá; e à tua terra, Beulá, porque o SENHOR se agrada de ti; e com a tua terra o SENHOR se casará.

[[v23-62-5]]

^<<v23-62-5,5>>^ Porque, como  o jovem se casa com a donzela, assim  teus filhos se casarão contigo; e, como  o noivo se alegra com a noiva, assim  se alegrará contigo o teu Deus.

[[v23-62-6]]

^<<v23-62-6,6>>^ Ó Jerusalém! Sobre os teus muros pus guardas, que  todo o dia e toda a noite se não calarão; ó vós que fazeis menção do SENHOR, não haja silêncio em vós,

[[v23-62-7]]

^<<v23-62-7,7>>^ nem estejais em silêncio, até que confirme e até que ponha a Jerusalém por louvor na terra.

[[v23-62-8]]

^<<v23-62-8,8>>^ Jurou o SENHOR pela sua mão direita e pelo braço da sua força: Nunca mais darei o teu trigo por  comida aos teus inimigos, nem os estranhos beberão o teu mosto, em que trabalhaste.

[[v23-62-9]]

^<<v23-62-9,9>>^ Mas os que o ajuntarem o comerão e louvarão ao SENHOR; e os que o colherem beberão nos átrios do meu santuário.

[[v23-62-10]]

^<<v23-62-10,10>>^ Passai, passai pelas portas; preparai o caminho ao povo; aplainai, aplainai a estrada, limpai- a  das pedras; arvorai a bandeira aos povos.

[[v23-62-11]]

^<<v23-62-11,11>>^ Eis que o SENHOR fez ouvir até às extremidades da terra: Dizei à filha de Sião: Eis que a tua salvação vem; eis que com ele vem o seu galardão, e a sua obra, diante dele.

[[v23-62-12]]

^<<v23-62-12,12>>^ E chamar-lhes-ão povo santo, os remidos do SENHOR; e tu serás chamada Procurada, Cidade não desamparada.

'''

xref:023-isaias/023-isaias-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaias/023-isaias-063.adoc#v23-63-0[Próximo Capítulo &#62;]