include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// arc ?, ARC - Almeida Revista e Corrigida

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o SENHOR: Onde está a carta de divórcio de vossa mãe, pela qual eu a repudiei? Ou quem é  o meu credor, a quem eu vos tenha vendido? Eis que por vossas maldades fostes vendidos, e por vossas prevaricações vossa mãe foi repudiada.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que razão vim eu, e ninguém apareceu? Chamei, e ninguém respondeu? Tanto se encolheu a minha mão, que já  não possa remir? Ou não há mais  força em mim para livrar? Eis que, com a minha repreensão, faço secar o mar, torno os rios em  deserto, até que cheirem mal os seus peixes, pois não têm água e morrem de sede.

[[v23-50-3]]

^<<v23-50-3,3>>^ Eu visto os céus de negridão e pôr-lhes-ei um pano de saco grosseiro por sua cobertura.

[[v23-50-4]]

^<<v23-50-4,4>>^ O Senhor Jeová  me deu uma  língua erudita, para que eu saiba dizer, a seu tempo, uma boa  palavra ao que está cansado. Ele desperta- me  todas as manhãs, desperta-me o ouvido para que ouça como aqueles que aprendem.

[[v23-50-5]]

^<<v23-50-5,5>>^ O Senhor Jeová  me abriu os ouvidos, e eu não fui rebelde; não me retiro para trás.

[[v23-50-6]]

^<<v23-50-6,6>>^ As costas dou aos que me  ferem e a face, aos que me  arrancam os cabelos; não escondo a face dos que me afrontam e me cospem.

[[v23-50-7]]

^<<v23-50-7,7>>^ Porque o Senhor Jeová  me ajuda, pelo que me não confundo; por isso, pus o rosto como um  seixo e sei que não serei confundido.

[[v23-50-8]]

^<<v23-50-8,8>>^ Perto está  o que me justifica; quem contenderá comigo? Compareçamos juntamente; quem é meu adversário? Chegue-se para mim.

[[v23-50-9]]

^<<v23-50-9,9>>^ Eis que o Senhor Jeová  me ajuda; quem há que  me condene? Eis que todos eles, como vestes, se envelhecerão, e  a traça os comerá.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem há  entre vós que tema ao Senhor e  ouça a voz do seu servo? Quando andar em trevas e não tiver luz nenhuma, confie no nome do SENHOR e firme-se sobre o seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Todos vós que acendeis fogo e vos cingis com faíscas, andai entre as labaredas do vosso fogo e entre as faíscas que  acendestes; isso vos vem da minha mão, e  em tormentos jazereis.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]