include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-33-1]]

^<<v24-33-1,1>>^ E veio a palavra do SENHOR a Jeremias, segunda vez, estando ele ainda encerrado no pátio da guarda, dizendo:

[[v24-33-2]]

^<<v24-33-2,2>>^ Assim diz o SENHOR que faz isto, o SENHOR que forma isto, para o estabelecer ( o seu nome): é SENHOR.

[[v24-33-3]]

^<<v24-33-3,3>>^ Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e firmes, que não sabes.

[[v24-33-4]]

^<<v24-33-4,4>>^ Porque assim diz o SENHOR, o Deus de Israel, sobre as casas desta cidade e sobre as casas dos reis de Judá, que foram derribadas com os trabucos e à espada.

[[v24-33-5]]

^<<v24-33-5,5>>^ Eles entraram a pelejar contra os caldeus, mas para que os encha de cadáveres de homens, que feri na minha ira e no meu furor, porquanto escondi o rosto desta cidade, por causa de toda a sua maldade.

[[v24-33-6]]

^<<v24-33-6,6>>^ Eis que eu farei vir sobre ela saúde e cura, e os sararei, e lhes manifestarei abundância de paz e de verdade.

[[v24-33-7]]

^<<v24-33-7,7>>^ E removerei o cativeiro de Judá e o cativeiro de Israel e os edificarei como no princípio;

[[v24-33-8]]

^<<v24-33-8,8>>^ e os purificarei de toda a sua maldade com  que pecaram contra mim e perdoarei todas as suas iniquidades com  que pecaram contra mim e com  que transgrediram contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ E esta cidade  me servirá de nome de alegria, de louvor e de glória, entre todas as nações da terra que ouvirem todo o bem que eu lhe faço; e espantar-se-ão e perturbar-se-ão por causa de todo o bem e por causa de toda a paz que eu lhe dou.

[[v24-33-10]]

^<<v24-33-10,10>>^ Assim diz o SENHOR: Neste lugar (de que vós dizeis que está  deserto, sem homens nem animais), nas cidades de Judá e nas ruas de Jerusalém, que estão assoladas, sem homens, sem moradores e sem animais, ainda se ouvirá

[[v24-33-11]]

^<<v24-33-11,11>>^ a voz de gozo, e a voz de alegria, e a voz de noivo, e a voz de esposa, e  a voz dos que dizem: Louvai ao SENHOR dos Exércitos, porque bom é  o SENHOR, porque a sua benignidade é  para sempre; e a voz dos que trazem louvor à Casa do SENHOR; pois farei que torne o cativeiro da terra como no princípio, diz o SENHOR.

[[v24-33-12]]

^<<v24-33-12,12>>^ Assim diz o SENHOR dos Exércitos: Ainda neste lugar que está deserto, sem homens e sem animais e em todas as suas cidades haverá uma  morada de pastores que façam repousar o gado.

[[v24-33-13]]

^<<v24-33-13,13>>^ Nas cidades das montanhas, e nas cidades das planícies, e nas cidades do Sul, e na terra de Benjamim, e nos contornos de Jerusalém, e nas cidades de Judá, ainda passará o gado pelas mãos dos contadores, diz o SENHOR.

[[v24-33-14]]

^<<v24-33-14,14>>^ Eis que vêm dias, diz o SENHOR, em que cumprirei a palavra boa que falei à casa de Israel e à casa de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ Naqueles dias e naquele tempo, farei que brote a Davi um Renovo de justiça, e ele fará juízo e justiça na terra.

[[v24-33-16]]

^<<v24-33-16,16>>^ Naqueles dias, Judá será salvo, e Jerusalém habitará seguramente; e este é o nome  que lhe chamarão: O SENHOR É Nossa Justiça.

[[v24-33-17]]

^<<v24-33-17,17>>^ Porque assim diz o SENHOR: Nunca faltará a Davi varão que se assente sobre o trono da casa de Israel,

[[v24-33-18]]

^<<v24-33-18,18>>^ nem aos sacerdotes levíticos faltará varão diante de mim, para que ofereça holocausto, e queime oferta de manjares, e faça sacrifício todos os dias.

[[v24-33-19]]

^<<v24-33-19,19>>^ E veio a palavra do SENHOR a Jeremias, dizendo:

[[v24-33-20]]

^<<v24-33-20,20>>^ Assim diz o SENHOR: Se puderdes invalidar o meu concerto do dia, e o meu concerto da noite, de tal modo que não haja dia e noite a seu tempo,

[[v24-33-21]]

^<<v24-33-21,21>>^ também se poderá invalidar o meu concerto com Davi, meu servo, para que não tenha filho que reine no seu trono, como também com os levitas sacerdotes, meus ministros.

[[v24-33-22]]

^<<v24-33-22,22>>^ Como não se pode contar o exército dos céus, nem medir-se a areia do mar, assim multiplicarei a descendência de Davi, meu servo, e os levitas que ministram diante de mim.

[[v24-33-23]]

^<<v24-33-23,23>>^ E veio ainda  a palavra do SENHOR a Jeremias, dizendo:

[[v24-33-24]]

^<<v24-33-24,24>>^ Não tens visto o que este povo fala, dizendo: As duas gerações que o SENHOR elegeu, agora as rejeitou? E desprezam o meu povo, como se não fora já um povo diante deles.

[[v24-33-25]]

^<<v24-33-25,25>>^ Assim diz o SENHOR: Se o meu concerto do dia e da noite não permanecer, e eu não puser as ordenanças dos céus e da terra,

[[v24-33-26]]

^<<v24-33-26,26>>^ também rejeitarei a descendência de Jacó e de Davi, meu servo, de modo que não tome da sua semente quem domine sobre a semente de Abraão, Isaque e Jacó; porque removerei o seu cativeiro e apiedar-me-ei deles.

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]