include::./index.adoc[]

[[v24-34-0]]
=== Jeremias, 34
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-34-1]]

^<<v24-34-1,1>>^ A palavra que do SENHOR veio a Jeremias quando Nabucodonosor, rei da Babilônia, e todo o seu exército, e todos os reinos da terra que estavam sob  o domínio da sua mão, e todos os povos pelejavam contra Jerusalém e contra todas as suas cidades, dizendo:

[[v24-34-2]]

^<<v24-34-2,2>>^ Assim diz o SENHOR, Deus de Israel: Vai, e fala a Zedequias, rei de Judá, e dize-lhe: Assim diz o SENHOR: Eis que eu entrego esta cidade nas mãos do rei da Babilônia, o qual a queimará.

[[v24-34-3]]

^<<v24-34-3,3>>^ E tu não escaparás das suas mãos; antes, decerto, serás preso e serás entregue nas suas mãos; e teus olhos verão os olhos do rei da Babilônia, e ele te falará boca a boca, e entrarás na Babilônia.

[[v24-34-4]]

^<<v24-34-4,4>>^ Todavia ouve a palavra do SENHOR, ó Zedequias, rei de Judá. Assim diz o SENHOR a teu respeito: Não morrerás à espada.

[[v24-34-5]]

^<<v24-34-5,5>>^ Em paz morrerás, e, conforme as incinerações de teus pais, os reis precedentes, que foram antes de ti, assim te queimarão a ti e prantear-te-ão, dizendo:  Ah! Senhor! Porque sou eu que digo a palavra, diz o SENHOR.

[[v24-34-6]]

^<<v24-34-6,6>>^ E anunciou Jeremias, o profeta, a Zedequias, rei de Judá, todas estas palavras, em Jerusalém,

[[v24-34-7]]

^<<v24-34-7,7>>^ quando o exército do rei da Babilônia pelejava contra Jerusalém, contra todas as cidades de Judá que ficaram de resto, contra Laquis e contra Azeca; porque estas fortes cidades foram as que ficaram dentre as cidades de Judá.

[[v24-34-8]]

^<<v24-34-8,8>>^ A palavra que do SENHOR veio a Jeremias, depois que o rei Zedequias fez concerto com todo o povo que havia em Jerusalém, para lhes apregoar a liberdade:

[[v24-34-9]]

^<<v24-34-9,9>>^ que cada um despedisse forro o seu servo e cada um, a sua serva, hebreu ou hebreia, de maneira que ninguém se fizesse servir deles, sendo judeus, seus irmãos.

[[v24-34-10]]

^<<v24-34-10,10>>^ E ouviram todos os príncipes e todo o povo que entrou no concerto que cada um despedisse forro o seu servo e cada um, a sua serva, de maneira que não se fizessem mais servir deles; ouviram, pois, e os  soltaram.

[[v24-34-11]]

^<<v24-34-11,11>>^ Mas, depois, se arrependeram, e fizeram voltar os servos e as servas que tinham libertado, e os sujeitaram por servos e por servas.

[[v24-34-12]]

^<<v24-34-12,12>>^ Veio, pois, a palavra do SENHOR a Jeremias, da parte do SENHOR, dizendo:

[[v24-34-13]]

^<<v24-34-13,13>>^ Assim diz o SENHOR, Deus de Israel: Eu fiz concerto com vossos pais, no dia em que os tirei da terra do Egito, da casa da servidão, dizendo:

[[v24-34-14]]

^<<v24-34-14,14>>^ Ao fim de sete anos libertareis cada um a seu irmão hebreu que te for vendido a ti e te houver servido a ti seis anos; e despedi-lo-ás forro de ti; mas vossos pais me não ouviram, nem inclinaram os ouvidos.

[[v24-34-15]]

^<<v24-34-15,15>>^ E vos havíeis, hoje, convertido e tínheis feito o que é  reto aos meus olhos, apregoando liberdade cada um ao seu próximo; e tínheis feito diante de mim um  concerto, na casa que se chama pelo meu nome.

[[v24-34-16]]

^<<v24-34-16,16>>^ Mudastes, porém, e profanastes o meu nome, e fizestes voltar cada um ao seu servo, e cada um, à sua serva, os quais já  tínheis despedido forros, conforme a sua vontade; e os sujeitastes, para que se vos fizessem servos e servas.

[[v24-34-17]]

^<<v24-34-17,17>>^ Portanto, assim diz o SENHOR: Vós não me ouvistes a mim, para apregoardes a liberdade, cada um ao seu irmão e cada um ao seu próximo; pois eis que eu vos apregoo a liberdade, diz o SENHOR, para a espada, para a pestilência e para a fome; e dar-vos-ei por espanto a todos os reinos da terra.

[[v24-34-18]]

^<<v24-34-18,18>>^ E entregarei os homens que traspassaram o meu concerto, que não confirmaram as palavras do concerto, como eles fizeram diante de mim com  o bezerro que dividiram em duas partes, passando pelo meio das duas porções.

[[v24-34-19]]

^<<v24-34-19,19>>^ Os príncipes de Judá, e os príncipes de Jerusalém, e os eunucos, e os sacerdotes, e todo o povo da terra que passou por meio das porções do bezerro,

[[v24-34-20]]

^<<v24-34-20,20>>^ entregá-los-ei, digo, nas mãos de seus inimigos e nas mãos dos que procuram a sua morte, e os cadáveres deles servirão de mantimento às aves dos céus e aos animais da terra.

[[v24-34-21]]

^<<v24-34-21,21>>^ E até o rei Zedequias, rei de Judá, e seus príncipes entregarei nas mãos de seus inimigos e nas mãos dos que procuram a sua morte, e nas mãos do exército do rei da Babilônia, que já  se retirou de vós.

[[v24-34-22]]

^<<v24-34-22,22>>^ Eis que eu darei ordem, diz o SENHOR, e os farei tornar a esta cidade, e pelejarão contra ela, e a tomarão, e a queimarão; e as cidades de Judá porei em  assolação, de sorte que ninguém habite nelas.

'''

xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[&#60; Capítulo Anterior] | <<v24-34-0,Topo>> | xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[Próximo Capítulo &#62;]