include::./index.adoc[]

[[v24-27-0]]
=== Jeremias, 27
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-27-1]]

^<<v24-27-1,1>>^ No princípio do reinado de Zedequias, filho de Josias, rei de Judá, veio, da parte do SENHOR, esta palavra a Jeremias, dizendo:

[[v24-27-2]]

^<<v24-27-2,2>>^ Assim me disse o SENHOR: Faze umas prisões e jugos e pô-los-ás sobre o teu pescoço.

[[v24-27-3]]

^<<v24-27-3,3>>^ E envia-os ao rei de Edom, e ao rei de Moabe, e ao rei dos filhos de Amom, e ao rei de Tiro, e ao rei de Sidom, pelas mãos dos mensageiros que vêm a Jerusalém ter  com Zedequias, rei de Judá.

[[v24-27-4]]

^<<v24-27-4,4>>^ E lhes darás uma mensagem para seus senhores, dizendo: Assim diz o SENHOR dos Exércitos, o Deus de Israel: Assim direis a vossos senhores:

[[v24-27-5]]

^<<v24-27-5,5>>^ Eu fiz a terra, o homem e os animais que estão  sobre a face da terra, pelo meu grande poder e com o meu braço estendido, e os dou a quem me agrada.

[[v24-27-6]]

^<<v24-27-6,6>>^ E, agora, eu entreguei todas estas terras nas mãos de Nabucodonosor, rei da Babilônia, meu servo, e até os animais do campo lhe dei, para que o sirvam.

[[v24-27-7]]

^<<v24-27-7,7>>^ E todas as nações servirão a ele, e a seu filho, e ao filho de seu filho, até que também venha o tempo da sua própria terra, quando muitas nações e grandes reis se servirão dele.

[[v24-27-8]]

^<<v24-27-8,8>>^ E acontecerá que, se alguma nação e reino não servirem o mesmo Nabucodonosor, rei da Babilônia, e não puserem o pescoço debaixo do jugo do rei da Babilônia, visitarei com espada, e com fome, e com peste essa nação, diz o SENHOR, até que a consuma pelas suas mãos.

[[v24-27-9]]

^<<v24-27-9,9>>^ E não deis ouvidos aos vossos profetas, e aos vossos adivinhos, e aos vossos sonhos, e aos vossos agoureiros, e aos vossos encantadores, que vos falam, dizendo: Não servireis ao rei da Babilônia.

[[v24-27-10]]

^<<v24-27-10,10>>^ Porque mentiras vos profetizam, para vos mandarem para longe da vossa terra, e para que eu vos lance dela,  e vós pereçais.

[[v24-27-11]]

^<<v24-27-11,11>>^ Mas a nação que meter o pescoço sob o jugo do rei da Babilônia e o servir, eu a deixarei na sua terra, diz o SENHOR, e lavrá-la-á e habitará nela.

[[v24-27-12]]

^<<v24-27-12,12>>^ E falei com Zedequias, rei de Judá, conforme todas estas palavras, dizendo: colocai o pescoço no jugo do rei da Babilônia, e servi-o, a ele e ao seu povo, e vivereis.

[[v24-27-13]]

^<<v24-27-13,13>>^ Por que morrerias tu e o teu povo à espada, e à fome, e de peste, como o SENHOR disse da gente que não servir ao rei da Babilônia?

[[v24-27-14]]

^<<v24-27-14,14>>^ E não deis ouvidos às palavras dos profetas que vos falam, dizendo: Não servireis ao rei da Babilônia; pois vos profetizam mentiras.

[[v24-27-15]]

^<<v24-27-15,15>>^ Porque não os enviei, diz o SENHOR, e profetizam falsamente em meu nome, para que eu vos lance fora, e pereçais vós e os profetas que vos profetizam.

[[v24-27-16]]

^<<v24-27-16,16>>^ Também falei aos sacerdotes e a todo este povo, dizendo: Assim diz o SENHOR: Não deis ouvidos às palavras dos vossos profetas que vos profetizam, dizendo: Eis que os utensílios da Casa do SENHOR cedo voltarão da Babilônia; pois eles vos profetizam mentiras.

[[v24-27-17]]

^<<v24-27-17,17>>^ Não lhes deis ouvidos, servi ao rei da Babilônia e vivereis. Por que se tornaria esta cidade um deserto?

[[v24-27-18]]

^<<v24-27-18,18>>^ Porém, se são  profetas, e se há palavras do SENHOR com eles, orem, agora, ao SENHOR dos Exércitos, para que os utensílios que ficaram na Casa do SENHOR, e na casa do rei de Judá, e em Jerusalém não sejam levados para a Babilônia.

[[v24-27-19]]

^<<v24-27-19,19>>^ Porque assim diz o SENHOR dos Exércitos acerca das colunas, e do mar, e das bases, e dos restantes utensílios que ficaram na cidade,

[[v24-27-20]]

^<<v24-27-20,20>>^ os quais Nabucodonosor, rei da Babilônia, não levou, quando transportou de Jerusalém para a Babilônia a Jeconias, filho de Jeoaquim, rei de Judá, como também a todos os nobres de Jerusalém.

[[v24-27-21]]

^<<v24-27-21,21>>^ Assim, pois, diz o SENHOR dos Exércitos, o Deus de Israel, acerca dos utensílios que ficaram na  Casa do SENHOR, e na  casa do rei de Judá, e em  Jerusalém:

[[v24-27-22]]

^<<v24-27-22,22>>^ À Babilônia serão levados e ali ficarão até ao dia em que os visitar, diz o SENHOR. Então, os farei subir e os tornarei a trazer a este lugar.

'''

xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[&#60; Capítulo Anterior] | <<v24-27-0,Topo>> | xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[Próximo Capítulo &#62;]