include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-42-1]]

^<<v24-42-1,1>>^ Então, chegaram todos os príncipes dos exércitos, e Joanã, filho de Careá, e Jezanias, filho de Hosaías, e todo o povo, desde o menor até ao maior,

[[v24-42-2]]

^<<v24-42-2,2>>^ e disseram a Jeremias, o profeta: Caia, agora, a nossa súplica diante de ti, e roga por nós ao SENHOR, teu Deus, por todo este resto; porque de muitos restamos uns  poucos, como veem os teus olhos;

[[v24-42-3]]

^<<v24-42-3,3>>^ para que o SENHOR, teu Deus, nos ensine o caminho por onde havemos de andar e aquilo que havemos de fazer.

[[v24-42-4]]

^<<v24-42-4,4>>^ E disse-lhes Jeremias, o profeta: Eu vos ouvi; eis que orarei ao SENHOR, vosso Deus, conforme as vossas palavras; e seja o que for que o SENHOR vos responder, eu vo-lo declararei; não vos ocultarei nada.

[[v24-42-5]]

^<<v24-42-5,5>>^ Então, eles disseram a Jeremias: Seja o SENHOR entre nós testemunha da verdade e fidelidade, se não fizermos conforme toda a palavra com que te enviar a nós o SENHOR, teu Deus.

[[v24-42-6]]

^<<v24-42-6,6>>^ Seja ela boa ou seja má, à voz do SENHOR, nosso Deus, a quem te enviamos, obedeceremos, para que nos suceda bem, obedecendo à voz do SENHOR, nosso Deus.

[[v24-42-7]]

^<<v24-42-7,7>>^ E sucedeu que, ao fim de dez dias, veio a palavra do SENHOR a Jeremias.

[[v24-42-8]]

^<<v24-42-8,8>>^ Então, chamou a Joanã, filho de Careá, e a todos os príncipes dos exércitos que havia  com ele, e a todo o povo, desde o menor até ao maior,

[[v24-42-9]]

^<<v24-42-9,9>>^ e disse-lhes: Assim diz o SENHOR, Deus de Israel, a quem me enviastes, para lançar a vossa súplica diante dele:

[[v24-42-10]]

^<<v24-42-10,10>>^ Se de boa mente ficardes nesta terra, então, vos edificarei e não vos  derribarei; e vos plantarei e não vos  arrancarei, porque estou arrependido do mal que vos tenho feito.

[[v24-42-11]]

^<<v24-42-11,11>>^ Não temais o rei da Babilônia, a quem vós temeis; não o temais, diz o SENHOR, porque eu sou  convosco, para vos salvar e para vos fazer livrar das suas mãos.

[[v24-42-12]]

^<<v24-42-12,12>>^ E vos farei misericórdia, para que ele tenha misericórdia de vós e vos faça voltar à vossa terra.

[[v24-42-13]]

^<<v24-42-13,13>>^ Mas, se vós disserdes: Não ficaremos nesta terra, não obedecendo à voz do SENHOR, vosso Deus,

[[v24-42-14]]

^<<v24-42-14,14>>^ dizendo: Não; antes, iremos à terra do Egito, onde não veremos guerra, nem ouviremos som de trombeta, nem teremos fome de pão, e ali ficaremos.

[[v24-42-15]]

^<<v24-42-15,15>>^ Nesse caso, ouvi a palavra do SENHOR, ó resto de Judá; assim diz o SENHOR dos Exércitos, Deus de Israel: Se vós, absolutamente, puserdes o vosso rosto para entrardes no Egito e entrardes para lá peregrinar;

[[v24-42-16]]

^<<v24-42-16,16>>^ acontecerá, então, que a espada que  vós temeis ali vos alcançará na terra do Egito, e a fome que vós receais estará convosco no Egito, e ali morrereis.

[[v24-42-17]]

^<<v24-42-17,17>>^ Assim será com todos os homens que puseram o seu rosto para entrarem no Egito, a fim de lá peregrinarem: morrerão à espada, à fome e da peste; e deles não haverá  quem reste e escape do mal que eu farei vir sobre eles.

[[v24-42-18]]

^<<v24-42-18,18>>^ Porque assim diz o SENHOR dos Exércitos, Deus de Israel: Como se derramaram a minha ira e a minha indignação sobre os habitantes de Jerusalém, assim se derramará a minha indignação sobre vós, quando entrardes no Egito; e sereis uma maldição, e um espanto, e uma execração, e um opróbrio e não vereis mais este lugar.

[[v24-42-19]]

^<<v24-42-19,19>>^ Falou o SENHOR acerca de vós, ó resto de Judá: Não entreis no Egito. Sabei, decerto, que testifiquei contra vós, hoje.

[[v24-42-20]]

^<<v24-42-20,20>>^ Porquanto, enganastes a vossa alma, pois me enviastes ao SENHOR, vosso Deus, dizendo: Ora por nós ao SENHOR, nosso Deus; e, conforme tudo o que disser o SENHOR, Deus nosso, declara-no-lo assim, e o faremos.

[[v24-42-21]]

^<<v24-42-21,21>>^ E vo-lo tenho declarado hoje; mas não destes ouvidos à voz do SENHOR, vosso Deus, em coisa alguma pela qual ele me enviou a vós.

[[v24-42-22]]

^<<v24-42-22,22>>^ Agora, pois, sabei, por certo, que à espada, à fome e da peste morrereis no mesmo  lugar onde desejastes entrar, para lá peregrinardes.

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]