include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-23-1]]

^<<v24-23-1,1>>^ Ai dos pastores que destroem e dispersam as ovelhas do meu pasto, diz o SENHOR.

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim diz o SENHOR, o Deus de Israel, acerca dos pastores que apascentam o meu povo: Vós dispersastes as minhas ovelhas, e as afugentastes, e não as visitastes; eis que visitarei sobre vós a maldade das vossas ações, diz o SENHOR.

[[v24-23-3]]

^<<v24-23-3,3>>^ E eu mesmo recolherei o resto das minhas ovelhas, de todas as terras para onde as tiver afugentado, e as farei voltar aos seus apriscos; e frutificarão e se multiplicarão.

[[v24-23-4]]

^<<v24-23-4,4>>^ E levantarei sobre elas pastores que as apascentem, e nunca mais temerão, nem se assombrarão, e nem uma delas faltará, diz o SENHOR.

[[v24-23-5]]

^<<v24-23-5,5>>^ Eis que vêm dias, diz o SENHOR, em que levantarei a Davi um Renovo justo; sendo  rei, reinará, e prosperará, e praticará o juízo e a justiça na terra.

[[v24-23-6]]

^<<v24-23-6,6>>^ Nos seus dias, Judá será salvo, e Israel habitará seguro; e este será o nome com que o nomearão: O SENHOR, Justiça Nossa.

[[v24-23-7]]

^<<v24-23-7,7>>^ Portanto, eis que vêm dias, diz o SENHOR, em que nunca mais dirão: Vive o SENHOR, que fez subir os filhos de Israel da terra do Egito,

[[v24-23-8]]

^<<v24-23-8,8>>^ mas: Vive o SENHOR que fez subir e que trouxe a geração da casa de Israel da terra do Norte e de todas as terras para onde os tinha arrojado. E habitarão na sua terra.

[[v24-23-9]]

^<<v24-23-9,9>>^ Quanto aos profetas. O meu coração está  quebrantado dentro de mim; todos os meus ossos estremecem; sou como um homem embriagado e como um homem vencido pelo vinho, por causa do SENHOR e por causa das palavras da sua santidade.

[[v24-23-10]]

^<<v24-23-10,10>>^ Porque a terra está cheia de adúlteros e a terra chora por causa da maldição; e os pastos do deserto se secam, pois a sua carreira é  má, e a sua força não é  reta.

[[v24-23-11]]

^<<v24-23-11,11>>^ Porque tanto o profeta como o sacerdote estão  contaminados; até na minha casa achei a sua maldade, diz o SENHOR.

[[v24-23-12]]

^<<v24-23-12,12>>^ Portanto, o seu caminho lhes será como lugares escorregadios na escuridão; serão empurrados e cairão nele; porque trarei sobre eles mal, o ano mesmo da sua visitação, diz o SENHOR.

[[v24-23-13]]

^<<v24-23-13,13>>^ Nos profetas de Samaria, bem vi eu loucura: profetizaram da parte de Baal e fizeram errar o meu povo de Israel.

[[v24-23-14]]

^<<v24-23-14,14>>^ Mas, nos profetas de Jerusalém, vejo uma coisa horrenda: cometem adultérios, e andam com falsidade, e esforçam as mãos dos malfeitores, para que não se convertam da sua maldade; eles têm-se tornado para mim como Sodoma, e os moradores dela, como Gomorra.

[[v24-23-15]]

^<<v24-23-15,15>>^ Portanto, assim diz o SENHOR dos Exércitos acerca dos profetas: Eis que lhes darei a comer alosna, e lhes farei beber águas de fel, porque dos profetas de Jerusalém saiu a contaminação sobre toda a terra.

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim diz o SENHOR dos Exércitos: Não deis ouvidos às palavras dos profetas que entre vós profetizam; ensinam-vos vaidades e falam da visão do seu coração, não da boca do SENHOR.

[[v24-23-17]]

^<<v24-23-17,17>>^ Dizem continuamente aos que me desprezam: O SENHOR disse: Paz tereis; e a qualquer que anda segundo o propósito do seu coração, dizem: Não virá mal sobre vós.

[[v24-23-18]]

^<<v24-23-18,18>>^ Porque quem esteve no conselho do SENHOR, e viu, e ouviu a sua palavra? Quem esteve atento à sua palavra e a ouviu?

[[v24-23-19]]

^<<v24-23-19,19>>^ Eis que saiu com indignação a tempestade do SENHOR, e uma  tempestade penosa cairá cruelmente sobre a cabeça dos ímpios.

[[v24-23-20]]

^<<v24-23-20,20>>^ Não se desviará a ira do SENHOR até que execute e cumpra os pensamentos do seu coração; no fim dos dias, entendereis isso claramente.

[[v24-23-21]]

^<<v24-23-21,21>>^ Não mandei os profetas; todavia, eles foram correndo; não lhes falei a eles; todavia, eles profetizaram.

[[v24-23-22]]

^<<v24-23-22,22>>^ Mas, se estivessem no meu conselho, então, fariam ouvir as minhas palavras ao meu povo, e o fariam voltar do seu mau caminho e da maldade das suas ações.

[[v24-23-23]]

^<<v24-23-23,23>>^ Sou eu apenas Deus de perto, diz o SENHOR, e não também Deus de longe?

[[v24-23-24]]

^<<v24-23-24,24>>^ Esconder-se-ia alguém em esconderijos, de modo que eu não o veja? — diz o SENHOR. Porventura,  não encho eu os céus e a terra? — diz o SENHOR.

[[v24-23-25]]

^<<v24-23-25,25>>^ Tenho ouvido o que dizem aqueles profetas, profetizando mentiras em meu nome, dizendo: Sonhei! Sonhei!

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando sucederá isso no coração dos profetas que profetizam mentiras e que são  só profetas do engano do seu coração?

[[v24-23-27]]

^<<v24-23-27,27>>^ Os quais cuidam que farão que o meu povo se esqueça do meu nome, pelos sonhos que cada um conta ao seu companheiro, assim como seus pais se esqueceram do meu nome, por causa de Baal.

[[v24-23-28]]

^<<v24-23-28,28>>^ O profeta que teve um  sonho, que conte o sonho; e aquele em quem está  a minha palavra, que fale a minha palavra, com  verdade. Que tem a palha com o trigo? — diz o SENHOR.

[[v24-23-29]]

^<<v24-23-29,29>>^ Não é a minha palavra como fogo, diz o SENHOR, e como um martelo que  esmiúça a penha?

[[v24-23-30]]

^<<v24-23-30,30>>^ Portanto, eis que eu sou  contra os profetas, diz o SENHOR, que furtam as minhas palavras, cada um ao seu companheiro.

[[v24-23-31]]

^<<v24-23-31,31>>^ Eis que eu sou  contra os profetas, diz o SENHOR, que usam de sua língua e dizem: Ele disse.

[[v24-23-32]]

^<<v24-23-32,32>>^ Eis que eu sou  contra os que profetizam sonhos mentirosos, diz o SENHOR, e os contam, e fazem errar o meu povo com as suas mentiras e com as suas leviandades; pois eu não os enviei, nem lhes dei ordem e não trouxeram proveito nenhum a este povo, diz o SENHOR.

[[v24-23-33]]

^<<v24-23-33,33>>^ Quando, pois, te perguntar este povo, ou qualquer profeta, ou sacerdote, dizendo: Qual é  o peso do SENHOR?, então, lhe dirás: Vós sois o peso, eu vos deixarei, diz o SENHOR.

[[v24-23-34]]

^<<v24-23-34,34>>^ E, quanto ao profeta, e ao sacerdote, e ao povo que disser: Peso do SENHOR, eu castigarei o tal homem e a sua casa.

[[v24-23-35]]

^<<v24-23-35,35>>^ Assim direis, cada um ao seu companheiro e cada um ao seu irmão: Que respondeu o SENHOR? Que falou o SENHOR?

[[v24-23-36]]

^<<v24-23-36,36>>^ Mas nunca mais vos lembrareis do peso do SENHOR, porque a cada um lhe servirá de peso a sua própria  palavra. Vós torceis as palavras do Deus vivo, do SENHOR dos Exércitos, o nosso Deus.

[[v24-23-37]]

^<<v24-23-37,37>>^ Assim dirás ao profeta: O que te respondeu o SENHOR? O que falou o SENHOR?

[[v24-23-38]]

^<<v24-23-38,38>>^ Mas, porque dizeis: Peso do SENHOR, assim o diz o SENHOR: Porque dizeis esta expressão Peso do SENHOR (havendo-vos eu ordenado: não direis Peso do SENHOR),

[[v24-23-39]]

^<<v24-23-39,39>>^ por isso, eis que também eu me esquecerei totalmente de vós e a vós, e à cidade que vos dei a vós, e a vossos pais, tirarei da minha presença.

[[v24-23-40]]

^<<v24-23-40,40>>^ E porei sobre vós perpétuo opróbrio e eterna vergonha, que não serão esquecidos.

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]