include::./index.adoc[]

[[v24-44-0]]
=== Jeremias, 44
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-44-1]]

^<<v24-44-1,1>>^ Palavra que veio a Jeremias acerca de todos os judeus habitantes da terra do Egito, que habitavam em Migdol, e em Tafnes, e em Nofe, e na terra de Patros, dizendo:

[[v24-44-2]]

^<<v24-44-2,2>>^ Assim diz o SENHOR dos Exércitos, Deus de Israel: Vós vistes todo o mal que fiz cair sobre Jerusalém e sobre todas as cidades de Judá; e eis que elas são,  hoje, um  deserto, e ninguém habita nelas;

[[v24-44-3]]

^<<v24-44-3,3>>^ por causa da sua maldade que fizeram, para me irarem, indo queimar incenso e servir a deuses estranhos, que eles nunca conheceram, eles, vós e vossos pais.

[[v24-44-4]]

^<<v24-44-4,4>>^ E eu vos enviei todos os meus servos, os profetas, madrugando e enviando a dizer: Ora, não façais esta coisa abominável que aborreço.

[[v24-44-5]]

^<<v24-44-5,5>>^ Mas eles não deram ouvidos, nem inclinaram os ouvidos, para se converterem da sua maldade, para não queimarem incenso a deuses estranhos.

[[v24-44-6]]

^<<v24-44-6,6>>^ Derramaram-se, pois, a minha indignação e a minha ira e acenderam-se nas cidades de Judá e nas ruas de Jerusalém; e elas tornaram-se em deserto e  em assolação, como hoje se vê.

[[v24-44-7]]

^<<v24-44-7,7>>^ Agora, pois, assim diz o SENHOR, Deus dos Exércitos, Deus de Israel: Por que fazeis vós tão  grande mal contra a vossa alma, para desarraigardes ao homem, e à mulher, à criança, e ao que mama do meio de Judá, a fim de não deixardes ali resto algum;

[[v24-44-8]]

^<<v24-44-8,8>>^ irando-me com as obras de vossas mãos, queimando incenso a deuses estranhos na terra do Egito, onde vós entrastes, para lá peregrinardes, para que a vós mesmos vos desarraigueis e para que sirvais de maldição, de opróbrio entre todas as nações da terra?

[[v24-44-9]]

^<<v24-44-9,9>>^ Esquecestes já as maldades de vossos pais, e as maldades dos reis de Judá, e as maldades das suas mulheres, e as vossas maldades, e as maldades das vossas mulheres, que cometeram na terra de Judá e nas ruas de Jerusalém?

[[v24-44-10]]

^<<v24-44-10,10>>^ Não se humilharam até ao dia de hoje, nem temeram, nem andaram na minha lei, nem nos meus estatutos, que pus diante de vós e diante de vossos pais.

[[v24-44-11]]

^<<v24-44-11,11>>^ Portanto, assim diz o SENHOR dos Exércitos, Deus de Israel: Eis que eu ponho o rosto contra vós, para mal e para desarraigar a todo o Judá.

[[v24-44-12]]

^<<v24-44-12,12>>^ E tomarei o resto de Judá, que pôs o rosto para entrar na terra do Egito, a fim de lá peregrinar; e ele será todo consumido na terra do Egito; cairá à espada e  de fome morrerá; consumir-se-ão, desde o menor até ao maior; à espada e à fome morrerão e serão uma execração, e um espanto, e uma maldição, e um opróbrio.

[[v24-44-13]]

^<<v24-44-13,13>>^ Porque visitarei os que habitam na terra do Egito, como visitei Jerusalém, com a espada, com a fome e com a peste.

[[v24-44-14]]

^<<v24-44-14,14>>^ De maneira que não haverá  quem escape e fique da parte remanescente do Judá que entrou na terra do Egito, a fim de lá peregrinar, para tornar à terra de Judá, à qual era grande desejo da sua alma voltar e habitar lá; mas não tornarão senão os que escaparem.

[[v24-44-15]]

^<<v24-44-15,15>>^ Então, responderam a Jeremias todos os homens que sabiam que suas mulheres queimavam incenso a deuses estranhos e todas as mulheres que estavam em pé em  grande multidão, como também todo o povo que habitava na terra do Egito, em Patros, dizendo:

[[v24-44-16]]

^<<v24-44-16,16>>^ Quanto à palavra que nos anunciaste em nome do SENHOR, não te obedeceremos a ti;

[[v24-44-17]]

^<<v24-44-17,17>>^ antes, certamente, cumpriremos toda a palavra que saiu da nossa boca, queimando incenso à deusa chamada  Rainha dos Céus e oferecendo-lhe libações, como nós e nossos pais, nossos reis e nossos príncipes temos feito, nas cidades de Judá e nas ruas de Jerusalém; e tivemos, então, fartura de pão, e andávamos alegres, e não vimos mal algum.

[[v24-44-18]]

^<<v24-44-18,18>>^ Mas, desde que cessamos de queimar incenso à Rainha dos Céus e de lhe oferecer libações, tivemos falta de tudo e fomos consumidos pela espada e pela fome.

[[v24-44-19]]

^<<v24-44-19,19>>^ Quando nós queimávamos incenso à Rainha dos Céus e lhe oferecíamos libações, fizemos-lhe bolos para a adorar e oferecemos-lhe libações sem nossos maridos?

[[v24-44-20]]

^<<v24-44-20,20>>^ Então, disse Jeremias a todo o povo, aos homens e às mulheres, e a todo o povo que lhe havia dado esta resposta, dizendo:

[[v24-44-21]]

^<<v24-44-21,21>>^ Porventura,  não se lembrou o SENHOR, e não lhe subiu ao coração o incenso que queimastes nas cidades de Judá e nas ruas de Jerusalém, vós e vossos pais, vossos reis e vossos príncipes, como também o povo da terra?

[[v24-44-22]]

^<<v24-44-22,22>>^ De maneira que o SENHOR não podia por mais tempo sofrer a maldade das vossas ações, as abominações que cometestes; pelo que se tornou a vossa terra em deserto, e em espanto, e em maldição, sem habitantes, como hoje se vê.

[[v24-44-23]]

^<<v24-44-23,23>>^ Visto que queimastes incenso, e pecastes contra o SENHOR, e não obedecestes à voz do SENHOR, e na sua lei e nos seus testemunhos não andastes, vos sucedeu este mal, como se vê  neste dia.

[[v24-44-24]]

^<<v24-44-24,24>>^ Disse mais Jeremias a todo o povo e a todas as mulheres: Ouvi a palavra do SENHOR, vós, todo o Judá que estais  na terra do Egito.

[[v24-44-25]]

^<<v24-44-25,25>>^ Assim fala o SENHOR dos Exércitos, Deus de Israel, dizendo: Vós e vossas mulheres não somente falastes por vossa boca, senão também o  fizestes por vossas mãos, dizendo: Certamente, cumpriremos os nossos votos que fizemos, de queimar incenso à Rainha dos Céus e de lhe oferecer libações; perfeitamente confirmastes os vossos votos e perfeitamente cumpristes os vossos votos.

[[v24-44-26]]

^<<v24-44-26,26>>^ Portanto, ouvi a palavra do SENHOR, todo o Judá que habitais na terra do Egito: Eis que eu juro pelo meu grande nome, diz o SENHOR, que nunca mais será pronunciado o meu nome pela boca de homem de Judá em toda a terra do Egito, dizendo: Vive o Senhor Jeová !

[[v24-44-27]]

^<<v24-44-27,27>>^ Eis que velarei sobre eles para mal e não para bem; e serão consumidos todos os homens de Judá que estão  na terra do Egito à espada e à fome, até que se acabem de todo.

[[v24-44-28]]

^<<v24-44-28,28>>^ E os que escaparem da espada tornarão da terra do Egito à terra de Judá, poucos em número; e saberá todo o resto de Judá que entrou na terra do Egito, para peregrinar ali, se subsistirá a minha palavra ou a sua.

[[v24-44-29]]

^<<v24-44-29,29>>^ E isto vos servirá  de sinal, diz o SENHOR, que eu vos castigarei neste lugar, para que saibais que, certamente, subsistirão as minhas palavras contra vós para mal.

[[v24-44-30]]

^<<v24-44-30,30>>^ Assim diz o SENHOR: Eis que eu entregarei o Faraó Hofra, rei do Egito, nas mãos de seus inimigos e nas mãos dos que procuram a sua morte, como entreguei Zedequias, rei de Judá, nas mãos de Nabucodonosor, rei da Babilônia, seu inimigo e que procurava a sua morte.

'''

xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[Próximo Capítulo &#62;]