include::./index.adoc[]

[[v24-26-0]]
=== Jeremias, 26
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-26-1]]

^<<v24-26-1,1>>^ No princípio do reinado de Jeoaquim, filho de Josias, rei de Judá, veio esta palavra do SENHOR, dizendo:

[[v24-26-2]]

^<<v24-26-2,2>>^ Assim diz o SENHOR: Põe-te no átrio da Casa do SENHOR e dize a todas as cidades de Judá que vêm adorar à Casa do SENHOR todas as palavras que te mandei que lhes dissesses; não esqueças nem uma palavra.

[[v24-26-3]]

^<<v24-26-3,3>>^ Bem pode ser que ouçam e se convertam cada um do seu mau caminho, e eu me arrependa do mal que intento fazer-lhes por causa da maldade das suas ações.

[[v24-26-4]]

^<<v24-26-4,4>>^ Dize-lhes, pois: Assim diz o SENHOR: Se não me derdes ouvidos para andardes na minha lei que pus diante de vós,

[[v24-26-5]]

^<<v24-26-5,5>>^ para que ouvísseis as palavras dos meus servos, os profetas, que eu vos envio, madrugando e enviando, mas não ouvistes.

[[v24-26-6]]

^<<v24-26-6,6>>^ Então, farei que esta casa seja  como Siló e farei desta cidade uma maldição para todas as nações da terra.

[[v24-26-7]]

^<<v24-26-7,7>>^ E ouviram os sacerdotes, e os profetas, e todo o povo, a Jeremias anunciando estas palavras na Casa do SENHOR.

[[v24-26-8]]

^<<v24-26-8,8>>^ E sucedeu que, acabando Jeremias de dizer tudo quanto o SENHOR lhe havia ordenado que dissesse a todo o povo, pegaram nele os sacerdotes, e os profetas, e todo o povo, dizendo: Certamente, morrerás.

[[v24-26-9]]

^<<v24-26-9,9>>^ Por que profetizaste no nome do SENHOR, dizendo: Será como Siló esta casa, e esta cidade será assolada, de sorte que fique sem moradores? E ajuntou-se todo o povo contra Jeremias, na Casa do SENHOR.

[[v24-26-10]]

^<<v24-26-10,10>>^ E, ouvindo os príncipes de Judá estas palavras, subiram da casa do rei à Casa do SENHOR e se assentaram à entrada da Porta Nova da Casa do SENHOR.

[[v24-26-11]]

^<<v24-26-11,11>>^ Então, falaram os sacerdotes e os profetas aos príncipes e a todo o povo, dizendo: Este homem é  réu de morte, porque profetizou contra esta cidade, como ouvistes com os vossos ouvidos.

[[v24-26-12]]

^<<v24-26-12,12>>^ E falou Jeremias a todos os príncipes e a todo o povo, dizendo: O SENHOR me enviou a profetizar contra esta casa e contra esta cidade todas as palavras que ouvistes.

[[v24-26-13]]

^<<v24-26-13,13>>^ Agora, pois, melhorai os vossos caminhos e as vossas ações e ouvi a voz do SENHOR, vosso Deus, e arrepender-se-á o SENHOR do mal que falou contra vós.

[[v24-26-14]]

^<<v24-26-14,14>>^ Quanto a mim, eis que estou nas vossas mãos; fazei de mim conforme o que for bom e reto aos vossos olhos.

[[v24-26-15]]

^<<v24-26-15,15>>^ Sabei, porém, com certeza, que, se me matardes a mim, trareis sangue inocente sobre vós, e sobre esta cidade, e sobre os seus habitantes, porque, na verdade, o SENHOR me enviou a vós para dizer aos vossos ouvidos todas estas palavras.

[[v24-26-16]]

^<<v24-26-16,16>>^ Então, disseram os príncipes e todo o povo aos sacerdotes e aos profetas: Este homem não é réu de morte, porque, em nome do SENHOR, nosso Deus, nos falou.

[[v24-26-17]]

^<<v24-26-17,17>>^ Também se levantaram alguns dentre os anciãos da terra e falaram a toda a congregação do povo, dizendo:

[[v24-26-18]]

^<<v24-26-18,18>>^ Miqueias, o morastita, profetizou nos dias de Ezequias, rei de Judá, e falou a todo o povo de Judá, dizendo: Assim disse o SENHOR dos Exércitos: Sião será lavrada como um campo, e Jerusalém se tornará em montões de pedras,  e o monte desta casa, como os altos de um bosque.

[[v24-26-19]]

^<<v24-26-19,19>>^ Mataram-no, porventura,  Ezequias, rei de Judá, e todo o Judá? Antes, não temeu este ao SENHOR e não implorou o favor do SENHOR? E o SENHOR se arrependeu do mal que falara contra eles. E nós não fazemos um  grande mal contra a nossa alma?

[[v24-26-20]]

^<<v24-26-20,20>>^ Também houve um homem que profetizava em nome do SENHOR: Urias, filho de Semaías, de Quiriate-Jearim. Ele profetizou contra esta cidade e contra esta terra, conforme todas as palavras de Jeremias.

[[v24-26-21]]

^<<v24-26-21,21>>^ E, ouvindo o rei Jeoaquim, e todos os seus valentes, e todos os príncipes as suas palavras, procurou o rei matá-lo. Mas, ouvindo isto Urias, temeu, e fugiu, e foi para o Egito.

[[v24-26-22]]

^<<v24-26-22,22>>^ Mas o rei Jeoaquim enviou uns homens e a Elnatã, filho de Acbor, ao Egito.

[[v24-26-23]]

^<<v24-26-23,23>>^ E eles tiraram a Urias do Egito e o trouxeram ao rei Jeoaquim, que o feriu à espada e lançou o seu cadáver nas sepulturas dos filhos do povo.

[[v24-26-24]]

^<<v24-26-24,24>>^ A mão, pois, de Aicão, filho de Safã, foi com Jeremias, para que o não entregassem nas mãos do povo, para ser morto.

'''

xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[&#60; Capítulo Anterior] | <<v24-26-0,Topo>> | xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[Próximo Capítulo &#62;]