include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-2-1]]

^<<v24-2-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v24-2-2]]

^<<v24-2-2,2>>^ Vai e clama aos ouvidos de Jerusalém, dizendo: Assim diz o SENHOR: Lembro-me de ti, da beneficência da tua mocidade e do amor dos teus desposórios, quando andavas após mim no deserto, numa terra que se não semeava.

[[v24-2-3]]

^<<v24-2-3,3>>^ Então,  Israel era  santidade para o SENHOR e era as primícias da sua novidade; todos os que o devoravam eram tidos por culpados; o mal vinha sobre eles, diz o SENHOR.

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouvi a palavra do SENHOR, ó casa de Jacó e todas as famílias da casa de Israel.

[[v24-2-5]]

^<<v24-2-5,5>>^ Assim diz o SENHOR: Que injustiça acharam vossos pais em mim, para se afastarem de mim, indo após a vaidade e tornando-se levianos?

[[v24-2-6]]

^<<v24-2-6,6>>^ E não disseram: Onde está o SENHOR, que nos fez subir da terra do Egito? Que nos guiou através do deserto, por uma terra de ermos e de covas, por uma terra de sequidão e sombra de morte, por uma terra em que ninguém transitava, e na qual não morava homem algum.

[[v24-2-7]]

^<<v24-2-7,7>>^ E eu vos introduzi numa terra fértil, para comerdes o seu fruto e o seu bem; mas, quando nela entrastes, contaminastes a minha terra e da minha herança fizestes uma abominação.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não disseram: Onde está  o SENHOR? E os que tratavam da lei não me conheceram, e os pastores prevaricaram contra mim, e os profetas profetizaram por Baal e andaram após o que é de nenhum proveito.

[[v24-2-9]]

^<<v24-2-9,9>>^ Portanto, ainda pleitearei convosco, diz o SENHOR; e até com os filhos de vossos filhos pleitearei.

[[v24-2-10]]

^<<v24-2-10,10>>^ Porquanto, passai às ilhas de Quitim e vede; e enviai a Quedar, e atentai bem, e vede se sucedeu coisa semelhante.

[[v24-2-11]]

^<<v24-2-11,11>>^ Houve alguma  nação que trocasse os seus  deuses, posto não serem deuses? Todavia, o meu povo trocou a sua glória pelo que é de nenhum proveito.

[[v24-2-12]]

^<<v24-2-12,12>>^ Espantai-vos disto, ó céus, e horrorizai-vos! Ficai verdadeiramente desolados, diz o SENHOR.

[[v24-2-13]]

^<<v24-2-13,13>>^ Porque o meu povo fez duas maldades: a mim me deixaram, o manancial de águas vivas, e cavaram cisternas, cisternas rotas, que não retêm as águas.

[[v24-2-14]]

^<<v24-2-14,14>>^ Acaso é Israel um servo? Ou um escravo  nascido em casa? Por que, pois, veio a ser  presa?

[[v24-2-15]]

^<<v24-2-15,15>>^ Os filhos de leão bramaram sobre ele e levantaram a sua voz; e puseram a sua terra em assolação; as suas cidades se queimaram, e ninguém habita nelas.

[[v24-2-16]]

^<<v24-2-16,16>>^ Até os filhos de Nofa e de Tafnes te quebraram o alto da cabeça.

[[v24-2-17]]

^<<v24-2-17,17>>^ Porventura,  não procuras isso para ti mesmo, deixando o SENHOR, teu Deus, no tempo em que ele te guia pelo caminho?

[[v24-2-18]]

^<<v24-2-18,18>>^ Agora, pois, que te importa a ti o caminho do Egito, para beberes as águas de Sior? E que te importa a ti o caminho da Assíria, para beberes as águas do rio?

[[v24-2-19]]

^<<v24-2-19,19>>^ A tua malícia te castigará, e as tuas apostasias te repreenderão; sabe, pois, e vê, que mau e quão amargo é deixares ao SENHOR, teu Deus, e não teres o meu temor contigo, diz o Senhor Jeová  dos Exércitos.

[[v24-2-20]]

^<<v24-2-20,20>>^ Quando eu já  há muito quebrava o teu jugo e  rompia as tuas algemas, dizias tu: Nunca mais  transgredirei; contudo, em todo outeiro alto e debaixo de toda árvore verde te andas encurvando e  corrompendo.

[[v24-2-21]]

^<<v24-2-21,21>>^ Eu mesmo te plantei como vide excelente, uma semente inteiramente fiel; como, pois, te tornaste para mim uma planta degenerada, de vide estranha?

[[v24-2-22]]

^<<v24-2-22,22>>^ Pelo que, ainda que te laves com salitre e amontoes sabão, a tua iniquidade estará gravada diante de mim, diz o Senhor Jeová .

[[v24-2-23]]

^<<v24-2-23,23>>^ Como dizes logo:  Não estou contaminado nem andei após os baalins? Vê o teu caminho no vale, conhece o que fizeste; dromedária ligeira és, que anda torcendo os seus caminhos;

[[v24-2-24]]

^<<v24-2-24,24>>^ jumenta montês, acostumada ao deserto e que, conforme o desejo da sua alma, sorve o vento; quem impediria o seu encontro? Todos os que a buscarem não se cansarão; no mês dela a acharão.

[[v24-2-25]]

^<<v24-2-25,25>>^ Evita que o teu pé ande descalço e que a tua garganta tenha sede; mas tu dizes: Não há esperança; não, porque amo os estranhos e após eles andarei.

[[v24-2-26]]

^<<v24-2-26,26>>^ Como fica confundido o ladrão quando o apanham, assim se confundem os da casa de Israel; eles, os seus reis, os seus príncipes, os seus sacerdotes e os seus profetas,

[[v24-2-27]]

^<<v24-2-27,27>>^ que dizem ao pedaço de madeira: Tu és  meu pai; e à pedra: Tu me geraste; porque me viraram as costas e não o rosto; mas, no tempo do seu aperto, dirão: Levanta-te e livra-nos.

[[v24-2-28]]

^<<v24-2-28,28>>^ Onde, pois, estão os teus deuses, que fizeste para ti? Que se levantem, se te podem livrar no tempo da tua tribulação; porque os teus deuses, ó Judá, são tão numerosos como  as tuas cidades.

[[v24-2-29]]

^<<v24-2-29,29>>^ Por que disputais comigo? Todos vós transgredistes contra mim, diz o SENHOR.

[[v24-2-30]]

^<<v24-2-30,30>>^ Em vão castiguei os vossos filhos; eles não aceitaram a correção; a vossa espada devorou os vossos profetas como um leão destruidor.

[[v24-2-31]]

^<<v24-2-31,31>>^ Ó geração! Considerai vós a palavra do SENHOR. Porventura,  tenho eu sido para Israel um deserto? Ou uma terra da mais espessa escuridão? Por que, pois,  diz o meu povo: Desligamo-nos de ti; nunca mais a ti viremos?

[[v24-2-32]]

^<<v24-2-32,32>>^ Porventura,  esquece-se a virgem dos seus enfeites ou  a esposa dos seus cendais? Todavia, o meu povo se esqueceu de mim por inumeráveis dias.

[[v24-2-33]]

^<<v24-2-33,33>>^ Como ornamentas o teu caminho, para buscares o amor! De sorte que até às malignas ensinaste os teus caminhos.

[[v24-2-34]]

^<<v24-2-34,34>>^ Até nas orlas das  tuas vestes  se achou o sangue da alma dos inocentes e necessitados; não cavei para o achar, pois se vê em todas estas coisas.

[[v24-2-35]]

^<<v24-2-35,35>>^ E  ainda dizes: Eu estou inocente; certamente, a sua ira se desviou de mim. Eis que entrarei em juízo contigo, porquanto dizes: Não pequei.

[[v24-2-36]]

^<<v24-2-36,36>>^ Por que te desvias tanto, mudando o teu caminho? Também do Egito serás envergonhada, como foste envergonhada da Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ Também daquele sairás com as mãos sobre a tua cabeça; porque o SENHOR rejeitou as tuas confianças, e não prosperarás com elas.

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]