include::./index.adoc[]

[[v24-24-0]]
=== Jeremias, 24
// arc ?, ARC - Almeida Revista e Corrigida

[[v24-24-1]]

^<<v24-24-1,1>>^ Fez-me o SENHOR ver, e vi dois cestos de figos postos diante do templo do SENHOR, depois que Nabucodonosor, rei da Babilônia, levou em cativeiro a Jeconias, filho de Jeoaquim, rei de Judá, e os príncipes de Judá, e os carpinteiros, e os ferreiros de Jerusalém e os trouxe à Babilônia.

[[v24-24-2]]

^<<v24-24-2,2>>^ Um cesto tinha  figos muito bons, como os figos temporãos, mas o outro cesto tinha  figos muito maus, que não se podiam comer, de maus que  eram.

[[v24-24-3]]

^<<v24-24-3,3>>^ E disse-me o SENHOR: Que vês tu, Jeremias? E  eu disse: Figos. Os figos bons, muito bons, e os maus, muito maus, que não se podem comer, de maus que  são.

[[v24-24-4]]

^<<v24-24-4,4>>^ Então, veio a mim a palavra do SENHOR, dizendo:

[[v24-24-5]]

^<<v24-24-5,5>>^ Assim diz o SENHOR, o Deus de Israel: Como a estes bons figos, assim conhecerei aos de Judá levados em cativeiro e que eu enviei deste lugar para a terra dos caldeus, para seu bem.

[[v24-24-6]]

^<<v24-24-6,6>>^ Porei os olhos sobre eles, para seu  bem, e os farei voltar a esta terra; e edificá-los-ei, e não os destruirei, e plantá-los-ei, e não os arrancarei.

[[v24-24-7]]

^<<v24-24-7,7>>^ E dar-lhes-ei coração para que me conheçam, porque eu sou  o SENHOR; e ser-me-ão por povo, e eu lhes serei por Deus, porque se converterão a mim de todo o seu coração.

[[v24-24-8]]

^<<v24-24-8,8>>^ E, como aos figos maus, que se não podem comer, de maus que são  (porque assim diz o SENHOR), assim entregarei Zedequias, rei de Judá, e os seus príncipes, e o resto de Jerusalém, tanto os que ficaram nesta terra como os que habitaram na terra do Egito.

[[v24-24-9]]

^<<v24-24-9,9>>^ Eu os entregarei para que sejam um terror, um mal para todos os reinos da terra, um opróbrio, provérbio, um escárnio e uma maldição em todos os lugares para onde os arrojei.

[[v24-24-10]]

^<<v24-24-10,10>>^ E enviarei entre eles a espada, a fome e a peste, até que se consumam de sobre a terra que dei a eles e a seus pais.

'''

xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[Próximo Capítulo &#62;]